### ISSUE TITLE
Establish language for repos that fall under CommComm

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#100]
Have we established copy yet that we can copy/paste into repos that fall under CommComm? I was just looking at the issue for moving nodejs/education under CommComm and I wanted to make sure it hadn't been done elsewhere already, such as evangelism. Couldn't find anything.

**Comment by nebrius** [comment]
We don't have anything formal drafted, but I've been using this: https://github.com/nodejs/nodejs-collection#about-this-team

**Comment by bnb** [comment]
This is definitely something good we can standardize on. If someone would like to suggest how we can approach this (several of the repos under us already have something similar: [nodejs/nodejs-collection#about-this-team](https://github.com/nodejs/nodejs-collection#about-this-team), [nodejs/community-events#community-events](https://github.com/nodejs/community-events#community-events)) and could easily be snatched from one of those to be tweaked/standardized!

**Comment by bnb** [comment]
AFAIK we've standardized on this across a few different repos. Going to close this for now. Feel free to ping on this if we've got more work that needs to be done on it!
