### ISSUE TITLE
Another repo that falls under joint ownership

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#104]
The conversation was started a little while back about needing a Collaboration/Admin repo for the TSC and CommComm jointly administering the travel fund. There's now another repo I think falls under this category, too https://github.com/nodejs/getting-started. 

I indicated this also in the TSC issue regarding the prior conversation about [our collaborative committee work](https://github.com/nodejs/TSC/issues/295).

The need here is likely to have a meeting or create a doc with groups from both committees to get the ball rolling on this work.

**Comment by bnb** [comment]
Getting Started is in the Admin repo now 💥

Going to close this - feel free to re-open if further discussion is needed.
