### ISSUE TITLE
Request to join as observer

### ISSUE THREAD

**Issue by refack** [nodejs/community-committee#105]
Hello all,

I'm interested in joining as an observer, with the intention of joining the WG if it pans outs.
Some background &mdash; Born and raised in Israel, living in Boston for the last 2.5 years. I've been a techie for as far as I can remember, but only got into software while studying CS in Tel Aviv University 18 years ago.
After uni I worked for 3.5 year in a growing startup that got from 20 people to 150 during my tenure. In my last 2 years there I was team-leader/scrum-master and tech evangelist, but my passion was in conflict-resolution, and improving group dynamics.
I then opened my own startup/software-shop which was most of all a school of hard-knocks. I had to learn how to deal with myself, my life-partner, my business-partner, clients, and later 25 employees. During that time I was an ad-hoc evangelist for meetup culture in TLV, hosting two groups: [Alphageeks](https://www.facebook.com/groups/99923286442/) and [JSTLV](https://www.meetup.com/telavivjs/).
After the business wound down, I moved to the US following my wife who started a postdoc in Biology. I took this opportunity for a hiatus from hardcore software development, and dabbled in consulting and computational biology.
I have been back on "the OSS scene" in the last several months focusing my energy on node core. I found I'm gravitating again towards group dynamics, and interacting with "the community", both the regulars and the occasional participant. I'm also fascinated with team/team interactions, and IMHO improving those could be a major power-multiplier for nodejs.org as a whole (Upstream teams such as ECMA, V8, chakra, etc. As well as downstream teams such as Electron, IDE vendors, 3rd party module developers, npm, and JS user organizations for example [node.js.il](https://www.facebook.com/groups/node.il/))

**Comment by nebrius** [comment]
You're on the list!
