### ISSUE TITLE
Add list of Observers to README.md

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#106]
I think it would be helpful to add a list of current observers to the README.md file. In addition to having the list, including a link to the docs around membership and what that takes would be a huge benefit here.

**Comment by nebrius** [comment]
TBH I'd rather not. Our list of observers has been fairly static, but looking at the other committees, this list is expected to start changing more frequently in the future. Maintaining that in the README would, IMO, be cumbersome.

**Comment by renrutnnej** [comment]
I had the same feeling as @nebrius re: that level of maintenance of the README being unnecessary.

**Comment by RichardLitt** [comment]
Looking at the occurrences of [the word observer in this repo](https://github.com/nodejs/community-committee/search?utf8=%E2%9C%93&q=observer&type=), there's no clear statement saying that people can be observers. It might be nice to say explicitly that people are welcome to come and observe meetings. 

I don't think we need to formalize this into a list of observers, though.

**Comment by nebrius** [comment]
> Looking at the occurrences of the word observer in this repo, there's no clear statement saying that people can be observers. It might be nice to say explicitly that people are welcome to come and observe meetings.

Hmm...I thought we did, but I guess not. Yeah, we should get that fixed. This is probably related to the discussion in https://github.com/nodejs/community-committee/issues/21.

**Comment by bnb** [comment]
This PR is also relevant to the discussion - maybe worth adding something to the work @hackygolucky is doing in it pre/post merge. https://github.com/nodejs/community-committee/blob/21a4c4d5306929b223319fc6602b3a3116b7f836/CONTRIBUTING.md

**Comment by bnb** [comment]
Addressing @nebrius's and @renrutnnej's comments: Totally fair, thanks for the feedback. Happy to close if we feel this is settled, though I think the discussion around "observer" is valuable - maybe it should be moved to another issue 👍
