### ISSUE TITLE
Adjust time of CommComm meetings for our European friends

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#107]
We've got a number of active European CommComm members. Is now a good time to move the meeting to earlier in the day?

cc @nebrius @nodejs/community-committee 

Proposal but certainly up for debate: 12PM EST.

**Comment by hackygolucky** [comment]
Would especially love to hear from @pup @msmichellegar @jpwesselink about this time

**Comment by pup** [comment]
personally, i don't have any complaints with the current time! 12pm est would be a little early for me, even, because i'm not sure how that integrates with my usual routine

**Comment by gr2m** [comment]
I’m on PST so 12 PM EST would be 9am for me, which is totally fine 👍 I’m all +1 to make it easier for others to join

**Comment by nebrius** [comment]
I'm happy to change the time as well, and 12pm EDT works for me.

Super pedantic note: Did you meant EDT instead of EST? We should be careful to specify EST vs EDT correctly because we ultimately specify all of our meeting times in UTC. EDT is UTC-4 but EST is UTC-5, so it matters. Timezones, amirit?

**Comment by mhdawson** [comment]
12 EST is good for me.

**Comment by renrutnnej** [comment]
12 PM EST works better with my schedule now that I'm CST.

**Comment by msmichellegar** [comment]
Thank you! 💃  A tad earlier would definitely make things easier for me. 12PM EST works really well. Also could I selfishly request adding London to the table of timezones listed in the issue? I've been confused by the times before and missed the meeting.

**Comment by nebrius** [comment]
> Also could I selfishly request adding London to the table of timezones listed in the issue? I've been confused by the times before and missed the meeting.

The date functionality comes from the [tool we use to generate meeting issues](https://github.com/rvagg/make-node-meeting). I'm totally up for adding London to the list, but, uhmm, I don't know how that code works and my BASH scripting skills are weak 😅

**Comment by jpwesselink** [comment]
12 PM EST, which boils down to 6 PM Amsterdam time would definitely work better for me.

**Comment by msmichellegar** [comment]
@nebrius Ha I see! Don't worry, I will just work on my googling skills ;)

**Comment by bnb** [comment]
12 ET works for me, and is a bit less of a time drain on my day - ramp up/ramp down can be a bit hard later on a Thursday 😅

@rachelnicole I know you've had to miss several of the meetings because time/travel - would this time work for you, too?

**Comment by hackygolucky** [comment]
Done! https://github.com/nodejs/community-committee/issues/116
