### ISSUE TITLE
Skipping this weeks' meeting

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#108]
Hi @nodejs/community-committee! We do not currently have anything labelled as `cc-agenda` for this weeks meeting. Is there anything that you want to discuss?

If so, please tag the issue you would like to discuss as `cc-agenda`. If you don't have permission to label something for the agenda, please ask one of us to do it for you!

Otherwise, I recommend that we skip this weeks meeting.

**Comment by nebrius** [comment]
On a related note, I will be on vacation off the grid, and completely without Internet access from August 24th through September 4th. This means I will not be able to attend or prep the agenda for the meeting scheduled for August 31st.

If there is an agenda and if someone else would like to take on running this meeting, it would be much appreciated! We use a took called [make-node-meeting](https://github.com/rvagg/make-node-meeting) to generate our agendas, and I just updated the [CommComm config file](https://github.com/rvagg/make-node-meeting/blob/master/examples/cc.sh) to be up to date with the latest members/observers.

**Comment by pup** [comment]
i could take over the aug 31st meeting if it happens! scrolling through the issues, i don't think there's anything we could put on the agenda for this one, so i'm +1 on cancelling this week

**Comment by renrutnnej** [comment]
+1 to cancel if we don't have anything to discuss

**Comment by hackygolucky** [comment]
SGTM. I don't think there's anything urgent. @pup let me know if there's anything you need help with(streaming vid is prob the most likely culprit on this) for the Aug. 31 meeting.

**Comment by nebrius** [comment]
Thanks everyone, I think we can safely cancel today's meeting. Talk to you at a later meeting!

**Comment by mhdawson** [comment]
+1
