### ISSUE TITLE
Node.js User Feedback project planning

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#112]
We'll be working on Node.js user feedback mechanisms as described in issue #96 to collect data to make better decisions to help improve every part of the Node.js project.
Project plan:
- Schedule a planning meeting where the initiative can be hashed out and a project plan is written. The Individual Directors should be present. In this meeting:
  - choose a survey medium(SurveyMonkey, Google forms, etc.)
  - make a list of current small surveys/feedback we need and create a schedule for these
  - document how folks could request a survey question/set(likely issue filing or a PR flow) so we could continue to add to the survey schedule moving forward
  - Identify relevant gatherings for holding user focus groups: choose a few places as a first step that people IN the meeting will be present at and could hold a meeting, collect feedback, and synthesize for publish.
- Publish User Feedback Initiative plan, implement, and iterate.
coordinate with the Evangelism WG to share the surveys via their platform using the schedule

Indicate your availability, if you'd like to participate, [HERE](https://doodle.com/poll/9p48vis2xfxv27mk).
cc @ashleygwilliams @williamkapke @nodejs/community-committee @nodejs/evangelism

**Comment by mhdawson** [comment]
Filled in my availability.

**Comment by bnb** [comment]
Also filled in mine 👍

**Comment by mikehostetler** [comment]
Did this happen? I'd love to be involved and have experience gathering feedback like this.  If it's stalled, I'm happy to pick up where it was left off.

Thanks!

**Comment by mhdawson** [comment]
@mikehostetler its not happened yet and if you would like to help lead the effort that would be great.

**Comment by dshaw** [comment]
@mikehostetler I'm game to help bootstrap this too. We should have at least 3 team members. @williamkapke, do you have cycles for this effort?

**Comment by dshaw** [comment]
I pencilled 30 minutes for this immediately following the CommComm meeting on Thursday, November 26th at 10am PT (local time: http://www.wolframalpha.com/input/?i=5pm+UTC,+Oct+26,+2017+in+local+time ).

If there is time during the CommComm meeting, I'd love to hear a brief overview of project objectives and how this group is expected to interact with the CommComm. If the onus is on me to get an item on the agenda, 🙋‍♂️ please advise. /cc @bnb

**Comment by mikehostetler** [comment]
@dshaw This works for me! Talk to you net week

**Comment by mhdawson** [comment]
@dshaw just a note that you said November when I think you meant October in your post above.

**Comment by bnb** [comment]
@dshaw I have added this item to the agenda. I believe we've talked about it in the past, but @hackygolucky may be able to help give a brief overview of the goals and how you can onboard to start helping get the work done 👍

**Comment by dshaw** [comment]
I shared context from the today's breakout discussion in the [original thread](https://github.com/nodejs/community-committee/issues/96#issuecomment-339795490).

I will be scheduling the next major planning session for "Node.js User Liaising" during the week of November 13th. In the interim, I'm will be seeking explicit feedback and sign-off on the [3 key points](https://github.com/nodejs/community-committee/issues/96#issuecomment-339795490) to ensure I can dedicate my time to this effort.

**Comment by bnb** [comment]
Removing cc-agenda label since this work is progressing in other areas and the original reason for adding has been hashed out 👍

**Comment by dshaw** [comment]
@bnb Remember the reason we had it on the agenda this time was to tune folks into the fact that this is happening and invite participation in the initial areas of focus. I would appreciate the mention. Doesn't need to be much.

**Comment by dshaw** [comment]
We should remove the label `good-first-issue`. 

If the person who edits this also wants to update the "user-feedback-init" label, please change the label to "user-feedback". Init is a different thing than "initiative and not a good abbreviation. Just simplify it to the same identifier as the repo.

**Comment by mhdawson** [comment]
I removed the "good first issue"  I'm also thinking we can probably close this with a pointer to the user-feedback repo where the work is going on ?

**Comment by bnb** [comment]
Yep, sounds good @mhdawson 👍 

This work is now being handled in https://github.com/nodejs/user-feedback - check it out if you're interested in contributing ♥️
