### ISSUE TITLE
Twitter Account

### ISSUE THREAD

**Issue by willi84** [nodejs/community-committee#115]
it would be easier to access and know about events if I could follow a twitter account ... i know its work :-/
but u can also share cool new stuff, talks, links etc  ... if u already have one, plz share :-)

**Comment by rachelnicole** [comment]
@willi84 do you mean a twitter account for the Node community committee, or something else?

The twitter.com/nodejs account might be what you're looking for, it posts news and conference updates and talk videos

**Comment by willi84** [comment]
I mean sth. which informs us about news of the committee itself, upcoming events of u or related topics .... if I can find it on @nodejs ... fine :-)

**Comment by bnb** [comment]
The @nodejs twitter account is owned by the Node.js Foundation, and used in that context - they post talks, tutorials, guides, and (occasionally) news from the GitHub org. 

There is an issue in the Evangelism WG repo (https://github.com/nodejs/evangelism/issues/254) that opened up discussion about the possibility of the Evangelism WG working with the account to get more community content in there. This could probably be extended to the members of the CommComm as well - if anyone's interested in engaging more there, happy to assist with more context.

**Comment by rachelnicole** [comment]
@willi84 do you mean something along the lines of an automated twitter bot that posts when issues & pull requests are opened / closed / updated?

**Comment by williamkapke** [comment]
Ping @willi84

**Comment by bnb** [comment]
Going to close for now - if you've got any further questions or would like to discuss further, feel free to ping us @willi84 😄
