### ISSUE TITLE
form letter for global outreach + translations

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/community-committee#12]
as per convo in the public board meeting, create a form letter to send to global groups for outreach (get translations, etc) cc/ @williamkapke @hackygolucky

**Comment by bnb** [comment]
@ashleygwilliams is there anything actionable on this still? If not, I'd like to close - but totally happy to see what we can do if there's still work to be done.

**Comment by bnb** [comment]
Going to close this. Please, feel free to re-open if there's more discussion to be had! 🙏
