### ISSUE TITLE
Email Alias not up to date with membership list

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/community-committee#125]
https://github.com/nodejs/email/blob/master/iojs.org/aliases.json#L108-L115

    "nodejs.commcomm@martynus.net",
    "hello@bnb.im",
    "loveless@gmail.com",
    "joesepi@gmail.com",
    "tracyhinds@gmail.com",
    "richard.littauer@gmail.com",
    "hi@jennwrit.es",
    "michael_dawson@ca.ibm.com"

vs

Bryan Hughes (nebrius - Community Committee Chair)
Jenn Turner (renrutnnej - Community Committee Secretary)
Tierney Cyren (bnb - Community Committee Secretary)
Ashley Williams (ashleygwilliams)
Emily Rose (Amorelandra)
Gregor Martynus (gr2m)
JP Wesselink (jpwesselink)
Michael Dawson (mhdawson)
Myles Borins (MylesBorins)
Rachel White (rachelnicole)
Tracy Hinds (hackygolucky)
William Kapke (williamkapke)
Michelle Garrett (msmichellegar)

**Comment by williamkapke** [comment]
It was created stemming from: #89 

Only those that chimed in were added to the list. I wasn't added because I missed the moment.

Fix: https://github.com/nodejs/email/pull/61

**Comment by bnb** [comment]
FWIW, we were not able to get the emails of everyone on the list. Just submitted: https://github.com/nodejs/community-committee/pull/126

**Comment by bnb** [comment]
Created a PR for @jpwesselink at https://github.com/nodejs/email/pull/68  - only need to add @msmichellegar now 😁
