### ISSUE TITLE
I'd like to be considered as a CommComm member

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#129]
On June 30, I asked to become an observer. #85 

According to the Contributing guidelines, I need to observe for 3 months before being considered for membership:
https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#becoming-a-member-and-collaborator

On Sept 30, it will be 3 months.
We have a meeting on Sept 28.
Not sure when this issue should be addressed: at or after the Sept 28 meeting.

Thank you for your consideration!

**Comment by bnb** [comment]
I am +1, but this does bring up an interesting point: 

There were a few skipped meetings in that time. Are those considered a part of the three months, or must it be _present in three months of meetings_?

Personally, I think those should be counted toward the three months - it was a choice on the CommComm's part to not have those meetings, which doesn't reflect on you - but I'm not sure if the Governance allows this. 

This may also be a discussion for another issue (want to keep this on-track), but it is relevant here.

**Comment by joesepi** [comment]
Yeah, I wondered about this as well, but the contributing doc just says "3 months":
https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#becoming-a-member-and-collaborator

So I wasn't sure. Whatever is decided though, I am okay with.

**Comment by rachelnicole** [comment]
Yeah, I think the current wording is set to mean 12 weeks chronologically, not 12 consecutive meetings. 

I'm +1 to Joe also becoming a collaborator.

**Comment by gr2m** [comment]
I’d suggest start a PR and we can approve / discuss there? Might be easier than +1 comments here

**Comment by mhdawson** [comment]
A agree its chronological.

+1 to joesepi being added.  He's met the required criteria and would like to make it as easy as possible for him to participate/contribute to our activities.
