### ISSUE TITLE
September 2017 Election for Community Commitee Chair

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#131]
We are electing a new Chairperson of Community Committee.

> The CC will elect from amongst voting CC members a CC Chairperson to work on building an agenda for CC meetings and collaborate with the Individual Membership Directors the wishes of the CC to the Board for a term of one year according to the Node.js Foundation’s By-laws. The CC shall hold annual elections to select a CC Chairperson; there are no limits on the number of terms a CC Chairperson may serve.

## Nominated candidates:
- @bnb Tierney Cyren
- @rachelnicole Rachel White

As stated in the previous election, expected responsibilities include but are not limited to:
- Create each meeting's agenda. 
- Create the event and make sure it is live-streamed in YouTube. 
- Chair and facilitate each meeting. It is the chairperson's responsibility to ensure that the meeting stays on track, sticks to the agenda, and finishes within the allotted time.
- Collaborate with the Individual Membership Directors(currently @williamkapke and @ashleygwilliams) on presenting requests to the Board from CommComm that need attention. 
- Collaborate with the TSC Chair and Director
- Coordinate efforts in shared repos, as listed in Admin

All Community Committee active members are eligible to vote, and have been sent a private, secret ballot via email. If you are having trouble with voting, please email tracy@nodejs.org

**The election opened at 3:17pm ET on September 15, 2017. The election will close at 3:17pm September 19, 2017 unless all eligible members have finished voting sooner than the window allotted.**

The results of the election will be published to this issue.

**Comment by hackygolucky** [comment]
The result of the election has finished early due to all members completing their votes prior to the deadline.

The result is a tie with equal votes going to both Tierney and Rachel. After consulting with both of the candidates along with the Individual Directors, it was determined that a healthy solution to this tie would be co-chairs of the role.

**If no one objects, Tierney and Rachel will be our new co-chairs!**

We will then move forward with onboarding and refining what the shared role and communication would need to look like in implementation to ensure a smooth execution of duties.

**Comment by jpwesselink** [comment]
Congrats to the both of yous!

**Comment by dshaw** [comment]
Great. I'd love to see this evolve to be 2 discrete roles with a chair and a board representative. Mirroring the TSC's structure.

I also encourage the CommComm to plan for this in the future and structure a standard tie-breaking process. The coin flip process we used for Gold Directors feels a bit too arbitrary. (This is coming from the _winner_ of the last one.) Strong consensus is hard. We should be encouraging those amongst us who wish to lead to build the robust coalition necessary to serve as an effective representative.

**Comment by bnb** [comment]
@hackygolucky Can this issue be closed?

**Comment by mhdawson** [comment]
I'm going to close since the election is over, please re-open if that's not the right thing to do.
