### ISSUE TITLE
Add CommComm Section to Node.js Website

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#134]
I recently noticed that on the Node.js website there's a larger section on Governance that discusses the TSC at length, and a section about Working Groups. Neither of these sections mentions the Community Committee (or the Board, for that matter). 

I'd like to propose we come up with some copy for the CommComm and work on PRing it into the website WG. Additionally, with the way that WGs work under the CommComm, it may be smart to PR a section for CommComm WGs into the Working Groups page.

Would also like to see if @nodejs/website has any feedback 🙏

**Comment by bnb** [comment]
Going to remove `cc-agenda` label for now - we've discussed, and it's a known task. If anyone has time/cycles to work on this, we'd be happy to help with questions/comments if you need feedback or guidance. ❤️

**Comment by Tiriel** [comment]
I'd actually like giving it a try, but I'll definitely need guidance, advices, and inspiration! I just don't want to overstep on anyone...

**Comment by amiller-gh** [comment]
@bnb, just got back from a war room in NYC with I'm finally getting free cycles (what is sleep again?). I have the site up and running with a new page added for CommComm – just need content now. How would you like to move forward with drafting it, should I just take a stab at it and put it in PR?

**Comment by JemBijoux** [comment]
Heyo, heard that there might be the need for some help with this. I'm just an observer for now, but willing to PR / assist with whatever.

**Comment by amiller-gh** [comment]
@bnb, @rachelnicole Prelim PR is up! Feel free to start wordsmithing, I left a few comments to kick off the process: https://github.com/nodejs/nodejs.org/pull/1465#pullrequestreview-75930192

Largely mimicked the TSC's page – figured we can save work on a fancier layout for when the site gets a bigger IA redesign.

**Comment by rachelnicole** [comment]
thanks @amiller-gh ! Checking it out now. :D

**Comment by bnb** [comment]
Wanted to give an update: 

Looks like https://github.com/nodejs/nodejs.org/pull/1465 was merged! 💥

From here, I'd like to ask if there are any additional steps we'd like to take, or if what's up is sufficient.

Thoughts?

**Comment by bnb** [comment]
Asked in today's meeting and no further feedback was provided. Going to close this 👍
