### ISSUE TITLE
Kicking Off "How I Got Into Node Series"

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#138]
Hey All - I was talking with Myles and Michael D. about doing a little series featuring TSC and CommComm members around how folks got into Node, how they started contributing, how they use it, interesting projects they are working on, etc. Just a quick and nice profile piece essentially.

Would anyone in this group be interested in participating? I'll be heading to Node.js Interactive, so happy to set up an in-person interview there or we can always do it over the phone or via email. Either ping me here if you are interested or send me an email zkeaton@linxufoundation.org. 

Also I think I know almost everyone in this group, but in case not I'm on the comms team for the Node.js Foundation :)

**Comment by bnb** [comment]
Happy to help out however I can, @ZibbyKeaton - just let me know what's needed!

**Comment by rachelnicole** [comment]
Same goes for me.

**Comment by ZibbyKeaton** [comment]
Let's set up a time to chat - I'll send you both emails with a few suggested times :)

**Comment by msmichellegar** [comment]
Happy to help! NodeConf Argentina are doing something similar.

Eg. https://twitter.com/nodeconfar/status/916309823695634432

**Comment by mcollina** [comment]
I'm always happy to help.

**Comment by bnb** [comment]
Ping @nodejs/tsc @nodejs/community-committee - would be awesome to hear who's interested in doing this ❤️

**Comment by ZibbyKeaton** [comment]
Hey All -

To streamline this a bit, please provide answers to the following questions and send them to my email zkeaton@linuxfoundation.org. I'll edit them and create an intro. Once I have this, I will share with you for final review. I'll also provide a date when we'll publish this in the ed cal cc: @msmichellegar @mcollina 

Question 1: When did you start getting into programming in general?

Question 2: When did you start using Node.js?

Question 3: What intrigued you about Node.js or what prompted you to use it vs. another platform/framework?

Question 4: When did you start contributing to Node.js?

Question 5: Why do you continue to contribute? And how do you contribute?

Question 6: If someone is interested in contributing, what advice might you provide them?

Question 7: How do you use Node.js (either at work or outside of work)?

**Comment by ZibbyKeaton** [comment]
Following up on this thread to see if you have answers to these questions @msmichellegar or @rachelnicole :) Feel free to not answer all the questions if you don't have the time! Know schedules are hectic.

**Comment by bnb** [comment]
@ZibbyKeaton wanted to check to see how the CommComm can help you get more people for this. Would love to help you continue to grow this series! Are there any specific criteria or is there any specific scope you're looking for - i.e. the individual is a Contributor?

**Comment by ZibbyKeaton** [comment]
This series focuses on community members of the Node.js. The intention is to put a face and a story on those that are contributing to the project. I want to interview folks that have been contributing for a long time and those that might have just started. A few folks who have not contributed to the project requested to be interviewed as well, however I would prefer that we focus on those that are contributing. We can potentially expand this out. It would be great to get more community members involved in this if possible. If you know someone that would be a great interview, I would recommend connecting me to them, and I can share the questions and get them featured.

**Comment by pup** [comment]
@ZibbyKeaton somehow the email i wanted to send isn't being delivered by the mail system.. are there any other venues in which to contact you?

**Comment by bnb** [comment]
Going to close this now since it's over a year old. Nevertheless, I definitely think we should continue this series – perhaps in a newer issue ❤️

**Comment by viveksharmaui** [comment]
Can i continue this series ?

**Comment by bnb** [comment]
@viveksharmaui this is a series focused on how folks got into contributing to Node.js. It doesn't seem like you're a current contributor, so I don't know if that would necessarily make sense. There is the [nodejs-collection](https://github.com/nodejs/nodejs-collection) if you're interested in submitting an article to _potentially_ be published.
