### ISSUE TITLE
The Node.js Collection: A Node.js Medium Publication 

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#14]
A few members of the evangelism working group recently reached out the the Node.js Foundation communications team to figure out how we could work together to incorporate more community-generated content across Node.js Foundation social channels. 

We decided a great option for this would be to create a Node.js Medium publication. In addition to working closely with representatives from the EWG, we also worked with @hackygolucky to come up with a plan to address this.

We plan to launch this publication tomorrow; it will be titled The Node.js Collection. I will share the link once it's live.

Below are our overall goals for the publication, what we are looking for in submissions and how to submit. A key goal of ours is to showcase content that reflects the ever-expanding diversity of ideas, innovation and voices within the Node.js community. Any efforts this group can lend to help encourage a range of submissions from all corners of the community and globe are greatly appreciated. 

**Purpose of Node.js Foundation Medium publication**
The Node.js Foundation’s new Medium publication serves as a channel for the community to broadcast to a wide audience its views related to Node.js and its ecosystem. This may include:
-Summaries of incubated projects or technical decisions made
-Working project initiatives
-Use cases and success stories
-Industry insights and best practices around Node.js and development trends (see topic areas below)
-Reports on Node.js and JavaScript events (these events must have a code of conduct to be considered)
-Other topics will certainly be considered, but it should be something of interest to the Node.js community

**Quality**
We are looking for posts that teach and provide value to our community. Contributions should include the meta-narrative that “Node.js is maturing and gaining widespread use in mainstream enterprises, while continuing  to inspire amazing potential and creativity among the massive community using the platform.” 
Sub-domains and topics for the Medium page include:
-Serverless/Cloud
-Containers
-Community
-Best Practices (How To)
-Embedded/IoT
-AI/Mobile
-More (Essentially news from the Foundation and potentially more editorial style content about the future of Node.js Core) - see Google Cloud Platform’s More section as an example [here](https://cloudplatform.googleblog.com).

**Guidelines/General Tips of Submissions**
Posts from members and community members must be vendor neutral, though they may mention vendors involved in specific project deployments if this serves the purpose of educating readers. 
Posts about hosting of an in-person event or speaking at an event, or other indications of meaningful participation in the community, are allowed, but again shouldn’t feel like an advertisement for your services or company. 

Your post must be your original content, but can be published on the Node.js Foundation Medium publication, if you received permission from the editors of the website to do so.  

All content should have a byline (preferably by a company engineer) and be published with Creative Commons with Attribution, so you’re welcome to republish on your blog.

The most interesting posts are ones that teach or explain how to do something in a way maybe others haven’t thought of. Good blog posts show hurdles that were encountered and explain how they were overcome (not that everything is rainbows and unicorns). 

A few posts that have performed well on the Node.js Foundation Medium page include [Walmart Strives to be an Online Retailer with Node.js](https://hackernoon.com/walmart-strives-to-be-an-online-retail-leader-with-node-js-9484a4ff51f7#.eoeu9j56i) (use case); [Node.js Transitions to LTS](https://hackernoon.com/node-js-v6-transitions-to-lts-be7f18c17159#.aj48k8d75) (news); [The Progress of Node.js Post io.js and Node.js merger](https://medium.com/@nodejs/the-progress-of-node-js-a-year-post-node-js-and-io-js-merge-and-where-the-technology-is-going-f168ce9ec8ee#.wf5ik86jt) (progress update).

When showing upstreaming of a patch fixing an issue for others, link back to the Github issue so readers can follow along. We don’t avoid critical commentary or broad issues, but approach them with sensitivity, professionalism and tact in a way that is beneficial and positive for the community. Node.js Foundation Medium posts should be no longer than 1,000 words and no shorter than 300 words. 
Diagrams or photos are strongly encouraged. 

**How to submit for consideration**
Please submit a brief summary and the topic of the post to medium@nodejs.org for consideration. The email alias reaches the review team consisting of Zibby Keaton, Sarah Conway, Tracy Hinds, Mikeal Rogers, Tierney Coren, Ross Kukulinski (with the potential to expand in the future).

Members of the Node.js Evangelism Working Group and Node.js Foundation PR team will review your submission in an a timely manner and provide the green light to draft the entire article or provide feedback or direction. 

If you are submitting an article or presentation that already exists, please send it in its entirety with a note on the expressed permission to publish from the owner of content. 

Once your submission has been approved, it will be added to the Node.js Foundation Medium publication publishing calendar and a publish date will be provided, so you may plan to promote accordingly through your personal and company’s social media channels. 

**Review Process for Original Posts**
The review team will provide comments and edits. Once the review team has made suggested edits, the post will be shared with the full evangelism working group, which will be given three days to provide additional edits/comments.

The review team will share all suggested edits with the author, who has final sign off on content. Zibby Keaton will then post to the Node.js Foundation Medium publication. The review process may take between two to three weeks depending on the number of edits and revisions involved. 

**Review Process for Created Medium Posts**
-Members from the evangelism working group are invited to become editors on Medium. If interested, contact Zibby Keaton here: zkeaton@linuxfoundation.org.
-Editors are allowed to request to put already available public content on the Node.js Foundation Medium publication if they follow the above guidelines.

**Comment by hackygolucky** [comment]
Thanks for coordinating this @ZibbyKeaton. Really excited for people in the community to be able to share the rad work they are doing and Node.js being able to give it some shine!

**Comment by ZibbyKeaton** [comment]
Hey All - The publication is officially live. Please share with your communities to get voices added. Below are a few suggested tweets to make your life easier. Link to the introduction of the pub here: https://medium.com/the-node-js-collection/introducing-the-node-js-collection-4d0d60e72a64#.n0mj043wz

- Have a good story around @nodejs? Check out Node.js Collection, curated-content for the millions of Node.js users: http://bit.ly/2l1TxXs

- Introducing @nodejs collection - curated-content for the millions of Node.js users. Have a story? Submit here: http://bit.ly/2l1TxXs

**Comment by nebrius** [comment]
Since we have https://github.com/nodejs/community-committee/issues/45 to track actionable items for the Node.js Collection, I'm going to close this issue. Please feel free to open a new issue if there are other things you need help with, and thanks again for reaching out!
