### ISSUE TITLE
Sort Community Committee Members alphabetically by first name in README

### ISSUE THREAD

**Issue by gr2m** [nodejs/community-committee#140]
follow up for https://github.com/nodejs/community-committee/pull/137#issuecomment-332949316

Any objections?

**Comment by williamkapke** [comment]
I prefer it. +1

**Comment by mhdawson** [comment]
Sounds good to me.

**Comment by hackygolucky** [comment]
Thank you!

**Comment by mikehostetler** [comment]
Included this fix in my #141 PR, with the update of sorting alphabetically by Github handle, as opposed to the original suggestion of first name.

Because I first converted the list to be formatted like the TSC Committee, I felt this made more sense.  Feedback appreciated.

**Comment by bnb** [comment]
Just shipped https://github.com/nodejs/community-committee/pull/141, so going to close this.
