### ISSUE TITLE
Add Ben Michel (@obensource) as a meeting observer

### ISSUE THREAD

**Issue by obensource** [nodejs/community-committee#142]
Please add me as an observer on the community-committee's meetings.

Thanks all, today was amazing. Really excited to jump in! 🙌

🎉🎉🎉

**Comment by gr2m** [comment]
Welcome :)

**Comment by bnb** [comment]
Will do 😁

**Comment by obensource** [comment]
@gr2m @bnb 🎉 🙌 🎉

**Comment by mhdawson** [comment]
+1

**Comment by williamkapke** [comment]
🆒  +1 for Ben!

**Comment by rachelnicole** [comment]
+1!!!!!

**Comment by obensource** [comment]
Aww thanks y'all! ❤️❤️❤️

**Comment by rachelnicole** [comment]
hey @bnb do we list observers on the main Readme do you know? If so, can we open a PR? if not, I think this issue can be closed :)

**Comment by bnb** [comment]
We don't currently list the observers on the README.md. Closing ❤️

**Comment by foadlab** [comment]
Please add me as an observer on the community-committee's meetings.

**Comment by pchrysa** [comment]
+1. I would like to be an observer on the community-committee as well

**Comment by Jiasm** [comment]
I want to be join the community-committee's meetings. this will be a great thing in my life.♥️♥️♥️

**Comment by carlosorochi** [comment]
Boa noite gostaria de participar deste projeto e compreender esse mundo de programação e seu fabuloso entreterimento entre o mundo da Informática e o que é realmente programação

**Comment by bmanandhar** [comment]
I am still at a boot camp, will graduate 2/5/19. Willing to be a part of Node 
CocmmComm so that I will get most out of the tech and will be able to contribute in the future.

**Comment by DemonDadZeu** [comment]
I am excited and interested in being an observer in the community committee. Pleas add me to the weekly video sessions so I can participate in this great project.
