### ISSUE TITLE
Postpone CommComm Meeting until 10/26

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#145]
Due to how many people showed an interest in the CommComm meeting at Node.js Interactive in Vancouver, we need to use our secondary live streaming setup that consists of streaming from a local machine out to YouTube. This presents a challenge, and the people I know who are able to help with this are currently unavailable.

Additionally, at least four members are unable to attend because they're at a conference in NYC. With this number of members missing, and the need for a unique technical setup, I think we should postpone the meeting.

I'm proposing we move the meeting to the next meeting date, 10/26. This will also allow us to get the [nodejs/make-node-meeting](https://github.com/nodejs/make-node-meeting) tool set up effectively and repeatably.

cc @nodejs/community-committee

🙏

**Comment by rachelnicole** [comment]
+1 Thank you Tierney!!

**Comment by amiller-gh** [comment]
May want to at-mention those who listed themselves as interested too, so people who don’t check Github obsessively aren’t confused in ~30 mins ;)

**Comment by bnb** [comment]
Also pinging:

@chowdhurian (Manil Chowdhury)
Toby Farley tobyfarley [at] gmail.com
@ParidelPooya (Pooya Paridel)
@rykerrumsey (Ryker Rumsey)
@baez (Behzad Karim)
@BinarySo1o (Therese Stirling)
@JemBijoux (Jem Bezooyen)
@amiller-gh (Adam Miller)
@obensource (Ben Michel - ref: #142)
@yosuke-furukawa (Yosuke Furukawa)
@Maurice-Hayward (Maurice Hayward)
@dshaw (Dan Shaw)
@mikehostetler (Mike Hostetler)

**Comment by bnb** [comment]
Ha, thanks @amiller-gh - my bad. ❤️

**Comment by mhdawson** [comment]
+1 on postponing

**Comment by obensource** [comment]
Thanks for making this work and happen @bnb! Really appreciate it! 🙌

Definitely understand postponement based on needing a better setup–regarding attendance tho it might be worth considering choosing a participant minimum based on the total number of members we have to avoid possible future postponement? At very least, might be good to have for the 26th.

Sincerely, a super stoked observer. 🎉

**Comment by dshaw** [comment]
Thanks for pinging. For those of us who are newbies, mentioning the time would help immensely so we can block off that time now.

**Comment by ParidelPooya** [comment]
Also for those of us who are newbies, is there any agenda? Or anything I should be prepare for it?

**Comment by rachelnicole** [comment]
@paridelpooya we usually post the agenda a little bit before, but we are behind due to conference travel and agenda items discussed at the collaborator summit last week.

**Comment by bnb** [comment]
Date/time for the next meeting: Thursday, October 26th at 12pm ET (9am PT).

For reference, you can also add the meeting time to your calendar with the Node.js Calendar: http://nodejs.org/calendar

As @rachelnicole said, we usually post an issue the day of, or the day prior. I'd suggest making a note to check the repo for meeting details + join info beforehand. 

To address your question @ParidelPooya: We build an agenda of issues tagged with `cc-agenda` across the Node.js GitHub org. You can request that this label be added if you think it's appropriate and should be discussed, create an issue in this repo asking for it to be added to the agenda, or comment in the agenda issue we publish before the meeting.

Thanks for the questions and feedback everyone - we're looking forward to seeing you soon! If there are topics or discussions you'd like to have, please _don't hesitate_ to create issues in the CommComm repo - we're always open to discussions, questions, and ideas... and you're all a part of this now! ❤️ 

cc @dshaw, @mikehostetler, @ParidelPooya, and @obensource

**Comment by bnb** [comment]
Closing this, since the 10/26 meeting has happened! See y'all at the next meeting ❤️
