### ISSUE TITLE
Node.JS + MySQL - Getting a Result

### ISSUE THREAD

**Issue by natashasweety7** [nodejs/community-committee#147]
I've been using [node.js ](https://mindmajix.com/node-js-training)and mysql for a while now but I've run into a new issue. I know I made the title seem basic but I just have no idea how I can title this question. So let's say I have:

connection.query(SELECT column FROM table, function(err, result) {
  if (err) {
    console.log(err)
  }
  if (result.length > 0) {
    console.log(result[0].thisNeedsToBeAVar)
  }
})
now in most cases, I would just use result[0].column and it's all good. But the entire issue is that column could be anything in my case. So I have that column as a var. How do I use it when I log the result? If I simply put the var there, it thinks that the column's name is literally whatever the var is called...

**Comment by rachelnicole** [comment]
Hey @natashasweety7 I think you're looking for the https://github.com/nodejs/help repository! 

This one is just for organizing community issues.

**Comment by bnb** [comment]
Going to close for now - @natashasweety7, definitely check out the https://github.com/nodejs/help repo that @rachelnicole suggested, and feel free to ping us with any more questions regarding this specific thread if you have them! ❤️
