### ISSUE TITLE
Running a Values session at JSConf Colombia 3 - 4th November 2017

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/community-committee#149]
I'll be heading to JSConf Colombia in a couple weeks as a speaker. I checked with @julianduque who said it should be possible for us to run a values sessions at the event 🎉

Are people open to this? What do we need to plan in order to make sure it is successful

**Comment by bnb** [comment]
As a post-project, I'd like to start collecting this data into the Community Committee repo if there aren't any objections. This is a HUGE resource for the entire community, and I'd like to see us centralize it if possible. ❤️

**Comment by bnb** [comment]
@MylesBorins is there any additional context for this issue, or can we close it? 🤔
