### ISSUE TITLE
Add Sarah Conway (@sarahkconway) as an observer

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#152]
Sarah Conway(@sarahkconway)  has requested she be added as an observer on the community-committee's meetings. Sarah is the PR Manager for the Node.js Foundation, and all in all a great resource to get advice from when it comes to outreach and news.

**Comment by bnb** [comment]
Added as an observer in https://github.com/nodejs/community-committee/issues/155

Going to close ❤️
