### ISSUE TITLE
Bench-marking team request for survey

### ISSUE THREAD

**Issue by mhdawson** [nodejs/community-committee#153]
The benchmarking team would like to request help sending out a survey.  They first draft of the questions we have is:

**These should be text entry to leave the answers open:**

- What is your primary use case for Node? (Web Developer Tooling / Standalone Servers / Cloud Services / Others)
- Do you have infrastructure in place for tracking performance on your applications.
- What kind of language dialect do you use? (ES5 / ES6 / ESNext whatever supported by most recent Node version / TypeScript / Other)
- Do you run *optimization passes* on your JavaScript before you deploy it to Node? (Minification / Bundling / Obfuscation / Other) 
- Where do you report performance regressions if you see them when you upgrade Node.js versions 
- What's your preferred way to write asynchronous code? (Callbacks / Promises / async/await / Other)

- Which Node.js feature do you believe affects your performance the most.
- What tools do you use to investigate performance issues ? What command line options do you use ? 

- Do you have use cases were you cannot use Node.js because it is single threaded.
- Would a worker model were additional threads are available but data is exchanged as messages or shared array buffers be useful for your applications.

- Is startup time important to your use case ? 
- Do garbage collector or optimizer pauses cause problems for your application ? 

- If you could choose which JavaScript language/Node.js feature should be optimized next, what would that be? Using the latest Node release as the basis.
- If you had to choose one, would you want the Node.js community to improve CPU or Memory efficiency ?

- What are the top 5 Node modules that you use most often?

**Comment by mhdawson** [comment]
@hackygolucky this is the survey we discussed earlier

**Comment by bnb** [comment]
@mhdawson Is it possible to add what type of answer you're looking for in each question (ex. radio, multiple choice, input, textarea)? Overall I think that would help us create the survey more quickly 👍

**Comment by bnb** [comment]
We should kick this over to the @nodejs/user-feedback team to make sure they can track it appropriately and help y'all get set up 👍

**Comment by bnb** [comment]
Going to remove the cc-agenda label and add the user-feedback-init label.

**Comment by mhdawson** [comment]
@bnb when we discussed it in the benchmarking WG meeting we thought textarea would lead to the most interesting answers.

**Comment by dshaw** [comment]
Noted for the next @nodejs/user-feedback meeting. Please update label to [neuf-agenda](https://github.com/nodejs/user-feedback/labels/neuf-agenda).

**Comment by bnb** [comment]
Only concern would be that certain questions (for example, `What kind of language dialect do you use? (ES5 / ES6 / ESNext whatever supported by most recent Node version / TypeScript / Other)`) may be too verbose to get an accurate answer without drop-off of people who are attempting to answer the survey.

Additionally, having pre-defined answers and an "Other" option for a question like that helps us quantify data more easily - we can easily and instantly see results instead of needing to manually process every answer and manually mark answers as falling into one category or another.

**Comment by hackygolucky** [comment]
Should we move this issue over to the @nodejs/user-feedback so it can be tracked there?

**Comment by dshaw** [comment]
@hackygolucky I'm happy for this issue to stay here for now.

We are having our first official meeting using Node.js project infrastructure and practices this Friday, 12/1. Having an issue like this outside of the group's work space gives us an opportunity to practice agenda building. We'll create a tracking issue when we establish a project owner. 🙏

**Comment by mhdawson** [comment]
@bnb we did not chose specific answers + other as we were not sure what would be a good specific answers.  We were more interested to see what people would suggest, even if it was all over the map.

**Comment by dshaw** [comment]
The NEUF team now has a [tracking issue](https://github.com/nodejs/user-feedback/issues/22) and will launch this as soon as the Node.js Foundation team finalizes the form. This issue can now be closed.

**Comment by bnb** [comment]
Going to go ahead and close this 👍
