### ISSUE TITLE
Node.js Foundation Community Committee (CommComm) - Meeting 2017-10-26

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#155]
# Time

**UTC Thu 26-Oct-2017 16:00 (04:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 26-Oct-2017 09:00 (09:00 AM) |
| US / Mountain | Thu 26-Oct-2017 10:00 (10:00 AM) |
| US / Central  | Thu 26-Oct-2017 11:00 (11:00 AM) |
| US / Eastern  | Thu 26-Oct-2017 12:00 (12:00 PM) |
| Amsterdam     | Thu 26-Oct-2017 18:00 (06:00 PM) |
| Moscow        | Thu 26-Oct-2017 19:00 (07:00 PM) |
| Chennai       | Thu 26-Oct-2017 21:30 (09:30 PM) |
| Hangzhou      | Fri 27-Oct-2017 00:00 (12:00 AM) |
| Tokyo         | Fri 27-Oct-2017 01:00 (01:00 AM) |
| Sydney        | Fri 27-Oct-2017 03:00 (03:00 AM) |

Or in your local time:
* https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Community+Committee+%28CommComm%29+Meeting+2017-10-26&iso=20171026T16&p1=1440
* or http://www.wolframalpha.com/input/?i=4pm+UTC,+Oct+26,+2017+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1-oCbwBTLm7yK47hc5iMCXcR78n6L1g4l2-VuRYQm5CM/edit?usp=sharing>
* **Previous Minutes Google Doc**: <https://docs.google.com/document/d/1zBorpMl49vF_xnSeE1tdKQ58vQlSvTFYtuxc8DAlvww/edit?usp=sharing>

## Agenda

Extracted from **cc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.
* Add CommComm Section to Node.js Website (https://github.com/nodejs/community-committee/issues/134)
* doc: doc expectations on TSC and CommComm members (https://github.com/nodejs/admin/pull/12)
* Internationalization/Localization Working Groups (https://github.com/nodejs/community-committee/issues/114)
* Node.js User Feedback project planning  (https://github.com/nodejs/community-committee/issues/112)
  * Bench-marking team request for survey (https://github.com/nodejs/community-committee/issues/153)
* We should all talk about expectations of the moderation team https://github.com/nodejs/admin/issues/24
* Define Core CommComm Values (https://github.com/nodejs/community-committee/issues/156)
* meta: fix case of extensions on internal docs and move CoC to admin repo https://github.com/nodejs/admin/pull/25

## Invited

* Ashley Williams (@ashleygwilliams - CommComm)
* Emily Rose (@emilyrose - CommComm)
* Gregor Martynus (@gr2m - CommComm)
* Joe Sepi (@joesepi - CommComm)
* JP Wesselink (@jpwesselink - CommComm)
* Michael Dawson (@mhdawson - CommComm)
* Michelle Garrett (@msmichellegar - CommComm)
* Myles Borins (@MylesBorins - CommComm)
* Rachel White (@rachelnicole - CommComm)
* Rod Vagg (@rvagg - CommComm)
* Tierney Cyren (@bnb - CommComm)
* Tracy Hinds (@hackygolucky - CommComm)
* William Kapke (@williamkapke - CommComm)
* Oz Haven (@therebelrobot - observer)
* Refael Ackermann (@refack - observer)
* Manil (@chowdhurian - observer)
* @ParidelPooya (Pooya Paridel - observer)
* @rykerrumsey (Ryker Rumsey - observer)
* @baez (Behzad Karim - observer)
* @BinarySo1o (Therese Stirling - observer)
* @JemBijoux (Jem Bezooyen - observer)
* @amiller-gh (Adam Miller - observer)
* @obensource (Ben Michel - observer)
* @yosuke-furukawa (Yosuke Furukawa - observer)
* @Maurice-Hayward (Maurice Hayward - observer)
* @dshaw (Dan Shaw - observer)
* @mikehostetler (Mike Hostetler - observer)
* @sarahkconway (Sarah Conway - observer)

## Notes

The agenda comes from issues labelled with `cc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Please make sure you have Zoom installed beforehand: https://zoom.us/
 
Zoom Link (PC, Mac, Linux, iOS, Android): https://zoom.us/j/4425663362
Zoom Meeting ID: 442 566 3362

A standing invitation exists for all @nodejs/TSC members who are not also CommComm members to attend in observer capacity.

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

**Comment by Tiriel** [comment]
Quick note: both links for local timings are set to 8pm UTC whereas the note says 4pm UTC

**Comment by rachelnicole** [comment]
If you did not receive the meeting invite please DM me @ohhoe or Tierney @bitandbang on twitter and we can send it to you

**Comment by dshaw** [comment]
Note that the calendar meeting is pointing to a [Hangout](https://hangouts.google.com/hangouts/_/nodejs.org/commcomm) that isn't actually being used. I think the calendar is managed under Admin. I'd be happy to look into how to fix.

**Comment by dshaw** [comment]
I mentioned the Kubernetes charter and how healthy I found their assertion that they would not get it right. Here's the document: https://github.com/kubernetes/steering/blob/master/charter.md

/cc @bnb @rachelnicole @gr2m

**Comment by msmichellegar** [comment]
Hey apologies, have been long haul flying and won't be there for today's meeting.

**Comment by obensource** [comment]
Thanks @bnb @rachelnicole @hackygolucky @dshaw @mhdawson and others for being so awesome and inviting!🍻

As an observer, I 100% feel like y'all gave us a great indication of how and where to jump in! 🙌

**Comment by mhdawson** [comment]
PR for minutes https://github.com/nodejs/community-committee/pull/159

**Comment by bnb** [comment]
#159 merged, closing this. ❤️
