### ISSUE TITLE
Define Core CommComm Values

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#156]
Per the work being done in documenting expectations of both TSC and CommComm leadership (https://github.com/nodejs/admin/pull/12 and https://github.com/nodejs/admin/pull/12#issuecomment-339382066), I'd like to kick off a Values definition for CommComm. 

Ideally, this will be several simple bullets that cover the various things that the CommComm holds as values. I think building out a first draft and shipping it would be a good start - we can iterate over time as much as is needed 👍

**Comment by hackygolucky** [comment]
Should we try to do an online working session with this akin to what we did at Collab Summit? There's free software that plays like sticky notes on a white board that we could work with, and then we're getting a more genuine result from individuals.

**Comment by rachelnicole** [comment]
that sounds like a good idea Tracy

**Comment by bnb** [comment]
@hackygolucky Love that idea. 💥

**Comment by mhdawson** [comment]
+1

**Comment by Tiriel** [comment]
Although I'm not a member, just wanted to let you know you definitely have my +1

**Comment by dshaw** [comment]
🙌  Interested in joining the CommComm Core Values session.

**Comment by bnb** [comment]
Going to leave this on the agenda for tomorrow's meeting with a TODO of getting a meeting time/plan of action for this nailed down.

**Comment by JemBijoux** [comment]
Hi there! I'd be stoked to help out or participate too. This is great.

**Comment by komawar** [comment]
would like to add my two cents (&be helpful)

**Comment by sarahnovotny** [comment]
Are the CommComm's values substantially different from the core project values?  It might make more sense to push the core project value conversation to conclusion and then identify where commcomm is different instead of doing independent value exercises.

**Comment by mikehostetler** [comment]
Agree with @sarahnovotny here. Values are an incredibly important and core part of any organization and it seems that CommComm would inherit the values from the TSC or the Board (please excuse my naiveté here).

Additionally, it strikes me as an anti-pattern that the CommComm would potentially have different values than others in the Node Foundation.  If the CommComm finds that one of their values is not represented, the best solution would be to advocate to represent that value across the entire group.

**Comment by bnb** [comment]
@sarahnovotny @mikehostetler This discussion stemmed from the discussion around the expectations doc, linked in the original comment (references: https://github.com/nodejs/admin/pull/12#issuecomment-330581822, https://github.com/nodejs/admin/pull/12#pullrequestreview-65012367, https://github.com/nodejs/admin/pull/12#issuecomment-335618421, https://github.com/nodejs/admin/pull/12#issuecomment-337677517, https://github.com/nodejs/admin/pull/12#issuecomment-337677517, https://github.com/nodejs/admin/pull/12#issuecomment-339086355, https://github.com/nodejs/admin/pull/12#issuecomment-339382066). 

This was an effort to follow through with the discussions and actions suggested in that issue on the side of the CommComm. That same effort (to the best of my understanding) would be parallelled by the TSC, independently (hopefully that answers your question @mikehostetler).

I agree that an overall values doc is more valuable than fragmented values docs.

@Fishrock123 @mhdawson @williamkapke I'd like to ask: Has there been any update on a values doc from the TSC? If not, I'd like to propose that we work together in the nodejs/admin repo to define a minimum (and non-fragmented) set of values for the project.

**Comment by mikehostetler** [comment]
@bnb Thanks for the background!

**Comment by mhdawson** [comment]
There has not been work on specific TSC values yet.  

My understanding of the concept of having values for a particular group was that they would be more specific to the focus of that group  (ie additive versus being in conflict) versus the more general values that apply across all of the groups. For example in groups that focus on code a value might be "test-driven development" which would not be applicable to other teams.

In any case its a bit hard to see were the line between general/group might be until we have the top level ones in place.  I think we had discussed trying to get an initial version of those documented to give people a more concrete idea of what they will look like.

**Comment by bnb** [comment]
Closing this in favor of the Node.js Values efforts happening right now. We can reopen something similar in the future if we need something additive to those efforts 👍
