### ISSUE TITLE
Beginning CommComm Contributing Office Hour(s)

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#157]
Since we've got a LOT of interest in contributing to the Community Committee, I figured we could start doing office hours for getting started with or building up contributions to the Community Committee.

Some feedback I'd like to get from y'all who are already participating or looking to participate:

- As a new contributor to CommComm, what resources would help you start contributing more?
- As a new contributor to CommComm, which resources were most helpful when contributing?

I'm happy to help kick this off, hosting a regular Office Hour every other week, on Thursday from 12:00-1:00pm ET. This is a complementary time to the normal CommComm meeting, which will (hopefully) enable people to know when they'll be able to connect.

**Comment by mhdawson** [comment]
Sounds reasonable.  My suggestion for getting people started is to define a concrete set of "initiatives", "goals" and "tasks" that people can grab.

**Comment by Tiriel** [comment]
I'll second that. Most helpful things would be to know what to do, technically speaking. What specific can be helpful.

The "Good first issue" label is extremely helpful for that, and more of that sort of help should be promoted.

**Comment by bnb** [comment]
Going to remove cc-agenda label for now - when we get this rolling (targeting next week), we can see if there are any further action items that need to be raised to the Committee 👍

**Comment by bnb** [comment]
Unfortunately I've been traveling for work over the last four weeks, and will be heading into December as well. I'd still very much like to do this, but just haven't had cycles to get it set up.

**Comment by amiller-gh** [comment]
Closing due to in-activity 🙏 Let me know if someone would like to take point on this, otherwise we'll keep to "good first issue" labels and relying on the individual working groups to own their own on-boarding.
