### ISSUE TITLE
Should we work on making CommComm repos Code + Learn friendly?

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#158]
There's been talk over the last year about opening up the Code + Learn program to repos other than Node.js core. The real limitation is people resources–mentors from a repo able to provide clear onboarding/contributing/collaborating guidelines , good-first-pr issues, and availability for reviewing PRs. 

Code + Learn helps gain contributors long-term. It would be great to invest in this for our work as well.

**Comment by dshaw** [comment]
@hackygolucky This seems like a great idea.

From what I've observed, the #1 need in the CommComm right now is active collaborators. Given that need, I would propose that primary focus should be on recruiting active members.

**Comment by bnb** [comment]
@hackygolucky What are the steps needed to help enable this? 🤔

**Comment by hackygolucky** [comment]
1. Getting a couple of our issues around documenting onboarding and contributing PRed and walking through getting started with a willing participant to see what gaps we still have that make it too difficult.
2. Scheduling some admin time on a weekly basis to make sure that issues are appropriately labeled, including `good-first-contribution`. 
3. Watch for the 2018 Code + Learn schedule and start coordinating if any CommComm members will be there and would like to mentor. This also requires that we keep up with the `good-first-contribution` labels.

**Comment by bnb** [comment]
Added "good first issue" to this, since it would probably be helpful if someone who wanted to start helping out on managing it... meta, I know 😅 

Happy to help mentor if needed as well.

**Comment by amiller-gh** [comment]
Bump on this thread ❤️ @bnb, @hackygolucky, think this is still worth pursuing? I know Website Redesign would like to do an educational session of sorts – may be a good candidate as a C+L supplement.

**Comment by bnb** [comment]
Pinging this again. Discussed in today's CommComm meeting since there's a lack of tests for Code & Learn contributors to contribute ❤️

**Comment by hackygolucky** [comment]
I think it's certainly still worth doing, and I laid out the firs steps that we should do to start the work and begin to maintain it, but I can't volunteer myself to do that work. This is parking lot/backlog unless someone else can pick it up 😬

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
