### ISSUE TITLE
Revise the README to be more helpful for new users

### ISSUE THREAD

**Issue by rachelnicole** [nodejs/community-committee#161]
As the README stands right now, people that are interested in becoming a part of the community committee don't really have any idea of what we do. 

I think that we should revisit a lot of the existing markdown files that outline governance, code of conduct, collaborating, and contributing and make sure they're explained in the main readme file instead of just linking to it. 

We should also list working groups and initiatives more clearly, with a description of what they are / the help we need. And have visible action items people can take. 

If we don't make it more explicit about our practices, it's going to create a barrier to entry for new people wanting to get involved. 

- [ ] - Revise README to be more verbose
- [x] - Outline groups that are under our jurisdiction
- [ ] - Explain more about processes that happen during meetings
- [ ] - Move how to become a member and expectations to have higher visibility

I think these would be a start, feel free to add more as you see fit.

**Comment by mannypamintuan** [comment]
Hello @rachelnicole & @bnb!

I would like to take on this task as a `good first issue` and as someone relatively new to the community, this would be a great exercise in learning more about the community committee and the topics related to governance, code of conduct, collaboration, and contribution.

:) I appreciate the checklist and I would love to get started.

Who would be good points of contact to ask questions as I make the revisions?
Would a good approach be to re-read the README file and start marking sections that leave me with questions?  (As a someone new the community, I do not have a lot of prior knowledge on all that is involved, so my cache is clean :D )

I look forward to hearing back!
-Manny

**Comment by bnb** [comment]
@mannypamintuan Thanks for stepping up to take this on!

Good points of contact for this specifically would likely be any member of the Node.js Community Committee. If you have questions, definitely post them here - but also don't hesitate to reach out to _any_ of us. I'm personally happy to help if you have any questions as you go.

I definitely think that your suggestion of reading through the README.md and marking it up with your comments is a *very* good way to approach it. Once you do that, you could share that back into this issue and we could compare it with the things that the members of the CommComm note that are missing/needed. Combine the two and I think we'll have a holistic view on what's needed from the point of view of someone approaching the CommComm for the first time _and_ from a state of content-completeness. 👍

**Comment by mannypamintuan** [comment]
You are most welcome @bnb!

Thank you for the guidance, I will get started on this issue and any questions I will post here, but will also branch out and contact the CommComm members as needed 😄

**Comment by bnb** [comment]
>Outline groups that are under our jurisdiction

We've done that a bit in https://github.com/nodejs/community-committee/pull/167 and https://github.com/nodejs/community-committee/pull/191 - checked it off 👍

**Comment by ryzokuken** [comment]
@bnb @mannypamintuan it this still being worked on?

**Comment by oe** [comment]
@ryzokuken As far as I know, no. If you want to take a stab at it, feel free to do so, even if it's being worked on! We're here for any questions.

**Comment by ryzokuken** [comment]
@oe I'll jump in promptly. Thanks!

**Comment by ryzokuken** [comment]
@oe @bnb Let's start with pt. 3 and 4 because they are much less vague than pt. 1.

## 1. Explain more about processes that happen during meetings
## 2. Move how to become a member and expectations to have higher visibility

Could any of you take out the time to let me know any of these?  
It's okay if you're busy right now, even if you could point me to someone else who could it'd be helpful.

**Comment by oe** [comment]
@ryzokuken We're currently trying to shift focus away from becoming a members, and more towards engaging in one of our intiatives. I think it might be better if we put that front and center. A more detailed description of each initiative, and some initiatives that are currently looking for help might be good.

**Comment by ryzokuken** [comment]
@oe So from what I infer from it, accepting new members isn't the top priority, right? Makes sense.

I found a list of initiatives at https://github.com/nodejs/community-committee/blob/master/STRATEGIC-INITIATIVES.md is that all, or does this list need some changes? Should we list out a few to the README? (Especially those which require help)

**Comment by oe** [comment]
@ryzokuken That list should be up to date. I was thinking of having something of a dashboard for initiatives which are easy to contribute to (such as the translation initiative), keeping a complete list of them in the README is probably as bad idea since we'd have to sync the `STRATEGIC-INITIATIVES` file and the README.

**Comment by ryzokuken** [comment]
@oe that's completely on point. Could you point out which specific initiatives are easier to contribute to than the others? In the meantime, I'd look all of those up and will try my best to make a guess.

**Comment by bnb** [comment]
@ryanmurakami I'd suggest i18n, User Feedback, Website Redesign, and Badges for now.

**Comment by ryzokuken** [comment]
@oe @bnb should I add this small sub-list of special initiatives in the initiatives section itself, or do I make a new section named something like "Getting Started" and list them in there?

If you prefer the latter, where should I position the new section? Right after "Contributing" and before "Current Initiatives, Teams, and Working Groups" or somewhere near the end?

**Comment by bnb** [comment]
@ryzokuken I'd add it inside of the [Current Initiatives, Teams, and Working Groups
](https://github.com/nodejs/community-committee#current-initiatives-teams-and-working-groups) section 👍

**Comment by bint** [comment]
Hi I'd like to be involved and help with this too. Is there anything I could do to assist or be useful? Please let me know. Thank you!
