### ISSUE TITLE
User Feedback Project group formation

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#162]
A group has been formed around the User Feedback and Outreach effort with an associated repository: @nodejs/user-feedback and https://github.com/nodejs/user-feedback

Thank you, @hackygolucky for capturing notes from the [informal gathering today](https://docs.google.com/document/d/1NOQsC-nyYz75IMJVitzTwuCYgLWWLhWaSvWRPveiumU/edit#). See notes dated October 31st at the bottom.

@mhdawson has volunteered to be the Champion from the CommComm to work with this newly formed team. Dan Shaw will lead the effort and will be focusing on Enterprise User Feedback. He is joined by @williamkapke, representing Individual Members and @mikehostetler, representing local communities, using his local Chicago community as a starting point. @bnb and @hackygolucky will continue to support and act as advisors.

After laying out the project plan where we identify our initial areas of focus and document the areas we know we would like to explore but cannot yet, our initial focus will be on recruiting. At the next CommComm meeting (Nov 9th), @nodejs/user-feedback would like to share a high level overview of this initiative. The we would like to present the plan at the following meeting. (Which is currently scheduled for Thanksgiving Day. ??)

**Comment by dshaw** [comment]
@bnb Can you add this to the CommComm meeting agenda and introduce folks to https://github.com/nodejs/user-feedback and explicitly invite new participants around the initial activity areas? (Reminder: I will not be attending since I will be on flight home from NodeConf.EU.)

**Comment by ahmadnassri** [comment]
note: the note doc linked is set to "anyone can edit"

**Comment by dshaw** [comment]
Thanks for the heads-up, @ahmadnassri. CC @hackygolucky

**Comment by dshaw** [comment]
@nodejs/user-feedback is established and on a [regular cadence](https://github.com/nodejs/user-feedback/labels/neuf-meeting). Come [join us](https://github.com/nodejs/user-feedback/). Closing.
