### ISSUE TITLE
rejoining the commcomm

### ISSUE THREAD

**Issue by pup** [nodejs/community-committee#165]
so it's been a couple of months since i left the commcomm because of mental health concerns (#110). things have since calmed down in the project we started, ayo.js, (and also in my life) and as such i'd like to retire from being an emeritus, so to speak! i don't know if there's a process for this, though, and i respect if this doesn't work this way, i'm just making an inquiry!

**Comment by bnb** [comment]
I don’t believe we have a defined process. @hackygolucky do you know if @pup will need to go through the full membership process again, or if they can effectively rejoin because they are an emeritus?

**Comment by hackygolucky** [comment]
oooh this is such a good question. We don't have language for this, so I think we should create it. It would be good to reward those who reached emeritus status and have the bandwidth/would like to return. My short proposal would be a request to be reinstated(as @pup did here) and active members voting on it. Is that even necessary? I'd love others' opinions. We have a process for trimming inactive members out, so I'm trying to walk through a scenario where this simple reinstatement doesn't make sense.

**Comment by pup** [comment]
@hackygolucky the only scenario where i don't think a simple reinstatement of an emeritus wouldn't be appropriate would be if the emeritus was removed from the commcomm because of code of conduct (or other) offenses. but in that situation, i'm not sure whether they would be made an emeritus at all?

**Comment by pup** [comment]
whoops - accidentally closed

**Comment by rachelnicole** [comment]
I'm totally 100% fine with @pup coming back as a full member! 

Though I do think we need to put in some kind of time period in the future like maybe just 1 month where there is a temporary pause on voting capabilities. I understand the need to step away from things when you're stressed / life is more important and think it's ok for people to do so, but we should prob set something up so that it doesn't become a repeated process? 

I'm sorry if this doesn't make sense i've been up for a v long time.

**Comment by bnb** [comment]
Next steps that we landed on taking (in the private session of today's meeting):

- Sending out a blind ballot to current voting members, to vote on @pup's membership.
- PRing documentation for reinstatement of emeritus members who have requested to rejoin.

Further, @hackygolucky has started a discussion around lazy consensus and blind ballots when it comes to votes that need to be taken around _people_ that I think is moving in a positive and mature direction for the CommComm. You can find it here: https://github.com/nodejs/community-committee/issues/169

**Comment by hackygolucky** [comment]
Just as an update, we're still waiting on two members of @nodejs/community-committee to cast their vote before closing this. Please reach out to me if you'd like to abstain.

**Comment by pup** [comment]
@hackygolucky is there any progress on this?

**Comment by hackygolucky** [comment]
I'm sorry about the delay @pup. We were waiting for the final vote to come in, but we have provided more than enough time to vote. 

With no objections and 3 abstentions, CommComm has voted  to immediately reinstate Emeritus CommComm member Olivia(@pup) as of today's closing of the poll. http://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=1&id=E_fc84eea1909c4ab3&algorithm=runoff

**Comment by pup** [comment]
woo! i'll open a pull request. in the meantime, can someone invite me to the organization and add me to the relevant team(s)?

**Comment by mhdawson** [comment]
You should be getting the invites.

**Comment by bnb** [comment]
Removing agenda label since this has passed.

**Comment by bnb** [comment]
Merged: https://github.com/nodejs/community-committee/pull/178
