### ISSUE TITLE
Broader Community Committee Team in the Node.js Org

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#166]
I've been consistently pinging @nodejs/community-committee in several issues, as do others, where attention and feedback is needed. Once that that I'd not previously considered is that it would be helpful if Observers working toward membership had the opportunity to be included in these pings to help add context, review, and contribute. 

I just saw how the Automation team is set up, with several sub-teams: 

![image](https://user-images.githubusercontent.com/502396/32568636-ddd5c420-c48c-11e7-92a9-6526115ac4d4.png)

I would like to propose that we add a @nodejs/community-committee-(something) as an alias to include Observers in discussions and be able to enable them to engage everywhere that CommComm work is happening.

The only possible concern I see off the bat is adding more members to the Node.js GitHub org, but I don't necessarily see that as a problem - just an extra step in the process.

**Comment by refack** [comment]
Could do sleve inversion - **<span>@</span>nodejs/community-committee** could be everyone, and  **@nodejs/community-committee-members** be just voting members

**Comment by hackygolucky** [comment]
so, I think this is something we'd need to bring up in nodejs/admin, @bnb 

> The only possible concern I see off the bat is adding more members to the Node.js GitHub org, but I don't necessarily see that as a problem - just an extra step in the process.

Historically, we have added people to the GitHub org when they've hit some measurement of contribution within a repo(s). What we're talking about here is potentially adding folks who would be given GitHub org status by simply asking to be an observer of CommComm? I may be misinterpreting what you said...

**Comment by bnb** [comment]
@hackygolucky You're understanding what I said perfectly. That's the historical precedent, and I'm not sure if changing/dramatically simplifying that will be an issue.

**Comment by bnb** [comment]
Going to close this, given the state of what we discussed in our meeting yesterday 👍
