### ISSUE TITLE
Node.js Foundation Community Committee - Meeting 2017-11-09

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#168]
Node.js Foundation Community Committee (CommComm) Meeting 2017-11-09
--------------------------------------

## Time

**UTC Thu 09-Nov-2017 16:00 (04:00 PM)**
<details>

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 09-Nov-2017 08:00 (08:00 AM) |
| US / Mountain | Thu 09-Nov-2017 09:00 (09:00 AM) |
| US / Central  | Thu 09-Nov-2017 10:00 (10:00 AM) |
| US / Eastern  | Thu 09-Nov-2017 11:00 (11:00 AM) |
| Amsterdam     | Thu 09-Nov-2017 17:00 (05:00 PM) |
| Moscow        | Thu 09-Nov-2017 19:00 (07:00 PM) |
| Chennai       | Thu 09-Nov-2017 21:30 (09:30 PM) |
| Hangzhou      | Fri 10-Nov-2017 00:00 (12:00 AM) |
| Tokyo         | Fri 10-Nov-2017 01:00 (01:00 AM) |
| Sydney        | Fri 10-Nov-2017 03:00 (03:00 AM) |

Or in your local time:
* [Time Conversion](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Community+Committee+%28CommComm%29+Meeting+2017-11-09&iso=20171109T16&p1=1440)

</details> 

## Links
* **Minutes Google Doc:**
<https://docs.google.com/document/d/1SWJjGXEpTdu_2RbUkHr05h3WZco3pFrq59p4gDoKTnc/edit?usp=sharing>
* **Previous Minutes Google Doc:** <https://docs.google.com/document/d/1-oCbwBTLm7yK47hc5iMCXcR78n6L1g4l2-VuRYQm5CM/edit?usp=sharing>_

## Agenda

Extracted from **cc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

* Revisit Add some scope (aka: stake your claim!) (ref: https://github.com/nodejs/community-committee/issues/13#issuecomment-340038119)
* Define Core CommComm Values (ref: https://github.com/nodejs/community-committee/issues/156)
* Add Initiatives section + User Feedback Initiative (ref: https://github.com/nodejs/community-committee/pull/167)
* Internationalization/Localization Working Groups (ref: https://github.com/nodejs/community-committee/issues/114)
* Broader Community Committee Team in the Node.js Org (ref: https://github.com/nodejs/community-committee/issues/166)
* Add CommComm Section to Node.js Website (ref: https://github.com/nodejs/community-committee/issues/134)

## Invited
* Ashley Williams (@ashleygwilliams - CommComm)
* Emily Rose (@emilyrose - CommComm)
* Gregor Martynus (@gr2m - CommComm)
* Joe Sepi (@joesepi - CommComm)
* JP Wesselink (@jpwesselink - CommComm)
* Michael Dawson (@mhdawson - CommComm)
* Michelle Garrett (@msmichellegar - CommComm)
* Myles Borins (@MylesBorins - CommComm)
* Rachel White (@rachelnicole - CommComm)
* Tierney Cyren (@bnb - CommComm)
* Tracy Hinds (@hackygolucky - CommComm)
* William Kapke (@williamkapke - CommComm)
* Oz Haven (@therebelrobot - observer)
* Refael Ackermann (@refack - observer)
* Manil (@chowdhurian - observer)
* @ParidelPooya (Pooya Paridel - observer)
* @rykerrumsey (Ryker Rumsey - observer)
* @baez (Behzad Karim - observer)
* @BinarySo1o (Therese Stirling - observer)
* @JemBijoux (Jem Bezooyen - observer)
* @amiller-gh (Adam Miller - observer)
* @obensource (Ben Michel - observer)
* @yosuke-furukawa (Yosuke Furukawa - observer)
* @Maurice-Hayward (Maurice Hayward - observer)
* @dshaw (Dan Shaw - observer)
* @mikehostetler (Mike Hostetler - observer)
* @sarahkconway (Sarah Conway - observer)
* @Tiriel (Benjamin Zaslavsky - observer)

## Notes

The agenda comes from issues labeled with `cc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ/live** when we turn it on. 

There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and we'll be online shortly. ❤️

## Joining the meeting

Zoom join link for invited members and observers: https://zoom.us/j/415109804
A standing invitation exists for all @nodejs/TSC members who are not also CommComm members to attend in observer capacity.

**Comment by gr2m** [comment]
I’m sorry I can’t make it, I’ll be on my way to http://offlinefirst.org/camp/

**Comment by Tiriel** [comment]
I'd actually like to come as an observer, but I may not be able to talk (still at work at this hour). Would that be a problem, or should I attend on the public url?

**Comment by bnb** [comment]
@Tiriel You can join as an observer, even if you can't talk - I will add you to the list 👍

**Comment by Tiriel** [comment]
@bnb Awesome! Thanks!

**Comment by msmichellegar** [comment]
Sadly I can't make this meeting time (4pm London), I have a work meeting 😢 

Will read the notes, and might be able to join at the end.

**Comment by komawar** [comment]
Hi, I'd like to join this meeting. How do we do this?

**Comment by obensource** [comment]
Has the zoom link already been sent? Haven't received it yet.

**Comment by mikehostetler** [comment]
Looks like the times are off, due to DST ending. 

I'm in US Central time, which is listed at starting at 10am.  However, the Node.js Calendar (http://nodejs.org/calendar) says it starts at 11am CT.

**Comment by bnb** [comment]
Meeting link, starting in ~30 minutes: https://zoom.us/j/928979517

**Comment by bnb** [comment]
Updated Zoom link, since we're trying something new with the streaming: https://zoom.us/j/415109804

**Comment by Tiriel** [comment]
Sorry, service too bad, I'm switching to YouTube :(

**Comment by pup** [comment]
closing this since it's way in the past
