### ISSUE TITLE
Individual Membership as a responsibility of the Community Committee

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#170]
Individual Membership to the Node.js Foundation was established back in 2015 as a way to represent the voice of the community on the Node.js via Board seats. 

Individual membership costs $100 a year, or $25 for students. Contributors to the Node.js project, including all Working Groups and sub-projects, are eligible for free membership. The current benefit to being an Individual Member includes 20% off regular price registration to Node Interactive, access to the Node.js travel fund for request, and a vote/voice via the two Individual Membership Directors.

We are reaching a critical point of time for the Individual Membership where it has existed in its current state for a few years. This feels like enough time to examine what value it provides currently, who is responsible for improving it, and how it can be improved. 

Should the Community Committee, considering its scope, take the Individual Membership on as an initiative? This would be an incredible responsibility, but the Community Committee is a point of entry for the ecosystem that could positively contribute to the future value of the Individual Membership through quality feedback collection and project management. This has been brought up in various conversations with CommComm members in meetings but never addressed as a decision to vote on.

Responsibilities that exist with this currently:
- Administration of the membership platform: (Node.js Foundation team via @hackygolucky)
- Administration of the election platform for Individual Membership Director elections: (Node.js Foundation team via @hackygolucky)
- Assessing and editing membership benefits: Node.js Foundation team + Board of Directors
- Representation of voice at the Board level and gathering feedback from the member class: Individual Membership Directors(currently @williamkapke and @ashleygwilliams)

**Comment by bnb** [comment]
I'd like to say that I'm generally +1 to this. I've personally been very critical of how Individual Membership has approached since its creation, but I do think that the Community Committee could likely help enable both the project - Individual Membership - and the _members_ themselves.

Taking on Individual Membership will need a non-trivial amount of effort, so I'd like to suggest that we have someone explicitly champion the effort - similar to how the TSC is currently taking on new projects.

**Comment by dshaw** [comment]
I think this is a great idea. I see having Individual Membership representation working through the CommComm as the most effective to grow, support and engage Individual Members.

**Comment by refack** [comment]
I have bandwidth for helping with admin stuff.

**Comment by chowdhurian** [comment]
CommComm taking this on would be great. Maybe contingent on getting enough members and observers on board to eventually drive this. I can put time into the tasks.

**Comment by komawar** [comment]
From a third person standpoint, (w/o much context on the history), I think this looks like a good idea. The [blog](https://nodejs.org/en/blog/community/individual-membership/) that identifies who a Node.js Individual Member is under the community tag, there more information out there but looks mostly in github. (Of course, my google search might not be exhaustive). As a potential new Individual Member, I would expect CommComm to chaperone this.



count me in, will have bandwidth to contribute to the effort.

**Comment by JemBijoux** [comment]
I'm definitely a plus one for this. It seems like there's a lot of potential here.

Sounded like there's a wishlist of things that could be done better, it might be nice to enumerate some of those items here. Mentioned briefly during CommComm session:

- quarterly newsletter, 
- getting more regular feedback from individual membership (is this related or overlap at all with the User Feedback Initiative?)

If there's hesitation, maybe we could also touch on some of the extra responsibilities that would be involved (if they haven't already been mentioned above) so folks know what we're getting into.

**Comment by bnb** [comment]
@ParidelPooya Currently we have ~200 individual members. That number did go up recently with membership being bundled in some way with Node.js Interactive tickets. That's almost the full extent of my knowledge, I know @hackygolucky can definitely help provide any additional scope.

**Comment by bnb** [comment]
I'd like to start keeping a list of those that have expressed interest in helping champion/maintain Individual Membership - and have bandwidth to so so: 

- @refack 
- @chowdhurian 
- @komawar 
- @JemBijoux

**Comment by ParidelPooya** [comment]
I have bandwidth to help too. please add me to that list @ParidelPooya

**Comment by bnb** [comment]
@ParidelPooya Added 👍

**Comment by hackygolucky** [comment]
I am happy to help, I just down want to own it wholly anymore :) (and also by it being moved out of the Foundation, I shouldn't be wholly owning it anyway)

**Comment by hackygolucky** [comment]
Also at this month's count @bnb @ParidelPooya we are at 241 for membership. The demographic makeup is about half collaborators who have signed up for free because they get the contributor discount, and the rest were mostly signups through our conference registration add-on.

**Comment by devsnek** [comment]
> Contributors to the Node.js project, including all Working Groups and sub-projects, are eligible for free membership.

Probably the wrong place to ask, but how can I "redeem" this, I'm very interested in membership.

**Comment by Bamieh** [comment]
@devsnek 
nodejs.org/en/foundation/members/#becoming-an-individual-member

> Please contact us for discount codes. You are required to have a GitHub account to register. please email membership@nodejs.org.

**Comment by bnb** [comment]
Removing cc-agenda label for now. If it needs to be re-added to discuss further work, please feel free to ping a CommComm member or add it yourself 👍

**Comment by hackygolucky** [comment]
We will be meeting at Collab Summit Berlin, May 31, 2:30pm GMT+2 to discuss formation of a subgroup to workshop and draft out the challenges with the Individual Membership:

What questions we are trying to answer to assess expectations from the community and the Board. The CommComm owns the individual membership program. From that program, we need to define who the targets that should/could be represented by the remaining Individual Membership seat. A program that is of value to the individual membership group, collecting regular feedback in order to make decisions for needs expressed. 

Once this subgroup has been established, @sarahnovotny, Node.js Board member and Joint Strategy Sub-committee co-chair has offered to attend the next CommComm meeting that will focus on this program to provide context and focus.

**Comment by Bamieh** [comment]
I opened a related issue last year related to this: https://github.com/nodejs/community-committee/issues/175.

**Comment by hackygolucky** [comment]
@Bamieh the issue you filed is in reference to the Node.js GitHub organization members process, governance, and badging. What we are talking about in this issue is the Node.js Foundation individual membership program, which are separated for terms of scope and who oversees these groups. The Board of Node.js and the CommComm are responsible for the Individual Membership program. The TSC + CommComm is responsible for permissions and governance processes for GitHub membership management.

**Comment by Bamieh** [comment]
@hackygolucky I understand. This issue is about taking responsibility of the foundation individual membership rather than the foundation membership itself.

I mentioned that issue with the thought that if the commcomm becomes responsible for the foundation individual membership and has a shared responsibility over the github membership as well, We can motivate people to join the individual foundation membership by also inviting them to the Node.js github team.

**Comment by hackygolucky** [comment]
Ah, so, @Bamieh the scope is very different of these groups. The membership of the Github Node.js org is only for those commiting to the Node.js project itself. Whereas the Individual Membership, at least as it currently stands, was reaching for the wider community and ecosystem of those who contribute to Node.js, consume it, or work on something that is tangential to but contributes to the wellbeing of Node.js(such as npm, yarn, the modules ecosystem, v8, etc.). 

So are you proposing keeping the individual membership scope of the Node.js Foundation only to those who contribute to the Node.js project(which is the GitHub membership)?

**Comment by Bamieh** [comment]
@hackygolucky seems that you've got disconnected from the group call so I was not able to hear the rest of the meeting, I wrote on chat but google hangouts hide it by default 🤕 . 

My thought on this is that non-github members pay for their individual membership in the foundation. If there are non paying members at this moment, then we should re-think the scope of this membership and what it really enables. If we have paying members (non-github members) then maybe we should reach out to them to see what they are getting out of it.

**Comment by JemBijoux** [comment]
The last-minute notification this morning wasn't time enough for me to call in, but I'm very interested in helping out in this space. I'm excited about CommComm taking this on. 

Were there any notes or takeaways from the group disco this morning? Let me know how I can help!

**Comment by codeekage** [comment]
@hackygolucky do you mean having an ecosystem (members) outside the regular Github contributors membership?

**Comment by Tiriel** [comment]
We will get back to you very soon with more context and recap of Thursday's discussions, but just so you know the actual reflection is much broader than that.

In essence, we have to think about whether we want to completely sunset the actual individual membership program or not, and then whether we want to change it completely it (if we keep it), make something entirely new (if we sunset it), or abandon the idea about community acquisition/retention program.

For now, there is some inclination toward the following ideas (many of which cascading from one to the other):
* **Context:**
  * The current Individual Membership program doesn't work.
  * If we have to maintain some form of community program, it has to bring value to everyone and preferably be set within the scope of a broader Community project.
  * We should probably sunset the current program and replace it completely, and get a fresh start.
* **Several ideas have been expressed as to what to do for this fresh start:**
  * First and foremost, we should try to gather feedback from both the community and the board as to what value they would like such a program to bring them.
  * We should try and develop partnerships with companies and open-source communities to offer some kind of "Node.js Developer pack" (// GitHub Developer Pack)

In the coming days or the next CommComm meeting (@bnb @hackygolucky  correct me if I'm wrong), we will bring together a small task force to work specifically on these questions by October and be able to present a concrete set of propositions to the rest of the CommComm and the board.

So stay tuned people!

**Comment by williamkapke** [comment]
Are there meeting notes besides the info listed above?

**Comment by Tiriel** [comment]
AFAIR, and @bnb or @hackygolucky can correct me if I'm wrong, we didn't take formal notes, for the same reason we decided not to broadcast the meeting on YouTube: we wanted to have more candid discussions around the subject, thus making it nearly private.

**Comment by williamkapke** [comment]
I'm very disappointed this was done and didn't include me. Hard to think context was appropriately conveyed without the Individual Director present.

**Comment by hackygolucky** [comment]
@williamkapke I'm not sure what you mean by 'done'? This was establishing that a subgroup needs to happen and anyone here, including you especially, should attend once the first official meeting happens.

**Comment by williamkapke** [comment]
@hackygolucky Apologies, I was referring to the meeting having happened- not the completion of this issue.

**Comment by chowdhurian** [comment]
Efforts by the Individual Membership subgroup after engaging and discussing regularly for several months has produced a proposal to tackle this initiative 🎉

#390 is a request for feedback. Please go in, engage, and/or add new comments!

As this has progressed, I'm closing this for now. Please feel free to reopen if necessary! 💖
