### ISSUE TITLE
Joining the NodeJS team on github

### ISSUE THREAD

**Issue by Bamieh** [nodejs/community-committee#175]
Hello,

> tldr; Adding people to the NodeJS team on GitHub might be an incentive to become a member of the foundation and a contributor to node.

Under the foundation/members section on the website, There is a "Becoming an Individual Member" section which states the benefits of being a NodeJS member, however becoming part of the NodeJS team on GitHub is not one of those benefits.

I asked on the IRC chat about this issue and I was informed that:
> The GitHub "team" is just a convenience for communication and tracking. If you feel like contributing, the door is always open. Just find something you feel is interested in and dig in. -[refack](http://logs.libuv.org/node-dev/latest#19:29:22.442)

However, I feel that this could be used as an incentive / motivation to contribute and get more involved in the NodeJS Foundation.

#### Issue Type
Suggestion

**Comment by williamkapke** [comment]
Hi @Bamieh. Yes, the idea of adding the badge to those that sign up has been discussed- but it is hard to keep track of and organize. I'd be all for it if we had a way to make it logistically feasible.

Currently, you need to contribute to the Node Project on GitHub and get recognized for it. There are many ways to do so- but all of them take many months of dedication. It all comes down to what @refack said: "find something you feel is interested in and dig in"

**Comment by Bamieh** [comment]
@williamkapke a scheduling tool connected to github to automatically add people upon subscription and remove them upon expiration would be more than enough for the logistics part. implementing such tool on a lambda function or such would be super simple, am willing to write a mockup as well if a homemade simple solution is required.

Since these individuals are a form of fund for the foundation, maybe it is worth the trouble of implementing it?

**Comment by williamkapke** [comment]
A [bot to manage the members of the org](https://github.com/nodejs/community-committee/issues/22) has been discussed for years with some objects... and it's a slow evolving concept. While, my current proposal doesn't work in paid foundation members, it has always been on the potential feature list.

**Comment by Bamieh** [comment]
After reading the discussion you opened about the bot. This tool would be given access only to one team in the organization which is the `individual-foundation-members` honorary team.
