### ISSUE TITLE
Delay CommComm Meeting from Thursday, November 23 to a later date

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#176]
Given our normal CommComm meeting schedule, the meeting this week would happen to land on Thanksgiving Day in the U.S. 

Given that we have many members in the US, we probably won't be able to have an effective meeting during this time.

I'd like to suggest we delay the meeting one week (instead of two) from the normal meeting - so we would next meet on November 30th, 2017 - to get us together again soon and touch on several agenda items that will be resolving around that time. That said, totally open to other suggestions!

**Comment by Tiriel** [comment]
Hey there!

I know I'm just an observer, but just a quick note. I don't know if there are many people in my timezone, but the usual time makes the meeting happen during most people's commute here, including mine. I can take dispositions some times, and I'll try as often as I can, but I have to admit if the meeting time was one hour earlier or later, it'd be awesome.

If it's not possible, I totally understand and I'll do my best to attend anyway, but I figured I should ask.

**Comment by mhdawson** [comment]
+1 to delaying so that we get good attendance.

**Comment by dshaw** [comment]
+1 for Nov 30th

**Comment by msmichellegar** [comment]
👍  for Nov 30th, this also means I can attend! (Since daylight savings, CommComm always falls during one of my recurring meetings at work 😢 ).

**Comment by mhdawson** [comment]
Going to assume the meeting is rescheduled.

**Comment by komawar** [comment]
I assume too

**Comment by komawar** [comment]
checking in, November 30th? am not able to locate the issue. ty

**Comment by Tiriel** [comment]
@komawar I think @bnb was literally flying high (:small_airplane: back home) few hours ago. No doubt we'll have the issue soon, right when he'll have the time to land :smile:

**Comment by toby-farley** [comment]
Is the meeting occurring at this time?

**Comment by bnb** [comment]
Closing this as we've had the next meeting 🙏
