### ISSUE TITLE
Open Source Friday

### ISSUE THREAD

**Issue by benjamingr** [nodejs/community-committee#180]
Hey, I just found out about https://opensourcefriday.com/

I don't see existing discussion - it looks like it could be an interesting way to access non-traditional collaborators.

Opinions?

**Comment by bnb** [comment]
@benjamingr Sounds good to me! Would absolutely love to help enable this - couldn't find anything specifically that we can enable or add to help with this. Is there something specifically?

**Comment by benjamingr** [comment]
The registration page is https://opensourcefriday.com/maintainers

**Comment by bnb** [comment]
@benjamingr I know I'm coming back to this over a year later, but is there actually a way to sign up on that page? If there is I don't see it 😢

**Comment by benjamingr** [comment]
I don't remember this 😅

**Comment by codeekage** [comment]
Should this be discussed in the next meeting?

**Comment by bnb** [comment]
Looking at the Maintainers page for this, I'm not really seeing anything that's practically actionable for maintainers / projects to do beyond have a good readme, have boundaries, and have automation.

Happy to push others to this as individuals but as far as I can tell we can't really do much with it, unfortunately 😅 

Going to close this for now. Additionally, I'm going to remove it from the initiatives list 👍

**Comment by WaleedAshraf** [comment]
PR: https://github.com/nodejs/community-committee/pull/496
