### ISSUE TITLE
Retrieve translatable word count for current website and LTS docs

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/community-committee#183]
This count includes all plain-text, and all comments inside code blocks. This count should exclude all code examples, titles that are simple method names, and other non-translatable content.

Counts should be reported by page / module, not as a single number.

As is being discussed in https://github.com/nodejs/community-committee/issues/114#issuecomment-343874899, we are evaluating if/how much LinkedIn would be able to donate i18n to the Node.js project. 

To submit a proper scope-of-work we need to collect the top requested languages (done in https://github.com/nodejs/community-committee/issues/114#issuecomment-343623384), and a word count for the requested translatable material.

**Comment by sotayamashita** [comment]
@amiller-gh I try to get data with GitLocalize. I will share the stats tomorrow.

**Comment by sotayamashita** [comment]
@bnb Do you know where LTS docs is?

**Comment by sotayamashita** [comment]
@amiller-gh I have uploaded compressed CSV file on dropbox.

- website: https://www.dropbox.com/s/qcgc9w3kgqbc9dt/website.csv.zip?dl=0
- LTS: doing now

**Comment by sotayamashita** [comment]
@bnb 

I would appreciate you if could tell me know how to build LTS docs. Which version of the current master branch is based on?

Thanks in advance

**Comment by amiller-gh** [comment]
Thank you for the work @sotayamashita! It is SO appreciated!

I believe current LTS docs live here in the 8.x branch: https://github.com/nodejs/node/tree/v8.x/doc (@bnb can correct me if I'm wrong).

The CSV format will work well, I like the breakdown by markdown file. Does that count exclude code examples that won't need to be translated?

After we get data for LTS I can get the proposal put together and submitted to LinkedIn in the new year 👍

**Comment by bnb** [comment]
Sorry, I thought I posted this - may have said it on Twitter to @sotayamashita:

You can `make build` in the relevant branch and you should be able to build the Node.js docs. So run it in the branch @amiller-gh shared and it should build.

**Comment by sotayamashita** [comment]
@amiller-gh 
> The CSV format will work well, I like the breakdown by markdown file. Does that count exclude code examples that won't need to be translated?

Yes. It must be.

@bnb 
 Thank you for the information

**Comment by sotayamashita** [comment]
@amiller-gh @bnb 

I'm sorry it took so long to get back to you. I have prepared compressed files. https://github.com/nodejs/community-committee/issues/183#issuecomment-350983765

**Comment by bnb** [comment]
Going to close this for now, but @amiller-gh please feel free to re-open if there's still more that needed to be followed up on 👍
