### ISSUE TITLE
Node.js LinkedIn Group

### ISSUE THREAD

**Issue by DiegoZoracKy** [nodejs/community-committee#185]
# Node.js LinkedIn Group

**Edit:** After discussion with YLD and the Foundation we're going to move for the LinkedIn group to become our second Partner Community! This ticket will be closed by a PR adding the LinkedIn group to the list in [PARTNER_COMMUNITIES.md](https://github.com/nodejs/community-committee/blob/master/PARTNER_COMMUNITIES.md). To move forward we need to:

 - [ ] Iterate on our plan to help develop the LinkedIn group with @ZibbyKeaton 
 - [ ] Ensure a Code of Conduct.
 - [ ] Ensure a Moderation Policy.
 - [x] Have a Node.js Collaborator who is willing to act as a liaison and is an administrator (@amiller-gh)

## Original Ticket

Initial reasons published at: #186

The major LinkedIn group related to Node.js is managed by a company, and it seems that is not easy to get a permission to join it. I couldn't. The group has enabled the "fast access" feature, that automatically accepts people related to some specific domain (their own domain) and it seems that this is the only way that is working right now.

An important aspect of LinkedIn, is that there are also people who are in charge of taking decisions about tech, but aren't developers. As today the "News" section on the main website has only technical content, the LinkedIn group can be a mix of technical and business types of contents. There will be probably these two sides of profiles.

LinkedIn is used by a lot of companies to find developers, and *Groups* has a great feature for that, which is a tab named *Jobs*, which serves specifically to post jobs offerings. It can be a great, and easy connection between Companies X Developers.

Recently I created one group on LinkedIn, named "Node.js People Everywhere" with the intention to be more open. However I believe that would be better if managed by the Node.js Foundation: https://www.linkedin.com/groups/8640198

**Comment by dshaw** [comment]
@DiegoZoracKy Do you think it would be better to engage with the team behind the group and try to open up administration to broader CommComm collaboration? YLD is a Node.js Foundation member. https://www.linkedin.com/groups/2906459/members/admins

**Comment by DiegoZoracKy** [comment]
@dshaw the main intention of this idea is to help on the following:

 * Provide an "open" place on LinkedIn where companies and developers can meet
 * Make it a place where people can join easily and fast
 * Having a low barrier to post Jobs (by companies), and to post anything related to Node.js (companies plus developers)

Consequently heating up the talk and connections between Companies and Developers.

If YLD could help on that, it would be definitely a better way to go in my opinion. There would be no reason to create another group, and we would instead leverage the group that is already there.

**Comment by dshaw** [comment]
Glad to hear. I agree. Let's see if we can work with the team at YLD to figure out the best solution.

**Comment by DiegoZoracKy** [comment]
@dshaw Great. Thanks for taking this step.

**Comment by bnb** [comment]
@dshaw how are you proposing we can work with the team at YLD? Want to make sure that we're moving forward and taking action, and having accountability for that action. If you are willing to take this on, that would be appreciate that.

**Comment by ZibbyKeaton** [comment]
I'm seeing if there's a way that we might be able to do this with the Node.js Foundation LinkedIn page. It might cost some money, but will let this group know once I hear a little bit more about options and whether or not we can add it to the budget. Stay tuned!

**Comment by bnb** [comment]
@ZibbyKeaton @dshaw any ideas if we've made progress on this, or if there are any blockers? To the best of my knowledge we've _not_ done this, so just trying to figure out the state 🤔

**Comment by ZibbyKeaton** [comment]
@bnb I checked into posting jobs as a "company page" and it's way too expensive. It's must better to have just a group do this and I think the intention of what Diego is looking for would serve better as a group on LinkedIn vs company. I never reached out to YLD, but I can do so if @dshaw has not. I'm more than happy to take this action and provide some next steps to this, just don't want to step on Dan's toes here.

**Comment by dshaw** [comment]
Thanks, @zibbykeaton. Please reach out.

**Comment by DiegoZoracKy** [comment]
@ZibbyKeaton, I believe that if we spread the word about a dedicated, and open, group on LinkedIn, people and companies will end up joining and connections will happen naturally.

**Comment by amiller-gh** [comment]
@ZibbyKeaton, make sure you check out our non-profit pricing – I believe the foundation would qualify for significant discounts, and probably free volunteer postings https://nonprofit.linkedin.com. Not sure we could use it to post other companies' job listings, but the group would definitely be a good place to up-sell existing job postings.

**Comment by ZibbyKeaton** [comment]
@amiller-gh thanks for the heads up. The intention was to post for other companies outside of the Node.js Foundation and that's where it ended up being a bit sticky with posting jobs on a page vs in a group.

I talked with the YLD folks and they are very much open to making the LinkedIn Group for the community as that was always its intention. Currently, they are having issues because they have about 5,000 folks that want to join the group and they have to add them in manually.

@DiegoZoracKy and whoever else is interested, I thought it might be good to chat with the YLD team on the phone to talk through the transfer or just next steps here. Does that sound like a good next step here or wold you propose something else?

**Comment by DiegoZoracKy** [comment]
> Currently, they are having issues because they have about **5,000 folks** that want to join the group and they have to add them in manually

Yes, this is really bad because it seems that LinkedIn doesn't help too much with that. 

They only provide a solution to approve up to 25 (or one page) of pending requests, as they mention here: https://www.linkedin.com/help/linkedin/answer/205/approving-and-pre-approving-group-members?lang=en

And unfortunately it seems that they don't accept "@gmail.com" as a pre-approved domain. That would help a lot in approve automatically the majority of the requests to join the group. However, I believe that a better way would be to have an option to accept every request without the need to approve each one of them.

**Comment by Tiriel** [comment]
Is there any news on this front?

**Comment by ZibbyKeaton** [comment]
Need to follow up with the YLD folks to set up a call. Lots of folks have been busy with the GDPR stuff. Sending them an email now to schedule something. Who in this group would like to be on an intro call to talk about goals, handover, and next steps?

**Comment by amiller-gh** [comment]
Happy to help with this.

FWIW I talked with the Groups PMs, they said they’ll “take this use case into account in their next product revision” – I wouldn’t count on bulk / auto add to group becoming a feature any time soon.

**Comment by DiegoZoracKy** [comment]
>  they’ll “take this use case into account in their next product revision”

@amiller-gh good to know that you shared this use case with them 👍.

**Comment by bnb** [comment]
@ZibbyKeaton @amiller-gh wanted to follow up on this and see if we've made any progress ❤️

**Comment by ZibbyKeaton** [comment]
Let me follow up again. I think this just feel off our radar.

**Comment by ZibbyKeaton** [comment]
@Tiriel @amiller-gh @DiegoZoracKy would y'all be able to hold a call with the folks at YLD on this issue next week? They are available on Monday at 1PM BST and 2PM BST on Tuesday? 

One item that I want to call out as we go through this process (and talk with the folks at YLD) is how we are planning to manage this page once it goes into the community? I like the intentions of this initiative, but I also want to get a good sense of how much operational time this might be and who would want to lead the effort as well.

**Comment by amiller-gh** [comment]
Happy to! 2PM BST (6AM PST) will be preferable for me. I’ll do by best to be lucid at that time 👍

**Comment by ZibbyKeaton** [comment]
Meeting invite has been sent! If it's too early for you @amiller-gh I can also take notes and share with you post meeting. I'll plan to just do that here anyway, in case not everyone can make it.

**Comment by amiller-gh** [comment]
Note from CommComm meeting – we're leaving this ticket open until the LinkedIn group has been added to the Partner Communities list (or is otherwise resolved). Our next steps:

 - [ ] Iterate on our plan to develop the LinkedIn group with @ZibbyKeaton 
 - [ ] Ensure a Code of Conduct.
 - [ ] Ensure a Moderation Policy.
 - [x] Have a Node.js Collaborator who is willing to act as a liaison and is an administrator (@amiller-gh)

I'll edit the main issue text to include this checklist too 👍

**Comment by DiegoZoracKy** [comment]
@ZibbyKeaton I'm sorry. I believe I messed up with my email settings and all messages were being marked as unread. I didn't notice that call to the meeting. But probably it brought some results because YLD approved a lot of people during the past weeks.

**Comment by keywordnew** [comment]
Hey folks, thread ping to check if there has been progress on this that hasn't been captured in the issue 💛

**Comment by bnb** [comment]
Since we've seemingly made no progress on this over a few years, I'm going to go ahead and close this. Feel free to reopen if you'd like to drive it.
