### ISSUE TITLE
Node.js Strategic Initiatives beyond technical matters

### ISSUE THREAD

**Issue by DiegoZoracKy** [nodejs/community-committee#186]
# Node.js Strategic Initiatives beyond technical matters

## Summary

This issue proposes the creation of a document like TSC's Strategic Initiatives, but not so focused on technical subjects. The suggestion is to have topics more related to the business side of the Node.js community. With strategies to ease and give more confidence on the adoption of Node.js.

It seems to me that Node.js would be more adopted if companies could be more confident, by having a better sense that developers are around their location to join their team. Consequently developers would be more willing to dive deep on it, knowing that a great opportunity to be hired is out there.

I believe that would be great for us all, if Node.js Foundation could take a step on this direction and start (or improve), the communication on this sense.

Some of the initial ideas I propose are to facilitate developers and companies to find themselves and to bring awareness on how Node.js is being used.

**Node.js People Everywhere (npe)**

In order to easily answer the question: *Where are the Companies and the Developers?*, I believe that a list/directory of companies using Node.js, and Node.js Developers can be great. It would include where they are, how they are using it, providing features to search by location or by scope/skills.

This will help companies and developers to find each other, and to make them understand the profile of what is around.

I'm describing it better at: #184. There we can go deep on a discussion specifically about this idea.

From January onwards I will have some spare time to invest efforts on it, in case we agree on having that.

**LinkedIn**

The major LinkedIn group is managed by a company, and I believe that would be way better if there was an official group there. I've created an issue (#185) for us to discuss the pros of having it, and the cons of not having a group, more open, embracing the whole community.

**Content**

The Node.js main website is the first place where people go, to know more about it. If they can't find what is being searched for, is not guaranteed that they will try to look in another place. There is no content related to that scope I'm mentioning here, and if there is some, it is a bit hidden.

The Node.js channel on YouTube has some videos with people telling why Node.js was chosen, and the "use cases" section on the website (that I couldn't find it anymore, at the last time I checked) is something that should have more importance, in my opinion. The video from Walmart that used to be on the main page was a good help on that sense.

## Initial motivation and reasons (long text)

The TSC has a "Strategic Initiatives" document, which I think is a really great initiative to keep the good working being done, and also to share with the community what's going on. I would like to know if it's possible, and if it is felt important, to have another document as the "Strategic Initiatives", but with a scope more on the business level. Here, "businesses level" is also very related to the developers community, and not just to the one who owns, or is starting a company.

To explain better, I'm sharing parts (slightly modified) of an email I sent to @mhdawson, regarding this topic:

You guys have been doing a great job on Node.js, thank you all for that. It has been great all you have done and I can feel really safe about the direction the project is taking towards the future. I'm 100% sure that choosing Node.js as the basis of my current and next projects is a great move. I can see all the many benefits we have in technical terms, and also, how I can move faster and be very productive working with it. Having front-end and back-end teams sharing code, where they can work together creating and maintaining modules, is really powerful.

However, I have a feeling that I just can say all of that because despite of any position I had, or will have in the future, I will be still a developer. One with hands on coding. That leads me to be close to what is happening. Through technical talks, writings, looking at new modules being published, and also publishing modules and writing technical articles myself. But to a person that doesn't have this kind of profile (maybe, doesn't have it  anymore), and it is in a position of making decisions, where can one find data to be informed about how Node.js can be great for its business? For example:

* Are there Node.js developers in my area?
* Where are they?
* Once found, are they back-end developers, users of some front-end tooling, IoT?
* How teams can benefit from having Node.js on the stack?
* How could sharing code between front-end and back-end make me move faster, and thus reduce the costs of a project?
* How a culture of modularity can benefit my team?
* How the good job of the TSC impact my business in terms of reliability, security, LTS support, etc.?

When looking for companies investing heavily in Node.js I can't find many, even though we know about some big names here. Doing the inverse, to find Node.js developers, it is not easy either. A Node.js developer can mean a lot of things nowadays. Looking for someone to work with API servers, it is easy to end up with profiles of people that range from a user of some front-end tooling, to someone willing to work with IoT.

I just can find some companies investing for real on Node.js when looking abroad (BTW, I'm from Brazil). I talked recently with some foreign companies that were willing to relocate people to work with Node.js. This episode can makes us think about why weren't they able to find people to work with Node.js around there? The VP of engineering of one of those companies mentioned to me something like "we are choosing Node.js, but it hasn't being easy to find people to work with it".

In my point of view, it can end up on a bad loop where companies are not so sure about choosing Node.js, and that can make developers feeling that maybe it is not a good idea to invest on it.

**Comment by mhdawson** [comment]
@DiegoZoracKy thanks for volunteering to help push these suggestions forward.  @nodejs/community-committee I think there are a number of good ideas suggested here.  I wonder if discussing at one of the upcoming community committee meetings would make sense ?

**Comment by DiegoZoracKy** [comment]
@mhdawson No problem, and thanks for the support.

**Comment by bnb** [comment]
I've been thinking about exactly this idea - doing something along the lines of the strategic initiatives document that the TSC has - since I first saw that doc. I am definitely a huge +1 to this, but I do think it needs to take a slight step back from what you've proposed.

The CommComm is definitely focused on engaging with and finding representation for all users of Node.js. As such, focusing a document along the lines of the strategic initiatives doc specifically to any one group and efforts around that doesn't make a ton of sense. Rather, such a document would need to be a log of the initiatives that we're actively engaged with and that we'd _like_ to take on regardless of which users of Node.js are involved. There are a suite of initiatives that can already be funneled into such a doc (ref: https://github.com/nodejs/community-committee/issues/114,  https://github.com/nodejs/community-committee/issues/180, https://github.com/nodejs/community-committee/issues/172, https://github.com/nodejs/community-committee/issues/170, https://github.com/nodejs/community-committee/issues/158, https://github.com/nodejs/community-committee/issues/157, https://github.com/nodejs/community-committee/issues/138, https://github.com/nodejs/community-committee/issues/112, https://github.com/nodejs/community-committee/issues/63), which will help us keep track of them over the long-run and begin to understand how they're evolving and what we can do to support them.

I absolutely _love_ this idea. We should definitely surface this in the next CommComm meeting, but I honestly think that we can start off by simply PRing an empty clone of the structure that the TSC has for its doc and kick off the work, if someone's willing to take that on!

**Comment by DiegoZoracKy** [comment]
Hi @bnb, I'm glad good to hear that, and I definitely agree with you here:

> "Rather, such a document would need to be a log of the initiatives that we're actively engaged with and that we'd like to take on regardless of which users of Node.js are involved."

For someone that is not a member of the committee, but is part of the community, I believe is more important to have an idea about what is on the track to happen, than who is taking the lead on some of the topics. It will be better and easier for people to raise new ideas, if a doc like that is there to be checked upfront. I had seen previously some of the issues you mentioned, but others were new to me. The doc would be really good to group those initiatives.

Just a quick note. I see that most of the topics you mentioned are related to a conversation focused on the community of developers, and I think we should have more initiatives on the "business" side of it, as I mentioned. Do you see the same?

**Comment by bnb** [comment]
>Just a quick note. I see that most of the topics you mentioned are related to a conversation focused on the community of developers, and I think we should have more initiatives on the "business" side of it, as I mentioned. Do you see the same?

@DiegoZoracKy Absolutely. The Node.js community is extremely diverse in terms of applications and communities using the project as a platform. Even bucketing things into community and "business" doesn't begin to approach the variety of communities that Node.js touches. Some of the biggest ones that the project itself has left unaddressed are those business users, users of Node.js for front-end tooling, and module authors. That said, there are _many_ others that we've not even begun to approach - yet.

As long as we have people that are interest and are able to commit to actively working on any domain that Node.js is used in, I don't think we'd likely turn away someone from contributing or spinning up efforts around the domains.

This is not a one community vs. another community thing. We're all participating in and engaged in different communities, and at _no point_ will any one community be shut out or excluded from the discussions and work in the CommComm. There will never be prioritization of one over another, only the possibility of people who are domain experts in one or another having the possibility of investing more time and, thus, seeming like one is being invested in more than another.

**Comment by DiegoZoracKy** [comment]
@bnb Well said. I would like to see the follow-up of the discussion on this matter that as per you say, will be on topic on the next CommComm meeting. How can I follow that? Also, you can ping me if you think I can be helpful in some way.

**Comment by ZibbyKeaton** [comment]
I think this is a really great initiative. I have been trying to figure out a good way to post Node.js jobs whether it's on LinkedIn, maybe on our website, potentially on something like Dice and or StackOverflow. I am planning to talk with LinkedIn next week to see what options they might have for the Node.js Foundation LinkedIn homepage. Is this something that is up for discussion in the next CommComm meeting, and if so when is it and would it be okay for me to join? @bnb 

I can also talk about the current initiatives we have going on at the Node.js Foundation when it comes to telling the end user story, i.e. case study, enterprise conversations, and our app showcase.

**Comment by pup** [comment]
@ZibbyKeaton @DiegoZoracKy our next meeting is tomorrow at 4pm UTC! i can add you two as observers if you want to, and we can also add this to our agenda

**Comment by DiegoZoracKy** [comment]
Hi @pup, that can be great. You can add me as an observer.

**Comment by DiegoZoracKy** [comment]
Hey @ZibbyKeaton, good to hear that. For you to know, I've created one issue specifically about the LinkedIn idea I brought up here. In case you are interested, it is this one #185.

**Comment by ZibbyKeaton** [comment]
Yes, please add me into the convo too @pup

**Comment by SarahKConway** [comment]
Not sure if this is what you have in mind regarding npe, but on the kubernetes.io web site we've helped organize - https://kubernetes.io/partners/. 

The Cloud Native Computing Foundation helped create a list of criteria for the different service and technology partners and then worked closely with the community to develop the formal conformance and certification programs. 

Perhaps we start by considering the service, technology categories? We documented the criteria for each, created google form applications, and continue to review the applications as they come in and submit PRs once approved to add the partners to the website. Happy to join the meeting as an observer as well. Thanks!

**Comment by mhdawson** [comment]
@pup is it 4UTC ? I thought it was 5UTC/12 EST ?  At least that is what has been in the past.

**Comment by DiegoZoracKy** [comment]
@SarahKConway I believe your suggestion is very good. The Certified Partners could be one more section on the platform. In the end the platform would be helpful to find Developers, Companies and also Certified Partners. For the latter, a more close strict review to accept the partners, as you mentioned, would apply, but maybe not so much for the Developers and Companies.

For example, on npm we have thousands of users registered, and if a great share of them would decide to join at a short period of time, that workflow would be a burden to manage:

> created google form applications, and continue to review the applications as they come in and submit PRs once approved to add the partners to the website.

And for a company or a developer who just want to show up some interest on working with Node.js, maybe this kind of preselection it is not really needed (as it is not on npm).

I went a bit further on the idea around npe on the issue I created for it (#184). Reading there, I believe you will get a sense about why I believe that for Companies and Developers should have no barriers to the entrance. But I really see that a section for Certified Partners can be something great to have. Thanks;

**Comment by pup** [comment]
@mhdawson iirc the last meeting said 4pm utc in the issue description??

**Comment by mhdawson** [comment]
Looking at the foundation calendar future meetings show as 12 EST for me which I believe is 5pm UTC.  

Just want to make sure we all know the right time.

**Comment by mhdawson** [comment]
I think it may be the time change that is messing things up.  The foundation calendar shows 12 EST (5 UTC), probably because it was scheduled in a timezone that uses daylight savings time.  

What I can't remember is whether we met at 11 or 12 the last few times.  In any case we need to get the Foundation Calendar synced up with what is in the issues.  @bnb can you confirm the time and then I'll update the Calendar appropriately ?

**Comment by DiegoZoracKy** [comment]
Hi, I'm also a bit lost about how the "observer" role works. Where can I find the link to join the meeting at the right time?

**Comment by pup** [comment]
@DiegoZoracKy the link will be posted in the meeting issue (which isn't created yet) shortly before the meeting starts

**Comment by mhdawson** [comment]
So everybody is on the same page: UTC Thu 14-Dec-2017 17:00 (05:00 PM) is the time shown in https://github.com/nodejs/community-committee/issues/192

**Comment by ZibbyKeaton** [comment]
Thank you. I am unable to join this meeting as well, but look forward to hearing a recap of what is discussed.

**Comment by bnb** [comment]
Going to remove the cc-agenda label, unless there's further discussion to be had since the last meeting 👍

**Comment by DiegoZoracKy** [comment]
@bnb, I agree. I believe we'll be discussing on the specific issues for now.

**Comment by DiegoZoracKy** [comment]
@bnb It seems that you created the [STRATEGIC-INITIATIVES.md](https://github.com/nodejs/community-committee/blob/master/STRATEGIC-INITIATIVES.md) document. Nice🤘!!! Should we close this issue, as the other topics are being discussed on their own issues?

**Comment by bnb** [comment]
Yes! I'll go ahead an close this - thanks for getting the effort kicked off @DiegoZoracKy <3
