### ISSUE TITLE
CommComm Meeting 2017-12-07

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#187]
Unfortunately, I won’t be able to attend tomorrow’s meeting. I will be participating in a mentoring session mentoring on community at KubeCon.

@mhdawson Could you share context on @user-feedback from the 2017-12-01 meeting (first official meeting 🎉🎶✨)?

Key points I’d like to convey:
1) NEUF meets every 2 weeks on Friday at 9am PT. The next meeting is 2017-12-15. Please join us if you’re interested in helping enable bi-directional feedback to the Node.js project.
2) At the next meeting, we’ll be joined by Greg Wallace of the Linux Foundation. We’ll explore the annual Node.js User Survey and how we can help.
3) As our first major initiative, we’ll be helping the Benchmarking Working Group gather data on some open questions they have provided.
4) Watch https://github.com/nodejs/user-feedback/ to follow activity and learn more.

🙏 thank you

**Comment by pup** [comment]
did we decide on holding 2 meetings in a row, or do we skip this week and resume a "normal" schedule? how important would you think your key points are @dshaw?

**Comment by pup** [comment]
closing because of #189

**Comment by dshaw** [comment]
@pup I'll convey this at the meeting (https://github.com/nodejs/community-committee/issues/189), during the @nodejs/user-feedback section. Thanks.
