### ISSUE TITLE
Next CommComm Meeting: 2017-12-14

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#189]
Because our last CommComm meeting was only one week ago, we are still working on the things we discussed in that meeting and moving forward with what we discussed there. As such, we should _probably_ move today's meeting to next week and have this be our standard 2 week cadence.

I'm currently working to get the Foundation Calendar updated, as there's a recurring meeting on there for today that we've not been actively maintaining 👍

**Comment by msmichellegar** [comment]
Yes! Selfishly, this works great for me (the other rotation of two weeks clashed with a recurring fortnightly meeting of mine 🙈 ).

**Comment by bnb** [comment]
@msmichellegar Glad to hear that - we should probably do a doodle sometime in the future to ensure that we're hitting a time that meets a time that works for members.

**Comment by dshaw** [comment]
I'll be able to attend and can share an update on @nodejs/user-feedback per #187

**Comment by pup** [comment]
closing because of #192
