### ISSUE TITLE
Node.js Foundation Community Committee (CommComm) Meeting 2017-12-14

### ISSUE THREAD

**Issue by pup** [nodejs/community-committee#192]
## Time

**UTC Thu 14-Dec-2017 17:00 (05:00 PM)**
<details>

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | 09:00 (09:00 AM) |
| US / Mountain | 10:00 (10:00 AM) |
| US / Central  | 11:00 (11:00 AM) |
| US / Eastern  | 12:00 (12:00 AM) |
| Amsterdam     | 18:00 (06:00 PM) |
| Moscow        | 20:00 (08:00 PM) |
| Chennai       | 22:30 (10:30 PM) |
| Hangzhou      | 01:00 (01:00 AM) |
| Tokyo         | 02:00 (02:00 AM) |
| Sydney        | 04:00 (04:00 AM) |

Or in your local time:
* [Time Conversion](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Community+Committee+(CommComm)+Meeting+2017-12-14&iso=20171214T17&p1=1440)

</details> 

## Links
* **Minutes Google Doc:** https://docs.google.com/document/d/1t2mseYq8-EKlxMiluHq2k2s8qh7bIX0nIEJb8QiSFH4/edit?usp=sharing
* **Previous Minutes Google Doc:** https://docs.google.com/document/d/1SWJjGXEpTdu_2RbUkHr05h3WZco3pFrq59p4gDoKTnc/edit?usp=sharing

## Agenda

Extracted from **cc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

* Mentorship Team under the CommComm https://github.com/nodejs/community-committee/issues/172
* Node.js Strategic Initiatives beyond technical matters #186
* Node.js People Everywhere (npe) #184

## Invited
* Ashley Williams (@ashleygwilliams - CommComm)
* Emily Rose (@emilyrose - CommComm)
* Gregor Martynus (@gr2m - CommComm)
* Joe Sepi (@joesepi - CommComm)
* JP Wesselink (@jpwesselink - CommComm)
* Michael Dawson (@mhdawson - CommComm)
* Michelle Garrett (@msmichellegar - CommComm)
* Rachel White (@rachelnicole - CommComm)
* Tierney Cyren (@bnb - CommComm)
* Tracy Hinds (@hackygolucky - CommComm)
* William Kapke (@williamkapke - CommComm)
* Refael Ackermann (@refack - CommComm)
* Oz Haven (@therebelrobot - observer)
* Manil (@chowdhurian - observer)
* @ParidelPooya (Pooya Paridel - observer)
* @rykerrumsey (Ryker Rumsey - observer)
* @baez (Behzad Karim - observer)
* @BinarySo1o (Therese Stirling - observer)
* @JemBijoux (Jem Bezooyen - observer)
* @amiller-gh (Adam Miller - observer)
* @obensource (Ben Michel - observer)
* @yosuke-furukawa (Yosuke Furukawa - observer)
* @Maurice-Hayward (Maurice Hayward - observer)
* @dshaw (Dan Shaw - observer)
* @mikehostetler (Mike Hostetler - observer)
* @sarahkconway (Sarah Conway - observer)
* @Tiriel (Benjamin Zaslavsky - observer)
* @DiegoZoracKy (Diego ZoracKy - observer)
* @ZibbyKeaton (Zibby Keaton - observer)
* @tobyfarley (Toby Farley - observer)
* @Bamieh (Ahmad Bamieh - observer)

## Notes

The agenda comes from issues labeled with `cc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ/live** when we turn it on. 

There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and we'll be online shortly. ❤️

## Joining the meeting

The link for observers and members to join will be posted shortly before the meeting commences.
A standing invitation exists for all @nodejs/TSC members who are not also CommComm members to attend in observer capacity.

**Comment by Tiriel** [comment]
Is the time issue resolved and 5PM UTC the correct time then?
If so, I don't think I'll be able to attend today, I'll arrange for the next one though.

**Comment by pup** [comment]
@Tiriel yes, 5PM UTC is the correct time

**Comment by Tiriel** [comment]
Too bad! Thanks!

**Comment by bnb** [comment]
Was just about to create + publish this - thank you for doing the heavy lifting, @pup. Means a lot! 🙏

**Comment by tobyfarley** [comment]
Sorry if this is TL;DR. Is there any way I can move back to Observer status? I attended the one after Node Interactive. I missed the next one because I didn't understand the schedule and I hadn't set myself to watching the repo. I attended last week but had been dropped off the observer list. I made a comment last week about being added back in as an observer. I really am trying to jump through the right hoops. I don't feel like I am a good fit for any of the more technical groups and this is where I want to make a contribution.

**Comment by bnb** [comment]
@tobyfarley Yes, adding you now - and don't worry, your prior attendance hasn't been discounted, you're still technically an observer. Thanks for bearing with us.

FWIW because of you being dropped last week as well, I'm going to be working on getting a spreadsheet set up to track observers and their timeframe as an observer so we don't miss someone as an observer again.

**Comment by bnb** [comment]
I have added the `cc-agenda` label to https://github.com/nodejs/community-committee/issues/186 - definitely something that we should discuss, as I think it's actionable and can help us guide our efforts more effectively.

**Comment by bnb** [comment]
I've added the `cc-agenda` label to https://github.com/nodejs/community-committee/issues/184 - I don't have full context on it, but if @DiegoZoracKy attends the meeting I'd really like to have their thoughts on it. I will try to catch up before the meeting, and suggest others do the same 👍

**Comment by Bamieh** [comment]
can i join today's meeting?

**Comment by DiegoZoracKy** [comment]
@bnb I will be attending the meeting as an Observer. I just created this new comment [/nodejs/community-committee/issues/184#issuecomment-351734049](https://github.com/nodejs/community-committee/issues/184#issuecomment-351734049) with a summary/TL;DR; to serve as a quick intro for those who are interested in getting the initial idea of this topic, and see what has been discussed until now.

**Comment by bnb** [comment]
Thanks @DiegoZoracKy - looking forward to it 🙏

**Comment by bnb** [comment]
@Bamieh Yep, adding you as an observer. Thanks 🙏

**Comment by MylesBorins** [comment]
As I'm no longer on the commcomm I likely should be in the invitation list
☺️

**Comment by pup** [comment]
i likely won't make it since i need to sort out some stuff that'll overlap with this meeting 😢

**Comment by bnb** [comment]
Sorry to hear that, @pup 😢 

Thank you A TON for helping out with it ❤️ ❤️ ❤️

**Comment by JemBijoux** [comment]
:( I can't make it to this one either (only an observer for now) but will definitely be around for the next. Just have an important meeting taking over my morning before I head off for holidays.

**Comment by rachelnicole** [comment]
I won’t be attending this one, I asked Tierney to take the lead for the rest of the month as I’m trying to get some work stuff in order

**Comment by joesepi** [comment]
I will be about 20min late due to a meeting I just can’t push off. Thanks!

**Comment by bnb** [comment]
Join link for members and observers is here: https://zoom.us/j/209550902

**Comment by bnb** [comment]
I've updated the agenda to remove agenda items that have been previously discussed but did not have the cc-agenda label removed 👍

**Comment by dshaw** [comment]
Where's the live link?

**Comment by mhdawson** [comment]
2 comments up :)

**Comment by ZibbyKeaton** [comment]
I had to hop off the call early due to a prior engagement. Will listen to the rest of the meeting and view meeting minutes hopefully later today or tomorrow.

**Comment by gr2m** [comment]
I’m out on vacation. I’ll be back for next meeting

**Comment by DiegoZoracKy** [comment]
Hi @bnb, just a note. I was taking a look at the Minutes of yesterday's meeting and couldn't find a mention about the creation of the new doc "Strategic Initiatives" (#186). I believe it was decided that this topic should be on a TODO list.

**Comment by bnb** [comment]
@DiegoZoracKy Yes, it was. I will review as soon as I have time and add that section in. Thanks 🙏

**Comment by pup** [comment]
are there meeting notes for this meeting? if not, i'm closing it

**Comment by bnb** [comment]
@pup Just PRed them: https://github.com/nodejs/community-committee/pull/199

Going to close this 👍
