### ISSUE TITLE
Add @joesepi as Member

### ISSUE THREAD

**Issue by williamkapke** [nodejs/community-committee#193]
I believe @joesepi has met the requirements for membership to the @nodejs/community-committee.

Let's please vote to make him official.

**Comment by williamkapke** [comment]
Gah- looks like this already happened and the list I was looking at was wrong :(

please ignore.

**Comment by bnb** [comment]
Thanks for following up with it, @williamkapke <3

**Comment by joesepi** [comment]
Yall are the best.
