### ISSUE TITLE
Allow User Feedback to support Enterprise Advisory Group

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#195]
The Node.js End User Feedback (NEUF) team (@nodejs/user-feedback) has made itself available, and @dshaw in particular has made himself available, to help support a group of Enterprise End Users who have large deployments and are able to provide feedback on major changes to the Node.js project given the size and diversity of those deployments. These changes are primarily expected be technical in nature and therefore will engage the TSC, the owners of the technical project. That said, effort has been made to not limit the potential scope of feedback to only the TSC and therefore reference the "Node.js project". The audience for this group is primarily in managerial roles and therefore not engaged in GitHub. Therefore, @nodejs/user-feedback will need to operate as a proxy to bring the efforts of the group to the space where the Node.js project operates day-to-day, GitHub.

Efforts by @nodejs/user-feedback are currently blocked because of questions of whether the CommComm is willing to allow this project to exist under its charter: https://github.com/nodejs/enterprise-advisory-group/pull/5

This issue is a formal request to the CommComm for permission to engage with the End User community that members of @nodejs/user-feedback are attempting to facilitate.

I would like to try to get the questions of "why?" out amongst CommComm members, so we can move on to focusing on "how we accomplish this?".

**Comment by bnb** [comment]
Going to close this since it's been over a year with no further movement on it, and there is now a lot of effort going into the User Feedback Initiative which largely replaces a lot of the work this was initially going for.
