### ISSUE TITLE
call for moderators!

### ISSUE THREAD

**Issue by ashleygwilliams** [nodejs/community-committee#20]
over the past few month, the CommComm has been debating the relative merits of several communication channels for the Node.js project: https://github.com/nodejs/community-committee/issues/11

a key issue yet to be fully addressed is the need for active moderators and helpers in whatever channel(s) we end up choosing. this is critical as the tool(s) we choose need to work for the people who plan on staffing them.

to that end, this is an open call for people interested in volunteering to moderate and help in these channels. general tasks are:

- enforce Node.js CoC by calling out behaviors, educating users on better behaviors
- offer Node.js guidance, by pointing to resources or otherwise

if you are interested, please indicate your interest with details/restrictions you have below.

cc @emilyrose @aredridel @nodejs/tsc 

there is a long tradition of fantastic moderation in the Node.js IRC that i hope we can learn much from as we move forward.

**Comment by MylesBorins** [comment]
I've been heavily involved in this so far and am up for the challenge of onitnue this

**Comment by hackygolucky** [comment]
✋ I'm often a lurker, but I'd love to be more active in getting to engage folks as we grow our central communication. My current work in Node.js very much revolves around diplomatic communication, and as a long-time event organizer I've had to enforce codes of conduct in the toughest of cases.

**Comment by Trott** [comment]
o/

**Comment by AlexTes** [comment]
:raising_hand: I can regularly be found reading and chatting on both IRC and the unofficial slack.

**Comment by toddself** [comment]
Would love to help.  Long time lurker, occasional helper in the IRC channel

**Comment by italoacasas** [comment]
\o/

**Comment by gpestana** [comment]
Count me in!

**Comment by bnb** [comment]
Would love to help! ❤️

**Comment by jxm262** [comment]
I'll throw my name in that Hat :)  Seeing as I already moderate the current node.js Slack group (with much much help of course).  I feel obligated to help out the "official" community somehow

**Comment by IgorAntun** [comment]
I would also love to help out :)
Currently I help moderating the Slack group as well, and I'd love to get more engaged with the 'official' community.

**Comment by hemanth** [comment]
Count me in!

**Comment by ArtOfCode-** [comment]
I'm in :) Probably quieter around Node stuff than most here, but I'm a mod over on Stack Exchange, which I like to tell myself means something.

**Comment by satvim** [comment]
I am interested!!!

**Comment by sousandrei** [comment]
i am interested if possible! want to contribute in any way that i can

**Comment by evanlucas** [comment]
I'd be happy to help on this front.

**Comment by aredridel** [comment]
I am around somewhat: still looking for work and helping manage two other communities, so not able to be node primary, but into it.

**Comment by Fishrock123** [comment]
I am more than willing to help with IRC-related permissions and likely also management of any future alternative to IRC.

In reality though, I have only a very small bit of focus usable on moderating multiple channels. (I really just stick to #node-dev.)

---

Another, related thought:

Do we have a moderator group target size? Typically it is considered poor practice to have a very large group of **visible** moderators (those with `+O` and showing up in IRC clients).
Perhaps there is some false basis behind that and it might be helpful for longer-term users than myself, such as @emilyrose and @aredridel to elaborate.

**Comment by Fishrock123** [comment]
For those that currently have access, I've PR'd some info about moderation / "regular irc operator things" to https://github.com/nodejs/moderation/pull/80.

**Comment by bnoordhuis** [comment]
> Typically it is considered poor practice to have a very large group of visible moderators (those with +O and showing up in IRC clients).

As an IRC user and moderator since the mid-90s, I believe it's fairly uncontroversial that the best channels have mods that only op when needed.  An @ sign besides a nick creates something of a power imbalance and an us-vs-them dynamic.

**Comment by MylesBorins** [comment]
In previous channels I've had the bit flipped for op, but not had auto op enabled. You can get chanserv to still kick / ban as necessary without showing off that you are an op. In a handful of communities we simply had 0 ops, and only escalated as necessary... stops people from thinking there is a power imbalance, or that certain people are better qualified to answer something.

I've also had channels with a bot idling that had op permissions... you could then dm the bot to have it do moderation work. Moderators are registered with the bot.

**Comment by emilyrose** [comment]
It is important to show our community that there are people who are paying attention to how folks are engaging, and taking action when necessary. For this reason, I strongly disagree with the view expressed by @bnoordhuis.

Channels with no visible operators convey a sense of "wild west" mentality that can silence many marginalized users out of fear that there will be nobody to step in should they be met with harassment or hostility.

We *must* maintain a visible operator presence for the safety of the most vulnerable among us.

I'm so happy to see so many folks interested in sharing this responsibility! 🎉

**Comment by emilyrose** [comment]
On a related note: I would like to propose that we consider holding "Operator Orientation" meetings where current/previous operators can share their methods and experiences with those that would like to get involved. 

Demonstrating things like ChanServ commands, de-escalation techniques, what to expect, etc.

I am happy to make myself available for such a thing should it be deemed useful.

**Comment by bnoordhuis** [comment]
I've had this discussion before (many times) and the crux is always whether you believe people will be nice or jerks in the absence of a visible police force.  I'm in the 'nice' camp myself.

**Comment by ashleygwilliams** [comment]
@emilyrose i was going to reach out to a few people (including you) personally to talk about an on-boarding of sorts. so glad you are on board!

@bnoordhuis i think we want to give people the option to get more involved and while i hear your concerns i dont think they are entirely on topic with this thread which is encouraging volunteers. if you have concerns about the number of moderators, please file another issue! thanks!

**Comment by aredridel** [comment]
Visible moderators are excellent; you do have to speak with care, kindness and extra deference to maybe being wrong if you're giving advice as an operator. People will often take you seriously and like you know what you're up to if you're wearing the hat. However, I think that's the downside: visible mods discussing openly and kindly and welcomingly more than make up for this and can really foster a great atmosphere and make the community feel wonderful.

**Comment by Fishrock123** [comment]
From https://github.com/nodejs/community-committee/issues/33#issuecomment-294998010 - If we want to add people to #Node.js (and likely #node-dev) then we can.

@nodejs/community-committee How do ya'll want to decide on who to add as mods? Myself or (almost) any other OP in #Node.js can add people.

**Comment by Fishrock123** [comment]
Do note that to be added as an OP you **must** register your nickname (display / user name) with freenode via `nickserv` (basically, have a registered freenode "account"). Also, you need to `nickserv set enforce` to fully protect your nickname.

**Comment by Fishrock123** [comment]
I see no reason not to add the people who are currently involved with committees.
As such, I am adding @MylesBorins, @Trott, @hackygolucky, and @evanlucas.

If there is no movement within the next week I'll add the other two existing collaborators who put their hands up: @italoacasas, and @hemanth.

Do note that we will still need more oceanic, european/african, and asian timezone coverage.

**Comment by rachelnicole** [comment]
I'm on irccloud and am always 100% connected to irc and I would be willing to moderate.

**Comment by MylesBorins** [comment]
+1 to rachel

**Comment by hackygolucky** [comment]
@emilyrose @ashleygwilliams Do we have an issue where planning for onboarding could occur? It'd be really neat to see the resources and hear from good experience on how we can help out(for those newer to IRC moderating especially but moderating in general is something I love to learn about)

**Comment by feross** [comment]
I've been helping moderate IRC informally for some time too, but I was never really onboarded. +1 to having an onboarding session for the new moderators! Would have been very helpful for me :)

**Comment by pup** [comment]
can this be closed now that @ nodejs/moderation exists?

**Comment by bnb** [comment]
@pup I believe it can 👍

**Comment by bnb** [comment]
If anyone has further things they'd like to raise or continue from this discussion, please ping the moderation team 😄
