### ISSUE TITLE
Define Working Group expectations and create boilerplate

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#201]
Attempting to integrate the [TSC WORKING_GROUP.md doc](https://github.com/nodejs/community-committee/pull/194), revealed some gaps between what we assert as [CommComm contributions](https://github.com/nodejs/community-committee#contributing) and how this is [defined today](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md) for the Node.js project.

At the [2017-12-28 CommComm Meeting](https://github.com/nodejs/community-committee/issues/200) we identified the current boilerplate as a blocker for landing #194. This issue captures the intent to remove the [Working Group bootstrap governance](https://github.com/dshaw/community-committee/blob/661d92e9caaeeb815eaa6c2f7f175587e77986e6/WORKING_GROUPS.md#bootstrap-governance) in the PR and collaborate here to create new definition in line with CommComm governance and contribution expectations.

CommComm Bootstrap Governance items to ratify or define:

- [ ] Define Working Group scope and authority
- [ ] Collaborators
- [ ] WG Membership
- [ ] WG Meetings
- [ ] Consensus Seeking Process
- [ ] Developer's Certificate of Origin 1.1
- [ ] Code of Conduct

**Comment by bnb** [comment]
@dshaw have there been any updates on this?

**Comment by bnb** [comment]
I'd like to add this to the agenda, it's come up a few times in the past two weeks.

**Comment by bnb** [comment]
Going to close this and re-open a new issue with a bit more focus (given the current state of things) and that can be labeled as "Good First Issue" for someone new to the project.
