### ISSUE TITLE
Proxy data and membership or how does Node.js expand beyond GitHub

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#202]
With the @nodejs/user-feedback initiative, we immediately identified the need to expand member activity and be able to capture that activity beyond the confines of what can be done here on GitHub. As a part @nodejs/user-feedback we have been collaborating to create a space for Enterprise organizations to be able to provide feedback to the TSC with the @nodejs/enterprise-advisory-group. Most of these users are managers and do not spend their day-to-day on (public) GitHub.

Today's Node.js project relies heavily on activity logged in GitHub to attribute action. 

- [ ] How do we proxy data to CommComm organized projects with attribution?
- [ ] Can we have members of a working group be members who do not have GitHub accounts?

**Comment by bnb** [comment]
@dshaw Not sure if there is much follow up on this. Is there anything discussion here you'd like to lead within the CommComm? If so, please add the issue to the agenda for visibility and engagement so we can get the discussion rolling! If not, we should close this 👍

**Comment by Tiriel** [comment]
I feel this is an important issue, but like @bnb said, I'm not sure what we can do at this point. Since it's been more than a month, I'm going to close it, but if you'd like @dshaw please by all means reopen and label it for next meeting!
