### ISSUE TITLE
strategic initiative for coordinating the website redesign

### ISSUE THREAD

**Issue by pup** [nodejs/community-committee#203]
as discussed in todays meeting (#200), it would be good to start the nodejs.org website redesign at the organization level. for this, i believe it's best to set up a [strategic initiative](https://github.com/nodejs/community-committee/pull/196) that coordinates the website redesign at a high level. this initiative should likely consist of commcomm, tsc and website working group members.

questions:

- should this initiative report both to the commcomm and to the tsc?
- what resources does it need? (e.g. a repository, funding from the foundation, etc)

this is blocked by #196, also related: https://github.com/nodejs/nodejs.org/issues/1534

**Comment by pup** [comment]
oh yeah, for future reference, i'd be happy to champion this initiative to the commcomm, if nobody objects

**Comment by bnb** [comment]
@pup I didn't hear any objections in the meeting, and I don't _see_ any here. I think we can have you champion this ❤️

**Comment by bnb** [comment]
@pup I just landed https://github.com/nodejs/community-committee/pull/196 - do you want to go ahead and PR this into STRATEGIC-INITIATIVES.md and add yourself as the Champion?

**Comment by pup** [comment]
@bnb i will - however i'm busy until the end of the week 😦

**Comment by bnb** [comment]
@pup no worries - enjoy your week 😄
