### ISSUE TITLE
Blog on CommComm Initiatives in 2018

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#204]
I thought it would be great to write a Node.js Collection blog on some of the achievements of the CommComm in 2017 and also initiatives that the CommComm is working on in 2018 - highlighting where support is needed, etc.

Are there any documents that I can look at to get this kicked off or does anyone have 30 minutes to talk with me about this? Once I write the blog, I would share it with this group for editing before posting. 

Alternatively, if someone in this group would like to write the blog, then I'm all for it! Just trying to lighten the load :)

**Comment by bnb** [comment]
@ZibbyKeaton I just landed a PR adding [STRATEGIC-INITIATIVES.md](https://github.com/nodejs/community-committee/blob/master/STRATEGIC-INITIATIVES.md) - should be a good starting point.

I'd be happy to talk with you if nobody is is able to, though I definitely think there's quite a few people who you could have productive discussions with and should be prioritized first! 😄

**Comment by flickz** [comment]
@ZibbyKeaton  Great idea. This is my first time here and have made it a commitment to participate fully this year. Initiatives on what CommComm will be working on in 2018 will be helpful.

**Comment by ZibbyKeaton** [comment]
@bnb let's see if anyone responds to this by next Tuesday, January 9. If not then, we can start to work together on this and add in additional people as need. I would like to get a few voices and quotes for the blog post.

**Comment by mhdawson** [comment]
I'm happy to chime in as needed.

**Comment by bnb** [comment]
@nodejs/community-committee if anyone is interested, please don't hesitate to raise your hand ❤️

**Comment by pup** [comment]
i'll gladly take this on!

**Comment by ZibbyKeaton** [comment]
@pup awesome! Are you thinking more of me interviewing you or writing this piece? I had a good convo with @bnb yesterday and formatted an outline. Happy to send to you if you want to write this 😀. Also happy to review and edit, if you would like another set of eyes before you share it with this group for final approval.

**Comment by pup** [comment]
@ZibbyKeaton oh an interview format would be cool, but if you already have an outline, feel free to send it over to me at `olivia@fastmail.com` and i'll write something up in the next days

**Comment by ZibbyKeaton** [comment]
Wow. I can't believe I posted this issue 23 days ago. Time flies by! A big thank you for @pup for pulling this together. I wanted to share what we came up with and confirm if folks are okay with it. Please provide your thoughts by EOD Tuesday (January 30). I'll be posting this to the Node.js Foundation Medium page and then adding it to Node.js Collection on Wednesday (January 31): https://docs.google.com/document/d/1MdbmOLlpnaax0swbQ7nSHYT7wD0o7lRvLk-wSarFjDg/edit#

**Comment by oe** [comment]
@nodejs/community-committee I'd love to get some reviews on the document @ZibbyKeaton linked!

**Comment by bnb** [comment]
@oe (nice new handle!) I did a review - left a few comments, nothing major. Looks great, thank you for taking the time to write this! 🙏

**Comment by mhdawson** [comment]
@oe looks good to me.

**Comment by obensource** [comment]
@oe looks good to me - super rad! 🙌

**Comment by ZibbyKeaton** [comment]
@oe planning to post this at 12pm ET today unless. Okay with you?

**Comment by oe** [comment]
@ZibbyKeaton fine by me!

**Comment by ZibbyKeaton** [comment]
This has been posted. I'll start sharing on other social channels this week :) https://medium.com/@nodejs/introduction-to-the-node-js-community-committee-and-our-focus-for-2018-c6872c1292e4

**Comment by bnb** [comment]
Since this has been posted, I'm going to close this. Thanks @oe and @ZibbyKeaton 🙏
