### ISSUE TITLE
Mentorship Initiative

### ISSUE THREAD

**Issue by Bamieh** [nodejs/community-committee#206]
The mentorship program is now part of the nodeJS organization on github 🎉 .

It would be awesome to add this issue to the next commcomm meeting (tomorrow i assume) To discuss the following:

0. New issues related to the mentorship program should be opened in the new repo from now on.
    - CommComm members and people interested in the program should watch the repo.
    - A new team should be created for this initiative under node
1. Kicking off the mentorship program:
    - Open an issue to iterate over the program structure and process so it is visible to everyone before starting (need explicit agreement from members of the commcomm and the TSC). Check https://github.com/nodejs/mentorship/issues/2 
    - Create a slack channel for the mentorship channel under nodejs (or do we have an already existing slack channel ready to be used)
    - Coordinate with the [nodejs/node](https://github.com/nodejs/node) project about the program to announce mentorship under their project etc.
    - Open an issue / reach directly to the monetors list in the [node-forward mentors program for node](https://github.com/node-forward/mentors).
    - Reachout to node evangelists and other active members to publicize the mentorship program to gain momentum (i believe @ZibbyKeaton can help out here).
2. I don't have the full background about Initiatives etc, and we do not have (yet) a document for the process or general details, so i would like some input about how things are usually carried on after this point forward.

**Comment by ZibbyKeaton** [comment]
@Bamieh sorry for the delay in responding to this thread. Happy to share it with folks. To confirm, it sounds like you are currently trying to find mentors right now and are still seeking feedback for the program? Any restrictions or qualifications on who can be a mentor?

**Comment by bnb** [comment]
I think we can take this issue off the cc-agenda, as it can/should be reported in the Initiatives report before we discuss agenda items 👍
