### ISSUE TITLE
Automatic meeting issue/minutes doc generation

### ISSUE THREAD

**Issue by mhdawson** [nodejs/community-committee#214]
@bnb, @rachelnicole  if you can put together a PR for templates here: https://github.com/mhdawson/create-node-meeting-artifacts/tree/master/templates to add the templates for the user-feedback repo I can then add to the meetings for which the issue/minutes doc is automatically created.

The tool checks the calendar and then creates the github issue and google doc.  We still have to add the info for the hangout/zoom manually.  For a number of WG's and the TSC I have a cron job that runs it a few days before the meeting.

You should be able to just copy the templates for one of the other groups and edit as appropriate (there are 4 different templates to modify).

If you have any questions just let me know.

**Comment by bnb** [comment]
@mhdawson submitted the PR: https://github.com/mhdawson/create-node-meeting-artifacts/pull/8

 @nodejs/community-committee would love a review if y'all have time. ❤️

**Comment by mhdawson** [comment]
Should be all setup now.  Looks like the next meeting is Feb 15, so the Monday of that week will be the first time the meeting is generated.

**Comment by Tiriel** [comment]
This looks just fine to me. Just been pinged by the test generation!

**Comment by bnb** [comment]
@mhdawson thank you so much - I'll be at an off-site and this will take a lot of load off my plate for
 that 🙏

**Comment by oe** [comment]
Can this be closed then? I suppose we should wait until after the next meeting to see if it works correctly?

**Comment by bnb** [comment]
Yeah, let's wait until it fires to make sure it works then we can close 👍

**Comment by bnb** [comment]
We can probably close this since it's been working :)
