### ISSUE TITLE
Supporting the Node.js Foundation in efforts around JS Interactive

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#216]
Coming up this year is JS Interactive, a refinement of Node.js Interactive in collaboration with the [JS Foundation](https://js.foundation/).

I think there is definitely a lot the Community Committee and its WGs, Teams, and Initiatives can help with.

I'd like to see what the Community Committee can do to help bolster and polish the event to help make it a really good event.

Some initial ideas that _I_ have (but by no means limit the scope of what we could do - please, share _your_ suggestions!):
* Help review CFP submissions
* Help create some content for the event
* Help engage the Node.js Foundation Individual Membership to get them out to the event
* Help engage the broader Node.js Community in the event

cc @ZibbyKeaton @gtewallace

**Comment by SarahKConway** [comment]
Some other ideas: 

- help us promote the event reg. and CFP details through your social networks and any MeetUps you participate in. Node.js Foundation will be creating social assets for community members and speakers to leverage
- Submit CFPs!!
-Work with me and @ZibbyKeaton on pre-event press interviews and contributed articles 
- Collaborate with Node.js End User Forum to encourage end users to submit talks and attend
- Help us reach new audiences beyond JS and Node developers eg. React, Nginx, Appstract, Angular, React frameworks

**Comment by hackygolucky** [comment]
@SarahKConway @bnb Will there be a program committee this year to help with reviewing? 
From prior years, I know who is selected for reviewing can always be improved upon. The user types represented in who helps review(keeping in mind reviewing !== final selection and curation) on the program committee as well as people who have the bandwidth to do the work is really key to good content--reviewing takes a ton of time. It's a lot of submissions 😆 

(also this is me criticizing myself because I helped with that selection in prior years)

**Comment by SarahKConway** [comment]
This is a current topic of conversation with our team. No decisions made yet. But there will be a program committee approach and we were planning to blog about it again to be fully transparent. I believe someone from NF/LF will be reaching out to you as well!

**Comment by dshaw** [comment]
Would be great to invite Foundation team to a CommComm meeting to discuss further. (Tomorrow's session may not be enough notice.)

**Comment by dshaw** [comment]
Coordinating around the [Collaborator Summit](https://github.com/nodejs/summit) would be great. Lots of folks were confused last year. Myself included. I had to extend my travel plans because I messed up the initial booking. Do we have dates for this year's Collaborator Summit yet?

**Comment by SarahKConway** [comment]
Both @zibbykeaton and I will be on the call. Would be happy to share what we know and explore more ways to work together on JSI.

**Comment by dshaw** [comment]
I mentioned that the next CommComm meeting would be tomorrow. Apparently I still have an old recurring meeting from some rescheduling that happened over the holidays. My apologies for the misinformation. The next CommComm meeting is on Thursday, 1/25.

**Comment by SarahKConway** [comment]
Plenty of time then! I'll share more info. in this thread as I get it. Just asked for dates for Collaborator Summit.

**Comment by mrhinkle** [comment]
I'd be glad to host a joint meeting of the JS Event Management folks, CommComm and other relevant parties in February and we can do our best to educate you on what the production looks like and then we can figure out how to get everyone that wants to be involved.

**Comment by bnb** [comment]
Going to close this since we're well beyond the event. Thanks y'all 👍
