### ISSUE TITLE
Add CommComm to Getting Started on website

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#217]
The [Get Involved section](https://nodejs.org/en/get-involved/) of the website does not mention or point to the CommComm or any CommComm resources. Let's fix that!

**Comment by dshaw** [comment]
@nodejs/website-redesign We're still landing patches to the [website](https://github.com/nodejs/nodejs.org) during the redesign, right?

**Comment by pup** [comment]
@dshaw sure!

**Comment by dshaw** [comment]
This could be a [Good First Issue](https://github.com/nodejs/community-committee/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for a CommComm member or observer.

**Comment by WaleedAshraf** [comment]
@dshaw I'll be working on this. I think some content from [CommComm Readme](https://github.com/nodejs/community-committee/blob/master/README.md) would be enough.

**Comment by WaleedAshraf** [comment]
I added point under Discussion:
The [Community Committee](https://github.com/nodejs/community-committee) is a top-level committee in the Node.js Foundation focused on community-facing efforts.

Is it right/enough?
p.s I used to Google to translate into other languages. Someone should verify that.

**Comment by dshaw** [comment]
Looks good Waleed. My only suggestion would be to put the CommComm link immediately following the first discussion bullet point, "The GitHub issues list is the place for discussion of Node.js core features".

**Comment by WaleedAshraf** [comment]
@dshaw I was going to move it up, but someone already merged the PR.
Do you want me to open a new one and change the position or is it ok?

**Comment by fhemberger** [comment]
Sorry, I merged it after 5 people approved the PR. Changes land usually quickly on the website. :grinning:

**Comment by pup** [comment]
closing!

**Comment by dshaw** [comment]
Thanks, @fhemberger.

@WaleedAshraf I would create a new PR to move up to 2nd position.
