### ISSUE TITLE
Please help me when install logagent in windows server 2008

### ISSUE THREAD

**Issue by truyenthongmang** [nodejs/community-committee#218]
I want to test when logagent collection log dns data in windows server 2008 (installed DNS Role)

But, when install logagent follow tutorial in: https://sematext.com/docs/logagent/installation-windows/ 
It is not successful (image attached)

Beside, I install plugin logagent to tranfer logdns to consumer kafka, but still error (image attached)

Please, help me! 

Thank you 

https://drive.google.com/file/d/123NEUYri8nkyRTrVDDZJs1LnCcFe1ibR/view?usp=sharing 

https://drive.google.com/file/d/1i9mHOx-ykJDIIBHpWJMP6fWJRv94w6cP/view?usp=sharing

https://drive.google.com/file/d/1yg40IS4exjwuPw1Ei8qJTxKSKjdqRfgc/view?usp=sharing

https://drive.google.com/file/d/16w5d9amAOseSWyslVmSTf2Hrjxpl1nic/view?usp=sharing

**Comment by pup** [comment]
closing as it's an unrelated issue
