### ISSUE TITLE
Add Fathy Boundjadj (@fathyb) as a meeting observer

### ISSUE THREAD

**Issue by fathyb** [nodejs/community-committee#220]
Please add me as an observer on the community-committee's meetings.

It's been 5 years since the first time I used Node.js and I'd be honoured to help to community that helped me build awesome applications for all platforms. I request this after seeing @bnb tweet ❤️

**Comment by bnb** [comment]
Added you as an observer for todays meeting: https://github.com/nodejs/community-committee/issues/226
