### ISSUE TITLE
Current Strategic Initiatives Review

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#222]
Now that we've got a documented set of Strategic Initiatives, I'd like to propose that we review the Initiatives and prune any that may need to be retired for various reasons.

Of the initiatives listed in "[Current Initiatives](https://github.com/nodejs/community-committee/blob/master/STRATEGIC-INITIATIVES.md#current-initiatives)", there are two that are relatively inactive:

- [nodejs/community-events](https://github.com/nodejs/community-events): Originally kicked off in the very early days of the Community Committee, it doesn't seem like there has been much/any activity since its initial launch.
- [nodejs/evangelism](https://github.com/nodejs/evangelism): Originally chartered as a WG of the TSC, it's initial purpose was very similar to that of the CommComm. Unfortunately, the repository and team have been inactive for an extended period. As much as it pains me to say it, I think the Evangelism WG may need to be retired in favor of focusing other CommComm efforts.

Additionally, there's an initiative that I personally took on and would like to discuss the future of a bit more–if members are _interested_ in there being a future for it:

- [Office Hours](https://github.com/nodejs/community-committee/issues/157): I initially talked with @hackygolucky about this, and decided to try to kick it off. I did a personal stream to see if there was any interest in it before moving it to an official property, and didn't get much engagement. I think this could be a very valuable initiative, but I think having it framed as an open Q&A with CommComm members may not be the best approach with the current stage the CommComm is in. An alternative approach may be to have it be an open and optional working session Q&A for CommComm members to jump in and have a more casual session to work on CommComm projects and help lower barriers for observers in addition to Q&A, but that's just one idea. Would very much like to hear others thoughts on this one.

Additionally, there's the task of reviewing the "[Need Champion for](https://github.com/nodejs/community-committee/blob/master/STRATEGIC-INITIATIVES.md#need-champion-for)" initiatives–not sure if we want to discuss those here, or in another issue.

**Comment by Tiriel** [comment]
I think this should be discussed in the next meeting (today?), just to be sure.

Other than that, LGTM! I particularly like the new approach on the Office Hours

**Comment by bnb** [comment]
@Tiriel yes, you're right. Adding the cc-agneda label and moving it to the agenda.

**Comment by mhdawson** [comment]
One thing we did for the TSC was to have an open issue tagged tsc-agenda so that it showed up on the agenda for each meeting.  We then have each of the champions provide an update (if appropriate).  I think its a good way to keep the initiatives top of mind and keep the members aware of whether they are progressing or not.  We might want to do the same for CommComm.

**Comment by Bamieh** [comment]
@bnb Do you think we can close this as resolved?

**Comment by amiller-gh** [comment]
Closing since I recently merged in a README refactor that I think updated strategic initiatives section to reflect current state 🙂 Please feel free to re-open if thats inaccurate!
