### ISSUE TITLE
Mini-Ambassador Program (Let NF know if you are interested in participating) 

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#228]
A goal for the Node.js Foundation this year is to engage with communities that exist outside of Node.js. To help support this initiative, we have created [a list of suggested conferences](https://docs.google.com/spreadsheets/d/1EVhBdOSviFE7CBDxigtA4i-CbSqrO20d7qvRBw6FDPo/edit#gid=0) that fall a bit outside of the usual JS and Node conferences with call for paper information (this is a living document that will be updated regularly as new opps arise). 

I thought this group might be interested in submitting to speak at these conferences. The Node.js Foundation is happy to collaborate with you and support you in however we can, whether it's helping with submissions, providing key talking points, a few suggested slides or [swag from the Node.js Community store](https://node-js-community-store.myshopify.com).

Please note, we do not have the budget to pay for speakers to attend conferences, so you would need to work with your company or the conference organizers to work on compensation. 

Below are some open CFPs for this groups review:

- [OSCON](https://conferences.oreilly.com/oscon/oscon-or), Portland, Ore. - Deadline January 30, 2018
- [LinuxFest Northwest](https://linuxfestnorthwest.org/conferences/lfnw18), Bellingham, Wash. - Deadline January 31, 2018
- [MongoDB World 2018](https://www.papercall.io/mongodb-world-2018), New York, New York - Deadline January 31
- [We RISE Women in Tech Conference](https://werise.tech/), Atlanta, GA  Deadline February 7, 2018
- [LinuxCon China + ContainerCon + CloudOpen](https://www.lfasiallc.com/linuxcon-containercon-cloudopen-china), Beijing, China - Deadline March 4, 2018
- [DeveloperWeek NY 2018](http://www.developerweek.com/NYC/conference/apply-to-speak/), New York, New York - open, but no set CFP deadline

If I get a lot of positive feedback from this group and interest in submission, we can work on formalizing this process a bit more. I am currently just trying to figure out if folks in this group are interested in participating in this.

**Comment by hackygolucky** [comment]
Of course I'd be the first to comment :P but I'd love to help support this. I'm already planning conf travel for this year, so this is a good list of suggestions to fold in for consideration. I'm especially interested in We RISE and DeveloperWeek and would love to chat about submissions that their audiences would appreciate and we could also fold Node.js stories into!

**Comment by bnb** [comment]
Thanks for sharing @ZibbyKeaton - really appreciate it.

I can probably definitely help out with east-coast conferences, especially in NYC.

I'd like to note: It would be within the realm of possibility for CommComm and other Node.js Org members to use the Member Travel Fund to attend conferences listed here to be an Ambassador.

**Comment by rachelnicole** [comment]
I'm also interested in this idea. I spoke at We Rise last year and it was v good, but that's just a FYI

**Comment by ZibbyKeaton** [comment]
Great! @hackygolucky @bnb I can reach out to the DeveloperWeek and We RISE summit and see what types of content they might specifically want this year and share with you. Let me know how best to help and assist you :)

**Comment by ZibbyKeaton** [comment]
Could this potentially be a topic of discussion during our next CommComm call? Would love to discuss goals here and how best to support folks. We can always try to formalize this a bit more if we get more interested in participating.

**Comment by bnb** [comment]
Added `cc-agenda` label @ZibbyKeaton. I'd also be v interested in helping out/speaking at All Things Open.

**Comment by mhdawson** [comment]
Sounds like a good idea to me. Getting people out to conferences outside the core Node.js ones to represent the project can only help overall growth.  I think a list of conferences with some context as to why/what we want to have covered (for example intro do Node.js, intro to community, cool tech using Node.js etc) would be great.

**Comment by bnb** [comment]
@mhdawson agreed, especially since we have a set of people with diverse backgrounds. Being able to categorize the events will help us split out our time most effectively 😄

**Comment by ZibbyKeaton** [comment]
CFPs close on this **Thursday (February 8)** for the **[We RISE conference](https://www.papercall.io/we-rise-tech)**. 

The goal of the talks must be to share your knowledge about technical and soft skill experiences with technical leaders, software developers, product managers, designers and other technologies. If you use a specific language, your talk must be understandable by good developers.

Tracks for this conference include:
- Front-end development
- Back-end development
- New technologies
- Product / UX / UI
- Leadership/career
- Community
- Workshops
- 101 CodeLabs

@hackygolucky: I thought a few good topics for you might be:

- Becoming a Host: How to organize a large dev conference in your area
- A guide into contributing to the Node.js Project and how other communities can apply it to their open source projects
- What is a Community Committee: Lessons learned in creating a community committee for the Node.js Project and how it might be able to help your open source projects

You might already have some thoughts here, but just thought I would throw some out there to help get the creative juices flowing :)

@rachelnicole don't know if you are interested in speaking here again, but I think your creative applications of Node.js could be great and explaining how you got into coding would be interesting for those that might come from a non-traditional CS background.

Others please feel welcome to speak up and apply here too! Happy to take a look at any of your applications, if you would like another set of eyes.

This conference will take place in Atlanta and speakers will get a free ticket to attend all the conference events. More info on CFP here: https://www.papercall.io/we-rise-tech

**Comment by ZibbyKeaton** [comment]
@hackygolucky and @rachelnicole reminder that submissions for We RISE is due today :)

**Comment by hackygolucky** [comment]
@ZibbyKeaton eek thanks so much!

**Comment by ZibbyKeaton** [comment]
CTA for next steps with this program: Please let me know if you want to participate and if you do, please send me a bio, and your areas of expertise, so I can better understand what events you would best to speak at (serverless, IoT, containers, events that focus on underrepresented groups in tech, education, etc.). Best to send to my email zkeaton@linxufoundation.org. We can then work on building out a speakers bureau see EdgeX example: https://www.edgexfoundry.org/news/speakers-bureau/ and I can remind you of conferences that are coming up in your area of expertise.

**Comment by bnb** [comment]
Going to remove the cc-agenda label for now. @ZibbyKeaton I'm definitely interested in participating, and will get back to you with the info shortly 👍

**Comment by mhdawson** [comment]
@ZibbyKeaton sent you my info through email.

**Comment by ZibbyKeaton** [comment]
Would it make sense to create a team under the community committee focused on the ambassador program? Happy to create documentation, etc. for this if folks think this is a good idea. Also, @hackygolucky and @bnb mind sending me your preferred bio and a few speaking topics? @rachelnicole mind sending me speaking topics for you? I pulled your bio from your site (LMK if you would like to make adjustments to it). I would like to put these on the Node.js Foundation's website.

**Comment by bnb** [comment]
@ZibbyKeaton sent you an email - apologies for the delay, I've been playing catchup from travel/OOO time this week 😬

**Comment by vamshi9666** [comment]
i have a community in our city and we conduct workshops and conferences in various colleges and developer communities.
so how can i get swag from node to encourage our attendees in node js ?
we are presently involved in mozilla community and we are able to recieve swag from mozilla trough bugzilla .
is there any such way ?

**Comment by ZibbyKeaton** [comment]
@vamshi9666 can you send me more information on this in email zkeaton@linuxfoundation.org? Also do you have a code of conduct for your conferences and workshops?

**Comment by vamshi9666** [comment]
as of now , we are under mozilla only . so we didn't adopt our own code of conduct .and we are thinking to expand and even have code of conduct .
thanks for response @ZibbyKeaton

**Comment by chowdhurian** [comment]
@vamshi9666 a code of conduct will be very helpful as your community expands, and we could help get you started!

To help with starting to produce documentation for a code of conduct (plus reporting and enforcement guidelines), these are some examples. You may already have some, but I've been looking through this for other initiatives and I'm happy to share what we've found!

## Example Code of Conducts are:
[Django Project](https://www.djangoproject.com/conduct/)
[PyCascades Conf](https://www.pycascades.com/conduct/)
[Write the Docs](http://www.writethedocs.org/code-of-conduct/)
[JSConf](http://jsconf.com/codeofconduct.html)
[Contributor Covenant](https://www.contributor-covenant.org/) + [tool](https://www.npmjs.com/package/conduct)

## Examples of Reporting:
[Django Project](https://www.djangoproject.com/conduct/reporting/)

## Examples of Enforcement Guides:
[JS Foundation](https://js.foundation/community/code-of-conduct/enforcement)
[Django Project](https://www.djangoproject.com/conduct/enforcement-manual/)

I'm confident others here can provide you with more specific assistance, but I hope these are enough to get started.

**Comment by bnb** [comment]
@ZibbyKeaton would you be interested in getting this documented as a rolling thing for the entire Node.js org? I think it may be helpful to create a document and the publish it in the Admin repo if so 🤔

**Comment by ZibbyKeaton** [comment]
@bnb yes, I think that would be a good idea. I'll get something rolling on this.

**Comment by Tiriel** [comment]
Where are we on this subject? Is there something actionable, or need for an update on confs/more ambassadors?

cc @ZibbyKeaton

**Comment by ZibbyKeaton** [comment]
I just need to create a document on this and add to the admin repo per @bnb suggestions. I'm uncertain how I would create a document and add to admin repo, however... If anyone wants to give me the how to this or send me to a little tutorial on how to get this done that would be much appreciated.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton Will send you instructions in the mail. 👍

**Comment by codeekage** [comment]
@nodejs/community-committee Where are we on this?

**Comment by ZibbyKeaton** [comment]
cc: @nodejs/community-committee 

During the last community committee meeting, we discussed putting all those who were interested in being a part of the Node.js Foundation Speakers Bureau/ambassador program on the website and also providing more context on how folks can partner with the Node.js Foundation for third-party events. A few folks wanted to take a look at the third-party event section to see if it read clearly, addresses questions that this group might get time and again, etc. Please see the copy on this below. Let me know if this addresses most of the questions this group generally receives and/or if there's anything missing from here that we've talked about. 

Happy to put this copy in a Google Doc and share the Google Doc with the group, if that makes editing easier:

_Third-Party Events (Second Tab)
We have an amazing community store that you can check out here. The community store has various Node.js goods for purchase. If you are a student-group, running a Node.js meetup or you are a Node.js Project collaborator (current list of collaborators found here) attending a conference and you would like to bring swag, you have the opportunity to receive free swag from the Node.js Community Store. 

We have a limited budget for how much swag we are able to give out, so please keep this in mind when you make your requests. We will try to accommodate you as much as possible. 

Please note we are only able to provide swag for events that have a code of conduct. Please email pr@nodejs.org for all swag requests.

If you are running a larger Node.js or JavaScript conference and are looking to partner with the Node.js Foundation, please reach out to Zibby Keaton of the Node.js Foundation (pr@nodejs.org) to discuss opportunities. We ONLY partner with events that have a code of conduct, and in most cases, we are not able to sponsor the event, we can only offer partnership opportunities. 

A few Node.js working groups are working with the Node.js Foundation community team on swag bags. If you are interested in learning more about this program, please send a note to Tracy Lee (tracy@thisdot.co) and Ann Marie Tonog (annmarie@thisdot.co). This option is only open to Node.js working groups, which are listed here._

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton This is great 👍 

my suggestion:
> Zibby Keaton of the Node.js Foundation (pr@nodejs.org)

I think it would be better if you add your own email ID OR  rephrase it as "reach out us at pr@nodejs.org" because, from email id, the sender doesn't know who is going to read it.

And If there is only one email ID for all kind of requests, would it be better like this?

"
Please note we are only able to provide swag for events that have a code of conduct.

If you are running a larger Node.js or JavaScript conference, you can contact us to discuss partnership opportunities. We ONLY partner with events that have a code of conduct, and in most cases, we are not able to sponsor the event, we can only offer partnership opportunities.

Please email us at pr@nodejs.org for all swag requests and partnership opportunities.
"

**Comment by ZibbyKeaton** [comment]
We've posted the speakers' bureau and information on third-party partnerships to the Node.js Foundation page.

Speaker's bureau here: 
https://foundation.nodejs.org/news/speakers-bureau

Resources for event organizers here: 
https://foundation.nodejs.org/news/resources-for-event-organizers

**Comment by ZibbyKeaton** [comment]
I believe that we can close this issue, but let me know if others think it should keep it open or have questions here? I'll keep this open for another week, and then if I don't hear anything, I'll close :)

**Comment by MylesBorins** [comment]
Can I join?

Is there a way to let people know what content specific speakers can deliver?

**Comment by ZibbyKeaton** [comment]
Yes, you certainly can. I just sent you an email around how you can join. In terms of specific content, I recommend providing this information in your bio as well as your area of expertise section. Additionally, in our request a speaker form, we specifically ask what topics conferences are most interested in. When we get ad hoc requests, we will share this with the speaker bureau group, so they can determine if they are a good fit as well.

**Comment by bnb** [comment]
@RRomoff / @sarahkconway do y'all know if this is something the NF team is still pursuing?

**Comment by codeekage** [comment]
Should we revisit this issue or close since the [Speaker Bureau](https://foundation.nodejs.org/news/speakers-bureau) Programme already exist? 

cc: @ladyleet @amiller-gh

**Comment by keywordnew** [comment]
There's [this list](https://nodejs.org/en/get-involved/node-speakers/) of speakers on nodejs.org. I'm unclear if it's connected to this Mini-Ambassador Program :)

**Comment by bnb** [comment]
Considering we've not heard back from the LF folks, I'm going to close this for now. If we want to continue discussing we can re-open or create a new issue.
