### ISSUE TITLE
@nodejs/community-committee team members out of date?

### ISSUE THREAD

**Issue by addaleax** [nodejs/community-committee#23]
Just a quick question – is the @nodejs/community-committee team member list correct? If it should match the list of people in the readme, it’s outdated and should be updated (happy to do that myself if that’s the case). If not, I don’t quite understand the difference between the two groups (?).

**Comment by williamkapke** [comment]
They should be the same. It would be great if you would do that for us!

**Comment by addaleax** [comment]
Ok, done!

(ps: I noticed this because I thought of maybe pinging you in https://github.com/nodejs/summit/issues/39, just so you are aware the TSC/CTC is doing another collaborator summit in Berlin on May 4th/5th, right before JSConf.eu. I’m not sure whether that’s relevant to your interesets at all, and I’ve made enough noise now, so I’ll just leave it at this. :smile:)
