### ISSUE TITLE
Record and serve the meetings in audio format 

### ISSUE THREAD

**Issue by DiegoZoracKy** [nodejs/community-committee#232]
Hi, it seems that zoom client has an easy way to record a meeting in audio format. Would it be possible to serve the meetings in audio format (not live)? 

It will be way easier to have people following what's happening, listening to the meetings, if those could be downloaded to be listened offline, via mobile, while on the go. 

YouTube is really a great platform to keep the history of meetings, however it is not the best platform to be used in some cases. It doesn't support an offline mode, and it is required to be with the screen turned on during all the time (mobile). Currently, it is almost a requirement for those who want to listen to the recorded meetings, to be on an environment with Wi-Fi available (because of the amount of the data downloaded to play a video) plus some considerable amount of battery charge remaining. 

https://support.zoom.us/hc/en-us/articles/201362473-Local-Recording?mobile_site=true

**Comment by bnb** [comment]
Following up on this issue that apparently didn't get a response (sorry!), I don't think we should be opposed to meeting artifacts - it may be helpful to download the assets on a semi-regular basis from YouTube via the Admin dashboard and upload them.

This may deserve its own repo so we can archive _all_ meetings, as opposed to focusing exclusively on the videos for CommComm. At that point, we could (hopefully) automate it... though I'd definitely be interested in everyone's thoughts/feedback on this.

Also, for what it's worth: YouTube Red (the paid version of YouTube) provides offline availability and backgrounding. Not saying this is the most accessible or ideal solution, but it _is_ one approach 😬

**Comment by williamkapke** [comment]
YouTube plays in the background for me (iPhone X). 🤔 

Related history: https://soundcloud.com/node-foundation/

**Comment by chowdhurian** [comment]
For me, the Youtube app plays in the background of Android if I split the screen. Not it I just change to another app or activate the launcher. If I play Youtube through the Firefox browser (standard beta, don't remember for Focus), it will play in the background.

The point I'd like to make is that it would be better long-term to not rely on the behaviour of the Youtube app within the mobile ecosystem.

I'd propose having an audio version of each meeting that we could upload to a Node.js podcast. Podcast apps (open source ones available! 🎉) make sorting, searching, and offline availability easier to do for those who need it.

**Comment by refack** [comment]
> YouTube plays in the background for me (iPhone X).

I think that is available only to people with "YouTube Red"

**Comment by bnb** [comment]
Perhaps setting up an automagical conversion service would be a good way to help resolve this? Going to add Good First Issue and let someone grab it if they'd like.

**Comment by 07Gond** [comment]
Hi guys!
Is this issue still relevant?
I was wondering, we can use the '_youtube-dl_' package and doing some script around it for the audio download and then use the SoundCloud SDK or the HTTP API for the upload process.
🤔

**Comment by bnb** [comment]
Since we have not seen traction on this in quite a few months, going to close. @07Gond if you or anyone else is interested in picking this up, I'd be happy to re-open.
