### ISSUE TITLE
February CommComm meeting schedule

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#233]
My calendar has fallen out of sync mid-month with http://nodejs.org/calendar again.

@bnb Can you confirm that the Feb 8th meeting has been moved to Feb 15th?

In the future, when these scheduling changes happen, it would be really nice to have a heads-up issue so we can adjust our calendars. 🙏 Thank you.

**Comment by bnb** [comment]
@dshaw Meeting is Feb 8th as you'd expected. Looks like @mhdawson made this one recurring, where the previous ones weren't (each had been entered manually by someone other than myself).

**Comment by bnb** [comment]
I moved the meeting on the calendar to reflect the appropriate date. From now on the calendar should accurately and unchangingly reflect reality unless otherwise noted in this repository.

**Comment by dshaw** [comment]
Closing. Thank you.
