### ISSUE TITLE
Meeting for reviewing membership guidelines

### ISSUE THREAD

**Issue by oe** [nodejs/community-committee#234]
Due to known, but also private reasons, I'd like to request that we hold a separate 1-hour meeting with the sole goal of revising membership guidelines. This has to take absolute priority over most other things we're currently doing.  I'd like to kick this off as soon as possible.

**Comment by Tiriel** [comment]
Obviously, given my last two issues, I'll second that.

Although, as have been pointed out, there is no crisis per se, It's still a matter that needs to be sorted before everything else IMHO.

And I'd like to state again because that seems to be a major concern and I don't feel I've been quite understood about that: there is no intent whatsoever to deter anyone. But I think better triaging of newcomers starts with clear roles, pathways, and expectations.

**Comment by oe** [comment]
Going to add this to the meeting agenda, if anything just to find people interested in coordinating this and scheduling a meeting.

**Comment by mhdawson** [comment]
@oe you may want to add to the issue for the meeting as well as it was already generated earlier in the week.

**Comment by JemBijoux** [comment]
I am definitely interested in participating. Subscribed.

**Comment by mhdawson** [comment]
I'd like to participate in the discussion.

**Comment by obensource** [comment]
I'd like to join as well! 🎉

**Comment by hackygolucky** [comment]
I'd love to participate!

Between scoping out what commcomm members do vs. working group members and enabling folks for the work they want to do. CommComm members are administrators who help remove barriers and enable the individual groups and teams to do work. This, combined with the prior governance written around participation or attending meetings to be onboarded needs to be revisited(much of this is my fault 😓 )

**Comment by Tiriel** [comment]
@hackygolucky Just to make it clear, at least in my opinion, it's not your "fault" at all. It's not even anyone's fault. The current governance guidelines worked great unitl now, to pick up some a good pace. Now that we're getting some speed and steam, it can be improved and reworked, but that doesn't mean it was terrible or faulty before that.

Thanks for your hard and continuous work ❤️

**Comment by bnb** [comment]
@oe do you want to take on the task of scheduling a meeting? Or would someone else want to?

I am also interested in participating.

**Comment by Tiriel** [comment]
As said in #245 I won't be here at this week's meeting, so I'll understand if someone takes on the task of organizing this.

Otherwise, if it's ok for everyone, I'd like to take this and open a doodle and suggest meeting times. I also got some propositions to discuss in this meeting anyway!

**Comment by oe** [comment]
@Tiriel that sounds like the best option, go ahead!

**Comment by Tiriel** [comment]
Sorry for the delay! Here's the doodle:
https://doodle.com/poll/kvvq48y4whcdx42q

I preserved week-end for family folks, but don't hesitate to suggest new dates if none fits your agenda.

**Comment by Tiriel** [comment]
Quick update, since the first date proposed is Friday, I'll let the doodle opened until Friday 1 PM UTC

**Comment by Tiriel** [comment]
I'll let it open for a few hours more since some people have expressed interest and have not responded yet. Namely, if @hackygolucky , @bnb and @obensource , I'm waiting for you!

Of course, if anyone else wants to participate, they are deeply welcome!

**Comment by Tiriel** [comment]
Hi everyone!

Based on the Doodle, the meeting will be on *next tuesday, February 27th at 6PM UTC* 

If you haven't answered the Doodle but can be here, don't hesitate! I'll try and setup a zoom, and give the link shortly beforehand.

See ya!

**Comment by bnb** [comment]
@mhdawson @chowdhurian @JemBijoux @oe just wanted to make sure to ping y'all about the meeting tomorrow at 1pm. See everyone there 😁

**Comment by bnb** [comment]
(Added it to the Node.js Foundation calendar)

**Comment by obensource** [comment]
Sneaker entry!

Just snuck into the poll last minute! Stoked to be a fly on the wall and offer any helpful thoughts I can! 🎉

**Comment by obensource** [comment]
@Tiriel apologies for not responding soon at all after you pinged me! 🙏

**Comment by JemBijoux** [comment]
Hey, thanks for the reminder @bnb. Unfortunately, I now have a scheduling conflict, something has come up. Any chance we can record it or make it available after the fact?

Very interested because I also want to step up my activity a bit. You folk have my full support with whatever is discussed either way.

**Comment by Tiriel** [comment]
Hey everyone!

Here's the last friendly reminder!
Meeting will be today *at 6PM UTC* (got mixed up in the last comment, the proper time is the one on the doodle).
Localized time of meeting:
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Community+Committee++-+Reviewing+Members+Guidelines+meeting&iso=20180227T18&p1=1440&ah=1

I'll post the zoom link at the last minute, so don't be afraid!
Thanks y'all!

**Comment by hackygolucky** [comment]
Hey y'all, I would have loved to attend this meeting, but unless we @-everyone who expressed interest directly, it's generally less likely they will catch that these messages continued for planning and attending a session(otherwise it assumes everyone is paying close attention every day to an issue they commented on, which is tough when you're not working on oss for day work). 

I'm unfortunately also not going to be able to attend this meeting.

**Comment by bnb** [comment]
Sorry it wasn't communicated as effectively as it could have been, @hackygolucky 😞

I will personally try to do better with this in the future, and also encourage others to do the same.

**Comment by bnb** [comment]
Here's the join link for the Zoom meeting: https://zoom.us/j/719834158

Also, per request, I've created a doc for us to take notes on the meeting: https://docs.google.com/document/d/1jVUmEId-McK8Aooenwfm8gDjsaAbisiLDMjQ9PsyYlA/edit?usp=sharing

At the beginning of the meeting, I'll ask if there's anyone who can take notes for the meeting.

**Comment by Tiriel** [comment]
Thanks @bnb for the huge help!

@hackygolucky : 

> I'm unfortunately also not going to be able to attend this meeting.

I'm sorry to read that, your advice would have been deeply welcomed. I tried to ping a few persons interested some days ago, including you, but since I've not been working with GitHub for long, I may have missed something to get it done properly. I'll check this so I improve on communications for the next time! 
Anyway, I don't think we'll have everything resolved in just one meeting, so I hope we can find a time when everyone will be able to attend the next one!

**Comment by hackygolucky** [comment]
@Tiriel No worries! You tried. I'm really bummed I can't attend. I'm hoping to participate here after notes are added from today's meeting. Again, I'm really sorry I have a work conflict I can't move.

**Comment by oe** [comment]
Thanks everyone for coming! Unless anyone has objections, I'll schedule the next meeting for the __13th of March 2018, 6:00PM UTC__. I'll open a new issue accordingly.

**Comment by chowdhurian** [comment]
Meeting over. Scope has changed slightly. See [minutes](https://docs.google.com/document/d/1jVUmEId-McK8Aooenwfm8gDjsaAbisiLDMjQ9PsyYlA/edit?usp=sharing).

**Comment by bnb** [comment]
CommComm members: Feel free to reach out if you'd like a copy of the meeting recording ❤️

**Comment by JemBijoux** [comment]
Thanks @bnb. yeah had a look at the notes, and I'll definitely make time for the next one. (I'm a new manager at my company so sometimes end up pulled into work stuff I can't skip, but if I block off the time in my calendar sufficiently ahead of time it's usually good.) 

If I could get a recording that would be great. Thanks!

**Comment by hackygolucky** [comment]
Blocking off my calendar right meow to help out in the next meeting! Thanks everyone!

**Comment by Tiriel** [comment]
Thanks everyone for yesterday's meeting!

I know it must seem pretty unproductive for some since we haven't come to a concrete proposal yet, but I think we have taken a big step forward anyway by redefining the scope, and I like the discussions we had.

**Comment by mhdawson** [comment]
Sorry I missed the meeting, but from the notes it looks like there was a good discussion.

**Comment by JemBijoux** [comment]
Dang, I know I said I wanted to make this one, but with the time change this weekend I now have a conflict again. (Meetings early in the day PST are tricky for me to make with my work schedule.)

I'll watch for your meeting notes. Still in full support of improving our processes here and will help out from the sideline.

**Comment by bnb** [comment]
Meeting join link: https://zoom.us/j/150571995

**Comment by Tiriel** [comment]
Sorry, last minute problem, I'll try to join before the end

**Comment by chowdhurian** [comment]
I believe the membership guidelines have been revised, as the original comment intended.

I'm closing for now, but feel free to reopen if necessary.
