### ISSUE TITLE
joining localization GitHub teams

### ISSUE THREAD

**Issue by Trott** [nodejs/community-committee#239]
You folks are looking at the localization groups and how to manage them, right? If so, is there an agreed-upon procedure for joining a localization team? I'm not sure if it's consistent across teams or not. I've typically taken the approach that if you're already a member of some other team and want to join a localization team, then hey, sure fine. But I should obviously stop that if it's inconsistent with recent (or not-so-recent) policy. Help?

**Comment by Tiriel** [comment]
@Trott Glad you ask the question!
Since the new i18n effort has been kickstarted that's something we can talk about.

Actually, I see you've added some people to the [at]nodejs-fr team (not trying to ping them) for example, but A lot of these teams a pretty inactive. Like, I opened an issue to reactivate the fr team and start working again but I still haven't been added to the team and it has fallen silent again.

I think we need to make a big audit of the l10n teams and define some public interfaces, so to speak.

**Comment by Trott** [comment]
@Tiriel Would it help if I (or someone else) added you to nodejs-fr team? Until CommComm comes up with some concrete guidance, I'm fine with the idea that it's A-OK to add existing org members to dormant i18n groups they want to be a part of.

**Comment by Tiriel** [comment]
@Trott Honestly, I think so, since part of our new i18n effort is to see if existing teams want to continue and seek their approval (@obensource correct me if I'm wrong). But I may not be the most objective on the subject since I already tried to see if it could be reactivated.

**Comment by obensource** [comment]
@Trott @Tiriel my apologies–the flu knocked me out for the past week and I'm just starting to recover and pick back up.

Even though the translation process would be done via Crowdin now, the l10n group repos can definitely still serve as a place for formal membership definition and governance docs–which will be great for helping us keep track of who to communicate with as long as membership stays current. 

There's not an established a membership procedure yet, I think in light of the auditing @Tiriel mentioned–we need to:

* Do an audit of every l10n group to understand:
  * Is the group active, and/or would they like to continue the l10n group?
  * Who're the currently active members, and/or who has expressed interest in pushing the group forward?
* Request that currently active group members (or people who'd like to resurrect a group, or start a new one) update their l10n group's membership lists and add themselves to bring the group info up to date.
* PR 

@Trott I think as of right your loose-membership definition is what we've been operating under:

_Until we have a more formal process: if anyone says they want to help out with a l10n team effort–we should thank them and consider them a member._

This has mostly been the case for joining the i18n WG in the early stages too.

**Comment by obensource** [comment]
@Trott @Tiriel sorry–published that comment before I was done writing. If reading via email: please check out the additional points in the comment I've added.

**Comment by Tiriel** [comment]
@obensource ! Thanks ! Hope you’re getting better !

Sorry I had little time to develop earlier, but I’m pretty much on the same page concerning what needs to be done in terms of audit. I think this conversation can be transferred to the i18n repo though, we have lots to discuss I think. 

@Trott thanks for adding me to the fr team!

**Comment by obensource** [comment]
Thanks @Tiriel! No apologies necessary (I don't actually understand what you're apologizing about lol)! 

I agree. We can just open a new issue there and roll with it. 🙌
