### ISSUE TITLE
The Road to Charterdom

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#24]
I thought it would be helpful to create an issue to track what's still needed to get CommComm chartered by the board. It's probably too late to get any updates before the board meeting next Monday, but maybe we could target having an updated revision to present at the meeting after that?

My understanding is that there was some feedback from the board in a previous meeting, and that we still need to update the charter with that feedback. Is that correct @hackygolucky?

**Comment by ashleygwilliams** [comment]
we don't need this issue as the charter was approved by the board.

**Comment by williamkapke** [comment]
lol @ashleygwilliams that seemed abrupt 😖 

Indeed @nebrius, it was completed via email.

**Comment by nebrius** [comment]
Oh interesting, I didn't know we were approved, but yay! 🎉

**Comment by addaleax** [comment]
Is the charter somewhere public? Should it be in the repo here, like the TSC has it?

**Comment by williamkapke** [comment]
It is here:
https://github.com/nodejs/community-committee/blob/master/GOVERNANCE.md

I hadn't realized it was called "GOVERNANCE" till this moment 🤔
