### ISSUE TITLE
Node.js Application Showcase Announcement

### ISSUE THREAD

**Issue by mrhinkle** [nodejs/community-committee#240]
Just a quick note as a follow-on to this week's CommComm Meeting. 

The Node Foundation marketing team has recently released the Node.js Application Showcase on T[he Node.js Foundation Website](https://foundation.nodejs.org/resources/app-showcase).

From the Node.js Medium Blog post [announcement](https://medium.com/@nodejs/announcing-the-node-js-application-showcase-9fbaaa3e4824):

_The Node.js Application Showcase lists a variety of projects and products built with Node.js. It is sortable by development status (in development, in beta, in production), application type and by the other technology used. When clicked, each application “tile” reveals a short description of the app, its intended users, how the app helps them and how Node.js helped the app’s creator._

We have received over 80 submissions on examples of Node.js in action. We are vetting the applications and then publishing them as fast as we can. We've already published 40 of the examples but would love your help and feedback.  You can request an application to be added to the showcase via the [online form](https://docs.google.com/forms/u/1/d/e/1FAIpQLSecCh0Ze8TSjb2d1e8Xooik1Y4Jl4oMkpDxSBVhWYj824Qy5w/viewform?usp=sf_link).

**Comment by bnb** [comment]
Thanks for sharing, Mark! Going to close, since it's been up for a while now 👍
