### ISSUE TITLE
Should We Attempt an Update of Official Node.js Messaging

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#242]
For years, there has been some variation of the following tagline on the Node.js website:

> Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine. Node.js uses an event-driven, non-blocking I/O model that makes it lightweight and efficient. Node.js' package ecosystem, npm, is the largest ecosystem of open source libraries in the world.

The above is the _current_ tagline. While it's been modified and opened up a bit from the original tagline, I don't know if it is truly representative of what Node.js is... nor is it a very clear and concise or beginner-friendly way to describe the project.

Is this something that we should look at taking on? I'm not sure if this would be within the scope of @nodejs/community-committee, the Website Redesign team, or if it would need to be in collaboration with the @nodejs/tsc in the Admin repo. Mostly just interested in feeling out the right place for a formal discussion to happen 🤔

**Comment by Trott** [comment]
Evangelism WG, if it's still active, might be worth including too.

Node.js Foundation marketing folks as well? Not sure.

Lots of people have a stake. I agree it has vast potential for improvement. Just not sure who would be the best choice to make it happen.

**Comment by chowdhurian** [comment]
Testing the waters with a few thoughts here.

The scope for the Website Redesign team is being determined. The ongoing discussion is in its early stages. With the possibly extensive overhaul of the website, updating the official Node.js messaging could be a practical **parallel initiative**.

The Website Redesign may very well call for updated copy, messaging, and branding. If that's the case, action would be made easier by anticipating this need with early planning on how to involve Evangelism WG, Foundation marketing, the TSC, and other stakeholders.

I believe the next meeting for the Website Redesign team is on Thursday, 15th Feb. This matter could be added to the agenda. A discussion could be useful in finding the most relevant stakeholders, gauging interest, and finding relevance to the Redesign initiative 🤔

**Comment by MylesBorins** [comment]
I think a central issue in here, evangelism, or admin all could work. The most important part will be making sure active feedback is received from all stakeholders, likely during meetings or on mailing lists to ensure this isn't lost in the noise. I'm sure no one wants to be surprised

**Comment by ZibbyKeaton** [comment]
Representing the The Node.js Foundation Marketing team: we were actually working on a minor messaging refresh. The general focus of our messaging refresh is more towards media storylines and content for analyst work that we want to push out this year. Some items we might gather could be of use here. Happy to join in on further collaboration of messaging as it relates to the website or tagline/descriptions of Node.js.

**Comment by bnb** [comment]
For reference, it was discussed in the @nodejs/website-redesign meeting that this probably encompasses a more complete style guide rather than just an update the main header. We have some [existing content](https://github.com/nodejs/evangelism/blob/master/documents/socialMedia.styleGuide.md) in the Evangelism WG repo that can likely be iterated upon.

Given the context of a more complete document, @nodejs/website-redesign has agreed that they are willing to take this effort on. I made sure to let them know that there are _several_ stakeholders in this and that they will need to work with those stakeholders to make this work effective - they had no issue with that ❤️

**Comment by amiller-gh** [comment]
Now that website redesign is beginning to wrap up its IA phase and move towards content and high-fidelity mock development, I've created a ticket on our end to track this: https://github.com/nodejs/website-redesign/issues/34

If we feel it is better tracked in the @nodejs/website-redesign repo, we can close this issue to help keep the issues queue in CommComm clean! Otherwise we can leave it open for posterity/visibility's sake.

**Comment by bnb** [comment]
@amiller-gh totally up to you. I think tracking it in the website repo is 100% fine, and have no attachment to it being tracked here 👍
