### ISSUE TITLE
Translate Documents to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [nodejs/community-committee#246]
HI! I'd like to offer my contribution to this project by translating it into Spanish which is my native language. If you guys are interested let me know, And I'll gladly start working on it.

**Comment by Tiriel** [comment]
Hey! Thanks for your message!

There's now a fully active [i18n WG](https://github.com/nodejs/i18n) you can take a look at, and join us!. I can't guarantee you will be able to start translating today, but you'll be able to take part with the new workflow and start translating as soon as it's fully functional.

Thanks again, looking forward to seing you!

**Comment by obensource** [comment]
@LuigiBaute thank you for being willing to help out! We're excited to have you with us. 🎉

Since you've made a [related issue](https://github.com/nodejs/i18n/issues/21) in our working group repo, I'm going to go ahead and close this one. 🍻
