### ISSUE TITLE
nodejs-ko bot've been removed form org

### ISSUE THREAD

**Issue by outsideris** [nodejs/community-committee#247]
I'm one of nodejs-ko group. 
We're using `ko-bot` to deploy contents which we translated into [our blog](https://nodejs.github.io/nodejs-ko/) in CI automatically.
Recently `ko-bot`'ve removed from node.js org, see https://github.com/nodejs/nodejs-ko/issues/677 .

How can we fix this issue?

**Comment by Tiriel** [comment]
Hey! Sorry about this, I think that may be a side-effect of the Two Factor auth that has been enabled recently.

Part from that, there's now a [i18n WG](https://github.com/nodejs/i18n) active and the translation/localization will now have a new workflow you can take a look at. We'll be glad to have you there, everyone one is welcome!

**Comment by bnb** [comment]
cc @Trott (who was driving the enabling of 2FA) and @obensource (who's the CommComm champion for the i18n initiative).

**Comment by Trott** [comment]
Yes, even the bots require 2FA.  I forget who took care of it for some of the other bots, but it was *someone* on @nodejs/build, so hopefully they'll provide additional info here. Anyway, once you have 2FA enabled, the bot can be re-added (presumably as an outside collaborator?).

**Comment by gibfahn** [comment]
I think it was @rvagg, see https://github.com/nodejs/build/issues/943

**Comment by marocchino** [comment]
I am enabled 2FA of @ko-bot .

**Comment by Trott** [comment]
@marocchino Great. You are an admin for the https://github.com/nodejs/nodejs-ko repository. You should be able to go to https://github.com/nodejs/nodejs-ko/settings/collaboration, scroll to the bottom and put `ko-bot` in the box there and click the "Add collaborator" button. I think that should resolve this issue, but if not, let us know!

**Comment by outsideris** [comment]
@marocchino I've added @ko-bot as a collaborator of nodejs-ko. You should accept the invitation.

**Comment by rvagg** [comment]
<img width="707" alt="screenshot 2018-02-26 13 50 41" src="https://user-images.githubusercontent.com/495647/36651265-20489a6a-1afc-11e8-8c25-89b058307cde.png">

I don't think https://github.com/orgs/nodejs/teams/tsc/discussions/1 is accessible unless you're on that team right?

So, save the token seed and share it amongst the people that need access to it. Unfortunately when we do this we turn it into effectively a second password, so treat it carefully! We've saved seeds in nodejs/secrets along with backup codes for this purpose using dotgpg for org-level stuff fwiw.

**Comment by marocchino** [comment]
I received the invitation again and the build succeeded.
Thanks for all the help.

**Comment by Trott** [comment]
Thanks for following up on this and sorry for the inconvenience. I'm going to close it, but feel free to re-open or comment if it should remain open.
