### ISSUE TITLE
Setting up regular meetings

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#25]
Now that we have been officially chartered, should we start holding regular meetings like the TSC does? I think it would be helpful in generating momentum, at least at the beginning.

**Comment by nebrius** [comment]
As a start, how does offsetting our meeting from the TSC meeting sound? The TSC meet's every other week at 20:00 UTC on Thursday, so we could also meet at 20:00 UTC on Thursday on the week that the TSC doesn't meet.

Does this schedule work for everyone?

cc @nodejs/community-committee

**Comment by jasnell** [comment]
Works for me

**Comment by nebrius** [comment]
Following this schedule, our first meeting would be Thursday April 13th at 20:00UTC (4pm EDT, 1pm PDT).

**Comment by gr2m** [comment]
I can’t make the first meeting, I’ll try to make it work for the 2nd. Please send some notes :) If there is anything I can help with, let me know

**Comment by nebrius** [comment]
@gr2m we'll definitely have notes! Will this proposed time usually be difficult for you to make?

**Comment by hackygolucky** [comment]
Yes please, I'd love this! @nebrius scheduling our first meeting was on my immediate and unfortunately long to-do list. Thank you thank you.

We will document the meeting and publish notes to this repo @gr2m.

**Comment by jasnell** [comment]
I will have to miss that first call as I'll just be arriving at my hotel in Barcelona for NodeConf right about that time. However, I'll catch the notes after and will catch you all at the next one

**Comment by addaleax** [comment]
@jasnell That’s the TSC call next week you’d be missing then, this one would be a week after Barcelona ;)

**Comment by rachelnicole** [comment]
@jasnell omg im upset I didn't know about nodeconf Barcelona!!! Have a good time

**Comment by jasnell** [comment]
@addaleax ... ha! you're right... still may end up missing it as I'll be in Ireland visiting the new corporate overlords ;-)

**Comment by gr2m** [comment]
> Will this proposed time usually be difficult for you to make?

I’m in LA, the time works great for me, thanks!

**Comment by yasinaydin** [comment]
Works for me See you at 13th then

**Comment by jpwesselink** [comment]
SGTM!

**Comment by hackygolucky** [comment]
I may need to see if we can get an internal meeting moved. I can miss this week's, but the Node.js Foundation group has a standing meeting every week at this time. 

Should we set up a cal invite? Are we just going to use the Node.js uberconf account?

**Comment by williamkapke** [comment]
We should open a specific meeting issue for Thursday's meeting similar to the TSC/CTC's workflow and include the time/date, attendees, agenda, and participation information. Any volunteer?

AFA the time: It is better for _my_ schedule to keep it in line with the TSC's time... It's easier for my coworkers to remember that I block out "the 1 o'clock hour on Thursdays"

**Comment by nebrius** [comment]
I have it on my todo list for today to get an issue opened for this meeting. I want to try and use the same tool that we use to generate TSC/CTC meetings, which IIRC is pretty easy to update.

As for the meeting tool, I'd recommend sticking to Google Hangouts unless we know that we'll exceed the 10 person limit. It's a lot easier to get videos recorded and up on YouTube if we do everything through Google.

Looks like @williamkapke already added the event to the foundation calendar (thanks!)

**Comment by jasnell** [comment]
Very happy to see this moving forward. I will miss this first meeting this week unfortunately.

**Comment by bnb** [comment]
Would love to join in on the meeting, if possible!

**Comment by nebrius** [comment]
FYI the issue for the next specific meeting is at https://github.com/nodejs/community-committee/issues/27

@bnb we'd love to have you join!

**Comment by hackygolucky** [comment]
Heyo! I don't think we got a repeating meeting set up, but I believe the next one is supposed to be this Thursday. Is it possible that we could move it to 4:30pm EST? I have a weekly meeting I can't get out of moving forward.

We will also need some minutes of this meeting for a private session.

**Comment by jpwesselink** [comment]
works for me!

**Comment by nebrius** [comment]
I'm going to be flying from 12pm PDT to 5pm PDT on Thursday, so I'll have to skip. I can still prep the agenda though, I'll try and get to that later today sometime.

**Comment by nebrius** [comment]
Meetings are going regularly now, closing.
