### ISSUE TITLE
Speaker @NodeJS Event Africa, Nigeria

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#250]
A call out to awesome Noders and CC_Members to volunteer for a remote talk... Thanks, @MylesBorins  for accepting to participate!!

**Comment by mhdawson** [comment]
Is there a time set? If the talk is done remotely as long as it does not conflict with other things on my scheduled I would participate.

**Comment by dshaw** [comment]
Happy to help.

**Comment by codeekage** [comment]
Thank you all for participating... the event starts by 10 am WAT - 4pm WAT

**Comment by mhdawson** [comment]
What day ?  Given the timezone differences 3PM would work best for me.  

Are you looking for specific topics and how long are the talks going to be ?

**Comment by codeekage** [comment]
10th March, 15mins, 20mins tops... More talks on collaboration and contribution. Getting started with NodeJS...

**Comment by codeekage** [comment]
![ng9ci3xy](https://user-images.githubusercontent.com/24491408/36871179-a1b052bc-1da1-11e8-866b-5bb157d6bfc4.jpg)
Awesome Myles!!!!

**Comment by codeekage** [comment]
@mhdawson would like to have a flier too?

**Comment by inidaname** [comment]
This is awesome I can't miss this

**Comment by mrhinkle** [comment]
I would be glad to give a talk on behalf of the Node.js Foundation. I am trying to figure out my schedule that day so let me know if you'd like that and if so what time slot you'd like for me to do so. Great job pulling together this event!

**Comment by flickz** [comment]
@codeekage Do I have to travel down to PH?

**Comment by codeekage** [comment]
@flickz  oh yes... lol!

**Comment by codeekage** [comment]
@mrhinkle  Thanks a million

**Comment by mhdawson** [comment]
I could do sometime between 3-4 PM WAT, which I think translates to between 9-10AM for me.

Sounds like you want talks on getting started with Node.js.  I could put together a few slides on my recommendations of how to get started and then a quick overview of a few of the working groups and strategic initiatives as  good places to look at starting.   Node sure what @MylesBorins was planning to cover.

**Comment by mhdawson** [comment]
Alternatively if you want technical talks I could give one on N-API.

**Comment by bnb** [comment]
@codeekage I'd be happy to present as well, if you still need slots 👍

**Comment by codeekage** [comment]
please, @mhdawson @bnb @mrhinkle @dshaw drop your twitter handles.

Thanks  a million

**Comment by mhdawson** [comment]
My twitter handle is @mhdawson1

**Comment by bnb** [comment]
My twitter handle is [@bitandbang](https://twitter.com/bitandbang)

**Comment by codeekage** [comment]
Drum roll....... for NodeJS Event, the order of event!!!!!!

**Comment by codeekage** [comment]
NodeJS Event order of event

1. Opennig speech by NodeSchoolPhc Organizers - 10:30am - 10:45am

2. Welcome video by NodeJS Foundation TSC Director Myles Borins - 10:45am - 10:50am

3. Setup and preparation for Workshop proper - 10:50 - 11:00

4. First mentoring section in JS by GDG Gloria - 11:00 am - 12:00pm

5. Second mentoring section in Node by NodeJS Africa Precious Dyke - 12:00 pm - 1:00pm

6. Third mentoring section in Node by NodeSchoolSF and NodersJS champion Fernando Larrañaga - 1pm - 2:30pm

7. Networking, Games and Lite Refreshment - 2:30 am - 3:00pm

8. TSC and Strategic Initiative by NodeJS Foundation TSC Chair Michael Dawson - 3:00 am - 3:20 pm

9. Collaboration and Open Source by NodeJS Africa and Tech Ph Precious Chunkundah - 3:20 pm - 3:40 pm

10. About NodeJS Foundation by Chair NodeJS Foundation Tereny - 3:40pm - 4:00pm

11. Closing speech by NodeJS Africa Hassan Sani - 4:00pm - 4:10pm

12. Photos.

All-time is UTC(WAT)

**Comment by inidaname** [comment]
@bnb @MylesBorins @mhdawson @mrhinkle here is a zoom link to Port Harcourt NodeJs Event https://zoom.us/j/171884193

**Comment by codeekage** [comment]
Thanks to @inidaname  @mhdawson @bnb for making the event a successful!
