### ISSUE TITLE
No Longer Seeking Committee Membership

### ISSUE THREAD

**Issue by tobyfarley** [nodejs/community-committee#254]
I am withdrawing my request to join the community committee. Can I also have my name removed from the observer list? I will use the YouTube public stream to access future meetings.

**Comment by bnb** [comment]
Sorry to hear that you're not interested in joining anymore, Toby 😞

As linked above, I've submitted a PR to the tool we use to remove you from the observer list.

**Comment by bnb** [comment]
You've been removed. Thanks for being an observer, @tobyfarley ❤️
