### ISSUE TITLE
Is there a forum where I can ask questions?

### ISSUE THREAD

**Issue by markfilipak** [nodejs/community-committee#259]
Is there a forum where I can ask questions?

Warm Regards,
Mark.

**Comment by oe** [comment]
Hi @markfilipak! We don't have a traditional online forum, but for questions related to the usage of Node.js, we have the http://github.com/nodejs/help repository. For questions regarding internals, there's the #node-dev IRC channel. Additionally, we have a Slack community: http://nodeslackers.com. Hope this helps!

**Comment by bnb** [comment]
Thanks for the response @oe - going to close this for now. ❤️

**Comment by markfilipak** [comment]
@oe

[http://github.com/nodejs/help] is for programmers, not for civilians asking questions.
And [http://nodeslackers.com] is unresponsive. It appears to be some sort of invitation site for slack.zendesk.com. I don't know how it's supposed to work, but the folks at Slack are scratching their heads. I'm mystified.

I'm looking for discussion of nodejs, not creating a workspace. Do you know of any sites for nodejs discussion? -- I'm hoping that will eventually lead me to CJS.

**Comment by oe** [comment]
@markfilipak Ah, you're referring to conversation about Node.js from a non-programming standpoint? Unfortunately, I don't really know any good places for discussion about that. Maybe @dshaw or @bnb know of somewhere?

**Comment by codeekage** [comment]
@markfilipak  something on community building or ???

**Comment by bnb** [comment]
@markfilipak I highly suggest trying to fill out the form provided on http://www.nodeslackers.com/ - it will send you an email that will enable you to join the Node.js Slack team. No matter your question, even from a non-programming standpoint, someone may be able to help you in http://github.com/nodejs/help. Beyond those two resources, I'm not really sure either - there aren't any public forums as far as I know that will discuss that. 

Can you explain what you mean when you say you're hoping that will eventually lead you to CJS?

**Comment by markfilipak** [comment]
(I'm a bit overwhelmed by all the sudden attention...)

You see: This is why github is not an appropriate site for non-developers. Yet, when someone wants to point someone to a place where questions can be submitted, they point here (not just for nodejs, but for every project that's hosted by github). It's a real show-stopper.

@oe wrote: "... from a non-programming standpoint?" More from a non-developer viewpoint. I've been manipulating the DOM since DOM-1. I wrote my own DOM browser (in javascript) long before firebug existed. I've written thousands of lines of javascript (and other scripts, compiled code & assembled code, and chips too). Once upon a time, I even wrote a real-time, preemptive, multitasking kernel for an 8051 microprocessor in assembler. I know what developers do and how developers think. I've had plenty of developers work for me in my projects. What I need is nodejs from an architectural viewpoint, but that's not what most folks are going to want. What I REALLY need is to interact with other people who are exploring nodejs -- and that's not developers. Developers are not the people I want to converse with, except to get answers when questions come up (which is less often than you would assume). I want to work out answers with others of my type (!developers).

@codeekage wrote: "... community building or ???" I'm unsure what you mean. Do I want to build a nodejs community? Ahm...    ... I want to use javascript for scripting in Linux.

@bnb wrote: "... fill out the form provided on [http://www.nodeslackers.com/](http://www.nodeslackers.com/)" I've done that more than 10 times.

@bnb wrote: "Can you explain what you mean when you say you're hoping that will eventually lead you to CJS?" I'm not sure because I don't really know what CJS is (other than it's a fork of GJS targeting the Cinnamon desktop).

Look, I've been searching for an alternative to bash & perl & python for years. I heard of this thingy called "nodejs". I subscribed to the newsletter for half a year and couldn't get past the marketing drivel -- I know that nodejs will make my teeth whiter and my breath sweeter and my panties creamy. My question (for a long time) was simply "What the hell IS nodejs?"

I gave up on nodejs. Then, recently, a fellow named Jason Hicks steered me back to nodejs. Jason works on CJS. He says I need nodejs for CJS. I'm not sure what CJS is, but I'll go with him and have faith.

I guess what I seek is to write a file-browser -- like a web-browser, not for the Internet, but for files and programs. Linux has been around for 20 years and there's no way to even search for files... It's ridiculous. If you don't learn the CLI commands, you can't do squat with Linux, and learning the CLI commands is nearly impossible and I don't want to do it. I ran Unix and IBM JCL in college and hated it. I learned DOS CLI commands and hated them. I want a graphical OS with graphical utilities, even if I have to write them myself. ...Um, sorry for the rant, but now you know what I seek.

Cheers,
Mark.

PS: Do you know Total Commander? That's what I'd like to duplicate... and more.

**Comment by bnb** [comment]
Thanks for the lengthy response @markfilipak - I'll try to address each of your points as accurately and concisely as possible (if I miss any, please don't hesitate to let me know!)

>What I need is nodejs from an architectural viewpoint, but that's not what most folks are going to want.

This is a bit loaded. Node.js can run basically _anywhere_ - from on a RaspberryPi, to your desktop to power the everyday apps you use, to a a cluster of orchestrated servers distributing data across datacenters, globally.

There's quite a few ways you can look at Node.js from an architectural viewpoint - are you interested in _how Node.js works_, how it is used and managed in your system, or how you'd actually _architect_ a reliable system to deploy something like a web app built on Node.js?

I realize I just spewed quite a bit of information, and it may not all make sense - what I'm mostly trying to get at is: _what kind of_ architectural viewpoint?

We can almost certainly help you get to an understanding of any of those with a small bit of effort, we just want to make sure we're helping you get to the place you're looking to go! 😁

> What I REALLY need is to interact with other people who are exploring nodejs -- and that's not developers.

First: I **really** love this statement, and I've been trying to drive it home with more and more people recently. Thank you for sharing this.

You are correct - many people who are exploring Node.js aren't necessarily developers at this point. They're managers. They're DevOps teams. They're Security experts. They're the ones that Node.js is reaching now, and we're not doing a good enough job to optimize for their experiences–we're getting there, but we're _not_ there... yet.

My explicit advice on this: If it's at all humanly possible, go to a local meetup. Virtually every medium to large city in the world has some kind of Node.js-focused meetup, or at the very least a meetup that covers Node.js regularly. If you'd like help locating one near you, I'd be happy to help - I, or someone on the Community Committee, probably know one of the organizers and can help you figure out the where, when, and how.

I'll be blatantly honest–not many people _exploring_ Node.js are participating in the discussions on GitHub - which is a pure and utter failing on our end. This isn't to say they're not welcome or they're not invited, but rather that they feel intimidated by the workload and social systems we've set up and feel like it's too large of a barrier to jump as a beginner.

All that said, if we're able to help you figure out the answer to the previous question we can again probably point you to in the right direction to find those beginners you're looking for 😁

> I gave up on nodejs. Then, recently, a fellow named Jason Hicks steered me back to nodejs. Jason works on CJS. He says I need nodejs for CJS. I'm not sure what CJS is, but I'll go with him and have faith.

So I looked up CJS, and it looks like it's a way Linux OSes (specifically focusing on Mint) to interpret JS on the desktop. (The [source is all on GitHub](https://github.com/linuxmint/cjs), which probably doesn't help you out a ton 😅)

Looks like Jason is doing some cool work with it. My assumption is that Node.js is part of the build and/or runtime process of CJS, and the JavaScript that's getting passed through is being run _by_ Node.js. This is all me reaching, as there's not a ton of documentation that I can find in the repo. Nevertheless, CJS seems to be a pretty specific project that I'm _guessing_ the majority of the members of Node.js project don't have experience with.

That said, let's address your next point:

> I guess what I seek is to write a file-browser -- like a web-browser, not for the Internet, but for files and programs. Linux has been around for 20 years and there's no way to even search for files... It's ridiculous. If you don't learn the CLI commands, you can't do squat with Linux, and learning the CLI commands is nearly impossible and I don't want to do it. I ran Unix and IBM JCL in college and hated it. I learned DOS CLI commands and hated them. I want a graphical OS with graphical utilities, even if I have to write them myself. ...Um, sorry for the rant, but now you know what I seek.

This is DEFINITELY do-able with Node.js.

I took a few minutes and did some searches, and found some resources that _don't use CJS_ but implement what you describe here.

#### Tutorials:
Here are two tutorials that try to teach you how to build a file manager application yourself, one that uses Electron (which is basically Chromium + Node.js) and one that you just open up in your web browser. Hopefully these will help you approach the process of executing on this, or at least how you'd do that _with Node.js_.
- [Creating a File Manager with Electron](https://classmite.com/node/creating-file-manager-electron)
- [Building a Web Based File Browser with jsTree, Angular.js and Express.js](http://thejackalofjavascript.com/file-browser-with-jstree-angularjs-and-expressjs/)

#### Code Repositories with Source Files
Hopefully if you're curious about the _how_, you can take a look into these repositories and see how they're achieving what you'd like to achieve 👍 
- https://github.com/efeiefei/node-file-manager
- https://github.com/sanketbajoria/scullog
- https://github.com/sumitchawla/file-browser

If you're interested in building exclusively with CJS, I highly suggest you reach out to Jason and see how CJS and Node.js play together.

Hope this helped ❤️

**Comment by markfilipak** [comment]
You're very cordial. I have problems with github. I don't want to take up any more of your valuable time.

I now think I don't need 'nodejs'. It appears that I can do everything I want with 'cjs'. BTW, 'cjs' does not use 'nodejs'. 'cjs' is the Cinnamon Desktop's javascript runtime environment and much of Cinnamon is accessable through it. Cinnamon is for all Linux distros, not just Linux Mint.

I'm motivated to follow this up. If you are too, then PM me -- I made my email address visible.

Warm Regards,
Mark.

**Comment by bnb** [comment]
Going to close this for now - feel free to re-open if needed ♥️
