### ISSUE TITLE
Figure out voting mechanism for Slack vs. IRC

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#26]
We've had some really excellent discussions in #11 surrounding how we can improve our community's central chat space(and really what -that- is). 

An interesting question brought to me was how we DO finally decide this. I can't make that call and won't(not how the world works!). A simple vote by majority may not necessarily represent what will set us up for success. It's possible the volume of people voting may not have struggled with each of the mediums, the logistics of moderating them, and the problems with onboarding new folks to either. I find that weighing collaborators/moderators of IRC(or Slack if there are any currently)/community-at-large as separate votes may help us figure out the final call.

To get the feedback we need for folks to work together on this, I propose we run votes for the three separate votes for the various stakeholders here: 
1. contributors
2. community members
3. existing moderators

To do this, I think we need to iron out the logistics of voting. Does @nodejs/tsc have any precedence with doing something like this? Collaboration on this would be really appreciated and very helpful.

**Comment by bnoordhuis** [comment]
> Does @nodejs/tsc have any precedence with doing something like this?

I can't say we do.  The TSC is a single entity, not a distributed and disjoint collection (or collections) of people as is the case here.

Tangential: I wouldn't say contributors (insofar they don't overlap with the other two groups) are stakeholders.  We use #node-dev and I don't expect that to change; the vote doesn't materially affect us.

**Comment by bnb** [comment]
I have a suggestion: Use the same mechanism that the Org has used for LTS naming. A *locked* GitHub issue, with two comments - "Slack" and "IRC". 👍 is a +1. Whichever has more is selected.

Here's an example for Node.js 6 LTS: https://github.com/nodejs/node/issues/8026

**Comment by italoacasas** [comment]
What about creating a Form in Google Form, and sharing the form via twitter and maybe a blog post, etc?

**Comment by nebrius** [comment]
Can we close this issue? My understanding is that we've decided not to go with a single communication channel, and so we don't need to hold a vote now.

**Comment by bnb** [comment]
@nebrius Is that decision documented anywhere? 🤔

If so, then you can probably close this.

**Comment by nebrius** [comment]
@bnb it wasn't ever our decision to make, really. This is a topic that we and other's have influence over, but our purpose here is to facilitate discussion with the broader Node.js collaborator base. 

That said, yes I think we can close this now.
