### ISSUE TITLE
COMMUNITY [GLOBALIZATION, DIVERSITY]

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#268]
I opened an issue for Node in Africa (NodeJS Africa) which was later approved and I have started pioneering this opportunity to make it a real success, likewise I think the foundation should look into diversity, encouraging developers or individual members around the globe to start up regional NodeJS community Like NodeJS Africa, having something like Node in Asia (NodeJS Asia), Node in Europe (NodeJS Europe) and others. 

This will really assist the community to grow and get bigger. Giving individual responsibility to individuals is one of the fastest ways to grow and expand but sticking with the GitHub community that most people barely know about or heard of will just make the growth rate of the NodeJS Foundation community slow. 

This is what I will love to speak on at the Collaboration Summit if I become a member of the foundation before time. I really believe bringing in diversity and sharing individual responsibility across the globe will speed up the Nodejs growth.

It may seem impossible at first and probably having the appropriate funding to make that possible but it’s more about giving the right support and getting the right backing from the foundation and less of funding. I believe they are individuals out there or even right here that will gladly take up the responsibility.

**Comment by Tiriel** [comment]
Hey!

Thanks for the issue. I’m glad you take on this subject, as it’s one of the aspects I’d like to push through with the issue I opened the other day ( #260 ). 

I’d like to speak about this in the next CommComm meeting, and then if we can, definitely launch this initiative with volunteers. 

Cheers!

**Comment by codeekage** [comment]
@Tiriel Awesome! it will be a pleasure working together on this subject

**Comment by codeekage** [comment]
Closing this issue. Feel free to re-open. 🙏 #308
