### ISSUE TITLE
Hello, wanna join to your organization))

### ISSUE THREAD

**Issue by liashchynskyi** [nodejs/community-committee#269]

**Comment by WaleedAshraf** [comment]
Hi @liashchynskyi, thanks for showing your interest.
If you are looking for some guidelines on how to contribute then you must check [Get Involved](https://nodejs.org/en/get-involved/) and  [Contribute](https://nodejs.org/en/get-involved/contribute/) page at Node.js Website.

**Comment by liashchynskyi** [comment]
And what will after that?

**Comment by maddhruv** [comment]
@liashchynskyi  you have to contribute to NodeJs in some way, either code or maintain the various repos under NodeJs and after that if any one of us feels worth or if you are eligible we will add you as a member of Nodejs Foundation.
moreover, you can be a **Individual Member** with [Blog](https://nodejs.org/en/blog/community/individual-membership/) and [Join nodejs foundation](https://foundation.nodejs.org/about/join)

**Comment by bnb** [comment]
Hey there @liashchynskyi 👋

I just wanted to get some context on what you're looking to do exactly - do you want to become a contributor to the Node.js project? The Community Committee? Depending on what your specific interests and goals are, contributing to a specific sub-group may be more helpful.

I definitely appreciate the input of @WaleedAshraf and @maddhruv but depending on what you're interested in doing the path they suggested may not be the one you'll find most successful.

Thanks!

**Comment by hackygolucky** [comment]
I'd also recommend checking out a few of the videos on [our YouTube stream](https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ/videos), as I think between the CommComm and the TSC meetings, you can get a good feel for what's happening and therefore some work you'd be excited to contribute to.

**Comment by liashchynskyi** [comment]
@bnb I wanted to become a member but thank you for the advice ))
