### ISSUE TITLE
How should we address licenses for non-code initiatives / projects?

### ISSUE THREAD

**Issue by jemjam** [nodejs/community-committee#271]
This discussion started as part of the last two Community Committee meetings (details in meeting notes). We've gotten sanctioned advice about what how to license software projects, but there seem to be some running questions around "everything else" we want to address. 

Specifically:
- What do we do for mostly writing / process repos?
- What do we do for design assets (node badges / website design repos)?
- What do we do for “bits of code” (helper scripts)?
- What do we do with data and user feedback (feedback initiative)?

Bringing open-ended requests to the legal team isn't always effective, so we'd like to prepare ahead of another inquiry. 

For each question, it would be ideal if we could come up with concrete examples (links to existing repos / code / text / etc) so we can submit another question to the legal team.

Can folks add examples here or help flesh out the questions?

**Comment by bnb** [comment]
Really appreciate the initiative here @JemBijoux. I don't really think I have any additional questions that need to be covered.

One thing I will share: Some feedback from the legal team (that I believe Mark may have shared in the previous CommComm meeting) is that once a license is in, you should stick with it.

That said, this is a super helpful and something @mrhinkle may want to bring to the Board if @nodejs/community-committee agrees this is a good collection.

**Comment by bnb** [comment]
Here are some repos that are examples:

- https://github.com/nodejs/user-feedback
- https://github.com/nodejs/website-redesign
- https://github.com/nodejs/i18n
- https://github.com/nodejs/nodejs-collection
- https://github.com/nodejs/badges

**Comment by mhdawson** [comment]
One concrete question I'd have is. Can we just use MIT like we do for the rest of the project?  Are there any downsides for the project and for consumers of the repo?

**Comment by mhdawson** [comment]
We have a similar question with respect to the vulnerability database here: https://github.com/nodejs/security-wg/issues/156.

I think we were getting some advice through the foundation on this.  @bnb do you think that would apply in to the database as well.  If not can we get your help to get advice as to what we should do with respect to the licence for the vulnerability database data.

**Comment by bnb** [comment]
@mhdawson sure thing. I'll follow up with @mrhinkle to see what the status of this was 👍

**Comment by bnb** [comment]
Quick update from Mark: He's waiting on the membership's corporate attorneys to approve the minutes. Once that's complete, we'll hear back 👍

**Comment by chowdhurian** [comment]
_Checking the pulse on this issue_ 💛

* Any further developments?
* And from whom do we now expect to hear back?

**Comment by mhdawson** [comment]
I think I'd heard from @bnb that we had the answer but just in case I'm wrong I'll let him add it.

**Comment by bnb** [comment]
There was a _tentative_ update, but it was basically a TL;DR and I actually had a question about it because it wasn't entirely explicit. Will share in the private session of the CommComm meeting today 👍

**Comment by bnb** [comment]
Going to remove the agenda label for now 👍

**Comment by bnb** [comment]
@hackygolucky / @MylesBorins did we ever get a solid answer on this? I vaguely recall that when I was chair it was finalized but not fully communicated – y'all may have access to notes or context I don't. Would like to resolve if possible 👍

**Comment by mhdawson** [comment]
I'd like us to have this documented somewhere once we get the answer.

**Comment by MylesBorins** [comment]
i've added this to https://github.com/nodejs/TSC/projects/1

We should likely bring to legal sub-committee

**Comment by MylesBorins** [comment]
Recommendation has been made and is going to the legal committee for a final sign off. We should have an answer soon 🎉

**Comment by brianwarner** [comment]
Here is the answer we received:

**What do we do for mostly writing / process repos?**
If the material is documentation intended to be provided to users, use the CC-BY-4.0. For internal community documents, use the MIT license. 

**What do we do for design assets (node badges / website design repos)?** 
Any design assets including icons, logos or other graphic elements intended to be distributed with the code should use the MIT license. Company logos and/or trademarks should not be accepted.

**What do we do for “bits of code” (helper scripts)?** 
Use the MIT License.

**What do we do with data and user feedback (feedback initiative)** 
For data, use MIT License as default.  Dataset contributions may also be made under the CDLA-Permissive-1.0. User feedback should be accepted under the CC-BY-4.0 license.

**Comment by amiller-gh** [comment]
I'd like this to be documented somewhere – adding his issue to our new governance project board to track 👍

**Comment by mhdawson** [comment]
@amiller-gh it should probably be document in the openjs repo with possibly a link from the Node.js project.

**Comment by bnb** [comment]
I believe this has widely been addressed. If there are no additional replies within the next few days, I'm going to close it.
