### ISSUE TITLE
Reviving Evangelism Working and Other Inactive Working Groups 

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#275]
I did some snooping around and I noticed most working groups has been inactive since the last year 2017.
Is there any effort in bringing the working group back to life or closing the working group repos?

I'm very much interested in bringing any working group back to life especially evangelism working group since I personally have more interest in Community Building and Community Globalization #268.

Who is a +1 on this?

**Comment by maddhruv** [comment]
+1
If the groups are still needed to the org and are inactive due to some reasons or because the maintainers left.

**Comment by codeekage** [comment]
> The Evangelism WG creates promotional materials, brings discussions to a wider audience, and attempts to grow the community through positive, supportive messaging.

I think the Evangelism WG should not be closed, but rather contents of update and how this updates can be implemented by end user should be developed by Node.js Project Evangelist or Developer Evangelist (members of the Evangelism WG) this actually gives the WG a purpose.

Matters concerning having a chapter of the Node.js community can also be handled by a Community Evangelist in that region. So, the CommComm can have less to worry about diversity, chapters, and all that. Questions about chapters will be channelled to the WG that should be concerned about achieving a wider reach of the community.

**Comment by codeekage** [comment]
Here has been quite!

**Comment by Trott** [comment]
I could be wrong, but I don't think coming to consensus on whether an Evangelism group is necessary. Usually people start doing the work, *then* get chartered as a working group and all that.

**Comment by codeekage** [comment]
I imagine if this WG can be something like the MS Evanglist and all other related evangelism groups. 🤔

**Comment by Tiriel** [comment]
> I could be wrong, but I don't think coming to consensus on whether an Evangelism group is necessary. Usually people start doing the work, then get chartered as a working group and all that.

I concur. I think if you feel there's something to be done, you should do it and then we'll talk about making it an "official Initiative or WG" during CommComm meeting.

Other than that, I think this has been open for quite long, so I'm going to close it for now. But do feel free to reopen if you strongly feel there's discussion to be had on the subject :pray:
