### ISSUE TITLE
Create a tag for "How I Got Into Node" posts

### ISSUE THREAD

**Issue by trivikr** [nodejs/community-committee#278]
Hi,

I came across "How I Got Into Node" series from #138, the first post can be be viewed [here](https://medium.com/the-node-js-collection/introducing-how-i-got-into-node-398391594833)
There are [more posts](https://www.google.co.in/search?q=%22how+i+got+into+node%22), but I couldn't find a way to view them as a collection/series

If we create a tag for "How I got into Node" posts, it'll be easy to access all of them (example [nodecore](https://medium.com/the-node-js-collection/tagged/nodecore) tag)

Regards,
Trivikram

**Comment by bnb** [comment]
Hey there @trivikr 👋

This is probably a discussion that best goes into the [Node.js Collection Initiative](https://github.com/nodejs/nodejs-collection) repo, since the Node.js Collection is where that content lives.

**Comment by trivikr** [comment]
This issue was moved to nodejs/nodejs-collection#24

**Comment by trivikr** [comment]
Thanks @bnb, the issue was moved.
