### ISSUE TITLE
Request to be an Observer in the next Community Committee meeting

### ISSUE THREAD

**Issue by elainechan** [nodejs/community-committee#281]
Please add me as an observer on the community committee's meetings.

**Comment by chowdhurian** [comment]
@elainechan I've opened a PR to add you as an observer to the bi-weekly meetings!

**Comment by elainechan** [comment]
Thanks, @chowdhurian. Looking forward to participating.

**Comment by chowdhurian** [comment]
PR has merged, closing this issue
