### ISSUE TITLE
CommComm Restructuring Efforts Meeting 2018-04-10

### ISSUE THREAD

**Issue by chowdhurian** [nodejs/community-committee#285]
Continuation of #234, #253.

_(Proposed)_ meeting time: __3rd of April 2018, 5:30PM UTC__

Previous minutes: https://docs.google.com/document/d/1mlk48QmZcGCyJHVRCj_ZorHN3BX_xncQZ5tR-Hvsz6M/edit?usp=sharing
Current minutes: https://docs.google.com/document/d/1MIHNPmbVqKjHfQ3WfuN48rLfyAWISJQlvFeCldOhUcY/edit?usp=sharing

Invited: @nodejs/community-committee 

This meeting time was chosen using a doodle in #234, but the time is open to being changed to better fit the schedules of people who wish to attend and contribute 💛

Interested individuals can also contribute to the issue CommComm Membership: Call For Feedback on New Definitions (#276) and it will be discussed in the meeting.

**Comment by mhdawson** [comment]
6 UTC works for me. If we do change, 1 hour later would be better than 1 hour earlier for me.

**Comment by chowdhurian** [comment]
Will moving it one hour later, to 7pm UTC, be ok @Tiriel?

**Comment by chowdhurian** [comment]
@bnb Are we doing this today?

**Comment by chowdhurian** [comment]
As the time has passes, I'm revising the meeting issue for next week.

Earlier comments show interested people have ongoing conflicts at this time. The proposed time is being moved 1 hour earlier to help accommodate.

>  If we do change, 1 hour later would be better than 1 hour earlier for me.

@mhdawson is this still true of next Tuesday, the 10th?

**Comment by mhdawson** [comment]
Yes, I have a standing meeting.  1/2 hour earlier would be ok though.

**Comment by Tiriel** [comment]
Nope, 6 PM or 7 PM UTC won't do for me. I have lessons on every Tuesday from 6 PM UTC to 10:30 PM UTC.

At any rate, don't try to get meeting times based on my schedule, I'll try and see if I can move some students another night, and in the mean time I'll catch up with the minutes like I did with the last meeting.

**Comment by bnb** [comment]
@chowdhurian apologies. I don't think we could have done it regardless, since the Zoom account is in use all day today for the Modules Summit.

As we're planning this we should make sure there are no overlaps on the Node.js calendar: nodejs.org/calendar

**Comment by bnb** [comment]
That sounded a little be more... rough than I meant it to 😬 

Also realized I didn't note: Just LMK what time works for the group and I will work to make it happen. I only have a few hard blockers, one of which would be 11pm UTC every Tuesday.

**Comment by codeekage** [comment]
It seems nobody noticed today's meeting... was it cancelled or?

**Comment by chowdhurian** [comment]
@codeekage scheduling issues today. It's being rescheduled.

@bnb thank you for the heads-up. Will account for pre-scheduled events in the calendar going forward.

@Tiriel thanks for being considerate 🙏🏽 Would still like to accommodate everyone here if possible. And based on the responses so far, I think we can do so. The proposed time will be moved a half hour earlier, to 17:30 or 5pm UTC.

Conveniently there's an entry "Community Committee Membership Discussion Meeting" on the calendar on the same day April 10th, recurring every other week. If anyone seeing this has calendar privileges, we'll want to update that.

**Comment by Tiriel** [comment]
@chowdhurian Thanks a lot! I'll try to make it, although I also have to eat and see my kid at some point between my day and evening work :sweat_smile: (Tuesday is definitely a full day for me now, but I'll try to move some things by next meeting)

**Comment by mhdawson** [comment]
Calendar updated to show 5:30 UTC (1:30 EST) on Tuesday April 10.

**Comment by codeekage** [comment]
Is this meeting holding?

**Comment by codeekage** [comment]
@bnb @chowdhurian @mhdawson @Tiriel @hackygolucky canceled or still holding??

**Comment by Tiriel** [comment]
As far as I know yes, but it's scheduled at 5:30 PM UTC, so in about 5 hours from now.

**Comment by hackygolucky** [comment]
I am not going to be able to attend this meeting :( It's smack in the middle of a bunch of work meetings for me. I'm sorry. 

It looks like @chowdhurian pulled a great agenda together. I'd recommend focusing on the language that empowers the working groups and teams as we haven't been able to dive deep on that yet. Someone could drive writing while others give input as it is being drafted.

We've got some stuff still up in the air, such as the language around collaborator that requires having input from the TSC(it can affect their work so it should be collaborated on). If someone in the session is from the TSC, that would certainly help! The idea on that discussion is that we need a single term that defines everyone who is currently, actively, and meaningfully contributing to the Node.js project regardless of whether it is code, documentation, or community-centric(ecosystem work is unfortunately out of scope).

**Comment by mhdawson** [comment]
Has somebody setup a webinar for the meeting?  I can do that if necessary.

**Comment by chowdhurian** [comment]
> I'd recommend focusing on the language that empowers the working groups and teams as we haven't been able to dive deep on that yet

Added to the agenda. Thanks for the direction @hackygolucky! ⚡️

@mhdawson That would be very helpful! 🙌🏽 I do not have zoom access.

**Comment by mhdawson** [comment]
Zoom link https://zoom.us/j/390516989

**Comment by ryzokuken** [comment]
I hope this meeting will be streamed on Youtube too? I couldn't find a placeholder for the link, so I had been wondering.

**Comment by maddhruv** [comment]
Can you add me as an observer? 😀

**Comment by mhdawson** [comment]
We are planning to live stream, once it goes live will be available here: https://www.youtube.com/c/nodejs+foundation/live

**Comment by mhdawson** [comment]
Stream should start soon, just waiting for a few last people

**Comment by Tiriel** [comment]
Juste to be sure, is the meeting date every other week with the CommComm meeting on Tuesdays?
Like next Tuesday?

**Comment by hackygolucky** [comment]
Yeah, @Tiriel  I saw the next one on the calendar for tomorrow and was wondering whether this still needs to be recurring. I can delete it if tomorrow's meeting won't happen. cc @chowdhurian

**Comment by Tiriel** [comment]
Well, tbh I quite don't know where we stand on todos for this effort. I can't seem to find minutes for the last meeting (and can't watch the video right now, I'll try later on).

I'd say it depend on what remains to be done then. Or maybe we should finalize this at the Collab Summit?

**Comment by hackygolucky** [comment]
We've got an open pull request being worked on right now that should be bringing together the discussions we've had.

**Comment by hackygolucky** [comment]
Unless there's an objection, I'm going to delete today's calendared meeting since it sounds like we don't have much engagement on a call today. Would be good to spend some time on the pull request currently up.

**Comment by codeekage** [comment]
Sorry, please from the last meeting... what's the status of the current observers?

**Comment by mhdawson** [comment]
Sorry I got confused because the meeting was not on the Node.js calendar and removed from my internal calendar.
