### ISSUE TITLE
Reminder CFPs for JS Interactive Close on April 20 (Share the news!)

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#288]
I know a few of your are aware, but we are expanding Node.js Interactive this year and co-hosting it with the JS Foundation. Given the expansion, we are calling the conference JS Interactive. This year's event will combine Node.js content with lots of great JavaScript tracks. The intention of the conference is to build more collaboration within these communities, and also share knowledge between various JavaScript open source communities and their end users. 

There’s a ton of tracks and topics to submit on, including accessibility, community building, emerging use cases, frameworks and more - you can find the full list here. If you want to submit a talk that’s not found in any of the categories listed, feel free to leverage the wildcard category. Formats include presentations, hands-on workshops and panels. **The deadline to submit a presentation is April 20**. You can submit here: https://events.linuxfoundation.org/events/js-interactive-2018/program/cfp/

Please share with your colleagues or meetup groups or anyone else that you believe would be interested in speaking at this event. 

If you have any questions on this conference, please leave a comment or email events@jsinteractive.org.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton there's no option of "Hands-on workshops"


Submission Type*
- BoF
- Lightning Talk
- Panel (*maximum 4 panelists & 1 moderator)
- Presentation (*maximum 2 presenters)

**Comment by ZibbyKeaton** [comment]
@WaleedAshraf thanks for catching this - I alerted our events team and it should be fixed.

**Comment by bnb** [comment]
Going to close this, since we're past the date 👍
