### ISSUE TITLE
Create a `Working Group` label for WG repos

### ISSUE THREAD

**Issue by Bamieh** [nodejs/community-committee#291]
It would be nice to have each WG repo labeled with a WG, this way it is easier to identify all working groups.

**Comment by bnb** [comment]
As noted in https://github.com/nodejs/community-committee/issues/201, we don't actually have an official "working group" in the Community Committee and are looking for work/contributions around this 😬

Until we have officially have working groups in the Community Committee, I don't know if we should move forward with something like a label.

**Comment by Bamieh** [comment]
@bnb I meant across the node project, not the commcomm per se. Although i thought the i18n working group is operating under the commcomm. I mean WGs like security, i18n, release, and benchmarking.

**Comment by bnb** [comment]
@Bamieh Ah, gotcha - in that case, this discussion should probably go in the nodejs/admin repository. I posted something _similar_ recently: https://github.com/nodejs/admin/issues/88

**Comment by Bamieh** [comment]
closing this, I will follow up on this based on @bnb's recommendation.
