### ISSUE TITLE
NodeJs Presentation

### ISSUE THREAD

**Issue by LaurentGoderre** [nodejs/community-committee#296]
Hi, I am a core contributor to the official Docker images and I have been asked by my organization (Government of Canada) to present my work on Docker Node to a cloud working group. Is there any guidelines or rules about this kind of presentation given that I am a NodeJS foundation member?

**Comment by chowdhurian** [comment]
I don't believe there are rules restricting sharing your work in this manner. My understanding is that you're contributing to Docker Node in a personal capacity (thank you!) and are totally able to give presentations about your work and experience!

Although, to be sure, let's wait for a few others to weigh in here. 🤠

**Comment by mhdawson** [comment]
That's my expectation as well.

**Comment by chowdhurian** [comment]
@LaurentGoderre and if you're in Vancouver BC sometime, we'd love to have you present your work with Docker Node at one of the Node.js meetups 🇨🇦

**Comment by LaurentGoderre** [comment]
I'll keep that in mind! That would be awesome!

**Comment by bnb** [comment]
Going to close this for now, feel free to re-open if needed! 👍
