### ISSUE TITLE
Restructuring efforts transition phase proposal

### ISSUE THREAD

**Issue by Tiriel** [nodejs/community-committee#299]
Hey everyone!

@codeekage 's question in #285 deserves an answer, and that's a point that needs clarification anyway IMHO.

People who attended the last meeting can confirm or invalidate, but from what I remember, we had agreed that current observers would be kept on the current observer path.

If a formal proposition concerning this particular question has not been made yet, I'd like to propose this one:
* If accepted by the Node.js Foundation Board, and **as soon as accepted**, the change initiated by PR #294 should be the new standard path and **no new observership request should be accepted** (obviously).
* Every **current** observer should be evaluated on the soon-to-be-deprecated observership attendance standard. Meaning:
  * Current Observers **under the three month attendance period** will continue to have their attendance monitored for the remainder of their three months
  * Observers registered for **more than three months** will have their attendance evaluated, if they meet the requirements a vote to elevate them as Members will be made according to the former process, if not, their candidacy should be considered void (although we'll be perfectly happy having them self-nominate according to the new process).

Of course, the last bullet can allow some room for specific cases. For example, if someone has been Observer for three months and a half and has missed only one meeting more than allowed by the requirements, we can decide to allow their observership to continue for one more meeting to see if they meet requirements.

The only case that I'm not sure about is if someone submits (or has submitted) an observership request since the PR has been open. I don't know if we should keep the old process for them or get to the new one. Either way doesn't seem perfectly fair to me.

Of course, this is an absolute draft proposition, made on the top of my head, and with my relative skills in English. And of course, **I do not intend at all to be too restrictive or put people off**, but we have to do things fairly and openly while transitioning our processes.

Anyway, please do feel free to tell me to go to hell or improve it your way!
cc @nodejs/community-committee ?

**Comment by mhdawson** [comment]
+1 to the proposal above.  It matches what I understood the agreement to be. I'd lean towards the date #294 was opened as the cutoff date.

**Comment by Tiriel** [comment]
This has been open for 6 days without objection, so I think there's some measure of consensus. 

Now we just have to wait for an official response from the Foundation Board. In the meantime, I'll leave this open for a second chance on discussing this for all @nodejs/community-committee members.

And for the record, I'd also lean towards the date where @chowdhurian 's PR has been opened (which doesn't load anymore on my computer because of too many comments :smile: ).

**Comment by chowdhurian** [comment]
@Tiriel not on mine either lol! 😭

**Comment by chowdhurian** [comment]
The subject of cutoff dates were discussed at length during #307, and the _recommendation_ is that it be set to the date PR #294 was opened, as mentioned earlier in this thread.

Everyone is encouraged to continue contributing to our efforts to find a happy resolution to this.

Anyone who was on the observer path before this date will continue to be on the membership track to helping with CommComm administrative work, provided the original requirements are met. Observership after the date is not explicitly a path to membership. Membership will be determined by active contributions to working groups and initiatives.

**Anyone can contribute to working groups and initiatives. You do not need to be a member to do so!** 💙

The only person we can find who became an observer after that date is @jiasm. @bnb will be reaching out to you to figure out a path that could meet your goals.

**Comment by Tiriel** [comment]
I think we can close this, but before doing this I'd like another advice.

cc @nodejs/community-committee

**Comment by codeekage** [comment]
The CommComm has been successfully restructured. Safe to close this. Feel free to re-open. 🙏
