### ISSUE TITLE
Add language around emeriti to docs 📝

### ISSUE THREAD

**Issue by chowdhurian** [nodejs/community-committee#302]
Further to conversation stemming from #294 and #301, CommComm documentation needs to include language around emeriti, specifically:

* if an emeriti wants to become active, the process on how that could work

As it stands now, the documentation is not explicit. It simply reads that emeriti `...may request that
the CommComm restore them to active status`.

As suggested [here](https://github.com/nodejs/community-committee/pull/301#issuecomment-386099055), it would be advisable to have context on how the TSC handles parallel situations.

**Comment by Tiriel** [comment]
For now, the process for returning from emiriti to active that was used was quite simple:
* The emerit opens a PR on the README moving themselves from the emiriti section to the active section
* The rest of the CommComm has a vote during the next meeting to validate said return.

This is simple enough and works for now, so I'd say we stick to that, but we do need to write it somewhere I think.

**Comment by Tiriel** [comment]
Does someone wants to tackle this PR? This should be quite simple and represents a perfect good first issue!

**Comment by chowdhurian** [comment]
For anyone considering making this as their first PR, I'm happy to review it before it's merged ^_^
