### ISSUE TITLE
CommComm Restructuring Efforts Meeting 2018-05-14

### ISSUE THREAD

**Issue by chowdhurian** [nodejs/community-committee#307]
Note: There is a meeting scheduled in the Node.js calendar for Tuesday the 8th of May titled "Community Committee Membership Discussion Meeting". I'd like to propose a shift to the 14th of May. Time remains the same.

A "6pm UTC on alternating Tuesdays" meeting time was chosen using a doodle in #234, but the time is open to being changed to better fit the schedules of people who wish to attend and contribute.

_(New)_ meeting time: __14th of May 2018, 6:00PM UTC__

Previous minutes: https://docs.google.com/document/d/1MIHNPmbVqKjHfQ3WfuN48rLfyAWISJQlvFeCldOhUcY/edit?usp=sharing
Current minutes:
https://docs.google.com/document/d/1wy-53bWsoFeZWLDQlyS_5REsoMkWa6CzXxeZ55QrDNE/edit?usp=sharing

## Agenda 

#298 and #294 once they are merged will continue to need iterations. The proposed definitions in the PR has been broadly accepted. For reference, the last meeting's minutes are provided. However the latest discussions are on the two PR's referenced earlier.

The above PRs cannot land yet as we require one more approval from the foundation attorney first.

We will be discussing:

* emeriti (#302)
* working groups, and empowering other groups
* when big changes happen from a sub committee, we document it in some sort of history file so we have a record. (HISTORY.md? Changelog?)

(If anyone can open PR #294, please update the discussion points. It's timing out for me right now 😅)

## Invited

* @nodejs/community-committee 

## Joining the meeting

* link for participants: Will be added a few minutes before meeting starts
* For those who just want to watch:
* youtube admin page: https://www.youtube.com/my_live_events?filter=scheduled

**Comment by mhdawson** [comment]
I'll move the calendar entry to the 14th

**Comment by chowdhurian** [comment]
@mhdawson thank you! 🙏🏽

**Comment by codeekage** [comment]
is this meeting canceled??

**Comment by hackygolucky** [comment]
@codeekage I think this one is still happening, afaict. 

Unfortunately, @chowdhurian, I have a conflicting meeting so I will not be able to attend. I'm happy to help contribute to PRs post-meeting if I can check meeting notes for the result of the discussions. Also, I think the discussions in a few of the prior CommComm meetings re: history documenting was that we would create a file per thing we need to document so we can reference it and keep concerns separated. Might be neat to create a changelog of sorts, but the changelog would either get very wordy or could be short(as tends to be the case) descriptions that link to a longer markdown file that provides further documentation and explanation of the change.

**Comment by bnb** [comment]
Join link: https://zoom.us/j/887521403

**Comment by Tiriel** [comment]
Sorry people, couldn't make it, I had lessons at that time. That's a recurring thing though, so this hour is def not a good one for me.

Do you have a youtube link so I can catch up?

**Comment by bnb** [comment]
@Tiriel We generally don't stream these meetings, unfortunately. I'd be open to reassessing that for the future, but that's something we decided early on in this process. 😞

**Comment by Tiriel** [comment]
@bnb True, totally forgot that.  Are there any minutes then apart from the update made on #299 ?

**Comment by chowdhurian** [comment]
@Tiriel there's this if it'll help! https://docs.google.com/document/d/1wy-53bWsoFeZWLDQlyS_5REsoMkWa6CzXxeZ55QrDNE/edit

**Comment by Tiriel** [comment]
@chowdhurian Awesome thanks!
I'll try to move some lessons for next meeting so I can attend, there's a lot still going on and the discussions still seem to be fascinating. Thanks for all your work!
