### ISSUE TITLE
wanted to know how we can build MVC application using ejs template in nodejs since i already having my own rest api's?

### ISSUE THREAD

**Issue by kheteshR** [nodejs/community-committee#310]

**Comment by WaleedAshraf** [comment]
Hi @kheteshR 
I found this article related to your question: https://code.tutsplus.com/tutorials/build-a-complete-mvc-website-with-expressjs--net-34168

For further discussion, I'd recommend that you join [Nodejs Discord](https://discordapp.com/invite/XcbgTvJ) or [nodeslackers](http://www.nodeslackers.com/) for easy conversation. 🙂

**Comment by bnb** [comment]
Thanks for the speedy response @WaleedAshraf! Going to close this now 👍
