### ISSUE TITLE
Updating CONTRIBUTING.md with new/relevant context

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#313]
Given that we've got a few changes coming down the pipeline around membership, I figured now is a good time for us to give the Community Committee's `CONTRIBUTING.md` file a bit of polish. There are a few things that need to be updated and included.

Here's a list of some of the things that need to be changed in the file:

- [ ] [Vocabulary](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#vocabulary) needs to be updated with our new terminology
- [ ] Update [Teams and Working Groups](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#teams-and-working-groups) to reflect current state of our work. This includes adding initiatives and removing Working Groups language.
- [ ]  Fix non-existant in [Teams and Working Groups](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#teams-and-working-groups).
- [ ] Some of the language in [Logging Issues](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#logging-issues) is outdated, including usage of `Community Committee Collaborators` and mention of security disclosure (as far as I know we don't have anything that would fall under security disclosure!)
- [ ] [Contributions](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#contributions) can/should be updated with more recent context around how we approach contributions to the Community Committee. I'm not sure if we also want to add a section pointing people to the initiatives here 🤔
- [ ] [Becoming a Member and Collaborator](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#becoming-a-member-and-collaborator) needs an overhaul, specifically the ones outlined in https://github.com/nodejs/community-committee/pull/294
- [ ] Mentions of membership in [CommComm Process](https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#the-commcomm-process) needs to be updated.

If you want to take on any of these, feel free to comment on your interest here or just start working on a PR! ❤️

**Comment by Tiriel** [comment]
I'm going to up this a bit. I'll try working on some things ASAP, but lots to be done :sweat_smile:

**Comment by WaleedAshraf** [comment]
I'll try to pick some of these.
Ping @nodejs/community-committee members.

**Comment by bnb** [comment]
I can mentor non-CommComm members on this one if they'd like to try to contribute 👍

**Comment by amiller-gh** [comment]
Was going to take this when making my updates to the README – looks like I forgot :) Re-adding the labels, may get back to it in the next day or so, thanks for the reminder.

**Comment by 07Gond** [comment]
Hi y'all!
Can I help with this? 😄

**Comment by keywordnew** [comment]
@07Gond Of course. I'd suggest forking this repo, making changes, opening a draft PR, linking to this issue from the PR, and asking any questions that you may need answered to complete the PR. You may also choose what process works best for you!

**Comment by bnb** [comment]
Un-assigning @amiller-gh since I don't think we've seen traction on this. I may try to take a peek at addressing this in the next few weeks. Definitely still very needed.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
