### ISSUE TITLE
Add @codeekage as member

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#317]
I think... I've successfully completed my attendance 🎉 🎉 🎉

**Comment by bnb** [comment]
Hey there @codeekage! I'll send out a vote in the morning, apologies for the delay 👍

**Comment by WaleedAshraf** [comment]
Hi @codeekage,
I was just looking at [attendance sheet](https://nodejs-participation.herokuapp.com/nodejs/community-committee.html) and noticed that your name is missing from CommComm last meeting: [Docs refer](https://docs.google.com/document/d/1ynEM_MM9-K9EyWvC7avSplLHd7I73zNjSkXY7kwBySA/edit)
But I remember seeing you in the meeting. I'm not sure if you forgot to add your name to the sheet? OR maybe you joined at the end and didn't bother to mark that as a present.
Also not sure if it is the same case for Thu Apr 19th meeting.

I'm sharing this on my own experience, as I also forgot to add my name in #Present section in earlier CommComm meetings.

**Comment by codeekage** [comment]
I was at the meeting, forgot to add my name to the #Present section.

**Comment by codeekage** [comment]
@bnd @mhdawson @dshaw @WaleedAshraf 😃

**Comment by bnb** [comment]
Hey there @codeekage! Vote has finalized and we've finished discussion on the topic.

The vote passed! Welcome to the Community Committee membership.

**Comment by WaleedAshraf** [comment]
Closing this as Agiri has been added as CommComm member. 👍 
Feel free to re-open if needed.
