### ISSUE TITLE
Suggest putting "Close Meeting Issue" in Agenda

### ISSUE THREAD

**Issue by cdnadmin** [nodejs/community-committee#323]
For GH issues that facilitate CommComm meetings, suggest putting an agenda item, at the end, to _"Close the Meeting GH Issue"_ to help keep issues list tidy.  ;-) 

E.g. #311   👍🏼

**Comment by chowdhurian** [comment]
Thanks for opening the issue!

I think some context here could be useful to the discussion. While there is no documented process for closing meeting issues, it is a regular practice to close the issue with a PR of the relevant meeting minutes 👍🏽

**Comment by JemBijoux** [comment]
Yup! We usually close them as soon as the meeting minutes have landed. Usually just takes a couple of days so folks have a chance to review the PR before everything is merged.

**Comment by Tiriel** [comment]
Indeed there have been some times when we weren't quite on top of things with the meeting issues. But I do think we're getting better on this, and as said by @chowdhurian  and @JemBijoux , we have some kind of informal process.

If you feel we should get a more formal and written one, feel free to reopen to discuss, but I'm going to close this for now.
