### ISSUE TITLE
Begin Documenting Partner Communities (and what that means)

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#326]
Recently we've had some renewed discussion around extending "official" communities. This discussion isn't really new, and has taken a few different forms since the creation of the Node.js Foundation.

There's an example in [nodejs/node](https://github.com/nodejs/node/pull/20508) of a PR referencing one specific third-party Node.js community. I happened to create this third-party community, but there are quite a few others that exist that might not get the same level of credit because they don't presently have champions from the Node.js project to help encourage more engagement between Node.js and their communities.

As such, instead of going through and including those communities over time and one-by-one, we discussed the concept of introducing partner communities and creating a new top-level document in the [last CommComm meeting](https://github.com/nodejs/community-committee/blob/master/meetings/2018-05-17.md#nodejsnode-readme-add-link-to-unofficial-discord) that would enable us to be a bit more flexible with how we approach listing out partner communities. Ideally, such a document would follow the same path that documents like the Node.js Code of Conduct have set out–a single point of reference for a common or shared set of content.

To kick things off a bit, here's some of the general content that needs to be covered in this document:
* What does it take to become a partner community?
	* Adherence to the Node.js Code of Conduct
	* Adherence to the Node.js Moderation Policy
	* Participation of a Node.js representative as a moderator (likely an org member, or possibly a TSC/CommComm member?)
* Listing out partner communities
	* List partner communities names and descriptions
	* Possibly link a confirmation that they've agreed to adhere to the Node.js Code of Conduct and Moderation Policy?
	* List the Node.js representative's contact info

That's definitely not a comprehensive list, and I expect it to grow and evolve over time. Just wanted to throw a strawman of my own ideas together so we can pick it apart and begin to flesh out this kind document 😄

The work to be done here:
* Once we've generally got consensus, create a PR adding this file and filling in it's contents.
* Back-fill with existing communities that are already doing this (NodeSlackers and the Node.js Discord are the examples I'm immediately aware of)
* :shipit:

**Comment by WaleedAshraf** [comment]
@bnb 👍 🎉 
 Can "[Initiative for Nodejs Community Chapters - Collaboration with NodeSchool](https://github.com/nodejs/community-committee/issues/280)" relate to this?
If possible, can you have some conversation around this during the summit? I know it's too late to ask. I thought Agiri might take this but unfortunately Agiri is not able to attend.

**Comment by codeekage** [comment]
Yea... sadly @WaleedAshraf I think we could discuss at the end of the summit.

**Comment by Tiriel** [comment]
Throwing my two cents on this!

> What does it take to become a partner community?
>    Adherence to the Node.js Code of Conduct
>    Adherence to the Node.js Moderation Policy

These seem absolutely necessary and unavoidable to me.

> Participation of a Node.js representative as a moderator (likely an org member, or possibly a TSC/CommComm member?)

I'd say at the very least a member of the moderation team, but preferably a TSC/CommComm member. But do not that I don't think the representative should already be a representative beforehand. Explicitly, if one person in the partner community staff is already a valued contributor of the org, I see no reason not to have them follow the path to CommComm membership and become said representative.

If this is felt as too much a requirement, I think a representative for the community should be invited as a guest regularly (say like once in a quarter at the very very least) to the CommComm meetings to give updates on their community. Or perhaps make a reporting issue in the admin repo like the moderation team sometimes does.

> Listing out partner communities
> List partner communities names and descriptions
> Possibly link a confirmation that they've agreed to adhere to the Node.js Code of Conduct and Moderation Policy?

This seems quite necessary for transparency IMHO

> List the Node.js representative's contact info

Same as above.

**Comment by chowdhurian** [comment]
I'd like to have clarified: are we making a distinction here between 3rd party communities that meet in-person vs those that meet online?

> Participation of a Node.js representative as a moderator (likely an org member, or possibly a TSC/CommComm member?)

This will be more difficult when applied to in-person groups.

**Comment by bnb** [comment]
This has been achieved and landed in https://github.com/nodejs/community-committee/commit/be885d3d4c1239bc18a11193f886102b4bf5b717. Please feel free to iterate on the current document with anything from this issue that is missing! Going to close this since it was a success 💥
