### ISSUE TITLE
Reopen the Documentation repo

### ISSUE THREAD

**Issue by add1sun** [nodejs/community-committee#329]
We discussed this at the Berlin Node Collab Summit at a documentation session. We did not conclude whether we should open the old docs repo or not, so we should continue that discussion to get to a decision. 

I for one, think it makes sense to reopen it so there is a central place to coordinate and track docs work. There are a couple of groups currently working on docs, with the website redesign group taking most of that on. While that can make sense under the scope of the redesign and IA, it does not make sense from a project-level view to maintain and manage the docs beyond the redesign.

All that said, I'm new to the project and used to having a Docs issue queue from other projects I've worked on. So I'd love to hear arguments for both sides so we can figure out what is best for the Node project.

**Comment by bnb** [comment]
cc @amiller-gh @obensource :)

**Comment by amiller-gh** [comment]
Thanks for getting this conversation started @add1sun! There was also more discussion both in the other docs sessions, and individually after the working sessions, about all documentation – including long form tutorials content – living in @nodejs/node alongside the source code, and I'm leaning strongly in that direction too! It solves a number of problems:

 - API docs and Tutorials docs will be versioned and released in the same package so we don't have to worry version drift accidentally breaking links between pages as much
 - Simplifies ingestion infra for i18n
 - Lowers barriers for existing contributors to write tutorials as needed
 - Lowers overhead for code contributors to discover tickets about documentation: they already live in the repo they're in all the time. 
 - Simplifies documentation story for new contributors: *All* docs live in one place for both API and Tutorials
 - Only need to implement documentation integration tests once, in one repo (ex: make sure code examples actually compile)
 - Can unify Voice and Tone with the existing guidance for API docs and also have it live in @nodejs/node 

Downsides I see are:

 - Possibly lots of churn in @nodejs/node early on as we're writing a lot (didn't seem to be a large concern for collaborators I talked with, but may cause some frustration. We can get around this with process too.)
 - Docs issues filed in the main repo may get a little lost in the flow and add to the ever growing maintenance burden in the issue feed
 - Can you think of more to go here???

I think we can keep tickets in @nodejs/website-redesign for the first build out of content, and then either draft them in the @nodejs/website-redesign repo and dump them into @nodejs/node once they're ready, or we can just do all the work in @nodejs/node. Afterwords, we can keep a close eye on how docs maintenance works with tickets living in @nodejs/node. If we notice it causing issues, we can talk about breaking out issue tracking queue to a dedicated repo. Thoughts? 🙂

**Comment by amiller-gh** [comment]
Also something to think about – if the goal is to keep documentation alongside source code (I think it should be, having documentation live elsewhere has bitten LinkedIn's design systems team and we're now actively pushing for co-location of docs with a full site rebuild...), then there are actually other repos that will need docs to live on the site. Ex: streams https://github.com/nodejs/readable-stream/issues/336#issuecomment-394145140

To accommodate repos like these, of which there will be more and more, we may want to enable multi-source documentation ingestion (this is what we're doing at LinkedIn). Each repo that needs documentation on the site drafts the docs in a well-defined format in-repo. The website then becomes a very basic shell of a site who's *only* responsible is stitching all of the content in its target repos together in the correct locations.

**Comment by vsemozhetbyt** [comment]
Splitting source and API docs may complicate core development. Currently, if something is added, deleted or changed in the core, source, tests, and docs are changed simultaneously in one PR. After splitting, a collaborator will need to make two PRs in two repos. This would be difficult to do in one transaction. Complications for backporting may be even bigger.

**Comment by codeekage** [comment]
I think we should add a link to the @nodejs/website-redesign repo in the @nodejs/docs Readme.md file for folks looking to contribute to docs.

**Comment by amiller-gh** [comment]
Closing in leu of @nodejs/website-redesign – check out the `/documentation` folder 🙂

**Comment by amiller-gh** [comment]
Note - the plan is for documentation currently in website-redesign will be moved to their respective repos to live alongside source once we've established a standard "documentation package" format and ingestion method for the website. Come to website-redesign meetings, or open an issue in that repo if you'd like to discuss more!
