### ISSUE TITLE
JS Interactive Schedule is Up!

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#333]
We just announced the full schedule for JS Interactive (more keynotes to come). Check it out here: https://events.linuxfoundation.org/events/js-interactive-2018/agenda/schedule/

If you have the time, we would love for you to share news about it on your social channels.

Beyond JS Interactive, we'll also hold a Code + Learn and a Collaborator Summit post conference. Details are being worked out, but the Code + Learn will take place the morning of October 12 and the Collaboration Summit will take place afternoon of October 12 - 13. Details are being arrange [here](https://github.com/nodejs/summit/issues/59). 

One other item I want to call out to this group is that we have a few diversity scholarships for this conference. If you know someone who would benefit from this scholarship or an organization whose audience might benefit from receiving a diversity scholarship, please feel free to send details over or connect me directly with the organization. 

Happy to discuss collaboration on this front. Diversity scholarship details here: https://events.linuxfoundation.org/events/js-interactive-2018/attend/diversity-scholarship/

**Comment by codeekage** [comment]
Members of the Node.js Foundation do also need to create an attendee account and can also apply for scholarships?

**Comment by WaleedAshraf** [comment]
Closing this, as the schedule has been shared with everyone.
Feel free to re-open if needed.
