### ISSUE TITLE
Individual Membership Subgroup Meeting - June 25th, 2018

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#337]
As part of the recent discussions in the Joint Strategy Subcommittee, the CommComm has been asked to begin planning on how we'd like to approach managing Individual Membership.

I'd like to propose that our first public meeting on this subject occur on June 25th at 6:00pm-7:00pm GMT+0, taking over the current Membership meeting time slot.

**Minutes Doc:**
Link: https://docs.google.com/document/d/1OrFC5FrMt5nugE2hj7o0OP8O31Eg8QrZj60XyrHT-DM/edit?usp=sharing

**Attendees:**
The @nodejs/community-committee membership is invited, as is @sarahnovotny from the Board.

If you'd like to help out, please feel free to comment in this issue to be added.

**Agenda items:**
- Scope of Individual Membership

Feel free to request agenda items be added in this issue 👍

**Comment by bnb** [comment]
Updated issue to include mention of @sarahnovotny from the Node.js Foundation board 👍

**Comment by bnb** [comment]
Added Minutes Doc as well 👍

**Comment by chowdhurian** [comment]
I will attend, and I'd like to add an agenda item to discuss the the possible scope of the reimagined individual membership, where I will make a proposal.

**Comment by Tiriel** [comment]
Will do my best to be there!

**Comment by Tiriel** [comment]
Probably will be a bit late, been delayed in meeting at work.

**Comment by AnnMarieTonog** [comment]
Hi, would love to observe this meeting! Is there a zoom link?

**Comment by bnb** [comment]
Trying to kick this off, on a really bad connection.

**Comment by williamkapke** [comment]
Via @bnb: https://zoom.us/j/696227207

**Comment by williamkapke** [comment]
lol @mhdawson you booted us!

**Comment by WaleedAshraf** [comment]
I was about to ask this:
"Was there any question related to Individual Membership in Nodejs Survey?"
Like "Are you an Indiv Member?" "Do you plan to become an Indiv Member?"

If not, can we include these in our next survey?

**Comment by Tiriel** [comment]
Sorry, I think I try to connect at the exact moment you were ending the session, I was connected and got thrown out :(

Are there meeting notes? If not, I guess this will be discussed during Thursday meeting so that's ok.

**Comment by bnb** [comment]
@Tiriel meeting minutes are linked at the top of the issue.

**Comment by Tiriel** [comment]
@bnb :pray: Thanks, totally forgot to check!

**Comment by chowdhurian** [comment]
This meeting was followed by meeting #353.

Closing for now, please reopen when necessary!
