### ISSUE TITLE
How do I file a PR to take items off the CommComm Calendar

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#344]
Howdy! I need to file a PR to take the Node.js Certification Collaborator's meeting off for 7/5 date. Anyone know where I can find the calendar to make this request. The meetings will start up again after the holidays, but my colleague who runs them will be out until then. 

cc: @bnb @WaleedAshraf @mhdawson (cc'ing y'all as you usually help lead me with this stuff)

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton If you just want to remove the event from calendar than there is no need to create PR.
I think @mhdawson or @Trott have admin access to remove events.

If there is a related issue for that meeting: You may need to update it that meeting is canceled.

**Comment by maddhruv** [comment]
@ZibbyKeaton : I am also having access to the calendar, please tell me the events to remove from the calendar, moreover I can also help you getting them back online :heart_eyes:

**Comment by ZibbyKeaton** [comment]
Thanks for your help @maddhruv it's the one for the Node.js Certification on 7/5. I just need that meeting deleted as the person running it from the Node.js Foundation will be on vacation. Thanks again! Also, if it's easy for me to become an admin and follows the rules, I would like to become one. Just so I don't have to make this request again when it comes to NF meetings.

**Comment by mhdawson** [comment]
I removed the meeting on 7/5.  To request to be a calendar admin, people have been opening an issue to request that in the admin repo.

**Comment by WaleedAshraf** [comment]
@ZibbyKeaton Example PR for Calendar Admin Access: https://github.com/nodejs/admin/pull/114
Feel free to ping me if you need any help.

**Comment by bnb** [comment]
Also happy to expedite @ZibbyKeaton being a calendar maintainer 👍

**Comment by bnb** [comment]
Going to close this for now. Feel free to reach out if you need to be added as a maintainer @ZibbyKeaton
