### ISSUE TITLE
Review Member Onboarding Process from Initiatives and Working Groups

### ISSUE THREAD

**Issue by detrohutt** [nodejs/community-committee#345]
I'm opening this on behalf of @dshaw as a reminder to bring this up in the next meeting. Would someone please add the agenda label? Thanks.

**Comment by dshaw** [comment]
I found the policy in Admin: https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md

**Comment by refack** [comment]
Quick comment, since the narrower bottleneck is adding people to the Org, IMHO this could be done early on in advance to actual onboarding to a specific team by pinging an Org Owner (CommComm chair or even TSC members). After that adding Org members to teams can be done by any "Team Maintainer".

**Comment by bnb** [comment]
Going to close since this was a temporary issue/reminder for a meeting 6 months ago 👍
