### ISSUE TITLE
Moderation escalation policy

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#35]
We have a [moderation escalation policy in place](https://github.com/nodejs/TSC/blob/master/Moderation-Policy.md), but it is untested, unused, and pretty light on details. More specifically, it's not well suited to handling conflicts between people in more "leadership" roles (as much as we have leaders in this project).

We should do some research to see what best practices are for handling moderation escalations and how other projects are tackling this problem. Then, let's come up with a policy proposal and submit a PR to the moderation policy in the TSC repo.

**Comment by rachelnicole** [comment]
This is in direct relation to https://github.com/nodejs/TSC/pull/276/files  correct?

**Comment by jasnell** [comment]
I have updated the proposed modification to the Moderation Policy to include *mandatory* use of a Foundation-selected mediator for any Moderation/CoC disputes involving TSC, CommComm, or Moderation Team members. See https://github.com/nodejs/TSC/pull/276

**Comment by renrutnnej** [comment]
I reviewed some of the exchanges in the moderation repo, and I'm curious...does anyone engaging in moderation have to have experience in studying or practicing communication or deescalation techniques?

It appears that a good number of folks (especially from core) attempting to deescalate use communication techniques that do the exact opposite. I’m a trained conflict resolution mediator and facilitator, and that sort of education is pretty widely available and something I strongly recommend we should look into.

**Comment by bnb** [comment]
@renrutnnej I don't think many/any are, but obviously can't speak for anyone. That said, I'd definitely be interested if you've got suggestions on places to do this / resources to learn more. I think it is a generally useful skill, _especially_ in our field. 🙏

**Comment by renrutnnej** [comment]
I completed my training at an in-person workshop over the course of many weeks at a local dispute resolution center – but the general training was only 3 days long, it was the shadowing/practice in actual mediations that took several weeks. 
I know @hackygolucky has experience with this as well, and maybe she knows of a good program we could look into online?

**Comment by hackygolucky** [comment]
There is a proposal in the TSC right now for this that I think we should consider. Furthermore, I think it would be very helpful to look towards a future where the CoC and Moderation is in a separate repo, such as Admin, that is jointly scoped for both the TSC and CommComm where we are contributing together to these instead of contributing to another committee's CoC and then linking to it :)

**Comment by bnb** [comment]
@hackygolucky Not sure if this issue has any further TODOs, now that the Moderation Team has been created. Any thoughts? 🤔

**Comment by bnb** [comment]
Going to close. Please feel free to open a new issue in the CommComm or Moderation repos if further discussion is needed 👍
