### ISSUE TITLE
Recording meeting attendance via zoom

### ISSUE THREAD

**Issue by Bamieh** [nodejs/community-committee#350]
I usually forget to file attendance on the google sheet during meetings (completely my fault). Anyways I was looking for a better solution than manually recording attendance and reporting it.

Zoom provides a tool for reporting attendance for each meeting, it is both accessible via their admin dashboard and their API.

I give my +1 for using this approach for several reasons:
- The reporting tool we have can use the API instead of crawling sheets etc.
- 100% accurate and immutable.
- no more manual reporting for attendance.
- It also gives other juicy details such as the duration of attendance, which is something we do not record at the moment.

**Comment by bnb** [comment]
I'd argue against the truth of `100% accurate and immutable` purely for the reason that I know multiple users join in with the Node.js Foundation account. I end up renaming myself, but I'm not sure if others do. Basically, this assumes that everyone uses consistent naming or doesn't change accounts (I know a few CommComm members that have several - foundation, TSC, CommComm, personal, and/or work).

Totally +1 for finding a better tracking mechanism, and this is likely the best we're going to do – we'd need to implement tooling for it, though.

**Comment by bnb** [comment]
That said, I don't think we should track the duration of attendance... at least for CommComm and Initiative meetings. That begins to tread into the territory of mandatory attendance, which we've been trying to move away from 😅

**Comment by bnb** [comment]
Since attendance is less important now, I'm going to close this. Feel free to re-open if there's a need 👍
