### ISSUE TITLE
Open Meeting: Individual Membership Subgroup Meeting - Monday, July 16th

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#353]
Just wanted to give an early heads up that the time slot in the Doodle Poll we ran to gauge availability for Individual Membership was July 16th at 4-5pm ET / 1-2pm PT.

This is an open meeting for anyone who is interested in helping give feedback into what the definition of _Individual Membership_ of the Node.js Foundation should resemble under the Community Committee. This includes things like benefits, representation, voting, and so on.

If you do have an interest in this, I _strongly encourage you_ to join us!

Ping @nodejs/tsc, @nodejs/community-committee 💖

**Comment by bnb** [comment]
Just a heads up: We're really looking to get @sarahnovotny in to the next meeting we have around this. We may need to adjust this meeting's time / date to ensure we're able to do this 👍

**Comment by mhdawson** [comment]
I'm not going to be able to make the first half of the meeting as since filling in the doodle I have a 1/2 meeting booked to prepare for a panel at node summit next week.

**Comment by bnb** [comment]
Livestream: https://www.youtube.com/nodejs-foundation/live

Member and interested individual join link: https://zoom.us/j/997140597

**Comment by chowdhurian** [comment]
May be 5 mins delayed.
