### ISSUE TITLE
Creating an audio book for Nodejs Official Documentation

### ISSUE THREAD

**Issue by somsharan** [nodejs/community-committee#357]
Planning to record audio of NodeJs Official Documentation. 

Suggestion and HELP Required.

**Comment by bnb** [comment]
@somsharan I commend you for trying to create an audiobook – it's an unusually difficult task!

I'd like to ask what kind of help you're asking for from the Community Committee? Thanks! 🙏

**Comment by bnb** [comment]
Going to close this for now – please let us know if you can clarify the context requested above. Thanks!
