### ISSUE TITLE
Agenda Building – Node.js Foundation Individual Membership Meeting – Monday August 20th

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#360]
We've not had another meeting on Individual Membership, not due to lack of interest but due to lack of organization.

I wanted to quickly sketch out an agenda with y'all so we can move ahead and be a bit more prepared for the next meeting to discuss 👍

## Agenda
- Review Individual Membership Benefits doc (not linking because I can't recall if it was a public document or not 🤔)
- Discuss steps needed for actually implementing a new program (infrastructure)
- Comment with suggestions/requests for agenda items
-

**Comment by Tiriel** [comment]
Since I have some bandwidth and mojo back, I'd like to come back on track on this subject.

To that effect:
1. Would it be okay for everyone?
1. Since I don't know if I got everything that was produced, can someone point me to the resources or send me the docs?

Thanks everyone!

**Comment by mhdawson** [comment]
+1 to inviting  @ladyleet

**Comment by mhdawson** [comment]
Is the meeting on today and if so where can we find the link for the meeting?

**Comment by WaleedAshraf** [comment]
was not able to attend this one.
Here is the issue for the meeting: https://github.com/nodejs/community-committee/issues/364

**Comment by bnb** [comment]
Going to close this for now since we had the meeting 👍
