### ISSUE TITLE
Moderation Team Recertification

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#361]
We're coming up on around the 1 year anniversary for the initial selection of moderation team members. As a part of the Moderation Team process, both the TSC and CommComm need to recertify each Moderation Team Member independently with a simple majority vote.

We should have this vote in the next CommComm meeting to ensure that we're a bit ahead of the game with this process 👍

**Comment by refack** [comment]
> _An annual recertification vote is required for all moderators. For an individual	to continue as a moderator, a simple majority vote of each the TSC and CommComm members must vote in *favor* of retaining an individual moderator._

Since this is the first time we are doing this, we probably should define this a little bit more continued in https://github.com/nodejs/admin/pull/218

**Comment by refack** [comment]
FTR, a vote form went out:
```
In the time zone "(UTC-07:00) Los_Angeles" accounting for winter/summer time change:
The vote starts Monday 24 September 2018 at 08h 48min 00s.
The vote ends Thursday 27 September 2018 at 08h 58min 00s.
The vote will last 3 days 10 min
```

**Comment by amiller-gh** [comment]
The CommComm has re-certified all current members of the Moderation Team.

12 CommComm members have voted to re-certify all members. With 16 CommComm members total, that's a simple majority.

See you next year!
