### ISSUE TITLE
Individual Membership Subgroup Recommendation

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#365]
At the Individual Membership Subgroup meeting on 2018-08-20 (#364), we came to a preliminary agreement that we have strong consensus that individual membership is important to the success of Node.js.

A unanimous vote to continue Individual Membership was supported by @dshaw @bnb @mhdawson @williamkapke @codeekage @chowdhurian.

In the coming weeks, we will continue our work defining the nature, scope and technical requirements for a revised implementation of Individual Membership.

**Comment by chowdhurian** [comment]
#390 is the direct result of this initial motion to define the scope and technical requirements for a revised Individual Membership.

Closing this issue for now, please feel free to reopen when necessary! 💖
