### ISSUE TITLE
Individual Membership Subgroup Meeting - September 4th, 2018

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#366]
The Joint Strategy Subcommittee has asked the CommComm to begin planning on how we'd like to approach managing Individual Membership.

**Minutes Doc:**
Link: https://docs.google.com/document/d/1OrFC5FrMt5nugE2hj7o0OP8O31Eg8QrZj60XyrHT-DM/edit?usp=sharing

**Attendees:**
The @nodejs/community-committee membership is invited.

If you'd like to help out, please feel free to comment in this issue to be added.

**Agenda items:**
- Review Individual Membership formal request and parameters from the Joint Strategy Subcommittee 
- Request for Comments: Individual Membership identity providers
- Individual Membership MVP scoping

Feel free to request agenda items be added in this issue 👍

**Comment by dshaw** [comment]
Proposed agenda item: Consider partner community engagement. https://github.com/nodejs/community-committee/pull/352

**Comment by dshaw** [comment]
Please click the link below to join the webinar: 
https://zoom.us/j/353580629

Or iPhone one-tap :
    US: +16699006833,,353580629#  or +16465588656,,353580629# 
Or Telephone:
    Dial(for higher quality, dial a number based on your current location): 
        US: +1 669 900 6833  or +1 646 558 8656  or +1 877 369 0926 (Toll Free) or +1 855 880 1246 (Toll Free)
    Webinar ID: 353 580 629
    International numbers available: https://zoom.us/u/eaAvofE0S

**Comment by bnb** [comment]
Link isn't working for me 🤔

**Comment by dshaw** [comment]
@bnb Myself and a few other folks used that link and are on.

**Comment by chowdhurian** [comment]
This meeting was preceded by #364 and followed by #388.

Closing for now, please feel free to reopen when needed! 💛
