### ISSUE TITLE
Q&A with Abraham Jr. Agiri @codeekage: CommComm Chairperson Election

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#368]
CommComm Chairperson Q&A session for Abraham Jr. Agiri @codeekage! 

Feel free to drop your questions for @codeekage here as comments.

*CANDIDATE STATEMENT*
TBD

**Comment by bnb** [comment]
What are the current rough edges that you see with the Node.js Community Committee, and what would your ideal solutions be to those rough edges in a years' time?

**Comment by codeekage** [comment]
I’m happily resigning from running for CommComm Chairperson and will still love to watch how leadership works and run next year with the hope of a win. But we will happily love to help/assist anyone leading and who successfully becomes chair, where I can possible help. 

I also publicly give my votes to @amiler-gh && @dshaw. 😊 

Closing this now. 🙏🏼

**Comment by WaleedAshraf** [comment]
@codeekage Best of luck for next year.  👍Hopefully, you will win. :)

About giving vote publicly, I think we should keep it anonymous. It's not related to who you are voting for but for those who you are not voting. Everyone is doing their best. Hope you understand. ✌️
