### ISSUE TITLE
Q&A with Adam Miller @amiller-gh: CommComm Chairperson Election

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#370]
CommComm Chairperson Q&A session for Adam Miller @amiller-gh! 

Feel free to drop your questions for @amiller-gh here as comments.

*CANDIDATE STATEMENT*
TBD

**Comment by bnb** [comment]
What are the current rough edges that you see with the Node.js Community Committee, and what would your ideal solutions be to those rough edges in a years' time?

**Comment by amiller-gh** [comment]
CANDIDATE STATEMENT

First and foremost, major recognition is required for Tierney and the amazing work he's done over the past year+ to make the Community Committee what it is today. Without his vision and guidance we wouldn't have this amazing group of all-star members, or the large collection of successful initiatives both completed, and currently in flight. His success is only driven home by the awesome display of CommComm Chair candidates in this election – Tierney has fostered a wonderful community here, both externally in the Node.js ecosystem, and internally on the CommComm itself.

The Community Committee has a unique set of challenges to face in the next year, ones that I am eager and excited to tackle. The past year, we have seen this group successfully lay the groundwork for a productive, and independently functional, Community Committee. This next year needs to be focused on scaling our team's reach, impact, and empowerment – this will happen through continued improvements in our process, governance, and the relationships we forge throughout the project.

Helping spearhead the internal Design Systems team at LinkedIn has positioned me well to be a good steward for the Committee. In that position, helping support engineers across the 12,000+ employee company, I've been able to exercise the skills I believe will help push CommComm to the next phase of its success. I am most happy when I can help teams: 

 - design user-focused solutions to complex problems;
 - craft product timelines, rollout strategies, and track progress against well-defined deliverables;
 - create and manage internal team operational strategies to further the group's goals;
 - align external stakeholders, set expectations, and negotiate process and timelines with 3rd parties;
 - empower the team to create their own successes.

If given the opportunity, I would love to bring these skills to bear as Community Committee Chairperson!

Over the past year I have loved developing good working relationships with everyone on this committee, members of the TSC, and our connections at the Foundation. I firmly believe it is these kinds of relationships that will enable the Community Committee to operate more and more like a well-oiled product team, and scale to our next level of success ❤️

**Comment by amiller-gh** [comment]
Closing because elections are over ❤️
