### ISSUE TITLE
Q&A with Joe Sepi @joesepi: CommComm Chairperson Election

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#371]
CommComm Chairperson Q&A session for Joe Sepi @joesepi! 

Feel free to drop your questions for @joesepi here as comments.

*CANDIDATE STATEMENT*
TBD

**Comment by bnb** [comment]
What are the current rough edges that you see with the Node.js Community Committee, and what would your ideal solutions be to those rough edges in a years' time?

**Comment by joesepi** [comment]
CANDIDATE STATEMENT

We have such a great crop of candidates for chair. Huzzah for CommComm.

Here are the reasons why I would be a good steward of the Community Committee:

Management experience
- I've lead engineering teams on large-scale projects at places such as IBM, Adobe, The New York Times, Credit Suisse, Sears, Novus and more. This leadership was both from an engineering perspective as well as a team perspective. Over my 20 year career in tech, often promoted to leadership roles, I've developed and demonstrated skills in team management, including coordinating and delegating. I work to people's strengths and work towards effective collaboration and combined team effort.

Dedicated time
- For the past year I have lead the IBM NYC Developer Advocacy team. This was an honor and I am proud of the team and all that we've done. However, last Satuday I transitioned to a role focused on open source, particularly Node.js. My mandate is to spend the vast majority of my time (~90%) working on the Node.js project, community and foundation. I plan to split that time between community and technical (core, tooling, other TBD areas). I also plan to further build  Node.js applications that I've been working on which will keep me connected to the challenges of building cloud native Node.js applications (albeit on a smaller scale compared to our enterprise friends).

Plus
- I'm a people person, people like me!
- I can be very diplomatic
- I know a lot of people in the foundation (board, tsc, commcomm and foundation staff) as well as the larger community

My plan will be to 
- dive headfirst into the current challenges we are facing
- work to identify champions for problem areas
- empower others to lead and be involved
- organize around our efforts
- be involved on the technical side to further align the two TLCs and work for the full community.

All that being said, I am very proud of the Community Committee and am happy to see so many hats in the ring for the chairperson. Tierney has done such great work to get us this far. I am confident that, with the support of the committee overall, any one of us will do a superb job continuing the efforts to support and empower the community.

**Comment by joesepi** [comment]
@bnb To answer your question, one of the first things I would focus on is finding the rough edges. I'll admit that shortly after joining commcomm, I got promoted at work and had a lot less free time. That recently changed and all of my time is now focused on Node.js, the project, community and foundation.

My initial thoughts around rough edges are:
- better working relationships with both the TSC and the board (initial effort: I would work to facilitate more communication and be a conduit between, working with the TSC chair and committee members)
- getting more involvement from the community (outside of commcomm) on the initiatives and objectives we are focused on (and beyond) (initial effort: find ways to engage with the larger community to raise awareness and encourage involvement in our efforts. One thing I've been doing is presenting at conferences on how to get involved in open source, with a focus on the Node.js project.)

**Comment by amiller-gh** [comment]
Closing because elections are over ❤️
