### ISSUE TITLE
It's election time for the Chairperson of Community Committee!

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#373]
### It's election time for the Chairperson of Community Committee!

Nominations are now published for candidates to be considered for election! Candidates will each have their own Q&A issue, linked by their name, where they will answer questions through the election period ending **Sunday, September 9 at 11:59pm UTC**. Ballots will be emailed Friday, September 7 to all voting members of CommComm *in order to give time for candidates to answer questions* and have time to consider responses through September 9 before voting.

> The CC will elect from amongst voting CC members a CC Chairperson to work on building an agenda for CC meetings and collaborate with the Individual Membership Directors the wishes of the CC to the Board for a term of one year according to the Node.js Foundation’s By-laws. The CC shall hold annual elections to select a CC Chairperson; there are no limits on the number of terms a CC Chairperson may serve.

## Nominated candidates:
- Abraham Jr. Agiri @codeekage --> [Q&A](https://github.com/nodejs/community-committee/issues/368)
- Jem Bezooyen @jembijoux --> [Q&A](https://github.com/nodejs/community-committee/issues/369)
- Adam Miller @amiller-gh --> [Q&A](https://github.com/nodejs/community-committee/issues/370)
- Joe Sepi @joesepi --> [Q&A](https://github.com/nodejs/community-committee/issues/371)
- Dan Shaw @dshaw --> [Q&A](https://github.com/nodejs/community-committee/issues/372)

As stated in the previous election, expected responsibilities include but are not limited to:
- Chair and facilitate each CommComm member meeting. It is the chairperson's responsibility to ensure that the meeting stays on track, sticks to the agenda, and finishes within the allotted time.
- Cultivate and maintain good working relationships with the members of CommComm and groups contributing under the CommComm scope.
- Coordinate with the CommComm Director( @hackygolucky) on presenting requests to the Board from CommComm that need attention.
- Collaborate closely with the TSC Chair(@mhdawson), TSC Director(@MylesBorins), Individual Membership Director(@williamkapke), and appropriate ecosystem/Foundation stakeholders
- Coordinate efforts in shared repos, as listed in Admin
- Create each CommComm meeting's agenda and help facilitate other meetings under the CommComm's scope.
- Create events and ensure appropriate meetings are live-streamed on YouTube. 

All Community Committee active members are eligible to vote and will receive a ballot after the Q&A window has been open for a few days. If you are having trouble with voting, please email tracy@nodejs.org.

**Comment by hackygolucky** [comment]
Ballots have been emailed to all members listed on the CommComm README. Please ping me if you did not receive it!

**Comment by jakeNiemiec** [comment]
On the streamed meeting yesterday, I heard somebody express confusion about multiple-candidate voting methods (eg: [Single Transferable Vote](https://en.wikipedia.org/wiki/Single_transferable_vote#Terminology) aka instant-runoff voting aka ranked-choice voting). 

I just wanted to share an old (but good) video on the specifics & benefits of such a system (4mins): https://youtu.be/3Y3jE3B8HsE?t=1m14s

**Comment by amiller-gh** [comment]
Shared this in the Zoom chat during the meeting too – best (interactive!) example I’ve ever seen of different voting systems: https://ncase.me/ballot/

@ncase ===  ✨🌟🎉🤯🎉🌟✨
