### ISSUE TITLE
Document Initiative Setup Process

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#374]
Currently we're lacking documentation around creating an initiative.  Since this is coming up a bit with Outreach, I figured it would also be a good time to discuss documenting some of the content that is needed so this process is repeatable.

Templates that are needed in this repo:
- [ ] Template for inclusion of the Node.js Code of Conduct ([example](https://github.com/nodejs/community-committee/blob/master/CODE_OF_CONDUCT.md))
- [ ] Template for CONTRIBUTING.md ([example](https://github.com/nodejs/i18n/blob/master/CONTRIBUTING.md))
- [ ] Meeting minutes configuration (if needed – see [this](https://github.com/nodejs/create-node-meeting-artifacts/tree/master/templates) for the four kinds of templates)
- [ ] Add to the [STRATEGIC-INITIATIVES.md](https://github.com/nodejs/community-committee#strategic-initiatives) list

reference: [previous discussion/issue](https://github.com/nodejs/community-committee/issues/201)

**Comment by chowdhurian** [comment]
I can help mentor any person who wants to explore this!

**Comment by codeekage** [comment]
We could also add: 

- Initiative should have at least 1 CommComm member and 3 member collaborators. 
- Initiative should have a working meeting schedule. 
- Initiative should have an almost-proper documentation.

Correct me if all these are really not necessary. 

Some criteria’s an initiative should meet even before creating a repo. So, we don’t have repos that are not being used, and have no definitions.

**Comment by bnb** [comment]
@codeekage I believe we've generally seen success with 1 CommComm member and 2 initiative collaborators. Also not entirely sure what the last one would entail 😅

**Comment by lidoravitan** [comment]
@bnb @chowdhurian I'd happy to help :) sure, if it relevant.

**Comment by bnb** [comment]
@lidoravitan definitely still is! Happy to help if you're still interested. My suggestion:

- Fork this repo
- Create a new file, something like `governance/INITIATIVE_PROCESS.md`
- Start documenting what I listed in the original post – these can be basic documentation and can be expanded upon later by others if needed 
- Submit a PR!

**Comment by lidoravitan** [comment]
@bnb I want to push it forward soon, please can you give me a reference to the original post, ("**Start documenting what I listed in the original post**..."). it would be very helpful, thank you so much!

**Comment by lidoravitan** [comment]
@chowdhurian @bnb  thanks! I've opened a new pull request, hope it fits the requirements. 💚

**Comment by bnb** [comment]
This has been PR'ed and merged. Thank you @lidoravitan.
