### ISSUE TITLE
Individual Membership: Current and Past Members Survey

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/community-committee#375]
Emerged from the 2018-09-06 CommComm meeting.

We should craft surveys for current and past members to collect data on member wants and needs.

**Comment by amiller-gh** [comment]
Some initial thoughts: 

 - What is your current happiness (perceived value?) of Ind. Membership program?
 - Net promoter score – how likely would you recommend the program to a friend?
 - How did you hear about the IM program?
 - In your words, what value do you expect to receive from an open source individual membership?
 - (For people with lapsed membership) What made you not renew?

> IMO we should stay away from specific ind. membership benefit asks, ex: "Would you like to receive X?" since I think the answer will almost always be yes. Instead, lets try and get a feel for the *shape* of the program members expect.

**Comment by joesepi** [comment]
Here are some direct questions, framed to ask from a very neutral position

- Why did you become an Individual Member? (If lapsed, why?)
- The goal of the Individual Membership program is to <insert clearly defined goal here>; do you believe it is successful in that goal. If so/not, how/why?
- How do you think the program could be improved?

+1 on the NPS question

(There's some overlap with previous questions)

**Comment by mhdawson** [comment]
A few more suggestions

* Are you planning to renew your membership.  If not why?
* If you could only get one benefit from being an individual member what would it be?
* Are you an individual member of any other projects?
* If you are an individual member of another project what are the benefits you get from membership in that project?
* How often to you interact with the Node.js project (github, meetings, email, etc.)
*

**Comment by codeekage** [comment]
Are we going to be sending this survey via email or hope individual members eventually   stumbles on them?

**Comment by chowdhurian** [comment]
More complete data will be had with direct requests through email. Plus, past members (who are part of the target cohort) are unlikely to see a posted survey.

**Comment by lidoravitan** [comment]
can I help with this issue?

**Comment by bnb** [comment]
@lidoravitan yup! I'd suggest beginning with building out a markdown file of questions that address what was mentioned previously in the thread 👍

**Comment by dshaw** [comment]
@amiller-gh Re-adding this to CommComm agenda to check whether this is still a priority. @nodejs/user-feedback will not be able to prioritize this work in the next 2 months.

**Comment by keywordnew** [comment]
#437 adds the Membership Survey file.

**Comment by bnb** [comment]
Closing this. Individual Membership no longer exists within the Node.js project, and is instead something we've yeeted up to the OpenJS Foundation.
