### ISSUE TITLE
Ask the CommComm – Questions for the Community Corner CommComm Panel

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#378]
Hey there everybody!

Just wanted to get a thread going to queue up some questions from the community for the Community Committee panel at Node+JS Interactive in Vancouver. We had a ton of the CommComm members raise there hands, but we can unfortunately only fit 5 on the stage:

- Adam Miller (@amiller-gh)
- Agiri Abraham (@codeekage)
- Tierney Cyren (das me!)
- Tracy Hinds (@hackygolucky)
- Waleed Ashraf (@WaleedAshraf)

The panel will be happening during the **3:50-4:20 coffee break** in the Community Corner!

If y'all have any questions, we'd love to hear them so we can answer them. Regardless of if you're attending the event, if your question is answered I'll be sure to follow up with you and get you the answer in addition to answering on stage ❤️

**Comment by amiller-gh** [comment]
Closing because this HAPPENED AND WAS AWESOME 🎉
