### ISSUE TITLE
Add maintainer details to PARTNER_COMMUNITIES.md

### ISSUE THREAD

**Issue by refack** [nodejs/community-committee#381]
ATM we only have one, but still if for example a user has trouble connecting, or getting an invitation, who should they follow up with?

**Comment by joyeecheung** [comment]
BTW, I am having trouble getting the registration done (I am 30% sure I've registered before...but I cannot find anything when I searched for `nodeslackers` in my mail box)

**Comment by bnb** [comment]
Added the "Good First Issue" label to this.

For those interested in taking this issue on:

- We recently merged a new document: [PARTNER_COMMUNITIES.md](https://github.com/nodejs/community-committee/blob/master/PARTNER_COMMUNITIES.md)
- This document requires that partner communities have some kind of tie to a contributor to Node.js.
- @refack is suggesting that we list out who those contributors are.
- Currently there is only one partner community, NodeSlackers. The contributor in the case of NodeSlackers is @dshaw.
- Task: Update the issue to show that @dshaw is the contributor, in relation to NodeSlackers.

**Comment by chasingSublimity** [comment]
Hiya! I've been looking for a chance to contribute to the community committee since Node+JS interactive in Vancouver. I'd be happy to help here.

**Comment by bnb** [comment]
Awesome, @chasingSublimity! I generally outlined what needs to be done in my previous comment, but if you need more context or aren't sure what to do I'd be happy to help more directly 🤗

**Comment by ljharb** [comment]
fwiw I’m also a contact for NodeSlackera
