### ISSUE TITLE
Individual Membership Subgroup Meeting - October 1st, 2018

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#388]
The Joint Strategy Subcommittee has asked the CommComm to begin planning on how we'd like to approach managing Individual Membership.

**Minutes Doc:**
Link: [Individual Membership Subgroup – Rolling Meeting Minutes](https://docs.google.com/document/d/1OrFC5FrMt5nugE2hj7o0OP8O31Eg8QrZj60XyrHT-DM/edit)

**Attendees:**
The @nodejs/community-committee membership is invited.

If you'd like to help out, please feel free to comment in this issue to be added.

**Agenda items:**
- Review Individual Membership formal request and parameters from the Joint Strategy Subcommittee 
- Request for Comments: Individual Membership identity providers
- Individual Membership MVP scoping

Feel free to request agenda items be added in this issue 👍

**Comment by dshaw** [comment]
Zoom meeting link: https://zoom.us/j/353580629

**Comment by dshaw** [comment]
Next meeting is #389 on 2018-10-16 at 11am PT / 2pm ET.

**Comment by chowdhurian** [comment]
There's a Request for Feedback (#390) on the proposal generated by this and prior discussions 🎉🎉🎉 Please comment on it and/or join the discussion on the comments when #389 happens.

Closing this for now, feel free to reopen when necessary! 💛
