### ISSUE TITLE
Individual Membership Subgroup Meeting - October 16th, 2018

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#389]
The Joint Strategy Subcommittee has asked the CommComm to begin planning on how we'd like to approach managing Individual Membership.

**Meeting:**
2018-10-16 at 11am PT / 2pm ET

**Minutes Doc:**
Link: [Individual Membership Subgroup – Rolling Meeting Minutes](https://docs.google.com/document/d/1OrFC5FrMt5nugE2hj7o0OP8O31Eg8QrZj60XyrHT-DM/edit)

**Attendees:**
The @nodejs/community-committee membership is invited.

If you'd like to help out, please feel free to comment in this issue to be added.

**Agenda items:**
- Review Individual Membership formal request and parameters from the Joint Strategy Subcommittee 
- Request for Comments: Individual Membership identity providers
- Individual Membership MVP scoping

Feel free to request agenda items be added in this issue 👍

Zoom meeting link: https://zoom.us/j/353580629

**Comment by amiller-gh** [comment]
Hey! 

I won't be able to make this one (also, I have a calendar invite for today (Monday) but this ticket says tomorrow – which is correct?

My only points to raise: there was a lot of convo at Collab Summit about the Ind. Membership seat in the scope of the new Foundation – it would be great if someone could capture our thoughts in a little finer detail in the `FOUNDATIONS.md` recommendations document over in nodejs/bootstrap (in the [`bootstrap-process`](https://github.com/nodejs/bootstrap/pull/7/files/f9b1ef59a277553f679a49898a9d5dd812cd7cd2) branch I have going). Its touched on in there, but the current version isn't particularly clear.

That same repo introduces an RFC process for new programs – it may be helpful to use that format to formally write the proposal for the individual membership program.

**Comment by chowdhurian** [comment]
Hey folks, I have a calendar invite for today the 12th of November but wasn't able to find an issue for the meeting. Is the calendar still correct?

**Comment by codeekage** [comment]
Is there a meeting today?
