### ISSUE TITLE
Individual Membership Subgroup proposal request for feedback

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#390]
The individual membership subgroup has compiled recommendations to be shared with the board. We would like to get feedback ahead of Node+JS Interactive. We have been asked to provide our final recommendation by October 31st, 2018.

- [Individual Membership – Outline of Possibilities](https://docs.google.com/document/d/1GzNmv3effVQe8iHxvJCvhFS36WOlctQ0LB1zD4cYeHs/edit)

If you'd like to participate in future Individual Membership Subgroup meetings, please join us: [individual-membership](https://github.com/nodejs/community-committee/labels/individual-membership).

**Comment by dshaw** [comment]
For @hackygolucky:

"The Individual Membership Subgroup is building upon the [consensus achieved in August that the Community Committee believes in the continued value of individual membership in Node.js](https://github.com/nodejs/community-committee/issues/365) has shared the outline of the next generation of individual membership program. The revamped program draws inspiration from [GitHub Education's Student Developer Pack](https://education.github.com/pack) to connect Node.js Foundation member companies with Node.js Individual Membership through incentive bundles. These incentives are broken into flexible payment tiers similar to how [Humble Bundle](https://www.humblebundle.com/about) works to accommodate a diverse, globally distributed Node.js Individual Member community. Some examples of expected incentives include cloud services credits, education credits and corporate swag. The Individual Membership Subgroup is tracking toward October 31st, 2018 for its recommendations for the Joint Strategy Committee."

**Comment by chowdhurian** [comment]
Thanks for the feedback folks! The outline will be socialized with the board tomorrow, and we'll continue to build this out over the next while.

Super stoked to see this become a core channel for people to engage with Node.js 💖

**Comment by bnb** [comment]
Can we make a read-only version of this to share with the general public? I'd love to be able to publish something that we can share more broadly.

**Comment by mhdawson** [comment]
+1 to circulate more broadly.

**Comment by bnb** [comment]
Added cc-agenda to discuss the above ☝️

**Comment by hackygolucky** [comment]
Update! It sounds like we'll be having a Board meeting the first week of December, so walking back to make sure we have plenty of time to surface the finalized proposal, I think this draft needs to be official by November 23 for us to email to the Board.

**Comment by amiller-gh** [comment]
Update! @hackygolucky and I are going to tag team this and come up with a draft in the Bootstrap committee staged proposal format. We'll share the draft for scrutiny once we have something 👍

**Comment by bnb** [comment]
Since this work has been moved over to the CPC, I'm going to close this issue. If there's any context here that needs to be lifted up to that, we should go ahead and do that but as far as I can tell there's no need for this issue to remain open ❤️
