### ISSUE TITLE
Stepping down from CommComm

### ISSUE THREAD

**Issue by rachelnicole** [nodejs/community-committee#391]
Hey everyone, I haven’t been participating for a while now, and I need my time to focus on my career. If in the future I have the time I’m fully aware I’ll have to start over as an observer. 

Thanks

**Comment by Bamieh** [comment]
Sorry to hear that 😢  I hope you'll join us again in the future. Good luck with your career

**Comment by amiller-gh** [comment]
Thank you @rachelnicole – best of luck! 🎉 We'll always be here.

**Comment by mhdawson** [comment]
Sorry to hear but understandable and wishing you well as you pursue your career.

**Comment by WaleedAshraf** [comment]
Best of luck @rachelnicole
