### ISSUE TITLE
So, what about NodeConf?

### ISSUE THREAD

**Issue by PatrickHeneise** [nodejs/community-committee#41]
It's been quite a long story with One-Shot, NodeConf and Node conferences around the world, so I'd like to bring up this discussion again without looking too much into the past.

From my perspective, NodeConf organisers are individuals standing up and making a huge effort for Node.js and, having a NodeConf working group would be recognising that effort within he foundation.

As a founder and co-organiser of NodeConf Barcelona I'd like to help others to run a NodeConf in their city and maybe build up a Node.js User Group together with NodeConf. We could share experiences and build up a network (of sponsors, attendees etc.) to build up a global NodeConf brand.

What are your thoughts?

**Comment by hackygolucky** [comment]
@PatrickHeneise I think it would be awesome for community conferences that have helped build up Node.js to have a voice to the foundation. I would say we should be careful for it to not be exclusively 'NodeConf' conferences. It would be great to have more documentation for this, as being a conf organizer myself I get these questions often and have have to write it and explain it many times over.

**Comment by RichardLitt** [comment]
Hey! I had to step out to do some stuff; I wish I could have been there for the afternoon. I can help later?

**Comment by PatrickHeneise** [comment]
As far as I understood the conversation I had with @mikeal and others, NodeConf will become more accessible to other organisers who want to organise conferences in the future and it won't be limited to "The NodeConf in the US". IMHO "NodeConf" is the best name possible for a Node Conference.

Having a FAQ / some guidelines would be very helpful indeed, I have a couple of numbers, spreadsheets and reviews from NodeConf Barcelona to share.

**Comment by hackygolucky** [comment]
Hi @PatrickHeneise, as discussed in our CommComm session at Collab Summit last week, guidelines for organizers who would like to run a conference about Node.js would be super helpful! 

'NodeConf' has actual IP attached to it as a name in both the US and the EU, as far as I am aware, so we should refrain from using it as a Node.js Foundation title for anything. For those who have run conferences around Node.js and have not run under that title(currently I think there were 13-14 NodeConfs), there is an identity of some form attached to it. We don't want to convey any event exclusivity whatsoever or privilege to NodeConfs over other also good Node.js conferences, so avoiding invoking that name would be helpful unless used alongside other examples.

If you'd like, PR the documents you've got as a sort of Events working group, and the CommComm folks can comment from there!

**Comment by nebrius** [comment]
There's a template for creating working groups over at https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md.

That said, the way that the TSC and CTC have traditionally operated is to form a team _first_, and then once it's up and running to convert them to a WG.

If you'd like, we can create a new repo so you have a place to start organizing, and you can ping `@nodejs/community-commmittee` on issues to get us to take a look. We could call it `nodejs/events`, but I fear that will be confused with `require('events')`, so maybe something like `nodejs/community-events`?

What does the rest of @nodejs/community-committee think?

**Comment by hackygolucky** [comment]
SGTM

**Comment by nebrius** [comment]
Sorry I let this sit for so long. I created the https://github.com/nodejs/community-events repo and the nodejs/community-events team and added you to the team @PatrickHeneise!

**Comment by PatrickHeneise** [comment]
Thanks Bryan! Just seen it. I'll open a separate issue to discuss the purpose and guidelines.

**Comment by smithaitufe** [comment]
@PatrickHeneise

I am quite happy for the brilliant thought you shared here.

I will be glad if I, you and others can help us in Nigeria have a NodeConf.

Thanks for prompt response

**Comment by PatrickHeneise** [comment]
@smithaitufe I'd be happy to help! There might still be an issue with the name "NodeConf", that's best discussed with @hackygolucky at the moment. Let me know what I can help with in the https://github.com/nodejs/community-events repo.

**Comment by hackygolucky** [comment]
@PatrickHeneise @smithaitufe Yup, I'd say discussions in the Node.js project repos about conferences should try to remain void prioritizing nodeconf over other conferences because there are a lot of great Node conferences(and JS confs in general), but providing insight about how nodeconfs are run as an example is totally great!

**Comment by bnb** [comment]
@PatrickHeneise @hackygolucky is there anything else we can do to help support efforts around this? If not, I'd like to close this issue - of course, always happy to reopen an issue or open another issue if there's more to be done.

**Comment by PatrickHeneise** [comment]
We'll continue the discussion in @nodejs/community-events. Thanks!
