### ISSUE TITLE
Discussion - Merger - Community Committee across multiple projects

### ISSUE THREAD

**Issue by mhdawson** [nodejs/community-committee#414]
From the bootstrap meetings, the current picture in https://docs.google.com/presentation/d/1qUcvZz4wmQtwcWu9rWjxFNmWw5plD9-4_7mtvQvCegk shows the Community Committee across all of the projects.

I'd think it would be good for the Community Committee to discuss in the next meeting to see if this is what we think makes sense and surface any concerns/issues. 

It may be a quick discussion if everybody is aligned, but I think it is good to at least have a short discussion to see if that is the case.

**Comment by hackygolucky** [comment]
My understanding is that this is the foundation cross community council for all of the projects. That isn't the Node.js CommComm. I think there's a need for project specific focus to be maintained and also for cross-project work to empower all of the projects or whoever is excited for a specific initiative that it makes sense to collaborate on.

**Comment by mhdawson** [comment]
@hackygolucky thanks, I think that is why we should discuss as I was confused as there has been discussion as to whether CommComm should move to be across all projects and if there should 2, one at the top level and one at the Node.js level. I think the doc might even say that members of the C3 would be the existing CommComm members + some members from JSF.

**Comment by amiller-gh** [comment]
Ooh, I'd be very sad if the C3 takes that form. I agree that project-specific focus is very needed post merger. IMO, it should be the goal of C3 to help amplify community initiatives / organizational committees across all foundation projects, much like the CPC. Thats a very separate, dedicated goal.

**Comment by amiller-gh** [comment]
ref: https://github.com/nodejs/bootstrap/issues/38

**Comment by amiller-gh** [comment]
Action Item from CommComm meeting: @joesepi to help organize a dedicated meeting over in Bootstrap about CPC / C3, their responsibilities, and convo around the need for 1 or 2 top level bodies.

@joesepi, once that conversation kicks off feel free to close this ticket 🙂

**Comment by joesepi** [comment]
Opened an issue to gather TLC expectations and proposed to use Dec 10 2pm ET time slot to discuss.

https://github.com/nodejs/bootstrap/issues/52
