### ISSUE TITLE
About NodeJs Certification 

### ISSUE THREAD

**Issue by koklimabc** [nodejs/community-committee#420]
May I ask about NodeJS certification would be under version based or periodically based. Thanks.

**Comment by mhdawson** [comment]
@hackygolucky would you be able to provide some info on this front?

**Comment by bnb** [comment]
As far as I know it would be version based, but as of the original meetings (which were a while ago) will be focused on LTS releases, and will be updated to reflect LTS release lines as they progress.

**Comment by bnb** [comment]
Going to close this for now. Be sure to stay tuned to [@nodejs](https://twitter.com/nodejs) on Twitter and [The Node.js Collection](https://medium.com/the-node-js-collection), as I'm certain there will be announcements and details in both 👍
