### ISSUE TITLE
Individual Membership Subgroup next meeting

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#422]
We have an upcoming board meeting where @hackygolucky needs to present our proposal. We need Tracy and @amiller-gh to attend. Looking for something in the evening Eastern Time.

**Comment by mhdawson** [comment]
As an FYI I'm away for 2 weeks starting Dec 2nd.

**Comment by amiller-gh** [comment]
It's likely we can do this async – Tracy and I are meeting up today to get a more formal draft proposal written. We’ll share out for additional word-smithing after we get a baseline and determine if we need another in-person meeting from there. I think we’re in relative alignment about the details, it just needs codification 🙂

Adam Miller
[in] Design Systems Tech @ LinkedIn
⬡ Node.js Community Committee Chairperson
ammiller@linkedin.com
(413) 454-8261

**Comment by amiller-gh** [comment]
Closing because of discussion from our last meeting 🙂 

See: https://github.com/nodejs/community-committee/issues/423#issuecomment-442985247

We'll evaluate the need for a final doc planning meeting depending on feedback from the proposal Tracy and I are polishing!
