### ISSUE TITLE
Individual Membership Subgroup – Next Steps

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#423]
A few months ago, I stepped up to take point in coordinating our Individual Membership Subgroup meetings. This past month, I started a new job. I have been able to sustain my responsibilities to the @nodejs/community-committee,  @nodejs/user-feedback and @nodejs/mentorship which have meeting times that are compatible with my work schedule with meetings on Thursday and Fridays.

Individual Membership Subgroup meetings (and tangentially the Bootstrap meetings) are not compatible with my schedule. Individual Membership is something that I am very passionate about, but at this time, I am unable to lead this effort.

At this point, I need to step back from this and ask if there is someone who can step up and carry this forward.

**Comment by mhdawson** [comment]
I know @amiller-gh and @hackygolucky were going over the current draft to work on it together. I'm wondering if after that there will be a need for the group to continue meeting or not?

**Comment by mhdawson** [comment]
Of course the last comment is in the context of making a proposal to the board.  In terms of implementing a program that would be completely different.

**Comment by amiller-gh** [comment]
Current working plan discussed in today's CommComm meeting: 

1. @hackygolucky and I are working on an updated draft of both the program proposal and representation proposal using the Bootstrap repo's stages proposal template. We will share a draft of this in Google docs shortly (ETA is EOD tomorrow).
2. We will sync offline on the proposal as-written and wordsmith with the group / CommComm. If we feel there is need for a final meeting to polish we will plan for next week.
3. Once the proposals are in a happy place, Tracy will bring them to the board for approval! We will then consider this phase of the Individual Membership Recommendation Subgroup *done* 🎉 
4. Starting next year, assuming on Foundation support and approval, we will kick off a fresh initiative for program execution. The function of this group will be a lot different than the current subgroup, so it makes sense to me to treat it as a new initiative.

IMO – It is likely that: 

a) Program execution (membership tooling, recruitment, benefits communications, etc) will be a close partnership between our Foundation resources and the initiative; 
b) Representation recommendation, as currently written, is dependent on good program execution and will be blocked by point (a), and;
c) The representation plan recommendation will also likely move over to the Bootstrap repo for further refinement in the context of an umbrella foundation.

Does all this sound accurate / good? 🙂

**Comment by amiller-gh** [comment]
Re-purposing this ticket to talk about the next phase for individual membership implementation – we'll chat about it in today's meeting 🙂

**Comment by amiller-gh** [comment]
Ref, approved program proposal: https://docs.google.com/document/d/1qlQtsYCmRS1R5b7x0JJCd7hy4AFtRcdHhcQDmdHVJ2g

**Comment by mhdawson** [comment]
When you approved, approved by the Board?

**Comment by hackygolucky** [comment]
@mhdawson there were no objections explicitly from the Board when discussed, but to be 'approved' I am working on the ByLaws/Charter changes that will be a PR this week. We'll have folks here approve those drafts, and then in this month's Board meeting we would have the Board approve those changes as resolutions.

**Comment by hackygolucky** [comment]
@mhdawson @amiller-gh Furthermore, @MylesBorins and I met today to talk about lots of work we've got in flight and Individual Membership program as a bootstrap proposal will make its way there amended for the larger umbrella foundation where appropriate this week. So watch out for that!

**Comment by amiller-gh** [comment]
Closed since Bootsrap has taken ownership of the proposal 🎉
