### ISSUE TITLE
Node.js Contributor Cards

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/community-committee#428]
The Node.js Foundation has created business cards for Node.js Foundation, and are sharing them at conferences. At NodeSummit, @bnb discussed the possibility of creating one for contributors to share at in-person events for people who are interested in getting started.

Reference: https://docs.google.com/document/d/119ZhmWYjjy3-nW3CSMPaowUkMxyayJi7EjUrlsEIWdY

Steps to success:

 - [ ] Setup static point-of-entry site (@chowdhurian / @bnb)
 - [ ] Design the card (@amiller-gh / @bnb)
 - [ ] Set up a url redirect from nodejs.org to static site (unassigned)
 - [ ] Print cards (unassigned – likely foundation folk)
 - [ ] Static will be integrated into new site after redesign – community page? (@amiller-gh)

**Comment by bnb** [comment]
I will have some availability upcoming to work on this, and I apologize for the long-term delay ❤️

**Comment by LaRuaNa** [comment]
Cool idea I can help on this :]

**Comment by bnb** [comment]
Built out a strawperson repo for this (and have published it to npm so it doesn't get squatted): https://github.com/bnb/community-card

**Comment by bnb** [comment]
Some specific points: this does not currently point to the website in any way, as we'd originally discussed. All the links are hard-coded into the project.

**Comment by bnb** [comment]
Happy to re-pick this up but there's been zero interest outside myself for over a year. If someone else wants to take it, by all means feel free to ❤️
