### ISSUE TITLE
Exporting Google Docs -> Markdown Minutes Notes

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#43]
So I've noticed that the Minutes are usually taken in Google Docs, and that there's only currently _one_ markdown version of the Minutes in the [`/meetings`](https://github.com/nodejs/community-committee/tree/master/meetings) folder. 

At work, I've actually been using a small script I found online to convert Google Docs into Markdown files. I've put the script in a [Gist](https://gist.github.com/bnb/a7817b84f4cc8f05115e3e0c9a495f6f) (can't find the original source 🤔), and would be happy to help get people familiar with the workflow. 

I'd also be happy to take on this responsibility myself, if that would be helpful!

**Comment by nebrius** [comment]
Nice :). Does the script convert the styles to markdown styles? e.g. does _italic_ convert to `_italic_`? I _think_ we may end up with double style code if it does convert them. As is, we just need to copy paste the Google Doc straight into the markdown file.

**Comment by bnb** [comment]
@nebrius Yep, it does convert GDocs styled italics, boldface, etc to Markdown italics. If we already write in markdown style in GDocs, then I don't think it'll be an issue 😁 

That said, this may be a useful resource to provide for Teams to use for documentation purposes nevertheless. ❤️

**Comment by nebrius** [comment]
I'm going to go ahead and close this, since we don't have any actionable items to accomplish. Thanks again for the post!
