### ISSUE TITLE
Individual Membership at .NET Foundation

### ISSUE THREAD

**Issue by dshaw** [nodejs/community-committee#430]
@nodejs/community-committee Sorry, I didn't quite know where to put this.

Jory Burson pointed out to me that the .NET Foundation just adopted an Individual Membership model. They are specifically enabling individual membership for contributors.

https://dotnetfoundation.org/blog/2018/12/04/announcing-net-foundation-open-membership

https://tirania.org/blog/archive/2018/Dec-04.html

**Comment by amiller-gh** [comment]
Fascinating 🙂 The precedent may serve us well as we iterate on our program in the long term. Will be interesting to watch.

On first blush I don't see this changing anything about our proposal for this next iteration on the program  – I'm still happy with where we landed with it and think its the right way forward for where our org is right now. Do you see any action items coming from this, or is this largely an industry awareness PSA?

**Comment by bnb** [comment]
It's interesting that their approach looks almost identical to our existing one:

```
- Any individual contributor to a .NET Foundation project can apply to become a member. Contributions may include code contributions, documentation, or other significant project contribution.
- Upon approval, members will be notified with information on completing their membership. We’re requesting $100 annual dues, with liberal waivers for students or financial hardship.
- Each year, we’ll host an election for the board of directors. Any active member can campaign for a one year term, based on their community standing, plans to advance the .NET open source ecosystem, and past performance in case they are seeking reelection.
- Each .NET Foundation member can vote in the election. We plan to use ranked choice voting (specifically, single transferable vote), using OpaVote.
- We'll be running our first annual community elections starting in January 2019. Watch our blog and @dotnetfdn on Twitter for announcements on election dates.
```

**Comment by amiller-gh** [comment]
Closing for lack of action-item, but great callout – thanks for surfacing! May help with the discussion in #423
