### ISSUE TITLE
Kicking Off “Working Group Update” Blog Series

### ISSUE THREAD

**Issue by RRomoff** [nodejs/community-committee#435]
Hi All - Sarah and I have been speaking with Tracy Hinds and the Community Committee on a new blog series that would feature the Working Groups and what progress they’ve been making. By bringing some highlights to the forefront, we could potentially increase involvement in the working groups while showcasing what the teams are working on. We’ve started with the Security WG and will be posting an update in the coming days.

To make these a bit more streamlined, I’ve put together some questions to get these blogs started. We’ll need the subject matter experts to fill in details, but the template would act as a guide. Is there any feedback or additions to the following?

Title: Working Group X Update: DATE
Question 1: What’s the objective of your working group?
Question 2: What are the top priorities your group has been working on in the past quarter?
Question 3: What are the updates you’d like to highlight from the last quester?
Question 4: Any shout outs or special recognitions you’d like to mention? 
Question 5: Any new members to highlight?
Question 6: What are the top priorities for the next quarter? 
Question 7: How can someone get involved. 

Would anyone in this group be interested in participating/ have recommendations on getting this off the ground? Either ping me here if you are interested or send me an email rromoff@linuxfoundation.org.

**Comment by SarahKConway** [comment]
tagging @hackygolucky in case she wants to chime in with some ideas, folks to contact 1:1 to get this rolling

**Comment by mhdawson** [comment]
I think we should include teams in addition to working groups (Package-maintenance, user-feedback, modules etc.)

Since I'm part of a number of the Working Groups I'm happy to help with the first update for some of those.  I could help with N-API, benchmarking.  I'll volunteer @gdams to do the one for the Build WG. and @BethGriggs to help with the Release WG one.

**Comment by RRomoff** [comment]
Based on the last CommComm meeting a great discussion around kicking off regular Working Group/ Team updates, please find more information below. Feedback welcome.

Node.js Collection Working Group/ Team Update Series
Jan 2019
Objective:
To raise awareness within the Node.js community and generate more participation in the work happening, the Node.js Foundation marketing team, in collaboration with Community Committee, is starting a new monthly WG series with updates from each working group or team willing to/ able to participate. 
These updates will be featured on the Node.js Collection Medium blog and publicized via Node.js social channels. 
The Node.js Security WG kicked things off (see sample below). 
An issue on this has been open in GitHub:
https://github.com/nodejs/community-committee/issues/435 
Existing Example/ Post Guidelines:
Node.js Security WG — January 2019 
Each post should stay between 700 and 1000 words and should, at minimum, cover the following:
Latest accomplishments
New developments and progress 
Current focus of work
What's ahead
Call to Action


How to Submit?
To better support working groups and teams, we are recommending using a Google Form to gather answers. Here’s a draft: Node.js Collection Working Group/Team Blog Update Submission.
Or, if you love to write and are inspired to submit a draft, the Foundation marketing team would be happy to review, edit if necessary, and post the blog. 
Next Steps After Submission: 
Once you’ve submitted your update via the form, the Node.js Foundation marketing team will be in touch within a few days with any follow up questions. The Node marketing team will provide a draft version via google doc for review and final approval to the person(s) who submitted the form and other designated reviewers. 
Timeline/ Content Calendar
To give working groups and teams enough runway to complete their updates, and best allocate resources, we have proposed a timeline which will feature one team or WG per month.
Proposed Timeline/ Calendar
Based on feedback from the CommComm, the following working groups would good candidates to get this series started:
Release
Build
Benchmarking
Package Maintenance
User Feedback,
 i18n

**Comment by codeekage** [comment]
The google docs requires permission to access it. 😁😁

**Comment by RRomoff** [comment]
@codeekage Thanks for flagging that. I've updated the link access and we should be good now. Let me know if not.

**Comment by codeekage** [comment]
Awesome! It’s working. 🙏🏼

**Comment by amiller-gh** [comment]
Closing and we'll do regular check-ins during the Node.js Collection time slot at the beginning of each commcomm – excited this is rolling! 🙏
