### ISSUE TITLE
Node.js Collection – Next Steps

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/community-committee#439]
@RRomoff to fill out and discuss in CommComm meeting 1/10

**Comment by chowdhurian** [comment]
@RRomoff post CommComm meeting: would love a knowledge share, happy to be of help

**Comment by WaleedAshraf** [comment]
We had this Google Sheet for tracking: https://docs.google.com/spreadsheets/d/1xT8KEolYqcKj2L4Dijx8dbvwqKsOL_2uCADhK_xzOx8/edit#gid=0

@mhdawson I missed answering in the last meeting, you asked that this sheet wasn't shared with authors for tracking.
So, the answer is "kind of Yes". Most of the time it was used for reviewers/editors to keep track. And sometimes shared on GitHub issues also. But If someone wanted to access did easily. It just wasn't streamlined.

**Comment by amiller-gh** [comment]
Next Steps: @RRomoff to chat with @bnb and @chowdhurian, generate content, and we'll PR process into the CommComm repo.

**Comment by RRomoff** [comment]
Hi All- wanted to share some additional thoughts around a "Reader Survey" and how we can use it as a tool to guide content. Check out [details here](https://docs.google.com/document/d/1GOp7B_PMkMwX2McEPu2mvILs_Pd4pfg887SvPchBpOg/edit?usp=sharing) and please add in comments / feedback.

**Comment by amiller-gh** [comment]
@WaleedAshraf, can we PR this process in to the CommComm repo if it isn't already so we can close this ticket? 🙂

**Comment by WaleedAshraf** [comment]
Sure, I can take this on. 👍 
cc @RRomoff

**Comment by WaleedAshraf** [comment]
@RRomoff lets open a new issue for "Reader Survey" to track and discuss? and close this one once https://github.com/nodejs/nodejs-collection/pull/37 is merged.

**Comment by bnb** [comment]
Removing cc-agenda in favor of the actual PR.

**Comment by bnb** [comment]
Closing this since next steps have been taken.
