### ISSUE TITLE
Node.js Social Media Community Collaboration

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/community-committee#444]
For discussion in in Comm Comm meeting, 1/24

Ref: [Node.js.Social.Media.Community.Collaboration.pdf](https://github.com/nodejs/community-committee/files/2792502/Node.js.Social.Media.Community.Collaboration.pdf)

**Comment by bnb** [comment]
Reference for a possible tool we could use on the project side: https://github.com/gr2m/twitter-together

**Comment by WaleedAshraf** [comment]
Linked issue: https://github.com/nodejs/community-committee/issues/411

**Comment by RRomoff** [comment]
Including the blog here for feedback. Please add comments :) - https://docs.google.com/document/d/1awhvSAPSPAKuwlMnpgpm8CjxjbWVl71Um4gPRh5CE9o/edit?usp=sharing

**Comment by RRomoff** [comment]
Hello all! Big thanks to @bnb for going through the blog with me and providing some really valuable feedback! Tierney is good with it as it stands. I've gone through and updated the doc based on feedback received. The only thing that's outstanding from our conversation is a title. I've proposed two options, but suggestions are welcome. When you have a moment, please feel free to review and add comments for discussion during the next CommComm.
https://docs.google.com/document/d/1awhvSAPSPAKuwlMnpgpm8CjxjbWVl71Um4gPRh5CE9o/edit?usp=sharing

**Comment by mhdawson** [comment]
Looks good to me :)

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
