### ISSUE TITLE
Discuss Collab Summit Progress

### ISSUE THREAD

**Issue by ladyleet** [nodejs/community-committee#448]
This is to discuss collab summit progress at the next comm comm!

**Comment by ladyleet** [comment]
@chowdhurian

**Comment by joesepi** [comment]
I dont believe there have been Code+Learns at the last couple JSConf EU events. I assume there wont be one this year. Is that true? Thanks.

**Comment by keywordnew** [comment]
There are no plans for a Code+Learn so far. That would be rad to have though! Once a year seems too few ;-)

A Code+Learn this year would have extra complexity with the inclusion of projects from the JSF. If people have the bandwidth, it could be a signature event.

**Comment by mhdawson** [comment]
I will say that with the Collab summit and JSConfEU there is a lot packed into that week already which we should also consider with respect to a Code+Learn.

**Comment by keywordnew** [comment]
Closing for now as the Summit has passed. Please feel free to reopen if needed at any time!
