### ISSUE TITLE
Expanding the Node.js Collection: Reviewers

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#45]
Per a discussion with @ZibbyKeaton (also including @hackygolucky and @williamkapke) in the Node.js Foundation Marketing Committee meeting earlier today, I'd like to ask about getting more involvement around the Community Committee having involvement as technical editors for the [Node.js Collection](https://medium.com/the-node-js-collection).

Previously, this task has entirely fallen on the shoulders of @nodejs/evangelism - I'd love to see if the two groups could collaborate and share this responsibility to improve the flow and get a deeper level of technical and community-centric editing into the process.

Another topic of discussion around this is one that @williamkapke raised that flows into this discussion well: having a more open medium (no pun intended) for reviewers to collaborate on this process. I'd love to discuss this more and see how we can see this evolve into a streamlined way to get articles reviewed, approved, and published with a second iteration of the review process.

For what it's worth, here's some links to issues for background context on the Node.js Collection:

- The [initial issue](https://github.com/nodejs/evangelism/issues/278), created by @ZibbyKeaton, proposing the Node.js Collection to the Evangelism WG and detailing guidelines and structure. 
  - This could/should be moved into a doc for easier access/linking/reference - good low-barrier contribution to this 😊 
- An example of one of the [weekly threads](https://github.com/nodejs/evangelism/issues/289) that Zibby creates in the Evangelism WG for submissions to review
- The Node.js Collection [Announcement Post](https://medium.com/the-node-js-collection/introducing-the-node-js-collection-4d0d60e72a64)

**Comment by SarahKConway** [comment]
Thanks for raising this issue. FYI, here are the people on the current review board: Zibby Keaton, Sarah Conway, Tracy Hinds, Mikeal Rogers, Tierney Coren, Ross Kukulinski (with the potential to expand in the future). 

Is there anyone who wants to be dropped? 

We'd welcome more reviewers, especially someone to help vet technical facts and details.

**Comment by rosskukulinski** [comment]
Hi @SarahKConway I really haven't been pulling my weight on the review board and I don't see myself freeing up for active involvement within the node community over the next few months.  As such, it probably makes sense to drop me from the review board.

**Comment by nebrius** [comment]
Following up, is there anything that we need to discuss in the next CommComm meeting on this issue? Or can we remove the `cc-agenda` label?

**Comment by ZibbyKeaton** [comment]
Ideally, it would be great to have a few technical reviewer for these posts. What is tending to happen is we have a very ad hoc review process for the technical elements. It would be nice to get a few technical reviewers here that would need to sign off on these posts when they go up. Happy to discuss it during the community committee call.

**Comment by SarahKConway** [comment]
@ZibbyKeaton and I are working on updating our process guidelines and building in at least one technical reviewer as a requirement before any article is posted to the Node.js Collection.  Having a few technical reviewers would be even better :).

**Comment by nebrius** [comment]
I added you both as observer's to the meeting list at https://github.com/nodejs/community-committee/issues/62 @ZibbyKeaton and @SarahKConway. If you're free, we'd love to have you join in for a bit to chat about this. I have a couple of thoughts on how we can connect you with technical reviewers, and I'm sure others do too.

**Comment by nebrius** [comment]
I created a repo for organizing at https://github.com/nodejs/nodejs-collection and create the @nodejs/nodejs-collection team. I added @ZibbyKeaton and @bnb to the team, but it looks like @SarahKConway is not currently a member of the nodejs org, so I cannot add you myself.

@mhdawson IIRC you have permissions to add people to the org, correct? Can you add @SarahKConway so we can add her to this team?

**Comment by nebrius** [comment]
I'm going to remove the `cc-agenda` and `cc-review` labels from this issue since we discussed it last meeting and have a path forward.

**Comment by nebrius** [comment]
Thinking about this some more, we've created the team and repo for reviewers, so the next step is to work on recruiting reviewers in that repo. As such I'm going to go ahead and close this issue.
