### ISSUE TITLE
Please add Ilyes (@celyes) and Ahmed (@Aissaoui-ahmed) as meeting observers

### ISSUE THREAD

**Issue by celyes** [nodejs/community-committee#451]
Please add me and @Aissaoui-Ahmed as observers on the community-committee's meetings.
We're really excited to jump in! 🙌

**Comment by codeekage** [comment]
See https://github.com/nodejs/community-committee/issues/450#issuecomment-463086932

**Comment by jakeNiemiec** [comment]
Is there still a path to membership? Is CC a closed group now?

**Comment by keywordnew** [comment]
@codeekage's comment earlier links to the steps you can take to get notified when the meetings are happening. You don't have to attend the meetings to participate, but attending a meeting is a good way to get context. You'll also see notifications when discussions happen, and you're welcome to participate (by commenting, etc). Exploring and keeping up with the activities in this repo are a good way to find a space when you may enjoy contributing to with code or any other way! Stoked to have you on board, @celyes!

**Comment by jakeNiemiec** [comment]
@keywordnew But what about membership like @adarshsaraogi asked? Is it still 3 months as an observer?

**Comment by codeekage** [comment]
The observer to membership track has been removed from our charter. Membership can be gain through active participation, collaboration and participation. See here: https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md 

You can also start off from being a mentee on the Node.js Mentorship Programme to help provide guidance to membership and bettter understanding of the project. https://github.com/nodejs/mentorship
