### ISSUE TITLE
Strategic Initiative for Broader Node.js Community 

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#453]
# Node.js Current – LTS Summit
**Champion**
* @codeekage

## Introduction

This initiative is aimed at outreaching to the broader community and leveraging existing Experienced Node.js Developer to help move Node.js Current Release to Long Term Support (LTS), and graduate participants to Node.js Contributors/Collaborators. 

This initiative is Experienced Developers focused but creates room for Intermediate and Newbies to gain knowledgeable experience of Open Source and Node.js. 

This initiative is aimed to be fostered by Node.js CommComm through the Node.js Outreach Initiative. This initiative is also aimed at Node.js Developers in metro-location not fully opportune to be part of the broader Node.js Community. 

The initiative will also aid the launch of Node.js Experienced/(Expert) Developers Programme (NErD) and Node.js User Group (NUG) fostered by the CommComm through the Node.js User Feedback Initiative. The initiative is also adopted from Node.js User Feedback Meetups. This initiative is designed with Africa as its case study. 

#### Section 1.0
The Node.js Current – LTS Summit is to be an annual event matching the existing Node.js Release Calendar or can be improved to suit event timing around the world. The aim and objective of this event are to improve the inclusion of Node.js developers towards achieving a more a better and stronger Node.js project and ecosystem. Where everyone feels the need to be a contributor or collaborator, investing directly into the project be it code, documentation or community contribution; by bringing developers from diverse location to hack, build, debug and improve the Node project. 

**The benefit of this programme/event are as follows:**
-    A more broad and inclusive community 
-    More ideas and opinions on improving Node.js 
-    Reduces issue of Working Groups being understaffed 
-    Increases sense of responsibility
-    Closes multiple Node.js issues 
-    Etc.

**The Node.js Current – LTS Summit will feature the following events:**
-    Educating Developers on Node.js Standard for Collaboration 
-    Hacking Node.js Current Release 
-    Debugging Node.js Current Release 
-    Fixing Security Vulnerability in Node.js Current Release 
-    Submitting PRs for `help-wanted` and `good-first-issue` labels 
-    Creating Ticket for Node.js WGs
-    Pairing with Intermediate Developers to Submit PRs
-    Collaborating with Node.js Veterans and Node.js Collaborators/Contributors 

This event is sighted to be a one-week event; due to its numerous activities covered. This enables us to achieve the goal of graduating these Developers to Contributors/Collaborators. 

##### Participation 
From a community point of view: people find it difficult to join working groups or build the courage to make contributions even after conferences and meetups, this is usually caused by them being overwhelmed with/by the project. 

This event being experienced developers focused increases chances of developers being contributors at the end the of the event; whereby developers are attending to make contributions to the node project while being guided by existing node collaborators or contributors from various working groups. This also gives the opportunity to beginner developers to learn how open source codebase and collaboration works. This event being contributions focused [No Much Talks, All Codes]; improves participation of the broader community. Taking Node.js to the community and bringing the community to Node.js.
 
##### Participant Rules 
Rules towards how contribution will be made will be adopted from the existing CONTRIBUTORS_GUIDE in the TSC and WGs respectively. Rules will be enforced by Node.js TSC/CommComm WGs representative either WG champions or contributor volunteer(remotely/in-person), by providing guidance towards the contributions/contributors’ models and where help is most needed within the WG or project. 
Developers (Attendees/Participants) are to break and rebuild Node.js towards achieving Long Term Support for a particular release. Developers (Attendees/Participants) are also allowed to submit a proposal for a new release. 
##### Participants Rating
-    Experienced Developers (3 – 4 years)
-    Intermediate Developers (2 – 3 years)
-    Beginner Developers (1 – 2 years)
-    Newbie (0 – 6 months)
##### Ownership
The event is originally designed for Africa (Node in Africa) but be best adopted by the Node.js Project as it fits the current model of Outreach and User Feedback Meetups. Ownership can be completely transferred to the Node.js Project and improved for the entire Node.js Community. Making this event a standard event for Africans and Developers globally to convene annually in any African country.

**Node.js Current – LTS Summit can be owned:**
-    solely by Node.js Foundation/Org. 
-    independently but leverages Node.js resources to raise funds for the event
-    completely independent and Node.js Org as a SuperMax Platinum Sponsor 
-    completely independent and Node.js Org as Partner Community (similar to leveraging resources)
-    completely independent 
##### Node.js Experienced/(Expert) Developers (NErD) Programme 
Places a Higher-Order-Model, where existing Experienced Node.js Developers are empowered as champions to Create, Build, and Foster Node.js User Groups in their various locations. Granting them access to collaborator/contributor privileges (e.g. Travel Fund Reimbursement) and public listing of their names in a GitHub repo or web-page as benefits for taking up the mantle of a champion in their locations. 
This position of a champion can ONLY be attained by attending a Node.js Current – LTS Summit; as the education of duties will be shared and taught at the event. 
This position is restricted to Non-Node.js Collaborators; as this initiative is to encourage and empower the broader community to creating, building and fostering Node.js User Groups in their location. Also, bearing in mind that Node.js does NOT restrict anyone from hosting or organizing meet-ups or conference in their location.
This User Group is only preferably recognised by Node.js as they help with the survey, reports on bug and issues locally via relating issues, bugs, etc to the Node.js User Feedback Team through these champions.
##### How to attend 
The position is restricted to only participants of the event. Travel scholarship will be provided to enable developers across Africa to attend the event. Ways to win this scholarship is still TBD. The location will be constantly rotated across different Africa nations to also enable everyone to has the feel of the event.
##### Moving forward 
Every decision on implementation will be discussed and agreed upon before moving forward by the CommComm and most foundation folks interested in working on this project.

**Comment by Tiriel** [comment]
Hey!
As I'm getting back on track with everything I missed these last few months, I hope I'm not overstepping or intruding.

This looks impressive. There is evidently a lot of work in this document and this is awesome.
I have a few questions though if it's okay.

First, just to be sure: is this a document for putting together an Initiative/Working Group, a Summit, or an Initiative/WG tasked with the organization of a Summit? Reading the whole doc I'd say the latter, but I preferred to ask.

Secondly, Is this something you're launching right now or has it been discussed already in meetings? This is just out of curiosity, as I said above I'm trying to catch up and I'm worried I missed such an important topic.

Lastly, I'm not sure I understand the references to the Outreach Initiative since it hasn't officially been launched to my knowledge. That was what I was planning to work on in the next weeks/month though, so that's perfect if you actually want to couple these two tasks and work together on actually launching Outreach! (as is anyone else, actually)

Anyway as said, I don't want to step on anyone's toes and I hope these are not already answered questions. And if I'd love to help if there's anything I can do!

Cheers!

**Comment by codeekage** [comment]
Thank you very much for raising some reasonable concern around this draft. This helps everyone understand this better. 

> First, just to be sure: is this a document for putting together an Initiative/Working Group, a Summit, or an Initiative/WG tasked with the organization of a Summit? Reading the whole doc I'd say the latter, but I preferred to ask.

This is an initiative for a broader community designed as an event (Summit) to bring folks together. It’s an initiative with the responsibility of organising a Summit. 

> Secondly, Is this something you're launching right now or has it been discussed already in meetings? This is just out of curiosity, as I said above I'm trying to catch up and I'm worried I missed such an important topic.

This something I hope we launch together and discussion around it are yet to be made. 

> Lastly, I'm not sure I understand the references to the Outreach Initiative since it hasn't officially been launched to my knowledge. That was what I was planning to work on in the next weeks/month though, so that's perfect if you actually want to couple these two tasks and work together on actually launching Outreach! (as is anyone else, actually)

Context around what outreach is in this draft was referenced from here: https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#outreach

Hoping to see implementation soon. And I’m really happy to work anyone interested to fire this up.

**Comment by MylesBorins** [comment]
@codeekage it appears that the goal of this initiative is to get more contributors / collaborators... but I'm having a bit of a hard time seeing how it is related to release + lts. If something were to be titled an LTS summit, I would have the impression that it was a summit for the LTS or Release team to meet and work on it.

Is it safe to assume you want to tie this to the timing of a release becoming LTS? Trying to get people to do some work to help stabilize a release before it goes LTS? There might be a better name for this to avoid confusion.

There is a lot to take in with this proposal and I think it might benefit from a summary at the top identifying:

* who will be doing the work
* who will it be targetting
* when will it happen
* what will success look like

It may even be beneficial to follow the template for our foundation proposals, especially if this is to be a foundation initative

https://github.com/nodejs/bootstrap/blob/master/proposals/TEMPLATE.md

**Comment by codeekage** [comment]
Thanks @MylesBorins. 

> Is it safe to assume you want to tie this to the timing of a release becoming LTS? Trying to get people to do some work to help stabilize a release before it goes LTS? There might be a better name for this to avoid confusion.

Your assumptions are completely in line with the focus of the initiative. 

However, of cos it makes sense to have the release team on ground during the event. 

The document also highlighted having members from the Working Groups (Release) on ground during the event. 

The WG knows the hiccups more and understand where help is most needed and where should be the focus point of participants to move a current release to LTS. 

The name is also open to change as we work through decisions as a team. 

Will move forward with foundation proposal template in a new issue; now this is in discussions. 

Thank you @MylesBorins

**Comment by codeekage** [comment]
Closing with  #458
