### ISSUE TITLE
Please add me (@Aissaoui-ahmed) as a member in website team

### ISSUE THREAD

**Issue by Aissaoui-Ahmed** [nodejs/community-committee#454]
Please add me as a member in website team
My github profile : @Aissaoui-Ahmed 
I'm really excited to join you 💯 
thank you all 
@Interstellar @celyes

**Comment by celyes** [comment]
@MylesBorins please, would you review this issue?
@Aissaoui-Ahmed See here: https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md for details.

**Comment by MylesBorins** [comment]
/cc @fhemberger

@Aissaoui-Ahmed have you contributed at all to any of the repos within the website team?

**Comment by fhemberger** [comment]
@MylesBorins Yes, he is providing Arabic translations for the site:

https://github.com/nodejs/nodejs.org/commits?author=Aissaoui-Ahmed

**Comment by codeekage** [comment]
I think this issues for membership for website team should be opened in the website-redesign team. 

This the CommComm and membership process are  stated in the charter in the CONTRIBUTOR.md. 

Open this in https://github.com/nodejs/website-redesign I’m will be happy to follow up with the process to seeing added. 

Cheers 🥂

**Comment by codeekage** [comment]
@fhemberger do you mean adding him to the Org?

**Comment by fhemberger** [comment]
@codeekage It's for the current website, not the redesign. This will be handled differently in the future.

**Comment by codeekage** [comment]
How do you mean? 🤔. Maintenance will also be done by the team. However, adding him to the org is a completely separate issue which can still be done from website-redesign champion @admiller-gh

**Comment by amiller-gh** [comment]
The current website's repo is over at nodejs/nodejs.org and operates mostly independently of the website-redesign group 🙂 I'm pretty sure this issue was just opened in the wrong space and/or was in need of a repo to live in. @fhemberger, @MylesBorins, you have this one?

**Comment by MylesBorins** [comment]
invited. Closing this issue but we can try and document a better process... I think just open an issue on the nodejs.org website imho

**Comment by fhemberger** [comment]
@MylesBorins Thanks!

Changes to the process are already discussed [here](https://github.com/nodejs/admin/issues/282#issuecomment-449321745).

**Comment by Aissaoui-Ahmed** [comment]
Thank you so much @MylesBorins and @fhemberger 
I'm so excited to join you!
