### ISSUE TITLE
Member resignation

### ISSUE THREAD

**Issue by JemBijoux** [nodejs/community-committee#456]
Hello friends! I just wanted to open an issue to get this started. I've been thinking about this a lot, and it's probably better if I resign from the CommComm for now. This isn't the last you'll see of me, but I also have this huge imposter syndrome around remaining a voting member when my own activity is mostly limited to taking meeting notes. My job requirements recently have made showing up to some of these morning (PST) meetings more difficult as well, so I haven't always even been doing that.

> Members who do not participate consistently at the level of a majority of the other members are expected to resign.

I would love to stick around and show up to some meetings sometimes as an observer still. There are tons of opportunities to participate, I just don't think I've personally made enough time for node lately to meet the high standard that all of y'all set. I wanted to be honest about where I'm at. Thank you for understanding. ❤️

**Comment by keywordnew** [comment]
I just want state my respect for the level of self-awareness about your personal bandwidth @JemBijoux. Your work and time, as with members of this project, is valuable and appreciated! And past this point, that effort will continue to be as valuable as it ever was. 💛

**Comment by mhdawson** [comment]
@JemBijoux thanks for your work to date!  Whatever level you can participate at is appreciated and since we are all volunteers, its understood that it will change based on our other demands.

**Comment by amiller-gh** [comment]
@JemBijoux you are, and always will be, an immensely valued member of the project! Please do come as an observer when you can – we’ll miss you.
