### ISSUE TITLE
Node.js Broder Community closes issue:#453

### ISSUE THREAD

**Issue by codeekage** [nodejs/community-committee#458]
# Node.js Current - LTS
>  Stage 0

> Below is simply a suggested template for drafting a proposal, it will not fit all potential proposals.
## Champion
Abraham Jr. Agiri @codeekage

> Who is the stakeholder of this initiative?
-	
## Description
> A rough description of the program idea or policy

This initiative is aimed at outreaching to the broader community and leveraging existing Experienced Node.js Developer to help move Node.js Current Release to Long Term Support (LTS), and graduate participants to Node.js Contributors/Collaborators. 

This initiative is Experienced Developers focused but creates room for Intermediate and Newbies to gain knowledgeable experience of Open Source and Node.js. 

This initiative is aimed to be fostered by Node.js CommComm through the Node.js Outreach Initiative. This initiative is also aimed at Node.js Developers in metro-location not fully opportune to be part of the broader Node.js Community. 

## Required Resources
> What resources would be needed to execute it?
-	Iterated amount of discussions
-	A reasonable amount of funding and teamwork

## Who would be responsible? 
> Which committee would be overseeing or responsible for executing this proposal?
-	CommComm
-	Outreach Initiative 
## How would success be measured? 

> Please include potential metrics that can be used to measure the success of the proposal. 

This event being experienced developers focused increases chances of developers being contributors at the end the of the event; whereby developers are attending to make contributions to the node project while being guided by existing Node collaborators or contributors from various working groups. 

This also gives an opportunity to beginner developers to learn about Open Source codebase and collaborative work. Being contributions focused [No Much Talks, All Codes]; improves participation of the broader community taking Node.js to the community and bringing the community to Node.js. 

## Why this proposal is important?
> Why should we do this?

From a community point of view: people find it difficult to join working groups or build the courage to make contributions even after conferences and meetups, this is usually caused by them being overwhelmed with/by the project. 

The aim and objective of this event are to improve the inclusion of Node.js developers towards achieving a better and stronger Node.js project and ecosystem. Where everyone feels the need to be a contributor or collaborator; investing directly into the project be it code, documentation or community contribution; by bringing developers from diverse location to hack, build, debug and improve the Node project. The benefit of this programme/event are as follows:
-   A more broad and inclusive community 
-	More ideas and opinions on improving Node.js 
-	Reduces issue of Working Groups being understaffed 
-	Increases sense of responsibility
-	Closes multiple Node.js issues 
-	Etc.

## Unresolved Questions
> Current objections or concerns that will be required to reach stage 2
-	Will this project incur too many expenses?
-	CommComm approvals this proposal
-	CommComm presents the proposal to TCS and Foundation 
-	TCS and involved working group (Release, Build, and etc.) approvals 

## What is necessary to complete this proposal?
> Everything required to reach stage 3
-	Foundation approval 
-	Choose event date
-	Set up team willing to plan the event

**Comment by amiller-gh** [comment]
I am not convinced this needs to be have Foundation approval or funding really – I really think this single event proposal is best wrapped up in to a larger nodejs/outreach initiative reboot 🙂 I'd love to see the CommComm start to provide more concrete resources for local community development. Check out my comment here and see if you think there is a chance for synergy there: https://github.com/nodejs/outreach/issues/4#issuecomment-475279923

(side bar: oh god did I really just use the word "synergy" un-ironically in a sentence?!)

**Comment by amiller-gh** [comment]
Going to close this issue in leu of the work being done in @nodejs/outreach 🙏 I hope we can use that strategic initiative to accomplish exactly this – provide resources, information and discovery assistance for local leaders! Let's move work on this to the [soon-to-be-regular Tuesday meetings](https://github.com/nodejs/outreach/issues/6).
