### ISSUE TITLE
CommComm Member resignation

### ISSUE THREAD

**Issue by Tiriel** [nodejs/community-committee#465]
Hey everyone,

Sorry to drop this like that, but due to a long string of unfortunate and persisting events affecting my personal life, I don't know that I'll be able to invest myself as much as I want to, and the community deserves better. I already waited too long to take this decision, hoping to get more bandwidth. But I have to admit I don't see this time coming for the next few months, so this is the time for me to step down and resign.

I'd like to think that I'll be able to come back in some times though, so I'll keep following things from not too far, and participating as much as I can.

Anyway, thank you all for the being who you are and helping others as you do. Keep outreach alive now it's finally kicking!

**Comment by amiller-gh** [comment]
So sad to hear that Ben, we'll miss you! Thank you for everything you've put in – I do hope that things settle down for you soon, and that we'll still see you around as a contributor when you have the cycles ❤️

**Comment by ahmadawais** [comment]
Sad to see you leave Ben, thanks for all your work.
 — @maedahbatool and I are hoping to not only keep `nodejs/outreach` alive but make it better and more inclusive than ever. I hope you return back soon.
