### ISSUE TITLE
Engaging the community for new conference

### ISSUE THREAD

**Issue by zackarychapple** [nodejs/community-committee#468]
Hello everyone!

I wanted to open an issue real quick to see how to go about engaging more with the community via the Node Atlanta conference. We are a good ways along now and between conversations with @ladyleet and @mhdawson I thought it might be a good time to reach out to the community in an official capacity.  

So far our speaker lineup is looking amazing and includes @addaleax, @joyeecheung, @MylesBorins, @ladyleet, and @jasnell. 

Diversity and inclusion are incredibly important to us as a conference, currently 72% of our Node Atlanta lineup identifies as individuals from communities under-represented in tech. 

We could really use some pointers, advice, and/or assistance around a couple of things: 

1) Amplifying our reach on social media
1) Putting together a panel discussion on application security
1) Finding presenters for full day workshops (this operates on 
1) Possibly sharing a blog post that we talk about the conference 

I apologize in advance if this is not the correct place to be asking these questions.

**Comment by mhdawson** [comment]
@nodejs/security-wg lets talk about the request for a panel. Created https://github.com/nodejs/security-wg/issues/515 to discuss.

**Comment by mhdawson** [comment]
@zackarychapple I think you might have missed some text after  (this operates on....

**Comment by zackarychapple** [comment]
Awesome, thank you @mhdawson

**Comment by amiller-gh** [comment]
@mhdawson, any progress to report here from the Security working group here? Should we close this and track in https://github.com/nodejs/security-wg/issues/515 instead?

**Comment by zackarychapple** [comment]
@obensource here is the issue we talked about.

**Comment by mhdawson** [comment]
I think tracking the discussion on the panel can be tracked in  nodejs/security-wg#515 instead.

**Comment by zackarychapple** [comment]
Closing in favor of [nodejs/security-wg#515](https://github.com/nodejs/security-wg/issues/515)
