### ISSUE TITLE
Documentation surrounding movement to/from TSC <> CC

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#47]
With regard to https://github.com/nodejs/community-committee/issues/46, I'm wondering if there is any existing documentation for criteria or process around transitioning a WG/Team/Other from the TSC into the CC (and the reverse).

If there's not already existing documentation, I'd like to propose creating it and getting feedback on the exact steps that need to go into it. Happy to write this documentation myself, but there's a lot of context that I know I don't have (particularly on the TSC and Governance side of things) that several CC members _do_ have that I think is probably very important for this process.

**Comment by nebrius** [comment]
FWIW we have kinda sorta have part of this documented at https://github.com/nodejs/TSC/issues/218. The Inclusivity WG has been dechartered by the TSC, and will one day be rechartered by CommComm. Now normally the charter would transfer directly, and the WG won't go through a restructure at the same time like we're doing with the Inclusivity WG, so a number of those steps wouldn't apply.

**Comment by hackygolucky** [comment]
I think this is a great one to bring up in meeting today, if we have time.

**Comment by nebrius** [comment]
Agenda updated, thanks @hackygolucky!

**Comment by nebrius** [comment]
Pull request for this issue has been opened at https://github.com/nodejs/community-committee/pull/59 and discussion is happening in the PR, so I'm removing the `cc-agenda` and `cc-review` labels here.

**Comment by nebrius** [comment]
PR has been merged, closing!
