### ISSUE TITLE
CPC Representative Nominations

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/community-committee#470]
Hey @nodejs/community-committee!

We've agreed on the approach for electing the CPC representatives for Node.js in https://github.com/nodejs/admin/issues/316 – in CommComm we will use a process similar to our existing director nomination process to elect 1 CPC voting representative. Our "target" date for rep announcement is May 1 as per https://github.com/openjs-foundation/bootstrap/issues/115.

I'll be conducting the election process on the following timeline:

April 17: Call for nominations for CPC Representative
April 22: Nominations closed and Candidate Statements / Q&A open in issues on GitHub
April 26: Close Q/A, open balloting.
April 30: Announce CPC Representative

Please fill out the following form to nominate a candidate: https://forms.gle/4jcR19wgY5AXJ1aB7

Notes on nominations:
 - I will not share who nominated a particular candidate,
 - nominees should be picked from the pool active collaborators within the project, who are deeply involved with CommComm work,
 - all nominated candidates will privately be asked to accept their their nomination before announcing,
 - once a nomination is accepted, I will collect candidate statements to share in dedicated Q/A issues on the 22nd,
 - nominations made by non-CommComm members will also need to be seconded by a member,
 - self nominations are allowed and encouraged!

Please review [the expectations for voting CPC representatives](https://github.com/openjs-foundation/bootstrap/blob/master/proposals/stage-2/CPC_CHARTER/CPC-CHARTER.md#voting-members) before submitting a nomination.  

And please remember: participation in the CPC is not limited to voting members! Other Node.js org collaborators can freely participate as regular members in the CPC.

Here we go 🎉

**Comment by amiller-gh** [comment]
As a related task, we also need a PR to update our governance to reflect the election of a CPC member instead of a Board representative, but like the TSC, I believe we can do that in parallel.

**Comment by mhdawson** [comment]
Discussion in last CommComm meeting is that for this time to be consistent with the process for Director representative, nominees are limited to members of the CommComm.

**Comment by amiller-gh** [comment]
Good morning and happy Tuesday everyone! Polls have closed and I’m happy to announce that @joesepi has been elected as our new CPC Voting Representative 🎉

We will close this issue when our README has been updated to reflect the results of the election. Please remember, the CPC is open for all member project collaborators to participate it, so everyone please keep engaging with the Foundation at https://github.com/openjs-foundation 🙂

 https://civs.cs.cornell.edu/cgi-bin/results.pl?id=E_009ceb7f8a393a46
