### ISSUE TITLE
Resolve discrepancy in PR holding period

### ISSUE THREAD

**Issue by keywordnew** [nodejs/community-committee#474]
We have 3 files where we've specified the time a Pull Request should stay open for review before an action is taken. They are all somewhat different.

In governance/README.md:
> After 72 hours, if there are two or more LGTMs from other CommComm members and no explicit opposition from other CommComm members, then the proposal is approved.

In governance/ONBOARDING.md, under "Landing PRs":
> Leave at least 48 hours during the week and 72 hours over weekends to account for international time differences and work schedules.

In CONTRIBUTING.md, under "Contributions":
> ...pull requests should sit for at least 36 hours to ensure that contributors in other timezones have time to review. 

I think we should make the guidelines clearer.

48 hours during the week and 72 hours over weekends is balanced, but exceptions add complexity. My choice would be 72 hours across the board.

**Comment by mhdawson** [comment]
+1 to 72 hours, I think for much of what we land there is no rush.

**Comment by amiller-gh** [comment]
Agreed – 72 hours seems to work the best for this group.

**Comment by codeekage** [comment]
I also agree to 72hours
