### ISSUE TITLE
Who Uses Node.js

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#475]
In the website redesign meeting, the issue of being able to include a few companies logos on the new website was raised.

After a brief bit of discussion, it seems like this could be a larger project than what the Website Redesign should be taking on.

I'd like to propose a new repo or initiative managed by the Community Committee around this, as I think there's a lot of potential value for Node.js and end-users from having a dedicated resource to this. I'd be happy to help drive this work.

Suggested MVP:
- `users` Repo (or some similarly simple name)
- have a template for people to add their companies
 - name, size
 - possibly also Node.js jobs link?
 - no specific corporate information (how long they've been using node, what they use it for, etc)
 - low barrier to entry
- have a process that allows them to give us permission to use their logo
 - could work with the Foundation on this

**Comment by WaleedAshraf** [comment]
Looks good 👍 
Is it just for companies or can we list individuals also?

**Comment by keywordnew** [comment]
Defining the value of listing logos would help answer the question of whether or not to list individuals :)

**Comment by bnb** [comment]
I'd suggest that if we want to have a list of individuals that could/should be a seperate list.

I'd personally be -1 on it based off of what npm has asserted: there are 11 million users of npm... which also means there are that many users of Node.js. At that scale, it becomes unmanageable and not useful.

**Comment by Bamieh** [comment]
Thanks for writing this @bnb. I have a few ideas to share about this

Given the HUGE amount of companies using Node.js I can imagine two cases happening for the the `users` repo:
1. It will become unmanageable: It will take a huge effort to review and merge let's say 5k PRs over the course of several months.
2. It will gain very little traction or will be only used by a certain niches of companies which might reflect badly on Node.js as it will convey a different message from reality.

This is my opinion so please feel free to oppose it: I have had always gotten the feeling that small companies need a "who is using us" section to help their projects gain traction. I dont feel this is the case for Node.js as it is being used by almost every company out there. Putting a few logos on the will serve us unjust.

A simple google search will show millions of results for companies (from Huge corporates to 2 person startups) sharing their detailed experiences using Node.js.

**Comment by amiller-gh** [comment]
Related thread: https://github.com/nodejs/community-committee/issues/184

**Comment by amiller-gh** [comment]
Also related: https://nodejs.org/en/user-survey-report/

**Comment by Tera99** [comment]
This list could be helpful for people trying to decide if they should spend time learning Node.js (as opposed to something else). It might also be useful to add schools and universities that use Node.js in their curriculum.

**Comment by bnb** [comment]
I still think this is valuable, but have seen no traction from CommComm members, collaborators, or external folks. I'll leave this open for a few more days, but will then close it.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
