### ISSUE TITLE
Node.js Thank you program

### ISSUE THREAD

**Issue by mhdawson** [nodejs/community-committee#482]
As part of the social media program there was some discussion on giving out gift certificates for the Node.js store.

I think a program that applied across all of the Node.js programs would make sense. @Trott already spreads some thanks but it would be great to regularly give out something more tangible as well.

**Comment by 07Gond** [comment]
Hello!
I just saw that some open source repositories send a gift card for the stores on the first contribution to the repo.
Maybe it can be done too on the Node.js side, only thinking on code contribution.

**Comment by keywordnew** [comment]
Would be helpful if anyone who has seen open source projects implement similar initiatives drops links to those through an issue comment here.

It would be great to see models of how this could work well!

**Comment by lizparody** [comment]
I was wondering, the gift certificates will be for whom? Contributors, collaborators? 
How will this work?

**Comment by 07Gond** [comment]
This is a great example from Gatsby:/
https://www.gatsbyjs.org/contributing/where-to-participate/
https://www.gatsbyjs.org/contributing/contributor-swag/

**Comment by sendilkumarn** [comment]
For many, a handwritten note saying "thank you" will be the most prized "Thank You". ❤️

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
