### ISSUE TITLE
Nodejs not building for ARM9 in yocto

### ISSUE THREAD

**Issue by ramgopikrishna** [nodejs/community-committee#485]
We tried building version 7.10 in yocto build. It says your CPU ARM architecture is not supported.
Our ARM architecture is ARM9(ARM926EJ), so whether nodejs supporting ARM9, if so please let us know the proper vesrion which can help us and also do we need to have any minmum requirements of RAM(Ex:256MB RAM) in device to build node-red or any other modules through npm which is part of nodejs.

**Comment by WaleedAshraf** [comment]
Hi @ramgopikrishna
I'd suggest you post your question in [Build repo](https://github.com/nodejs/build) which is specific for build working group. You'll probably get a quick answer there.

**Comment by WaleedAshraf** [comment]
closing in favor of https://github.com/nodejs/build/issues/1809
