### ISSUE TITLE
Node.js LinkedIn

### ISSUE THREAD

**Issue by ZibbyKeaton** [nodejs/community-committee#486]

**Comment by ZibbyKeaton** [comment]
Hey - I am still the admin on the Node.js LinkedIn account. I generally accept everyone unless they are a recruiter. Unsure if someone else would like to be the admin here or not but I wanted to flag to the group in case there was an issue with this.

**Comment by mhdawson** [comment]
I'm good with that.  Might make sense to add some additional admins but thanks for keeping it going.

**Comment by 07Gond** [comment]
Is this related to https://github.com/nodejs/community-committee/issues/185 ?

**Comment by keywordnew** [comment]
Having multiple admins sure does improve reliability and continuity.

My proposal would be to have one person at the OpenJS Foundation and one person from the CommComm as supplementary admins, for a total of two more in [group manager roles](https://www.linkedin.com/help/linkedin/answer/2736/group-owner-and-admin-roles).

**Comment by bnb** [comment]
Perhaps making @amiller-gh the admin and removing yourself if you want to @ZibbyKeaton (you are not being paid to do this work and we genuinely appreciate your continued help despite that ❤️). Once @amiller-gh is admin we can take care of managing it from there.

**Comment by amiller-gh** [comment]
Interesting! I thought I was already a manager in the group – on second inspection it looks like I'm not. @ZibbyKeaton, feel free to add me if you'd like. TBH though I'd appreciate more help from the group, despite working at LinkedIn I'm not a power user of the product :) Happy to help, but the more hands the better.

**Comment by amiller-gh** [comment]
@ZibbyKeaton, lets also add Bryan and Rachel to the group

**Comment by amiller-gh** [comment]
Bump, @ZibbyKeaton  :)

**Comment by ZibbyKeaton** [comment]
@amiller-gh added you as manager Rachel and Brian need to join the group and then you can add them as well. There's a lot of folks who have requested to join +4,000 since I last did a scan so you will def want some help here.

**Comment by Kirill255** [comment]
@ZibbyKeaton Can you tell what that means? Thank you
![group](https://i.imgur.com/p7GdOg2.png)

**Comment by WaleedAshraf** [comment]
@Kirill255 I think it means that LinkedIn was having technical issues at that time. Try again, as it says.
It's working fine for me.

**Comment by Kirill255** [comment]
@WaleedAshraf Unfortunately, this is not the case. I think I was banned for asking to join the group :confused: Therefore, I would like to know the reason. Given that there are 4000+ requests, there are probably some (maybe 1000+) people who have been banned as well as me because for example someone had a bad mood.

![req](https://i.imgur.com/XfrmbbR.png)
