### ISSUE TITLE
Follow up - Node.js Collection and Social Media

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/community-committee#491]
We had a "Node.js Collection and Social Media" session at Collab Summit.
There are more feedback and new ideas on how we can drive it. @RRomoff and I were facilitating the session.

We'll like to have a followup with the rest of the team. This issue is just a placeholder to decide a common day/time for it.

This meeting would be open for everyone to join and share their views.

**Comment by RRomoff** [comment]
Following up with some notes from this session. Thanks to all who joined. Found it to be a very good session! 

**OpenJS Collaborator Summit
Node.js Content and Social Media Session Recap/ Debrief**

**Node.js Collection**

**General Recommendations/ Guidelines/ Comments for Consideration**
-Schedule / Assign reviewers a week/ specific time frame to review content that comes in (Set up a schedule)
-Rachel to PM, keep track of who’s the week it is.
-Use the medium platform to get submissions, review and approve
-Review time should be about one-week turnaround
-Form a small blog team/ subcommittee
-Formalize a goal (Short term and long term, posting X times per week? Gaining X followers?)

**Incentives for Editors, Contributors** 
To further incentivize community members from participating, we discussed the following options
-Badges and stickers
-Follow up with Node.js thank you issue @manil
-Gatsby thank you program

**Submitting/Reviewing**
What’s the Process? (two options)

-Someone submits and IDEA to medium@nodejs.org
-Writers are encouraged to submit a brief summary and the topic of the post to medium@nodejs.org for consideration
-Rachel kicks off the discussion with the Node.js Collection Editorial Team
-If the topic is accepted, the writer is notified by Rachel and writer will start the draft. Rachel will add to the content calendar.
-Rachel will add the person as a writer to the Node.js Collection; once the blog post is finalized, the writer will submit the full article as a DRAFT and email the editors via medium@nodejs.org.
-Rachel pings the reviewer on call. 
-Reviewer accepts or declines (life happens!) If accepts, the reviewer provides edits within a week. If unavailable, Rachel will find an alternate.
-Once the submission has been approved, it will be added to the Node.js Collection Medium publication - a publication date will be provided for proper social planning/ promo.

Someone submits a FULL DRAFT to medium@nodejs.org
-Rachel pings the reviewer on call. 
-Reviewer accepts or declines (life happens!) If accepts, the reviewer provides edits within a week. --Rachel will add to the content calendar. 
-The writer will be alerted of these edits and suggestions; the author of the post has the final sign off on content and can approve/accept all edits.
-If the author feels comfortable, the post should come with a list of those who helped edit the content.
-The review process could take up to a month depending on the number of edits and revisions involved.
-The review process and edits needed will happen on Medium with few exceptions.

**Ideas to build Contributor/ Writer List**
-Call for contributions via social media
-Promote the Node.js Collection on the project blog
-Reach out to previous writers

**Ideas to gather content/ Build the pipeline:**
-Repurpose recent conference talks ( Invite folks who gave relevant talks to submit a blog on the same topic)
-Get in touch with Write the Docs, API the Docs for technical writing, blogs.
-Focus on topics by month and conduct a “Call for Blogs” via Twitter ( Be advised that we’d need long lead time to gather enough content to fill a month)
-Reach out to others in the space to find out what topics are interesting right now (Ask from Node weekly / JS weekly)
-Reader survey

**Types of Content/Topics**
-Working Groups (in motion)
-Featured Developers/ Node.js Dev of the week/ month. (Open up for nominations)
-Diversity and Inclusion in Node.js
-Broader JavaScript coverage 
-The project of the week- folks can submit a quick post about what they are working on
-List roundups

**Ideas to get more Reviewers**
-Ask writers to review
-Call for reviewers via social
-Create a Style Guide (longer-term goal)
-Update GitHub with new guidelines (Sample Below)

**Process for Becoming a Technical Reviewer of the Node.js Collection** (EDITOR PROCESS STORED ON GITHUB)
*This would be completely new content that we can store on GitHub and share with those who are interested in becoming editors of the Node.js Collection.

ABOUT
Node.js Collection is a publication on Medium that focuses on content for Node.js users. The content can be for those who are just getting started with Node.js to those who are more advanced. You can learn more about the publication via this introduction blog.

Technical reviewers provide the following:
Approve suggested abstracts that are submitted to medium@nodejs.org.
Review and edit content drafts submitted to the Node.js Collection Medium page.

BECOME AN EDITOR
Submit your interest to the current Node.js Collection editors via medium@nodejs.org. Provide your area of expertise.
Once you are accepted, you will be added as an editor to Node.js Collection (Medium account is required). You will also be added to the alias medium@nodejs.org.

REVIEW PROCESS
Writers submit an abstract via email at medium@nodejs.org. Editors have one week to provide approval - this is done internally on the alias and not to be shared with the writer until a final decision and suggested changes are reached as a group.
If the article is approved, the writer will submit a draft on Medium and an editor or two will be assigned to review - we suggest providing feedback to the writer two to three weeks once it is submitted depending on the number of changes and recommendations.
The writer to approve all content and send a note to medium@nodejs.org once finished.
Editor/a member of the Node.js Foundation PR team to review one final time and accept into publication.

**Social Media**
*The convo was driven more by content and Node.js Collection, but here are notes regarding social media

**Questions to ask-** 
what platforms should we focus on? Which are the most important?
How can he help signal boost what’s helpful to the community? How can we identify that?
New tactics to try-
#AMANode (use this hashtag when asking a question)
Front load questions to ask via twitter- the community loves these
Have a big spreadsheet of topics/content type which is already selected by social media team / social m chair.
Careful about what topic to ask about, like not everyone has positive about feedback about streams

**Node.js Social Media**
-How can we place some safeguards for the content we share on social media about COC.
-How we drive Social Media Chair initiative.
-How to select?
-What to offer in return?
-How much time/effort they need to put in? (Is this addressed enough in the blog?)
-How to monitor the outcome of this initiative? What does success look like?
-How we can improve diversity/inclusivity in the content we publish?
-What other steps we can do to improve content quality?
-Which kind of feedback we should get from users regularly? (votes on twitter)
-Creative ideas to increase engagement on social channels (use of video, live streams, etc)
-Managing Twitter through Github? (https://github.com/gr2m/twitter-together)

**Next Steps:**
Node.js Collection:
-Approval/ Feedback on the new submission/ review process. Once approved, Rachel to post on GitHub/Update GitHub.
-Feedback on ways to build the content pipeline. Once we decide the best way to accept submissions, we can start promoting the Collection more heavily and test our process.

Social Media
-Feedback/ Approval on the Blog
-Ideas to get additional social content

**Comment by amiller-gh** [comment]
@RRomoff, @WaleedAshraf, want to ping this ticket and see where we are with collab summit follow-up! Has this been (or does it need to be) documented anywhere other than this issue?

**Comment by WaleedAshraf** [comment]
I'll document this Nodejs Collection repo. 👍 
cc @RRomoff

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
