### ISSUE TITLE
Socialize fast-closing CFP for Node+JS Interactive

### ISSUE THREAD

**Issue by keywordnew** [nodejs/community-committee#492]
The next Interactive is in Montreal, Canada on December 11th and 12th.

The CFP closes on Jun 14 2019 11:59 PM (PDT).

If you're interested, submit soon: https://linuxfoundation.smapply.io/prog/nodejs_interactive_2019/

Ref: [nodejs/admin#368](https://github.com/nodejs/admin/issues/368)

**Comment by RRomoff** [comment]
Update: This has been extended to June 21!

**Comment by WaleedAshraf** [comment]
Closing this issue as the date has passed.
