### ISSUE TITLE
Access policy to the Zoom account to start meetings needs revisiting

### ISSUE THREAD

**Issue by keywordnew** [nodejs/community-committee#494]
We've recently encountered situations where the very limited number of people with the creds to kick off Zoom meetings were unavailable due to other commitments. Let's revisit the policy that regulates this, and maybe make this available on a needs-based basis.

**Comment by amiller-gh** [comment]
Resolution: Chairs are empowered to share Youtube streaming permissions and Zoom acct. info will be sharable as well. We're going to explore a lastpass integration to better share longin info.

TODO: Document.
