### ISSUE TITLE
Removing labels in archived repos

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#505]
I generally try to share the `good first issue` label with individuals who are trying to get started in contributing to Node.js. Today, while working on a PR for nodejs/getting-started, I realized that two CommComm repos – evangelism and website-redesign – still have a dozen or so issues labeled "good first issue". These issues show up when searching for good first issues in the Node.js GitHub organization.

Since the repos are archived, apparently I can't actually remove the labels from those issues.

I'd like to un-archive the repos temporarily for the purpose of removing those labels. 

Additionally, I'd also like to request that we consider up-leveling removing the label from any issues labeled "good first issue" prior to archiving as a soft policy in nodejs/admin to allow others to do this work in the future (even if the repos are already archived).

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
Completed last week 👍

**Comment by darcyclarke** [comment]
@bnb is this something that could be automated in any way in the future? (ex. a Probot integration to clean up labels when an issue is closed)

**Comment by yourwpmadesimple** [comment]
Hi! I am new to node.js. But want to get involved. What can I do to contribute? Thank you!

**Comment by keywordnew** [comment]
@yourwpmadesimple this issue has already been closed, I think all the work here is complete. I'd suggest watching other [open issues](https://github.com/nodejs/community-committee/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and volunteering to take on a task when it becomes available and you'd like to give it a go! 👍🏽
