### ISSUE TITLE
Towards less conflicts from biases/assumptions in communication styles/conventions

### ISSUE THREAD

**Issue by SMotaal** [nodejs/community-committee#507]
<div align=center>

# 💭
#### I gave this my best effort as someone with writing difference trying to relate to others with a more traditional communication style — it is undignifying to be honest and I give up trying to — please feel free to help by closing this first gap where if it will ever communicate and make sense to others then it takes that other's communication benefit to get it there

</div>

---

<details><summary align=center><code>Roadmap</code></summary><small>

<p>

**Goals**

1. Establish appropriate long-term space/efforts for this dialog to begin, so that more dialog can happen, towards less conflicts from biases/assumptions in communication styles/conventions.

**Next Steps**

- [ ] Open an issue proposing and detailing an initiative towards better odds for equal-access across official collaboration mediums (maybe).

  - [x] Create a public slack channel for discussions
    > **Note**: Discussions ongoing in [#equal-access-initiative](https://app.slack.com/client/T043VB7PW/CMQM6ME1Z)
    > 
    > [Join the slack Node Slackers workspace!](http://www.nodeslackers.com).

  - [x] Set up an out-of-band meeting for first steps
    > Thanks for everyone who joined — no meetings scheduled for this time.

  - [ ] Seek a champion #539 

  - [x] Put out "feeler" survey questions #538

    - [ ] Parse the data and Make it count!

</small></details>

<details><summary align=center><code>Explainer</code></summary><small>

<p>

For someone who has to always put so much effort into doing things others take for granted, there seems to be a disconnect between our excitement and sentiment of making our communication mediums more accessible and how much it actually takes from them to feel that they are able to attain appropriate relevance of their communication among their peers.

So aside from what obviously is not meant here, I am sure that some of us out there collaborating (or trying to) in open source projects often feel the unintentional but overbearingly disabling and sometimes maybe unwittingly misappropriated exclusion by the impatience and false assumptions forming around their attempts to communicate. The sad reality of it, at least from personal experience, these challenges are not easily relatable to others, and while most are able to focus on making their point heard, others are left dealing with odds that take away any contribution they offer.

To elaborate on this, cautiously but realistically speaking, others reading more similarly being the systematically inherent bias forced on people who cannot keep up with what is taken for granted, what is intended and quickly gleaned, let alone what was assumed to be (or not) implied between-the-lines. And, because it is not relatable to others, the discrimination burdens of our norms of pace and adherence to naturally biased communication means, forces one to choose either to withdraw and perpetuate this bias or to become increasingly the one burdened by observing it unfolding on to them. And, because it is not relatable to others, the logical foregone conclusion that it is only downhill to even try when one starts noticing their best efforts are considered their own burden of wanting to be part of a so called "dialogue", and I quote, "it is on the messenger to…" — as in if fail happens, where they know you struggle (sometimes even because of the knowing bit itself), they are in and you are out 😞 — not what is said, and certainly not what is intended, but is more often than not the less popular conclusion some in particular are too too often left to draw when they are inevitably becoming omitted from many a discussion by conventions and norms.

Please appreciate that the above is my best effort to try to state this, and the goal here in my mind at least is not to point fingers or complain. Instead, my hope is to take my readiness to openly disclose my own experience (and hopefully others) as the missing feedback from a segment of our community that finds struggles in subtle aspects of our collective collaboration experience that can be gradually improved upon when suitable feedback and response mechanisms are in place to make that possible.

</small></details>

**Comment by mhdawson** [comment]
I talked to @SMotaal last week before suggesting he open this issue.  One of the discussions to be had is how to understand the challenges  (which are likely not obvious to many of us already engaged) and then what we might do within the project to help new contributors 

One of the concrete examples we discussed was around handling conflict and that some additional guidance might help. For example, to recommend that if you need to step away from a discussion it is important to let other participants know you are doing that and some additional context (are you dis-engaging completely, cooling off and then you'll come back or whatever?)

**Comment by SMotaal** [comment]
I can give one dramatization model for effect only!

<div align=center>

<h3>How sometimes it feels from one perspective less heard.</h3>

<small>I promise, and surely someone out there can second this, it is has little to do with technical matter.</small>

</div>

<table>

<tr><th> Is it really about one (X) not making sense?
<th> Read
<th> Think
<th> Write

<tr><td> X: something hard to explain, more lines than usual, contentious
<td> 0
<td> 5
<td> 5

<tr><td> Z: 👎
<td> ?
<td> ?
<td> ?

<tr><td> Y: not sure what you mean
<td> ?
<td> ?
<td> 1

<tr><td> Z: 👍 
<td> ?
<td> ?
<td> ?

<tr><td> X: reiterate, less lines, contentious
<td> 1
<td> 10
<td> 20

<tr><td> Z: 👎
<td> ?
<td> ?
<td> ?

<tr><td> Y: that doesn't work
<td> ?
<td> ?
<td> 1

<tr><td> Z: 👍 
<td> ?
<td> ?
<td> ?

<tr><td> X: demonstrate, more lines, contentious
<td>1
<td>40
<td>40

<tr><td> Z: 👎
<td> ?
<td> ?
<td> ?

<tr><td> Y: not sure what you mean
<td> ?
<td> ?
<td> 1

<tr><td> Z: 👍 
<td> ?
<td> ?
<td> ?

<tr><td> X: good compromise
<td>1
<td>80
<td>40

<tr><td> Z: 👎
<td> ?
<td> ?
<td> ?

<tr><td> Y: sure, that is good
<td> ?
<td> ?
<td> 1

<tr><td> Z: 👍 
<td> ?
<td> ?
<td> ?

<tr><td> …
<td> …
<td> …
<td> …

<tr><td> Y: I'm lost… why is this needed anyways
<td> ?
<td> ?
<td> 1

<tr><td> Z: 👍 
<td> ?
<td> ?
<td> ?

<tfoot>
<tr><td colspan=4 align=center>

<br/>

Certainly, mind-reading would help, but, one often wonders if not reading beyond contentious.

Maybe with enough repetitions it just makes sense to X that in X + Y, they conclude that Y defaults to considering X only brings things not Y or Z like, so why bother.

Z is certainly not helping anyone, beyond maybe making Y happy and so Z is happy, who knows!

---

Again, the context is about human interactions not complaining. So how this dynamic can be improved, requires a level of coordination not possible without a few folks with mutual commitment to affect change by understanding, trying, failing, suceeding.

<br/>

</table>

**Comment by SMotaal** [comment]
Please join in the discussion, there is nothing wrong with recognizing things needing to improve far beyond the scope of this committee, or nodejs itself, so taking this on is about more than this.

In the end, some improvement is better than nothing. This being a popular thing is not something to be expected… diving in here is a personal decision.

/cc @nodejs/community-committee

**Comment by bnb** [comment]
@nodejs/community-committee please check this issue out prior to the next meeting.

**Comment by SMotaal** [comment]
@bnb I made the assumption that there would be a meeting today while travelling (sorry if I missed it elsewhere) — did I miss it?

**Comment by bnb** [comment]
@SMotaal nope, meetings are every other week. It'll be next Thursday 👍

**Comment by SMotaal** [comment]
Next step from the Aug-08 meeting:

> Open an issue proposing and detailing an initiative towards better odds for equal-access across official collaboration mediums (maybe).

- This probably being a good effort for more individuals, please reply here if you are interested in co-authoring or helping in any capacity.

- I am traveling through August so it will likely be very spares effort at first.

- If it helps we can create a slack thread to begin the discussion.

**Comment by SMotaal** [comment]
Folks… please help start the discussion in [node-js.slack.com — #equal-access-initiative](https://app.slack.com/client/T043VB7PW/CMQM6ME1Z).

A good first step would be to join and introduce (maybe).

**Comment by SMotaal** [comment]
Any @nodejs/community-committee member willing to help in setting up an out-of-band Zoom slot [sometime next week](https://calendar.google.com/calendar/embed?src=nodejs.org_nr77ama8p7d7f9ajrpnu506c98%40group.calendar.google.com&dates=20190923/20190927&mode=week&wkst=1)?

It's the first time for me to be coordinating a meeting with the org's zoom instead of personal ones or hangouts so I'm trying to wrap my head around the moving parts before opening up the doodle.

**Comment by SauloNunes** [comment]
We could also use others sources of meeting like gmeets if zooms slot is not available

**Comment by SMotaal** [comment]
I was talking to @bnb earlier and he could weight in… As I understand, we're trying to keep everything in the official space, right?

I'd like to get some traction so if we can manage to organize the zoom through the @nodejs/community-committee account, would be preferred/ideal.

**Comment by bnb** [comment]
If it's about a potential Initiative, I'd prefer to keep it within official media so there wouldn't be any question of it being covered by the Code of Conduct.

If a recording is provided and y'all document that you're using a different medium + assert that this is a meeting where the Node.js Code of Conduct is expected to be followed, I'd assume it would be acceptable.

**Comment by SMotaal** [comment]
Added the [doodle](https://doodle.com/poll/tvbfetteke392mwu) link to op.

**Comment by codeekage** [comment]
I wouldn’t want to miss this... and would to see this move towards and long term initiative moving forward. 

However, does this  have a CommComm champion guiding on processes and ensuring  the CoC is been followed?

**Comment by SauloNunes** [comment]
I Believe that would be @SMotaal

**Comment by SMotaal** [comment]
@codeekage: Sorry I had unexpected appointments today but saw you only had a single time available.

Is it fair to say that your availabilities don't overlap the offered times… if so, do you want me to add extra slots for the same days (a) earlier or (b) later or (c) both?

Also, please note that since we only have few responses it was reasonable to assume waiting for the more traditional 2-day window of opportunity for others.

I'm happy to work around my schedule to get as many as we can together and as I understand @SauloNunes would too.

**Comment by SauloNunes** [comment]
yeah, me too. already update my doodle slots availability

**Comment by SMotaal** [comment]
> However, does this have a CommComm champion guiding on processes and ensuring the CoC is been followed?

@codeekage per progression of early discussions during regular CommComm meetings, this is direction heading.

So coming from a completely different space within the nodejs, it has been very welcoming and inspiring to have the opportunity to attend and have those discussions. My hope is to find a champion as we start laying the groundwork. Given the subject, there likely will be gaps of the less traditional kind, but I'd be jumping ahead getting into such details now.

Sounds fair?

**Comment by SMotaal** [comment]
@codeekage Can you revise your doodle times so we can find a slot where we can all talk? 

> **Note**: once we're all ready, we start recording to make the discussions public as usual.

**Comment by codeekage** [comment]
I will be available on Friday 16:00 WAT don’t know if that will be ok?

**Comment by SMotaal** [comment]
Based on that, we can have just a preliminary meeting this Friday at 1100 EDT/AMT - 1600 WAT.

The doodle will remain open until Sunday 0800 EDT time to gauge interests for  next week too.

@codeekage: I reflected that in your doodle (hope you don't mind)

**Comment by SMotaal** [comment]
Just updated op with [out-of-band Zoom meeting](https://zoom.us/j/739913390?pwd=eEpSVnB4Skt2QjF3YjZqTmhRMDY1QT09) link

**Comment by SMotaal** [comment]
Per today's meeting, we need to open two issues for:

- Questions for the Annual Survey
- A Backing Champion

I'm proposing "improving odds" here as working title for moving forward… please 👍 or 👎 here (suggestions are welcome).

/cc @nodejs/community-committee

**Comment by bnb** [comment]
I'd personally recommend something that's a bit more explicit as a name that explicitly defines your goal that could be easily understood by someone who doesn't have context. Improving Odds is incredibly broad, and many of the things that I think of when I hear that aren't – as far as I know – an intended part of this.

I'm still not feeling familiar enough with the intent to be able to suggest something more precise, unfortunately 😬

**Comment by SMotaal** [comment]
Sure… sorry I just saw this, reflecting on issues :)

**Comment by SMotaal** [comment]
**Moved**: Per today's meeting, we need to open two issues for:

- Questions for the Annual Survey
- A Backing Champion

**Comment by SMotaal** [comment]
> I wish I could be doing more… To somehow make available my strengths to the community, not just have underlined the weaknesses (on conventional things) enough to make it less likely for others to notice the strengths, or notice how wanting those to be wrapped more conventionally is a catch 22 for those who "cannot".

Still, put together a medium draft with my best ability to find a middle ground between how I express myself and how others can relate (maybe).

I don't think it is fair to let this initiative suffer my limitations on affecting change via conventional ways, more typical communication styles, only that it needs to account for the fact that there are like me… Always afraid, to be wrong, to miscommunicate and sound wrong, and to fail to get enough breath to know they have correctly conveyed their message.

But we take a leap of faith when it comes to the open source community, because it is about the only place left in the world that inspires it.

I apologize if my words in the article are not well selected, obviously not meant to be offensive at all. I apologize if the ideas are scattered, obviously not meant to be uninviting at all.

Please, give feedback, not on the article, but in general… The most taunting problem of "miscommunicators" is having too little enough that it is likely just noise — leaves it more likely they will make less sense over time.

I cannot read your minds, but I hope you can see a little into mine.

[:)](https://medium.com/@saleh_34940/towards-open-source-2fca1878b9b6)

**Comment by SMotaal** [comment]
So, since the first article clearly avoids the question of what I personally need, I started drafting one, but I know I will never be able to finish it on my own, not in a way that others will be able to relate to what it conveys, and possibly not without unintentionally offending people coming from a different frame (ie the void) — [Maybe Improving My Odds](https://medium.com/@saleh_34940/improving-my-own-odds-4bcf406c417f).

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
