### ISSUE TITLE
Add Saleh Abdel Motaal (@SMotaal) as observer

### ISSUE THREAD

**Issue by SMotaal** [nodejs/community-committee#508]
Hi everyone:

Please add me as an observer on the community-committee's meetings.

For transparency, I come in with one long-term agenda item in mind (#507), the details of which I hope we can work through together as a collective.

Looking forward to contributing towards your amazing work.

**Comment by keywordnew** [comment]
You're very welcome to join the Zoom through the links on the meeting issues. We don't have an observer track.

**Comment by SMotaal** [comment]
Thank you

**Comment by SMotaal** [comment]
I was following the [contributing bit](https://github.com/nodejs/community-committee#contributing) in the README.

If that is changing — can you guide me through what I need to do instead?

**Comment by bnb** [comment]
Will work with you on this over Slack, @SMotaal :)
