### ISSUE TITLE
Can I join the meetings as an observer.

### ISSUE THREAD

**Issue by mhdawson** [nodejs/community-committee#51]
Now that I better understand the scope from reading the last minutes,  I'd like to at least listen in.

**Comment by gibfahn** [comment]
From https://github.com/nodejs/community-committee/issues/48

>A standing invitation exists for all @nodejs/TSC members who are not also CommComm members to attend in observer capacity.

So I think you are already invited.

**Comment by nebrius** [comment]
Definitely hop on in @mhdawson, we'd love to have you! As @gibfahn mentioned, all TSC and CTC members have a standing invite.

**Comment by mhdawson** [comment]
Where is the dial-in info or is it the standard uber conference ?

**Comment by nebrius** [comment]
@mhdawson we're going to use Google Hangouts. That reminds me, I need to create the event, thanks! The link will be posted in the meeting issue.

**Comment by mhdawson** [comment]
k thanks
