### ISSUE TITLE
Meeting Notes Helper

### ISSUE THREAD

**Issue by SauloNunes** [nodejs/community-committee#510]
Hello, my name is Saulo and today i help [mentorship program](https://github.com/nodejs/mentorship/) 

So, i have more spare time and will to help.

if there is any group that need someone to take meeting notes

i'm available.

thanks for your time.

@ladyleet if u could help me thx ^^

**Comment by keywordnew** [comment]
If you're still willing, there's an upcoming regular meeting :-)

https://github.com/nodejs/community-committee/issues/517

**Comment by SauloNunes** [comment]
thx @keywordnew i will attend the meeting.

**Comment by WaleedAshraf** [comment]
Thanks for the support 👍 :)

**Comment by keywordnew** [comment]
Thanks for your help today @SauloNunes. Just to be explicit, you're very welcome to keep attending and contributing.

**Comment by SauloNunes** [comment]
thanks, you can count on me. i'll finish the notes tomorrow and make the pr.
