### ISSUE TITLE
Request to join the Node.js org as a i18n member

### ISSUE THREAD

**Issue by JohnTitor** [nodejs/community-committee#514]
I recently joined Node.js i18n working group as a member.
Also, I'd like to join the i18n team of the Node,js organization to get ping and rights.
I've pinged some members but not been heard from them.
See also [this issue](https://github.com/nodejs/i18n/issues/203).
The i18n working group is related to community-commitee so I opened this here.
Feel free to close if this request is invalid or this place is inappropriate.
(I sent emails to some members, sorry for bothering you!)

**Comment by keywordnew** [comment]
Thread ping to the @nodejs/i18n team for this issue.

**Comment by zeke** [comment]
I'm a member of @nodejs/i18n, but not able to invite new members to the @nodejs organization.

**Comment by JohnTitor** [comment]
I think joining the working group has been approved so I would appreciate it if someone that has the right could invite me.

**Comment by keywordnew** [comment]
@Trott i18n team needs to invite a new person. But they'll need to be in the @nodejs organization first.

**Comment by Trott** [comment]
> @Trott i18n team needs to invite a new person. But they'll need to be in the @nodejs organization first.

Sent an invitation. (I imagine this can be closed?)

**Comment by JohnTitor** [comment]
Thanks, @Trott! I confirmed the invitation and finally joined the org. So let's close.
