### ISSUE TITLE
For Review: Social Delegate Nomination Form

### ISSUE THREAD

**Issue by RRomoff** [nodejs/community-committee#516]
Hi All-
Per the last CommComm meeting, I am requesting a review of the self-nomination form which will be used to determine Social Media Delegates for the Node.js Project.

Background on this initiative can be found here: https://github.com/nodejs/community-committee/issues/444

When reviewing, please consider what information you would find helpful in determining qualifications for someone for this role.

**Timing**
Deadline for feedback is Wednesday, August 21st.

**Form Link**
https://forms.gle/xiFHSx33zcusssMP6

Thanks!

**Comment by mhdawson** [comment]
LGTM

**Comment by ahmadawais** [comment]
Overall, looks good to me. It might be a good idea to link to the CoC and ask people if they agree to the Node.js Foundation CoC in advanced? Just thinking out loud here.

**Comment by bnb** [comment]
Going to close this since the Social Team has been implemented.
