### ISSUE TITLE
Add Section to README.md about the Community Representatives

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#52]
I think that adding a section to the `README.md` file about the Community representatives, who are - as I understand it - representatives of the Community Committee to the Node.js Foundation Board, would be a good idea.

I imagine this would be in addition to the Community Committee members list. This also allows easy discovery and contact for the active Community representatives at any given time.

**Comment by nebrius** [comment]
I'm definitely on board with this, although with a caveat. In https://github.com/nodejs/community-committee/issues/21, we discussed getting rid of the concept of community representatives as a formal concept entirely, which would negate this issue. Let's see how that plays out first, and then make the change here. Also, we'll need to have some community representatives that aren't also members, which we currently do not have.

**Comment by rachelnicole** [comment]
@bnb can you make a PR for this / is this done?

**Comment by bnb** [comment]
@rachelnicole This is not done, I'll open a PR for it 😄

**Comment by bnb** [comment]
This landed in https://github.com/nodejs/community-committee/commit/b46cb227a93719134adc82792d0e5e0ab00a9622 😁
