### ISSUE TITLE
Pin Meeting Agendas

### ISSUE THREAD

**Issue by darcyclarke** [nodejs/community-committee#522]
👋 I was trying to determine the best WG for this as this is an idea/topic that spans all Node/OpenJS Foundation groups...

I've noticed that meeting threads can often get buried in the noise of existing conversations happening within WGs and thought it would be good practice/standard to have these agendas pinned; making them visible to ease the pain of discovery & entice new attendance. 

I'm not quite sure how the existing tooling works to generate meeting agendas but issues can indeed be [pinned/unpinned via API](https://developer.github.com/v4/mutation/pinissue/) (ex. [good-first-pin](https://github.com/JasonEtco/good-first-pin) Probot app).

I'm willing to help out with any leg work required to make this a reality if there is consensus it has/adds value.

**Comment by bnb** [comment]
Going to close since @mhdawson provided a good avenue for adding this as a feature to all of Node.js :)
