### ISSUE TITLE
Create Custom Url on Youtube

### ISSUE THREAD

**Issue by saulonunesdev** [nodejs/community-committee#527]
Hi,

i was updating the meeting issue on mentorship program and i was curious about the youtube channel url,

after a little search, i found out this article:

https://support.google.com/youtube/answer/2657968?hl=en

> Custom URL eligibility
> To create a custom URL for your channel, your account needs to:
> * Have 100 or more subscribers
> * Be at least 30 days old
> * Have an uploaded photo as a channel icon
> * Have uploaded channel art

So, can we update the youtube url channel to a friendly /nodejs ?

**Comment by bnb** [comment]
Unfortunately, https://youtube.com/nodejs is already taken. If you have another suggestion, I think we'd be all ears. We currently have https://youtube.com/nodejs-foundation but there is now no such thing as the Node.js Foundation so that slug is slightly misleading.

**Comment by SauloNunes** [comment]
thks @bnb https://youtube.com/nodejs-foundation is better than https://www.youtube.com/channel/UCQPYJluYC_sn_Qz_XE-YbTQ

i'm going to use this url now.

Thanks

**Comment by bnb** [comment]
Going to re-open, since I think it's definitely worth us having a discussion about renaming the channel since the nodejs-foundation no longer exists – totally fine for now, but definitely worth approaching as if we have a fresh slate ❤️

**Comment by SauloNunes** [comment]
sure, 

i dont know if its okay, but we could reach youtube, because the current user NoDejS has only 3 subscribers and doesnt fits the 100subs rule

**Comment by bnb** [comment]
I'd prefer to avoid that, given that they do actively use it and specifically use the lists features. I have zero subscribers but pay YouTube for my account and use it constantly.

IMO it's in a similar vein to what happened with Kik that triggered left-pad. While they're not in our ecosystem, I'd prefer to avoid using brute force to take something like that away from someone.

**Comment by codeekage** [comment]
Hey, sorry I’m catching up on all the open issues that doesn’t seem to have an agenda label. 😊 What’s the final update on this? Or is it fine to close?

**Comment by bnb** [comment]
I would love to see us be able to change the nice slug to something else, but I also don't think getting nodejs (or node) is something that we'll realistically be able to do :(

If we can think of something else that fits and is available, we could do that 👍

**Comment by SauloNunes** [comment]
> I'd personally prefer to avoid that, given that they do actively use it and specifically use the lists features. I have zero subscribers but pay YouTube for my account and use it constantly.
> 
> IMO it's in a similar vein to what happened with Kik that triggered left-pad. While they're not in our ecosystem, I'd prefer to avoid using brute force to take something like that away from someone.

i agree, would be better to find a different solution for this.

perhaps we could ask for suggestions and see which one fits better.

like: node-js or node.js (i dont know if . is able to be used)

**Comment by SauloNunes** [comment]
@bnb what do you think about **openjsnode**

https://www.youtube.com/openjsnode

**Comment by bnb** [comment]
I would _personally_ prefer not to directly tie Node.js branding to OpenJS branding.

**Comment by mhdawson** [comment]
How about http://www.youtube.com/nodejs-project

**Comment by joesepi** [comment]
I asked the person who has /nodejs very nicely if they'd gift it to us -- I'll let you know if they respond.

https://twitter.com/joe_sepi/status/1233242558542831617

**Comment by bnb** [comment]
nodejs or nodejs-project are both nice 👍

**Comment by joesepi** [comment]
The person I reached out to is not the person who owns youtube/nodejs :(

And the person who is NoDejS on Youtube favorited videos as recently as March of this year so they are active to some extent. I say with go with choice #2: nodejs-project that @mhdawson suggested.

**Comment by saulonunesdev** [comment]
Thanks @joesepi i also think **nodejs-project** is a good friendly name

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
