### ISSUE TITLE
Regarding my membership...

### ISSUE THREAD

**Issue by jasnell** [nodejs/community-committee#53]
I'm going to voluntarily withdraw my (potential?) status as a voting member of the community committee. I will still certainly be involved in the discussions as appropriate, but given that there are already a couple of Node.js core participants here whom I trust implicitly, there's not much to be gained by me having voting status :-) ... it also saves me a bit of time (and guilt given that I haven't been able to make the meetings as of late). I am quite excited about the direction of the CommComm so far and hope it does quite well.

**Comment by nebrius** [comment]
Makes sense to me, and thank you for the vote of confidence :). Would you mind submitting a quick PR to update the README?

**Comment by jasnell** [comment]
Done!

**Comment by pup** [comment]
this can be closed now, right?

**Comment by nebrius** [comment]
yep!
