### ISSUE TITLE
Add my email to CommComm team meetings

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/community-committee#531]
Hi,

Can someone with Foundation Calendar Permission add my email waleedashrafhere[@]gmail.com to CommComm meetings?
I see there are already some people invited.

Maybe we should invite all the members of CommComm with their email. And make this step part in the onboarding process for new members. This way, when you share your calendar with someone, they can see that you are busy. It helps a lot.

I know there is a way to copy the events to own calendar, but that gets outdated when original event is updated.

Maybe someone can suggest a better solution.

**Comment by joesepi** [comment]
@brianwarner can help with this.

**Comment by brianwarner** [comment]
Unfortunately this is one thing I can't help with... I believe the CommComm calendar invitation is maintained somewhere else.  I don't have it in the OpenJS Foundation general calendar.

**Comment by WaleedAshraf** [comment]
I think @bnb can add.

**Comment by bnb** [comment]
Theoretically added. Let me know if it didn't work.

**Comment by WaleedAshraf** [comment]
I think it didn't work as I didn't receive an invitation email. Also, I don't see it in the event.

![image](https://user-images.githubusercontent.com/8335457/66329440-cf779980-e92e-11e9-8b52-b24d3cba0177.png)

**Comment by bnb** [comment]
Saved the event and it kept not adding you. I assumed it was sending you an email. Let me look into it.

**Comment by bnb** [comment]
Should have worked now.

**Comment by codeekage** [comment]
Please, can I get added too?

**Comment by WaleedAshraf** [comment]
It worked. 👍  thanks.
