### ISSUE TITLE
Initiative #507 — Backing champion for phase 0, …

### ISSUE THREAD

**Issue by SMotaal** [nodejs/community-committee#539]
Hi folks… based on discussions from last meeting #537, we're looking for a super enthusiastic backing champion from @nodejs/community-committee, guiding us and making sure procedures are followed

Tasks:

- See us through the bootstrapping (phase 0) over the next few weeks, which I am hardly able to estimate time wise, but includes helping with:

  1. Setting up a regular meeting slot.
  2. Determining/creating a space for collaboration (repo may be).
  3. Draft the docs and structure to facilitate the collaboration and participation from the community.
  4. Help frame and guide towards meeting phase goals:
     - Help with #538 to put forward questions on the general survey to help explore the problems from the various perspectives shaping our community (tight timeframe).
     - Help determine if and guide the process of having a more effective survey aiming to understand the finer grains of the challenges ahead for all members of the community (moderate timeframe).
     - Help chart the road map for next phases (practical timeframe).

- And, potentially, See us also through future phases… TBD

---

Thanks to everyone in the committee, everyone participating in these discussions and everyone helping to keep pushing our larger community forward.

---

> - [ ] Rename op once we settle on a title in #507

**Comment by bnb** [comment]
If there is interest in continuing this, I'm happy to leave it open. From a previous discussion with @SMotaal, I believe he's no longer working on anything in the Node.js project and will likely not be driving this forward.

**Comment by SMotaal** [comment]
@bnb yes, sorry for not getting back sooner, I've been taking time away from the project. Seeing that the issue was open back in October, 2019, we gave this enough time for folks to express interest.

Hopefully the few positive aspects that came out of this, like the survey questions… etc, would better position things to reconsider this kind of effort down the road.

Thank you!

**Comment by bnb** [comment]
Thank you for the time and energy you've put into this @SMotaal ❤️
