### ISSUE TITLE
Proposal: CommComm "working" meeting on off-weeks

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#543]
I propose that we have a "working" meeting on the off-weeks in the same timeslot as the CommComm meeting.

My thinking is for it to be an open office hours type meeting where CommComm members can be available to the community. In lieu of open office hours engagement, we could make progress on other initiatives. I'd also like for this to be a resource for potential new members.

- Open Office Hours: be available to the community
- Mentoring: be a resource for current and potential new members
- Initiatives: collaborate/discuss initiative work

**Comment by joesepi** [comment]
I propose 18:00 UTC (2pm ET) on the off-weeks of Comm Comm, starting next week.

**Comment by bnb** [comment]
Sounds good to me 👍

**Comment by joesepi** [comment]
With no objections in today's meeting, I will plan to run this next week at the proposed time. Thanks. 🙌

**Comment by joesepi** [comment]
Sorry, yall. I have had a tough week with a Macbook that died and have been struggling to fix it while also keeping up with work and community work. I failed on this first meeting. Many apologies. With NodeConfEU next week, I'll have to try again at this same time slot in two weeks. I'm open to other time slots if people prefer and I am also open to an ad-hoc meeting if anyone wants to meet before the next meeting in two weeks.

**Comment by amiller-gh** [comment]
I've taken this off the regular agenda – give us a status updates after the first meeting 🙏

**Comment by joesepi** [comment]
I have a newly recurring meeting at this time slot and need to move the meeting. Sorry for short notice. I’ll get this idea off the ground today at 1pm ET. I’ll personally alert a few of the people I thought might attend. Thanks.

**Comment by joesepi** [comment]
Today’s meeting, 1pm ET:
https://zoom.us/j/802779834

**Comment by WaleedAshraf** [comment]
@joesepi Is this happening?

**Comment by joesepi** [comment]
Hey friends. I've been putting a lot of thought into this initiative and think the best idea is to elevate this up to the OpenJS level. I'll personally focus on Node.js but will have an open door to all OpenJS projects.

https://github.com/openjs-foundation/cross-project-council/issues/465

Meeting today at 1pm ET https://zoom.us/j/478648416

**Comment by joesepi** [comment]
One last comment on this before I close it.

This is now a regular thing -- every other Thursday at 1pm ET (off weeks from Comm Comm meeting).

See more here: https://github.com/openjs-foundation/open-office-hours

Yay 🎉
