### ISSUE TITLE
Add SauloNunes to the mentorship team

### ISSUE THREAD

**Issue by Bamieh** [nodejs/community-committee#553]
Hello :wave:

@SauloNunes has been active with mentorship for a very long time now and he's doing great contributions to the mentorship initiative.

Saulo accepted becoming the mentorship community manager, following up on issues/PRs and on our slack channel to help us stay engaged with the community (mainly with people who have not been matched up for mentorship yet).

Can we please invite Saulo to become a member in the node organization so I can invite him to the mentorship team in the ogranization.

Thanks!

**Comment by SauloNunes** [comment]
thanks @Bamieh

**Comment by SauloNunes** [comment]
@mhdawson can you label 'cc-agenda' to this issue plz. Thanks

**Comment by bnb** [comment]
Done!
