### ISSUE TITLE
What do I need to build local Node.js community?

### ISSUE THREAD

**Issue by naugtur** [nodejs/community-committee#554]
I'd like to set up a place online, build a network of local meetups and likely also organize a conference for the Node.js community in Poland.

1. From reading the trademark docs I'm not sure if I can remix the Node.js logo into something referring to Poland (like change colors to the ones form the flag)
2. I'm not sure if I need specific permission to call something `nodejspl`
3. I'd like to know what's the process of organizing a conference calling NodeConf(.*) - NodeConfPL in my particular case.

Could anybody point me to docs on that? Or respond to the questions and point to a place where I could write those things down for others?

**Comment by WaleedAshraf** [comment]
You can look into starting https://nodeschool.io/ for Poland. I see there is none yet.
You may also get help from Outreach Initiative https://github.com/nodejs/outreach . They have a meeting every other Tuesday at 16:00 UTC. The next one is on the 26th.

**Comment by naugtur** [comment]
I want to build community first and nodeschool is not focusing on that. 
I know I need no permission to start a meetup, but wanted to get details on using the logo and calling something nodeconf if I end up organizing a conference

Will look into outreach

**Comment by mhdawson** [comment]
In terms of the logo I'm not an expert but I don't think you can use the Node.js logo for a remix. Guidelines are here: https://github.com/openjs-foundation/artwork and here https://openjsf.org/wp-content/uploads/sites/84/2019/10/OpenJS-Foundation-Trademark-Policy-2019-10-22.pdf

**Comment by bnb** [comment]
@naugtur I would recommend looking at this guide for NodeConf - that project is unrelated to the official project: https://github.com/nodeconf/collective/blob/master/GUIDE.md

Going to close this for now since it seems to have been addressed, happy to re-open if there's further discussion needed :)

**Comment by naugtur** [comment]
Thanks! I had no idea it's there :)
