### ISSUE TITLE
Zoom Credentials for Website Redesign

### ISSUE THREAD

**Issue by jonchurch** [nodejs/community-committee#557]
Hey ya'll, can I get some zoom credentials so I can host during Website Redesign meetings?

I'm not sure who all has the credentials for it, @amiller-gh and I had talked about me getting them at some point. It's happened a few times where there wasn't anyone available for a meeting who had credentials to host.

**Comment by bnb** [comment]
Previously @amiller-gh was running the meetings. Is that no longer the case?

**Comment by bnb** [comment]
I believe this has been taken care of? If not feel free to reopen.
