### ISSUE TITLE
Add licenses to CommComm repositories

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#559]
Quite a while ago https://github.com/nodejs/community-committee/issues/271 recieved the feedback we were waiting on. We should follow the feedback that was provided and ensure our repos are licensed correctly. We will need to audit the CommComm repos and figure out which are currently not licensed, and add the correct licenses to them.

I would also recommend submitting PRs and @ mentioning the appropriate teams to ensure that there are no objections - if there are, we will need to address them as necesssary.

**Comment by keywordnew** [comment]
There is a possible issue with the licence choice over at nodejs/mentorship.

https://github.com/nodejs/mentorship/pull/184

The guidance suggests:

> If the material is documentation intended to be provided to users, use the CC-BY-4.0. For internal community documents, use the MIT license.

The MIT license has specific mention of "software", which that repo does not have. 

Shall we switch to CC-BY-4.0? One could make the case that the material _is_, at least partly, documentation to be provided to users.

**Comment by mhdawson** [comment]
@keywordnew I think that despite the "software" mention the suggestion was that for internal community documents it would still be ok.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
