### ISSUE TITLE
Archive nodejs/user-feedback

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#567]
I've moved the repo to the OpenJS Foundation and we can archive the nodejs repo. (I still have a lot of cleanup in the newly "moved" repo but that doesn't prevent us from archiving this repo.)

https://github.com/openjs-foundation/user-feedback
https://github.com/nodejs/user-feedback

**Comment by mhdawson** [comment]
+1

**Comment by codeekage** [comment]
+1

**Comment by WaleedAshraf** [comment]
+1

**Comment by mhdawson** [comment]
We have a few approvals, mentioned in CommComm meeting with no objections today so archiving.  Can always un-archive if necessary.

**Comment by mhdawson** [comment]
Archived.
