### ISSUE TITLE
How to become member of node js community committee ?

### ISSUE THREAD

**Issue by viveksharmaui** [nodejs/community-committee#583]
Hi I'm working with node js from 2017 and I'm open source Contributor I'm looking forward to join node js community committee ? how can i join node js organization on github ?

**Comment by bnb** [comment]
The current process to becoming a member of the CommComm is by non-trivial participation in our initiatives: https://github.com/nodejs/community-committee#strategic-initiatives

**Comment by viveksharmaui** [comment]
I'm interested to become champion in how i got into node .

**Comment by bnb** [comment]
If you want to participate in work of the Community Committee, please see the above link and participate in an initiative 👍

**Comment by viveksharmaui** [comment]
Ok Thanks

**Comment by bnb** [comment]
Going to close this since it's been resolved with a proper answer.
