### ISSUE TITLE
OpenJS Foundation Cross-Project Council - Node.js CommComm Seat Election

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#586]
It’s time to elect the Cross-Project-Council voting representatives for next term which starts on April 1st 2020. CommComm's representative is @joesepi. Please see https://github.com/nodejs/admin/issues/472 for more details.

Timeline is:
* **March 9th:** Call for nominations for both CPC representatives
    * @nodejs/community-committee, please self-nominate in this issue
* **March 16th:** Close nominations and open balloting for CPC representative
* **March 23rd:** Close balloting and announce CPC representative
* **March 23rd:** Handover
* **April 1st:** Transition complete

Please note the expectations of the voting CPC representative: [CPC-CHARTER.md#voting-members](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members)

Also note: any member of the Node.js org can participate in the Cross Project Council as a regular member, as is defined in [CPC-CHARTER.md#voting-members](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#regular-members)

Similar to the practices in Node.js, the CPC follows the consensus seeking model and there is little difference between a voting rep of a project and a regular member. Becoming a regular member could be a good way to get involved if one is unsure of running for a voting member.

**Comment by joesepi** [comment]
Hi. 👋   I am self-nominating myself.

However, if anyone is interested in the work and wants to know more, I am happy to share. Please just let me know.

**Comment by bnb** [comment]
Since there have been no further nominations or self-nominations past the nomination window cutoff, we can presume that @joesepi is the winner. Will discuss this up in today's meeting 👍

**Comment by bnb** [comment]
ping @nodejs/community-committee

**Comment by mcollina** [comment]
@bnb what's the status of this?

**Comment by bnb** [comment]
Apologies, OOO this week. Per the last CommComm meeting’s discussion there have been no vocal -1s against @joesepi continuing his seat.

@joesepi has been elected.
