### ISSUE TITLE
Do we need a newsletter?

### ISSUE THREAD

**Issue by LaRuaNa** [nodejs/community-committee#590]
Based on discussions https://github.com/nodejs/community-committee/issues/587 and https://github.com/nodejs/nodejs.dev/issues/331 the question arises: Do we need a Node.js Newsletter?

**Comment by LaRuaNa** [comment]
@bnb Can't set labels :] Can you please take care.

**Comment by designMoreWeb** [comment]
I thought in our previous meeting we addressed the issue by stating that currently there is no plan as such but it could change in the future
