### ISSUE TITLE
Give Slack Channel Permissions

### ISSUE THREAD

**Issue by SauloNunes** [nodejs/community-committee#596]
Hello

I would like to ask to add permission to the users @dguttman @detrohutt @SauloNunes at Node.js Slack Channel #mentorship for using @here at that channel.

We need to send notifications/status updates for the mentorship initiative

**Comment by SauloNunes** [comment]
@mhdawson can you add Label Agenda to this ticket please

**Comment by mhdawson** [comment]
@SauloNunes done, although you should still comment on the issue for this week that you want to added it to the agenda as the agenda will have already have been auto generated.

**Comment by SauloNunes** [comment]
Oh, thanks @mhdawson didn't know that

**Comment by SauloNunes** [comment]
Closing this issue because the directions to get those permissions were already addressed

**Comment by ljharb** [comment]
As far as I can tell, this isn't a feature slack supports. Everyone is either an admin, or not (user groups are a paid feature, and the node slack is a free slack); and the only setting i can find is whether to *warn* about `@channel` or not, which wouldn't help here. There's no per-channel ownership or control over at-here/at-channel messages.

My suggestion would be to make a different channel for mentorship announcements, ask people to join it and set its notifications to a high level, and then reserve that channel for that purpose.

**Comment by SauloNunes** [comment]
Thanks @ljharb in this case we will probably migrate to OpenJS
