### ISSUE TITLE
Request admin access for nodejs repos

### ISSUE THREAD

**Issue by alexandrtovmach** [nodejs/community-committee#603]
Hello,
I'd like to have admin access to a few nodejs repos:
- https://github.com/nodejs/nodejs.dev
- https://github.com/nodejs/nodejs.org
- https://github.com/nodejs/i18n

## About me
I'm active contributor for probably last few months, and most of my activity is for i18n, but not only. I need these permissions, because with i18n initiative we're going to make CI/CD updates for each of these repos.
In addition, for nodejs/nodejs.dev I'm also going to help with implementation and this access will be useful for a team. For now, I know only one person from a team with these permissions - @bnb (related: https://github.com/nodejs/nodejs.dev/pull/460), and adding one more sounds reasonable.

@nodejs/website-redesign @nodejs/i18n - objections?

**Comment by RichardLitt** [comment]
I can second @alexandrtovmach's involvement. :)

**Comment by zeke** [comment]
No objection here 👍

**Comment by obensource** [comment]
Same. @alexandrtovmach is a wonderful asset to this project. 👍

**Comment by MylesBorins** [comment]
Definitely not my place to say anything re: i18n but I don't think I'm comfortable with giving this access to nodejs.dev or nodejs.org (and the appropriate place to ask for that access is likely nodejs/admin not here).

I did a quick review of the current existing access and there is only a single person with explicit admin privileges for either nodejs.dev or nodejs.org... the majority of folks have access through teams and those teams have only write access. Individuals like myself or other Org wide owners of course have elevated access... and that does help us limit certain things happening on the repo.

To be clear, this is not about any specific individual, but broad policy for how we manage those repos.

For reference, the i18n repo does have more than a single admin, and multiple of them have chimed in as a +1 for @alexandrtovmach in that repo. any of them should be able to sign off on this.

**Comment by alexandrtovmach** [comment]
@MylesBorins Sounds reasonable, and I agreed with policy. Problem with `write` access for teams there's no clear way to set up and test CI/CD stuff except only ping members with right permissions. For sure, I understand your concerns and just want to figure out optimal way between security and productivity.

Curious, is there a way to become "org wide owner"? This is something related to ["Observers and Membership"](https://nodejs.org/en/about/community/#observers-and-membership)?

/cc @nodejs/admin

**Comment by MylesBorins** [comment]
@alexandrtovmach [nodejs/admin](http://github.com/nodejs/admin) is a repo it has members of both the TSC and the CommComm so you can get a broader approval here. In the past there was a WG for the websites, but in lieu of that working group I believe the decision would likely fall somewhere between TSC + CommComm... but since we are talking about Ci/CD it might also intersect with interests of the build working group.

Introducing any new tools generally requires larger approvals as well... so it isn't necessarily as simple as flipping an admin bit.

The only folks who are owners of the org and TSC and CommCOmm

**Comment by alexandrtovmach** [comment]
@nodejs/community-committee @nodejs/tsc Any suggestions what I need to do?

**Comment by MylesBorins** [comment]
@alexandrtovmach I think you should make an issue in nodejs/admin.  But to set some expectations:

* You will likely not be given any sort of org admin / ownership. That is limited to TSC + CommComm + Code of Conduct group
* Folks will likely be hesitant to give admin permissions to nodejs.org or nodejs.dev. you are going to make a clear case as to why you need these permissions and why these permissions to be permanent

I understand you are just trying to improve things and running up against these constraints are frustrating, but I hope you can understand that we need to be very very careful about handing out these kinds of keys. For something like making CI/CD changes that repos / working groups / teams associated should likely have consensus before anything major is changed, and at that point a request can be made on nodejs/admin for such an action to be taken.

You likely are going to need multiple folks for both repos chiming in that you should have this access... and not to be harsh but I am one of those people and don't currently see why we need to give it. So maybe a good place to start would be to convince me 😇.

**Comment by alexandrtovmach** [comment]
@MylesBorins Yeah, I'm fully understood these points, without frustration. Closing this issue and will continue with current workflow 👍

P.S. I'll ping you everytime when I need to do some changes in repo settings...
![image](https://user-images.githubusercontent.com/28801003/80342227-72ace380-886c-11ea-9d82-066a70887091.png)

**Comment by bnb** [comment]
@alexandrtovmach for what it's worth, the CommComm chairperson (whoever that is, at present it's me) is an org owner with the explicit ability to help Initiatives as needed.
