### ISSUE TITLE
Update scope of nodejs-collection

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/community-committee#608]
As discussed in the last commcomm meeting (04-30), submitting the proposal to update the scope of Node.js Collection publication on Medium.

One of the main reasons for Node.js Collection was to amplify the usage of Node.js and to have related content available on the internet. Now, things have changed a lot and there are a lot more good and quality content available for users.

Another reason is that it's a lot of work to manage the whole process. We are in the [middle of revamping](https://github.com/nodejs/nodejs-collection/pull/37) and that also if taking a lot of time. Even after that is done, it will require a reasonable time from anyone who is managing it.

## What options do we have?
One option is to keep Node.js Collection alive but only use it for submission from collaborators and contributors. We can also use it for posts about new releases and features. Like [this](https://medium.com/the-node-js-collection/maintainers-should-consider-following-node-js-release-schedule-ab08ed4de71a).

Another option is completely shut it down and use other social media platforms for awareness.

## What will be the next steps?
If there is no objection from anyone for the first suggestion, I'll open a PR in Node.js Collection repo, and remove all the stuff from the readme and add new.
- It'll only include into about Node.js Collection
- And the email address to reach out to. medium@nodejs.org
Everything else will be removed.

Another option is that we archive the nodejs-collection repo. The initiative will still stay alive and publication will be managed by CommComm members and other collaborators.

**Comment by bnb** [comment]
cc @nodejs/community-committee

**Comment by bnb** [comment]
I would recommend:

>One option is to keep Node.js Collection alive but only use it for submission from collaborators and contributors. We can also use it for posts about new releases and features. Like this.

and:

>If there is no objection from anyone for the first suggestion, I'll open a PR in Node.js Collection repo, and remove all the stuff from the readme and add new.
>
> - It'll only include into about Node.js Collection
> - And the email address to reach out to. medium@nodejs.org
> Everything else will be removed.

**Comment by mhdawson** [comment]
Discussed in the CommComm meeting today, seems reasonable to proceed with the recommendation to open a PR as suggested given there have been no objections.

**Comment by WaleedAshraf** [comment]
@bnb @mhdawson Thanks for the input. I couldn't join last meeting. :(

I'll finalize it if there is no objection. @joesepi and I discussed a few ideas in OpenJS Office hours about this, but I think we can keep working those ideas. It should not block us from closing these PRs. @joesepi What you think?
