### ISSUE TITLE
Contributing - good first issue section needs updating

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#611]
https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md#choosing-a-good-first-issue-to-work-on

**Comment by joesepi** [comment]
Contributing good first issue should mirror the current initiatives from Comm Comm [README](https://github.com/nodejs/community-committee/blob/master/README.md#current-initiatives)

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
