### ISSUE TITLE
Meeting 2017-05-25 Community Committee (CommComm)

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#62]
Meeting 2017-05-25 Community Committee (CommComm)
--------------------------------------

## Time

**UTC Thu 25-May-2017 20:30 (08:30 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 25-May-2017 13:30 (01:30 PM) |
| US / Mountain | Thu 25-May-2017 14:30 (02:30 PM) |
| US / Central  | Thu 25-May-2017 15:30 (03:30 PM) |
| US / Eastern  | Thu 25-May-2017 16:30 (04:30 PM) |
| Amsterdam     | Thu 25-May-2017 22:30 (10:30 PM) |
| Moscow        | Thu 25-May-2017 23:30 (11:30 PM) |
| Chennai       | Fri 26-May-2017 02:00 (02:00 AM) |
| Tokyo         | Fri 26-May-2017 05:30 (05:30 AM) |
| Sydney        | Fri 26-May-2017 06:30 (06:30 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation++Meeting+2017-05-25&iso=20170525T20
* or http://www.wolframalpha.com/input/?i=8pm+UTC%2C+May+25%2C+2017+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1J14T5lXuFWsaTqfkpmPruAZ4E-WsVe2V5TAaKwDjHN0/>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/1tysRywkgReTXtYlG_hSvxmbnV7V3dUoXei2v6uXiC0A/>_

## Agenda

Extracted from **cc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/TSC

* Request to move moderation responsibilities to CommComm [#270](https://github.com/nodejs/TSC/issues/270)

### nodejs/community-committee

* Charter tweaks [#50](https://github.com/nodejs/community-committee/pull/50)
* Expanding the Node.js Collection: Reviewers [#45](https://github.com/nodejs/community-committee/issues/45)
* Adding folks as members [#38](https://github.com/nodejs/community-committee/issues/38)
* Moderation shortage [#33](https://github.com/nodejs/community-committee/issues/33)

## Invited

* Ashley Williams @ashleygwilliams (CommComm)
* Bryan Hughes @nebrius (CommComm)
* Emily Rose @emilyrose (CommComm)
* Gregor Martynus @gr2m (CommComm)
* Jenn Turner @renrutnnej (observer)
* JP Wesselink @jpwesselink (CommComm)
* Mikeal Rogers @mikeal (observer/Node.js Foundation)
* Myles Borins @MylesBorins (CommComm)
* Penny Hugger @pup (observer)
* Rachel White @rachelnicole (CommComm)
* Richard Littauer @RichardLitt (observer)
* Rod Vagg @rvagg (CommComm)
* Sarah Conway @SarahKConway (observer/Node.js Collection)
* Tierney Cyren @bnb (observer)
* Tracy Hinds @hackygolucky (CommComm)
* William Kapke @williamkapke (CommComm)
* Zibby Keaton @ZibbyKeaton (observer/Node.js Collection)

## Notes

The agenda comes from issues labelled with `cc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Google Hangouts; link will be posted here shortly before the meeting starts.

A standing invitation exists for all @nodejs/tsc members who are not also CommComm members to attend in observer capacity.

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

**Comment by pup** [comment]
it's gonna be a close call for me... i have a family thing on thursday and i'm not sure how long that's gonna go. i can probably fit this in though since its quite late

**Comment by RichardLitt** [comment]
I'll be unable to attend, as well; couchsurfing in Poland for a night and need to hang out with my host.

**Comment by ZibbyKeaton** [comment]
I will also not be able to attend this meeting, but @SarahKConway will fill the group in on the happenings of the Node.js Collection.

**Comment by mhdawson** [comment]
I'll be there.

**Comment by williamkapke** [comment]
I have an schedule conflict so I don't think I'll be able to make this one.

**Comment by nebrius** [comment]
Live stream will be at https://www.youtube.com/watch?v=tA1Ovl5eKRA, hangout link for participants will be posted here in about 20 minutes!

**Comment by nebrius** [comment]
My apologies for the delay, I had some internet issues. Here's the link for participants: https://hangouts.google.com/hangouts/_/ytl/Yn8HviH1B7YxROnNctu1106YontmqMjdE5-n2z-n9WA=?eid=100598160817214911030

**Comment by nebrius** [comment]
Sorry for the delays everyone, we've been having some technical difficulties. NEW HANGOUT LINK: https://hangouts.google.com/hangouts/_/ytl/mHMit4-TvAKq9Xyf3FZgwll_T-486YcOSnyViDoFLSE=?eid=100598160817214911030

**Comment by nebrius** [comment]
Thank you for updating links @williamkapke! I was kinda flailing around at the beginning of the meeting 😅

**Comment by nebrius** [comment]
Meeting notes landed, closing this issue.
