### ISSUE TITLE
Request to change website redesign meeting champion

### ISSUE THREAD

**Issue by designMoreWeb** [nodejs/community-committee#626]
Since a past few meetings we have had to ask someone to open the meetings for us for website redesign and we feel it would be beneficial to have a new champion for website redesign and new hosts to host our meetings for website redesign.

The champion we would like to nominate is : 
* Divy Tolia 

The hosts we want are: 
* Ben Halverson
* Saulo Nunes
* Divy Tolia

**Comment by saulonunesdev** [comment]
+1 on @designMoreWeb  as a champion

**Comment by saulonunesdev** [comment]
@designMoreWeb i just realized now that this is an issue, we need an PR to update this section here: https://github.com/nodejs/community-committee#current-initiatives

**Comment by designMoreWeb** [comment]
> @designMoreWeb i just realized now that this is an issue, we need a PR to update this section here: https://github.com/nodejs/community-committee#current-initiatives

I’ll create a PR in a bit

**Comment by designMoreWeb** [comment]
[Created the PR](https://github.com/nodejs/community-committee/pull/627)

**Comment by joesepi** [comment]
PR merged. This issue is resolved. Thanks everyone.
https://github.com/nodejs/community-committee/pull/627
