### ISSUE TITLE
Renaming default branch in this repository

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#634]
Just wanted to put up a quick issue to ask if folks would be +1 on renaming the default branch of the CommComm repo from `master` to `main`. If you would be, please reply or 👍🏻 . If not, please comment, 👎🏻 , or message me if you don't want to be public with it.

**Comment by bnb** [comment]
cc @nodejs/community-committee - surprised we don't have more eyes on this after 10 days.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
