### ISSUE TITLE
Community Committee Chairperson Election: 2020 to 2021

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#638]
It's now time for the CommComm 2020-2021 election, @nodejs/community-committee.

Please submit your self-nominations as comments in this issue (other comments are welcome!) by the time it is posted on Monday, August 24. I will create Q&A issues for CommComm chairpeople once this period ends.

> The CC will elect from amongst voting CC members a CC Chairperson to work on building an agenda for CC meetings [...] The CC shall hold annual elections to select a CC Chairperson [...]; there are no limits on the number of terms a CC Chairperson [...] may serve.

Expected responsibilities include but are not limited to:
- Create each meeting's agenda. 
- Create the event and make sure it is live-streamed in YouTube. 
- Chair and facilitate each meeting. It is the chairperson's responsibility to ensure that the meeting stays on track, sticks to the agenda, and finishes within the allotted time.
- Collaborate with the CPC Reps
- Collaborate with the TSC Chair
- Coordinate efforts in shared repos, as listed in Admin
- Managing the CommComm 1Password

I would recommend having _at least_ 10 hours of your working time available to be dedicated to CommComm for the next 52 weeks. I would also recommend being able to be flexible up to 20 hours of your working time during any of those weeks. All voting members of the CommComm are eligible to self-nominate.

## Nominated candidates:
- TBD

**Comment by rachelnicole** [comment]
I nominate @bnb to continue as chairperson for 2020-2021 as he's been doing a great job for the past few years.

**Comment by bnb** [comment]
I'll accept @rachelnicole's nomination. I also strongly encourage others to nominate or self-nominate if you're interested ❤️

**Comment by ahmadawais** [comment]
I'd also like to nominate @bnb — he's been doing an excellent job at it. 💯

**Comment by joesepi** [comment]
I third the @bnb nomination. Thanks for all that you do!!

**Comment by mhdawson** [comment]
+1 to @bnb to continue as chair.

**Comment by bnb** [comment]
I left this open a week past the 24th since I was the only person nominated and wanted to make sure there was space for others. However, we're now well past the nomination window and I'm the only person who's been nominated, meaning I'm the only option. Per our processes and past decision making around this, it seems that I'm continuing the role for another year 😅

I really appreciate the +1s from y'all. It means a lot to me.
