### ISSUE TITLE
Inactivity in CommComm and its Future

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#639]
Over the past few years, I feel we've seen a slow decline in activity in the Community Committee to the point that we're relatively unable to be effective in our goals.

Going to list some things that I've been thinking about/have struggled with:

- We currently have a handful of members who do not meaningfully engage in CommComm work outside of being a member and occasionally commenting on issues or attending meetings.
- For a handful of folks, I've reached out to per our processes to validate their membership in the Committee per our documented processes and they have re-certified that they actively want to be a member multiple times - our processes don't elaborate any limit to the number of times this can happen which has perpetuated inactive members who want to be a member but are not actively participating in the project.
- Many issues, PRs, and other basic CommComm work generally go unattended. Certain issues remain open well past them being stale or out of date, PRs are left open unreviewed for extended periods, and certain basic work is not done. 
- Many of our core documents are obviously outdated. I've brought this up with a handful of folks over time, but it seems it's not something others have time or priority to invest in.

None of these are meant to be judgements, they are just relatively precise statements of my experience and observations.

I've generally tried my best to help alleviate each of these challenges - trying to help new folks get involved in Initiatives so they could level in to CommComm itself, doing whatever I reasonably can to help the current members be involved or focus on things they care about, and generally maintaining the CommComm repository both in terms of issues and PRs (I end up being the one who finalizes most work in those categories), and updating our docs when I'm able to find the energy to do so.

That said, I don't think the portion of the pie I've cut out is a sustainable path for the CommComm; I could (and have in the past!) burn out, and in general I don't think a single person taking a large burden in a top level committee can meaningfully drive the volume of work that needs to be completed. I think what needs to happen for CommComm's long-term success is for the pie to _grow_. That's also not really something I can meaningfully impact outside of talking about it with others - it's something others need to invest in, or assert that we collectively _cannot_ invest in.

I'm not entirely sure if there's a specific outcome I want from this other than to start a discussion about CommComm, how we engage, and how we continue forward. I personally believe in CommComm and am proud to have been and continue to be involved in it and would genuinely be sad to see it die a slow and inactive death, but that is quite honestly the path I see us currently on.

**Comment by rachelnicole** [comment]
Going forward after this week I have the time availability and go ahead from my employer to be more deeply involved, so hopefully I'm able to alleviate some of the pressure for you and be able to contribute to growing the participation of people who would like to see the community succeed.

**Comment by joesepi** [comment]
@bnb and I used to have a weekly hour working meeting where we discussed this issue and how we could make things better. This meeting has fallen off the calendar in recent weeks but I think one idea to start to address this in a more open and collaborative manner is to have a weekly open meeting to improve the CommComm situation.

**Comment by joesepi** [comment]
I've finally created the doodle to meet. I've only put down times for this week, but I could expand it to next week too if we think that is a good idea. 

https://doodle.com/poll/z923nywufxbaxkrf

@nodejs/community-committee

**Comment by mhdawson** [comment]
I think we agreed in the meeting this week that we'd use the regular time for the next CommComm meeting intead.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
