### ISSUE TITLE
Create official secretary position

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#64]
I've been thinking about this for a while now, and I think we should create an official secretary role in CommComm. This person (people?) would serve as the official note taker during meetings. This person would be voted on in the same way as chairperson, and would also be called out in the README as holding this role so we can properly give attribution and thanks for this role. It's a really important and thankless role, and I think we should recognize those that decide to take this on.

**Comment by renrutnnej** [comment]
I was thinking about this same thing during the meeting yesterday, having experienced firsthand how difficult it is to run a meeting and record it. I’m interested in volunteering for the role, since I regularly review WG agenda notes across the project for recaps in the community newsletter. That said I’m not a CommComm member so I don’t know if I would even be eligible. 😬

**Comment by nebrius** [comment]
> I was thinking about this same thing during the meeting yesterday, having experienced firsthand how difficult it is to run a meeting and record it. I’m interested in volunteering for the role, since I regularly review WG agenda notes across the project for recaps in the community newsletter

Thank you @renrutnnej! Let's wait just a bit more to give anyone else a chance to speak up who may be interested in the role before we confirm you, but I'm sure I speak for everyone when I say we'd be happy to have you!

> That said I’m not a CommComm member so I don’t know if I would even be eligible. 😬

This is a thing that can be changed 😉

**Comment by nebrius** [comment]
I'm going to recommend we add a cutoff of, say, June 6th for nominations so that we can vote (if need be) at the next CommComm meeting on June 8th, or otherwise confirm Jenn in time for the June 8th meeting.

Does this sound good everyone?

**Comment by bnb** [comment]
I'd also be happy to participate in this role - I've recently grown to taking detailed notes for most of the Node.js meetings I attend, and am confident in my ability to contribute in this manner. Like Jenn, though, I'm not an official member yet. 😁

**Comment by nebrius** [comment]
Thanks for stepping up @bnb.

Since we have two candidates, we'll need to schedule a vote now. Thinking about it more, we shouldn't vote in the meeting for privacy reasons. @mikeal, once nominations are closed on the 6th, can we get a ballot set up like we did for the TSC director election?

**Comment by nebrius** [comment]
Nominations are now closed, and we have two candidates: @renrutnnej and @bnb!

Since we only have two candidates, we will do a winner-take-all vote among the voting members of CommComm. I will be sending out the ballot tomorrow using ballot bin before the meeting, and the election will be open for a week.

I will be sending the ballot to your email address listed in your GitHub profile, however there are a few folks that do not have an email address listed. Can @gr2m and @jpwesselink email me at bryan@nebri.us with their preferred address?

**Comment by nebrius** [comment]
Another question: how long should the term be for? A year is pretty typical for most elected positions in Node.js, but we can make it whatever we want.

**Comment by mhdawson** [comment]
Just a thought, feel free to ignore.  Would it make sense to share the position? One person is unlikely to be able to make all of the meetings and since its great that we have 2 people willing to take the minutes maybe we can maximize likelihood of getting coverage for all meetings and  share the load ?

**Comment by nebrius** [comment]
I can get behind sharing. @renrutnnej and @bnb, is this ok with you?

Do we want this to be completely shared between the two, or should there be a "primary" and "secondary" position to reduce stepping on toes?

**Comment by bnb** [comment]
@nebrius Sounds good to me. 👍 

From my experience in these kinds of community Node.js settings shared responsibility works best - I've not really ever seen stepping on toes and being unwilling to compromise and work together (the Evangelism WG is a great example of this), and it enables an equal sense of responsibility and ownership.

That said, I have nothing against "primary" and "secondary" roles.

**Comment by gr2m** [comment]
I’m okay with having a minute taking team. I think from the CommComm perspective it might be nice to have one person being in charge though, that person would be responsible to make sure that there is always someone in the meeting to take notes. I guess the same that you mean with the "primary" role. Other than that, I don’t mind how many people are helping out, I’d be happy to jump in, too if needed some time :)

**Comment by hackygolucky** [comment]
Done and working well!
