### ISSUE TITLE
Let's review current status of nodejs.dev work

### ISSUE THREAD

**Issue by designMoreWeb** [nodejs/community-committee#656]
Edit (@joesepi): Let's take a few minutes at a CommComm meeting to review the current status of nodejs.dev work. The team has been focused on an MVP of the following pages and while the progress has been good (and we want to show that), we also could use some decision making to unblock a couple PRs and issues.

Thanks!
</edit>

Website Redesign list of the PR's that need to be reviewed. 

Home Page: 
- [SVG ICONS](https://github.com/nodejs/nodejs.dev/pull/914)
- [Add Electron and other open js foundation project logos](https://github.com/nodejs/nodejs.dev/pull/1013)
- [Getting started section to homepage](https://github.com/nodejs/nodejs.dev/pull/1019)
- [Please note:Newsletter sign up discussion](https://github.com/nodejs/nodejs.dev/pull/331)

Community Page:
- [Page is wrong styling](https://github.com/nodejs/nodejs.dev/pull/1051)
- [Page is partially styled](https://github.com/nodejs/nodejs.dev/pull/1025)

Documentation page is completed
Downloads page is completed

**Comment by bnb** [comment]
I'm mildly confused where some of these requests are coming from. This kind of review is typically what you'd do in team/initiative meetings, not committee meetings.

Is there a specific reason the team has decided to bring it to the committee as a synchronous meeting request and not doing it within the team? Is there a barrier for the team in making these decisions independently?

**Comment by benhalverson** [comment]
I've tried pointing this out a few times. There maybe some confusion on what the team is allowed to make decisions on. 
It could also be low participation in the meetings and in the Github issues.  

The documentation page is not complete. Lots of broken links exist for [reasons](https://github.com/nodejs/community-committee/issues/656)

**Comment by bnb** [comment]
As is true of any team, initiative, or working group in Node.js, y'all are enabled to make decisions as the team. You don't need anyone's approval, regardless of whether or not folks provide feedback. There's been consistent outreach to CommComm and TSC members for validation, which has been provided upon request.

**Comment by joesepi** [comment]
I think this issue is good to close now. If the website redesign team has any questions, we can ask in an issue and always feel free to reach out to me. I am trying to attend meetings and be involved when I can. Cheers, friends.
