### ISSUE TITLE
Changing Default Branch

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#657]
Just wanted to give @nodejs/community-committee a heads up that I'm going to attempt to update the default branch to `main` in a bit here. I'll be happy to do the work of retargeting PRs, but wanted to provide a heads up that I'm going to pull the trigger on that here soon.

I've done this on a number of repos, including some in the Node.js org, painlessly so don't expect any kind of issue - it's pretty straightforward.

If folks have any objection, please feel free to voice it here.

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
Done - apparently you don't need to do it manually anymore.
