### ISSUE TITLE
CommComm work catchall for light agenda days

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#664]
@bnb and I talked about doing some work on meeting days when there is little to no agenda.

Please drop your work suggestions here and we can build out specific issues if need be.

**Comment by bnb** [comment]
Working on meta documents would be nice. There's a decent number of documents that are somewhat outdated, and processes or goals we were hopeful to implement but never actually did.

**Comment by bnb** [comment]
Updating the CommComm section on the current website.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
