### ISSUE TITLE
[announcement/share] Node.js Frontend for Android

### ISSUE THREAD

**Issue by warren-bank** [nodejs/community-committee#665]
Hi. I'm not sure if this is the best place to post this, but I just wanted to share a link to an [Android app](https://github.com/warren-bank/Android-NodeJS-Frontend) that I just [released](https://github.com/warren-bank/Android-NodeJS-Frontend/releases).

It packages a Node.js [native library](https://github.com/JaneaSystems/nodejs-mobile) and adds a frontend that makes it easy to configure it to run JS apps from external storage.

I think of this app in the same way as a REESE'S Peanut Butter Cup; it combines my 2x favorite things (Node.js and Android), and makes them even better together! :smiley:

**Comment by bnb** [comment]
Congrats on your release!

There's not particularly a correct place for sharing such a thing in the project. This repo is specifically for work of the committee. This has been open for a bit, so I'm going to close it.
