### ISSUE TITLE
Add Issue URL to Node.js CommComm Meeting Recording

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#67]
Just noticed that the Meeting Issue link was not added to the description of the second Hangouts On Air meeting. I know there was technical difficulty with getting it to go live, so I just wanted to ask if it could be added.

Video URL: https://www.youtube.com/watch?v=EOix1rU7s_Y
Meeting Issue URL: https://github.com/nodejs/community-committee/issues/62

**Comment by nebrius** [comment]
Added, thanks
