### ISSUE TITLE
When do we do the election of CPC Voting member from CommComm?

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#670]
This question came up in today's meeting. We should sort this out.

**Comment by joesepi** [comment]
Previous election was in March. :) 

https://github.com/nodejs/community-committee/issues/586

**Comment by bnb** [comment]
We should get this going again, @joesepi. I'll set one up now.

**Comment by bnb** [comment]
Done: https://github.com/nodejs/community-committee/issues/675
