### ISSUE TITLE
New CommComm Mentee skill requirements

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#673]
The @nodejs/mentorship team is working towards finding a mentee for the Community Committee team. Let's use this issue to gather skill requirements that would be helpful for this role.

I'll start...

Skill requirements:
- basic understanding of github issues, pull requests and code/file/document management.
- ability to communicate clearly

**Comment by GrooveCS** [comment]
Hi @joesepi,

Please let me know if I submit to applications. It was not my intent, yet could not remember later in the day.

**Comment by joesepi** [comment]
I'm closing this until further notice. We will consider a mentee opportunity at a later date. Thanks all.
