### ISSUE TITLE
OpenJS Foundation Cross-Project Council - Node.js CommComm Seat 2021 Election

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#675]
It’s time to elect the Cross-Project-Council voting representatives for next term which starts on April 1st 2020. CommComm's representative is @joesepi.

Timeline is:
* **April 13th:** Call for nominations for both CPC representatives
    * @nodejs/community-committee, please self-nominate in this issue
* **April 20th:** Close nominations and open balloting for CPC representative
* **April 23rd:** Close balloting and announce CPC representative
* **April 23rd:** Handover
* **May 1st:** Transition complete

Please note the expectations of the voting CPC representative: [CPC-CHARTER.md#voting-members](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members)

Also note: any member of the Node.js org can participate in the Cross Project Council as a regular member, as is defined in [CPC-CHARTER.md#voting-members](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#regular-members)

Similar to the practices in Node.js, the CPC follows the consensus seeking model and there is little difference between a voting rep of a project and a regular member. Becoming a regular member could be a good way to get involved if one is unsure of running for a voting member.

**Comment by joesepi** [comment]
I would be happy to continue. Consider this my self nomination. Thanks!

**Comment by bnb** [comment]
a reminder @nodejs/community-committee, today is the last day for self-nomination.

**Comment by bnb** [comment]
Since he ran unopposed, @joesepi will continue in this position. Congrats, @joesepi.
