### ISSUE TITLE
Create proposal for thread locking guidelines

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#68]
Sometimes it's necessary to lock a thread, as we did recently in nodejs/node. Other times, it's more appropriate to leave the thread unlocked but moderate certain users. We currently do not have any guidelines on when we should lock vs moderating individuals, nor do we have guidelines for collaborators on how to engage in a locked thread.

Let's get some discussion going here on this and come up with a proposal!

**Comment by Trott** [comment]
We also need a procedure or policy guidelines on if/how/when to *unlock* a thread.

**Comment by nebrius** [comment]
An issue brought up in another conversation:

What should we do with threads that are simultaneously a) contentious with multiple bad actors (typical reasons to lock a thread) but b) there is also legitimate conversation going on.

There was a suggestion for a given specific case that we lock the thread and open a new issue that's more targeted specifically to the productive conversation going on.

I suspect that will often be the right answer, but I'm not really certain. What does everyone else think?

**Comment by mikeal** [comment]
There's a few things that complicate this issue. The first is that thread locking has been used for a few different use cases: restricting a thread to collaborators **and** signaling that *all* comments should end. I would propose that we differentiate with locking vs. lock+close.

In both cases it's unclear *who* should be making such a large and consequential decision. In some cases locking is uncontroversial, but we've seen others that are borderline where some people think we should continue the discussion and others are ready to shut it down and move on.

I also think it would be far too much of a burden to reach consensus, or something approaching it, before locking a thread. In many cases this is used to de-escalate a thread and multi-day processes just aren't effective enough.

I think a lot of the concern over the effects of locking/closing are mitigated when you create a new thread that is more specifically scoped. Starting over is a good de-escalation strategy, and better scoping allows the people that were moderating more latitude to moderate out of scope comments.

I also don't think that (lock+close) without another better scoped issue being logged should be a general practice, particularly if the author of a new issue is locking and closing immediately. The reason we have public issues is to encourage discussion, we have other mechanisms for announcements with much wider audiences (twitter, blog, etc). In the cases where an issue is so out of scope that it needs to be closed we often just close them and don't see much of a need to lock, the closing alone is enough of a signal that the conversation is over.

**Comment by mhdawson** [comment]
As part of our standard practice we should @ mention the people who were contributing productively to the conversation in the new thread.

**Comment by bnb** [comment]
Can this thread be closed? Not seeing any forward movement on it and it seems that this discussion should probably go in nodejs/admin if it does need further context.

**Comment by Trott** [comment]
> Can this thread be closed? Not seeing any forward movement on it and it seems that this discussion should probably go in nodejs/admin if it does need further context.

Pinging @nodejs/moderation ...

**Comment by benjamingr** [comment]
We discussed it in the last mod team meeting. I suggest we continue this discussion within the team and bring a concrete proposal (or explicitly don't bring one) to the TSC.

**Comment by Trott** [comment]
> We discussed it in the last mod team meeting. I suggest we continue this discussion within the team and bring a concrete proposal (or explicitly don't bring one) to the TSC.

Cool. Sounds to me like this can be closed then. If the Moderation Team wants an issue to track it, a new one can be opened in nodejs/admin.

**Comment by Trott** [comment]
(Closing. Feel free to re-open or comment if you think that's the wrong thing to do!)

**Comment by Trott** [comment]
(Re-opening. Sorry. I thought this was the TSC repo. I'll leave it to comm comm folks to figure out whether or not to close.)

**Comment by Trott** [comment]
(Closed by accident. Leaving it to Comm Comm to decide if they want to close it or not.)

**Comment by bnb** [comment]
@Trott Yep, I think we're good to close this - opening a new issue in nodejs/admin is a +1 from me if further discussion is needed. If an issue is created, please reference this one for historical context around prior discussions. 👍
