### ISSUE TITLE
Community Committee Meeting 2017-06-08

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#70]
Node.js Foundation Community Committee (CommComm) Meeting 2017-06-08
--------------------------------------

## Time

**UTC Thu 08-Jun-2017 20:30 (08:30 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 08-Jun-2017 13:30 (01:30 PM) |
| US / Mountain | Thu 08-Jun-2017 14:30 (02:30 PM) |
| US / Central  | Thu 08-Jun-2017 15:30 (03:30 PM) |
| US / Eastern  | Thu 08-Jun-2017 16:30 (04:30 PM) |
| Amsterdam     | Thu 08-Jun-2017 22:30 (10:30 PM) |
| Moscow        | Thu 08-Jun-2017 23:30 (11:30 PM) |
| Chennai       | Fri 09-Jun-2017 02:00 (02:00 AM) |
| Tokyo         | Fri 09-Jun-2017 05:30 (05:30 AM) |
| Sydney        | Fri 09-Jun-2017 06:30 (06:30 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Community%20Committee%20(CommComm)+Meeting+2017-06-08&iso=20170608T20
* or http://www.wolframalpha.com/input/?i=8pm+UTC%2C+Jun+08%2C+2017+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/14Pd6e40n1wPEuRBknDJUFwlf9XDhWI94jCgMEvTfVS4/>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/1urhinDNJK-EEMziNob8-mlsOEZM_zecluDIgBA6kVOw/>_

## Agenda

Extracted from **cc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/community-committee

* Create official secretary position [#64](https://github.com/nodejs/community-committee/issues/64)
* Move Node Together Repo as an org under CommComm [#63](https://github.com/nodejs/community-committee/issues/63)
* Request to move nodejs/education under CommComm [#46](https://github.com/nodejs/community-committee/issues/46)
* Adding folks as members [#38](https://github.com/nodejs/community-committee/issues/38)
* Moderation shortage [#33](https://github.com/nodejs/community-committee/issues/33)

### nodejs/nodejs-collection

* Refreshing Node.js Collection Review Process and Gathering Technical Editors [#1](https://github.com/nodejs/nodejs-collection/issues/1)

## Invited

* Ashley Williams @ashleygwilliams (CommComm)
* Bryan Hughes @nebrius (CommComm)
* Emily Rose @emilyrose (CommComm)
* Gregor Martynus @gr2m (CommComm)
* Jenn Turner @renrutnnej (observer)
* JP Wesselink @jpwesselink (CommComm)
* Mikeal Rogers @mikeal (observer/Node.js Foundation)
* Myles Borins @MylesBorins (CommComm)
* Penny Hugger @pup (observer)
* Rachel White @rachelnicole (CommComm)
* Richard Littauer @RichardLitt (observer)
* Rod Vagg @rvagg (CommComm)
* Tracy Hinds @hackygolucky (CommComm)
* William Kapke @williamkapke (CommComm)
* Michelle Garrett (msmichellegar) (CommComm)
* Micheal Dawson @mhdawson (observer)
* Tierny Cyren @bnb (observer)

## Notes

The agenda comes from issues labelled with `cc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Link to view the event: https://www.youtube.com/watch?v=r5gL9sL3vyM
Link to participate: https://hangouts.google.com/hangouts/_/ytl/uXRMUBslCf5uMiqB95YK3gdaTARSxy4wtDxOFy9ET_c=?eid=100598160817214911030

A standing invitation exists for all @nodejs/TSC members who are not also CommComm members to attend in observer capacity.

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

**Comment by pup** [comment]
i can make it today!!

**Comment by gr2m** [comment]
I’ve been sick this week and can’t look much on the screen. I’ll try to attend but can’t promise. I’ll go trough the agenda issues though and if I have any input / thoughts I’ll comment on them

**Comment by bnb** [comment]
@nebrius Can I be added as an observer, as I have for previous meetings? 🤔

**Comment by MylesBorins** [comment]
I may not be able to join... but if I can it will be about 20 - 30 minutes into the meeting

**Comment by hackygolucky** [comment]
@bnb got ya!

**Comment by rachelnicole** [comment]
I can't make this week I'm in Atlantic City making bad life choices

**Comment by nebrius** [comment]
Sorry, I thought I had added you to the list @bnb, but looks like I forgot to update it here. Thanks for adding him @hackygolucky.

**Comment by williamkapke** [comment]
I will not be able to attend- I need to go get an x-ray on my knee.

**Comment by renrutnnej** [comment]
I'm fairly certain I'll be late but I'll be there.

**Comment by bnb** [comment]
@nebrius At the request of @ZibbyKeaton, could https://github.com/nodejs/nodejs-collection/issues/1 be added to the agenda? She cannot make it today but asked me to see if it could be discussed. 🙏

**Comment by nebrius** [comment]
Agenda updated @bnb

**Comment by nebrius** [comment]
Participation links added to meeting description

**Comment by pup** [comment]
hahaha completely forgot that i had a family thing today and didn't realize that i was missing the meeting until now.... timezones are bad

**Comment by nebrius** [comment]
Meeting notes have been landed, closing.
