### ISSUE TITLE
Update phrasing from "Collaborator" to "Member" everywhere

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#71]
Was reviewing [CONTRIBUTING.md](https://github.com/nodejs/community-committee/blob/de8ac87697bb2b3baf0409331488a6ab67841d9f/CONTRIBUTING.md) as a part of creating a new Contributing guide, and I noticed that the word "Collaborator" was still being used - instead of "Member" (ref: https://github.com/nodejs/community-committee/pull/49).

Here are the two documents where this word is still in place:
- [CONTRIBUTING.md](https://github.com/nodejs/community-committee/blob/de8ac87697bb2b3baf0409331488a6ab67841d9f/CONTRIBUTING.md)
- [COLLABORATOR_GUIDE.md](https://github.com/nodejs/community-committee/blob/de8ac87697bb2b3baf0409331488a6ab67841d9f/COLLABORATOR_GUIDE.md)

If the Community Committee has moved away from the idea of a "Collaborator", these should probably be updated 🤔

**Comment by nebrius** [comment]
Collaborators and members are different things and we need to keep references to both. Perhaps we need to clarify that in the docs?

**Comment by dshaw** [comment]
@bnb: Is this issue still valid? Reviewing https://github.com/nodejs/community-committee/blob/master/CONTRIBUTING.md for https://github.com/nodejs/user-feedback, it appears these files have been significantly updated.

**Comment by bnb** [comment]
@dshaw I brought this up recently somewhere, though I can't find - as far as I can tell we've effectively not used the "Collaborator" role. I'll likely end up bringing this up as an agenda item to discuss, but for now this issue can be closed.
