### ISSUE TITLE
Stated Code of Conduct Differs in Collaborator Guide/Code of Conduct file

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#72]
Was reviewing and noticed that there were two places where a Code of Conduct is stated - one in the [COLLABORATOR_GUIDE.md](https://github.com/nodejs/community-committee/blob/master/COLLABORATOR_GUIDE.md#code-of-conduct) file and one in the [CODE_OF_CONDUCT.md](https://github.com/nodejs/community-committee/blob/master/CODE_OF_CONDUCT.md#conduct) file. 

I read a bit of the two, and they vary slightly. To ensure that there is no confusion or pointing to an incorrect Code of Conduct, should we update the Code of Conduct to be the same in both places?

Since the [CODE_OF_CONDUCT.md](https://github.com/nodejs/community-committee/blob/master/CODE_OF_CONDUCT.md#conduct) file seems to be more detailed, I'm guessing that's the _intended_ primary Code of Conduct.

**Comment by nebrius** [comment]
Both instances should be modified to look like this: https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md

**Comment by bnb** [comment]
This can be closed, as #78 has been merged. https://github.com/nodejs/community-committee/pull/78
