### ISSUE TITLE
CommComm Chairperson Election for 2021-2022

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#729]
It's now time for the CommComm 2021-2022 election, @nodejs/community-committee.

Please submit your self-nominations as comments in this issue (other comments are welcome!) by the time it is posted on Monday, August 24. I will create Q&A issues for CommComm chairpeople once this period ends.

> The CC will elect from amongst voting CC members a CC Chairperson to work on building an agenda for CC meetings [...] The CC shall hold annual elections to select a CC Chairperson [...]; there are no limits on the number of terms a CC Chairperson [...] may serve.

Expected responsibilities include but are not limited to:
- Create each meeting's agenda. 
- Create the event and make sure it is live-streamed in YouTube. 
- Chair and facilitate each meeting. It is the chairperson's responsibility to ensure that the meeting stays on track, sticks to the agenda, and finishes within the allotted time.
- Collaborate with the CPC Reps
- Collaborate with the TSC Chair
- Coordinate efforts in shared repos, as listed in Admin
- Managing the CommComm 1Password

I would recommend having _at least_ 10 hours of your working time available to be dedicated to CommComm for the next 52 weeks. I would also recommend being able to be flexible up to 20 hours of your working time during any of those weeks. All voting members of the CommComm are eligible to self-nominate.

I will not be re-running this year.

## Nominated candidates:
- TBD

**Comment by bnb** [comment]
I'm deeply concerned that we've still not had any nominations.

@nodejs/community-committee please self-nominate by 11:59pm PST tomorrow.

If we have no self-nominations, I'd highly recommend that we evaluate the utility and necessity of CommComm.

**Comment by bnb** [comment]
We didn't receive any self-nominations in the period nor for a week after 🙃 

We can discuss what to do, but this reinforces my concerns about the long-term sustainability of CommComm.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
