### ISSUE TITLE
Mentorship Initiative reaching out to Node.js community

### ISSUE THREAD

**Issue by nstme** [nodejs/community-committee#732]
Are there good official channels in the organization we can utilize to let all of the internal members/groups of Node.js that [@nodejs/mentorship](https://github.com/nodejs/mentorship) is accepting applications for Mentors?
We also wouldn't like this to be seen as spam or solicitation, so if you have any ideas of how to achieve our goal of spreading awareness of our Mentorship Initiative, please let us know.
Thank you.

**Comment by mhdawson** [comment]
@nstme one thought is a discussion in the Node.js core repo.

**Comment by bnb** [comment]
+1 to @mhdawson's recommendation above.

**Comment by MrSlimCoder** [comment]
Hi I'm interested to be a mentor.

**Comment by DemonDadZeu** [comment]
I’m interested in being mentored and would like to know how I can communicate directly with someone so I can get started with the nodjes community.

**Comment by Trott** [comment]
I've unarchived this repo so I can close all PRs and issues before re-archiving.
