### ISSUE TITLE
Add "Good First Contribution" Label to CommComm repo

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#74]
Would love to get a "Good First Contribution" label added to the Community Committee repo by someone who has the privilege. I'm working on a draft of the contributing guide, and I'd love to be able to link to it as one of the items.

**Comment by bnb** [comment]
Forgot to mention why I suggested "Good First Contribution" as the name: that's the one that the [nodejs/node repo is using](https://github.com/nodejs/node/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+contribution%22), and I think it would be fantastic to be able to keep consistency across the repos.

**Comment by nebrius** [comment]
Done
