### ISSUE TITLE
Collaborator Guide has references to produced code and the website project

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#76]
Looking through the [Collaborator's Guide](https://github.com/nodejs/community-committee/blob/master/COLLABORATOR_GUIDE.md#nodejs-collaborator-guide) a bit, I noticed two references to the "website project" and several references to code contributions (like that executable code needs to run through the CI process).

I'm guessing this was a simple C&P from the website's Collaborator Guide with edits , and these parts were simply missed. 😊

**Comment by nebrius** [comment]
Yep, just need to correct those and submit a PR.
