### ISSUE TITLE
CONTRIBUTING and GOVERNANCE links broken in README

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#8]
The links to GOVERNANCE and CONTRIBUTING are both broken (send you to a 404) in the README.md. 

Took a look, and this is because of the file extension on both files - the actual extensions are `.MD` and the linked extensions are `.md`. What you typically see is `.md`, but not sure if changing the file extension at this point would be destructive to the commit history.

**Comment by nebrius** [comment]
Thanks for the catch! Looking at the other repos, we consistently use `.md`, so I agree let's rename the link in README.md like you did in your fork (want to submit a PR?)

**Comment by bnb** [comment]
@nebrius Submitted - was planning on submitting yesterday, but did it through GitHub's interface and it didn't appear in my repos list or in this issue (like it does now, apparently).

Anyway, the PR has been submitted 😊

**Comment by nebrius** [comment]
Thanks for the PR! I noticed that the links are still broken, so I submitted another PR to clean up the remaining issues: https://github.com/nodejs/community-committee/pull/10

**Comment by nebrius** [comment]
Links are now fixed and working, thanks again for the issue! Please feel free to reopen if you still notice anything weird.
