### ISSUE TITLE
Meeting 2017-06-22 Community Committee (CommComm)

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#80]
Meeting 2017-06-22 Community Committee (CommComm)
--------------------------------------

## Time

**UTC Thu 22-Jun-2017 20:30 (08:30 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Thu 22-Jun-2017 13:30 (01:30 PM) |
| US / Mountain | Thu 22-Jun-2017 14:30 (02:30 PM) |
| US / Central  | Thu 22-Jun-2017 15:30 (03:30 PM) |
| US / Eastern  | Thu 22-Jun-2017 16:30 (04:30 PM) |
| Amsterdam     | Thu 22-Jun-2017 22:30 (10:30 PM) |
| Moscow        | Thu 22-Jun-2017 23:30 (11:30 PM) |
| Chennai       | Fri 23-Jun-2017 02:00 (02:00 AM) |
| Tokyo         | Fri 23-Jun-2017 05:30 (05:30 AM) |
| Sydney        | Fri 23-Jun-2017 06:30 (06:30 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation++Meeting+2017-06-22&iso=20170622T20
* or http://www.wolframalpha.com/input/?i=8pm+UTC%2C+Jun+22%2C+2017+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1GXbfPhfbLTr7g9Hp7YP-M60ux_Ua2z8XRXg__me4u4k/>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/14Pd6e40n1wPEuRBknDJUFwlf9XDhWI94jCgMEvTfVS4/>_

## Agenda

Extracted from **cc-agenda** labelled issues and pull requests from the **nodejs org** prior to the meeting.

### nodejs/community-committee

* Adding Jenn and Tierny as members [#77](https://github.com/nodejs/community-committee/pull/77)
* Move Node Together Repo as an org under CommComm [#63](https://github.com/nodejs/community-committee/issues/63)
* Request to move nodejs/education under CommComm [#46](https://github.com/nodejs/community-committee/issues/46)
* Adding folks as members [#38](https://github.com/nodejs/community-committee/issues/38)

## Invited

* Ashley Williams @ashleygwilliams (CommComm)
* Bryan Hughes @nebrius (CommComm)
* Emily Rose @emilyrose (CommComm)
* Gregor Martynus @gr2m (CommComm)
* Jenn Turner @renrutnnej (observer)
* JP Wesselink @jpwesselink (CommComm)
* Mikeal Rogers @mikeal (observer/Node.js Foundation)
* Myles Borins @MylesBorins (CommComm)
* Olivia Hugger @pup (observer)
* Rachel White @rachelnicole (CommComm)
* Richard Littauer @RichardLitt (observer)
* Rod Vagg @rvagg (CommComm)
* Tracy Hinds @hackygolucky (CommComm)
* William Kapke @williamkapke (CommComm)
* Michelle Garrett (msmichellegar) (CommComm)
* Micheal Dawson @mhdawson (observer)
* Tierney Cyren @bnb (observer)

## Notes

The agenda comes from issues labelled with `cc-agenda` across **all of the repositories in the nodejs org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

Google Hangouts; link will be posted here shortly before the meeting starts.

A standing invitation exists for all @nodejs/tsc members who are not also CommComm members to attend in observer capacity.

## Public participation

We stream our conference call straight to YouTube so anyone can listen to it live, it should start playing at **https://www.youtube.com/c/nodejs+foundation/live** when we turn it on. There's usually a short cat-herding time at the start of the meeting and then occasionally we have some quick private business to attend to before we can start recording & streaming. So be patient and it should show up.

**Comment by rachelnicole** [comment]
I will be on a plane. :(

**Comment by nebrius** [comment]
Travel safe @rachelnicole!

**Comment by pup** [comment]
i'll be there! (also, could someone update my name in the OP to say olivia instead of penny? thanks)

**Comment by nebrius** [comment]
Done @pup!

**Comment by bnb** [comment]
Not sure if I will be able to make it today - will try to carve out the time 😅

**Comment by bnb** [comment]
>Tierny Cyren @bnb (observer)
Missed an e in my name 😁 `Tierny` > `Tierney`

No worries, happens to literally everyone.

**Comment by nebrius** [comment]
Sorry about that @bnbm fixed!

**Comment by williamkapke** [comment]
I have a conflict today that I cannot get out of. @ashleygwilliams I hope you can make it.

**Comment by bnb** [comment]
Not going to be able to make it, unfortunately.

**Comment by mhdawson** [comment]
I'll be there.

**Comment by nebrius** [comment]
Life stream: https://www.youtube.com/watch?v=gwSWLXD2nLw
Hangout link: https://hangouts.google.com/hangouts/_/ytl/fh7qIfuluLAuPrb1t0mCy8QLObxdidBbgP11PBH9GRE=?eid=100598160817214911030

**Comment by pup** [comment]
@nebrius i'm getting a 403?

**Comment by renrutnnej** [comment]
saaaaaame

**Comment by nebrius** [comment]
Hmmm...here's the full URL I'm at: https://hangouts.google.com/hangouts/_/ytl/fh7qIfuluLAuPrb1t0mCy8QLObxdidBbgP11PBH9GRE=?eid=100598160817214911030&hl=en_US&authuser=1

Note, you may need to fiddle with the `authuser` and `hl` parameters, as they're specific to me. Let me know if you're still having trouble

**Comment by pup** [comment]
can't get in, even when changing or removing the parameters :/

**Comment by renrutnnej** [comment]
Same, I tried those too 😭

**Comment by nebrius** [comment]
hmm, ok, let me restart it

**Comment by nebrius** [comment]
ok, try it again. It's the same URL so far: https://hangouts.google.com/hangouts/_/ytl/fh7qIfuluLAuPrb1t0mCy8QLObxdidBbgP11PBH9GRE=?eid=100598160817214911030&hl=en_US&authuser=1

If this doesn't work, I'll try deleting and recreating the event

**Comment by pup** [comment]
nope!

**Comment by renrutnnej** [comment]
Is anyone getting through?

**Comment by nebrius** [comment]
hmm, @richardlitt was able to join. Maybe try https://hangouts.google.com/hangouts/_/ytl/fh7qIfuluLAuPrb1t0mCy8QLObxdidBbgP11PBH9GRE=?eid=100598160817214911030&hl=en_US?

**Comment by RichardLitt** [comment]
Same with Michael Dawson. Strange?

**Comment by pup** [comment]
do you have to do a thing with adding email addresses for authentication maybe?

**Comment by nebrius** [comment]
I know the `authuser` part can make things complicated

**Comment by renrutnnej** [comment]
I can't even get to the screen where you can change your Google account, it automatically 403s

**Comment by pup** [comment]
yep same here

**Comment by pup** [comment]
this link works: https://hangouts.google.com/hangouts/_/ytl/fh7qIfuluLAuPrb1t0mCy8QLObxdidBbgP11PBH9GRE=

**Comment by nebrius** [comment]
Are you already logged in to YouTube? You need to be logged in first before it will work AFAIK

**Comment by renrutnnej** [comment]
Thank you @pup, that worked for me <3

**Comment by pup** [comment]
however, i will need to download google chrome first, so you all can start without me. ill be there in a couple mins

**Comment by nebrius** [comment]
Minutes landed, closing this issue now. Another successful meeting done!
