### ISSUE TITLE
CommComm Member Travel Fund allocation request for 2017

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/community-committee#82]
### CommComm Travel Allocation Request for 2017 for Board deck

We would like to encourage as many collaborators to attend/represent at Collab Summit and other relevant events for the remainder of this year, and part of that is making sure it is known that everyone meeting in one place is awesome(and valued) on our non-technical contribution side as well! This estimate is with the hope that all of this will not be needed, but we'll want to heavily evangelize this to all collaborators because we've been hearing a lot of feedback of the financial challenge it can be to attend these events. Calculating for members of CommComm and the Evangelism WG and reducing the count for employees of corporate members, with a North America to non-NA ratio at 60/40, and estimated at a $500 domestic/$1000 international flight rate, I expect at 2 nights' hotel:

***a general rule for our travel funds is that if you are an employee of a corporate member in Node.js, we ask that you refrain from requesting from the public fund and instead ask your employer. We are happy to help provide information on the value of these events.

| Whereabouts | Count  |  Flight Cost | Lodging  | 
|:-:|---|---|---|
| North America | 12 |  $500 | $210 |
| Everywhere Else | 8 | $1000  |  $210 |
| Total | 20 | $14,000  |  $8200 |

Total Allocation Request: $22, 200

**This allocation will be contingent upon the Board's approval of the fund being established in #81**

**Comment by pup** [comment]
i won't make it to the vancouver collab because it's in the same week as my first week of university, so that's roughly $1k less

**Comment by nebrius** [comment]
$22k sounds reasonable to me.

@pup even if you can't make it, there's always a chance we'll get someone else from Europe who wants to attend. I'd prefer to keep you counted for now, for statistical reasons if nothing else.

**Comment by pup** [comment]
@nebrius thats fair!

**Comment by bnb** [comment]
Will there be a collaborator's summit at this event? If so, and it follows the same structure we've done in the past, I'd like to request that hotel accommodations for that be included in this as well.

**Comment by nebrius** [comment]
> Will there be a collaborator's summit at this event? If so, and it follows the same structure we've done in the past, I'd like to request that hotel accommodations for that be included in this as well.

There will be a collaborator's summit right after Node Interactive in Vancouver in October, see https://github.com/nodejs/summit/issues/44 for more details.

Hotel is included, see the "Lodging" column. I do have a question though @hackygolucky, how many nights is that for? It sounds like one night to me, but we'll probably need three nights per person.

**Comment by mhdawson** [comment]
@nebrius I think the origin comment say its for 2 nights.

**Comment by nebrius** [comment]
@mhdawson ah, yes, you are correct.

I was thinking three nights so that people can arrive the day before and depart the day after the summit. Thinking about it further, two nights is probably sufficient for folks on the west coast, but I think it would be better to give folks with a long flight the ability to fly out the day after (unless you like red-eye flights of course!)

Thoughts?

**Comment by hackygolucky** [comment]
This whole thing is calculated for the Collaborators Summit only, for travel and lodging. I did not calculate for Node Interactive attendance or ticket registration, as even for collaborators it still costs $$$.

**Comment by nebrius** [comment]
> This whole thing is calculated for the Collaborators Summit only, for travel and lodging. I did not calculate for Node Interactive attendance or ticket registration, as even for collaborators it still costs $$$. If I calculated for that, each person would be nearly 5 nights' stay and the added reg cost. To note: this was not done for the TSC travel fund calculations either. I worried about the lack of neutrality of us calculating folks attending this conf and not other ones. Maybe that's nonsensical :-/

Ahh, I see, that makes sense. I think I still lean towards calculating three nights stay, aka assuming folks will _not_ be at the conference. That said, maybe it would make sense to use a proportion? We could assume that, say, 50% of people making use of this fund would be at the conference (and thus have the first night covered), and the other 50% would not. This would mean assuming 2.5 nights per person. What do you think?

**Comment by bnb** [comment]
@hackygolucky is there anything else that we need to do for this, or can we close it?

**Comment by hackygolucky** [comment]
This exists [in the Admin repo under joint responsibility of the TSC and CommComm](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md) for approving requests. Closing because it was approved as a joint effort via the Node.js Board of Directors for funding.
