### ISSUE TITLE
I'd like to join meetings as an observer

### ISSUE THREAD

**Issue by joesepi** [nodejs/community-committee#85]
Hi. I'm currently on the Node.js Foundation Marketing Committee. I've been wanting to be involved in the foundation more from a community and/or technical standpoint. I am currently moving to different team within IBM and figured now would be a good time to make a change. My goal is to participate in this committee and to start to contribute more technically as well. As a dev advocate for IBM, it may make sense for me to get involved with the evangelism group as well, but as I understand it, that group will be a part of this committee soon as well, correct? Irregardless*...

Thanks.

(* not a word)

**Comment by nebrius** [comment]
Hi @joesepi, we'd love to have you! I added you to the list :)

> As a dev advocate for IBM, it may make sense for me to get involved with the evangelism group as well, but as I understand it, that group will be a part of this committee soon as well, correct?

To clarify a bit, as I get this can be kinda confusing, the Evangelism will probably move _under_ CommComm soon, but not into it. The WG will continue to exist and operate as it does today as a distinct entity, but the reporting chain within the org will be different.

If you're interested in getting involved in evangelism, I'd recommend reaching out to them directly in addition to attending the CommComm meetings.

**Comment by joesepi** [comment]
Thank you for the clarity @nebrius. Will do. 👍

**Comment by nebrius** [comment]
Thanks @joesepi! I'm going to go ahead and close this issue, but feel free to reopen if you have more questions!
