### ISSUE TITLE
Request to move the Evangelism WG to CommComm

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#86]
Hi folks! I think most of you are already aware, but Evangelism has expressed interest in moving to CommComm.

We're still waiting on official signoff, but it looks like we have consensus from both [the Evangelism WG](https://github.com/nodejs/evangelism/issues/294) and [the CTC](https://github.com/nodejs/CTC/issues/145), who currently oversees the WG.

Are there any objections from @nodejs/community-committee to moving Evangelism under CommComm?

**Comment by nebrius** [comment]
Update, we have official signoff from the WG!

**Comment by bnb** [comment]
Per @Trott's comment (https://github.com/nodejs/CTC/issues/145#issuecomment-313581394), it looks like this can move forward on the CTC side.

**Comment by nebrius** [comment]
Yes, the CTC has officially signed off. Does anyone have any thoughts, concerns, or objections before we start making pull requests?

**Comment by RichardLitt** [comment]
Not that I know of. But if they did, they can raise those concerns during the PRs, which I think is probably a better place to voice concerns with salient points.

**Comment by nebrius** [comment]
I removed the `cc-agenda` label since we're now waiting on the PRs. I'm busy this week and next with conferences. I can submit the [necessary PRs defined in the moving guide](https://github.com/nodejs/community-committee/blob/master/documents/moving-across-committees.md), but it'll have to wait two weeks.

Is anyone else available and interested in submitting the necessary PRs? cc @nodejs/community-committee.

**Comment by bnb** [comment]
@nebrius Any further action needed from an Evangelism WG member or a CommComm member?

**Comment by nebrius** [comment]
@bnb, just gotta get the CTC to approve https://github.com/nodejs/CTC/pull/157, and for us to approve https://github.com/nodejs/community-committee/pull/92

**Comment by nebrius** [comment]
All PRs have been merged, and the move is now complete. Welcome Evangelism WG!
