### ISSUE TITLE
Create an email alias for CommComm?

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#89]
Currently, the CTC, TSC, and a few others have an [email alias on the iojs.org domain](https://github.com/nodejs/email/blob/master/iojs.org/aliases.json) that is used for a handful of purposes: sharing confidential information, reminding people to vote/review things, etc.

I think it would be worthwhile to create an alias for CommComm too that emails everyone here. It has also recently come to my attention that creating alias on the official nodejs.com domain is pretty straightforward (we used to be under the impression it was complicated).

What does everyone else think?

**Comment by mhdawson** [comment]
+1

**Comment by Fishrock123** [comment]
I'd be ok with an email being added.

> (we used to be under the impression it was complicated).

It's not difficult IIRC but we cannot automatically maintain it, so it is easiest to alias it to the io.js one which can do that automatically from the repo.

**Comment by renrutnnej** [comment]
+1

**Comment by bnb** [comment]
Thanks for that insight @Fishrock123. +1 to implementing this.

**Comment by renrutnnej** [comment]
+1

**Comment by nebrius** [comment]
> It's not difficult IIRC but we cannot automatically maintain it, so it is easiest to alias it to the io.js one which can do that automatically from the repo.

Ahh, good to know. Thanks for the insight @Fishrock123!

**Comment by nebrius** [comment]
@nodejs/community-committee can you let me know which email address you would like to use for this distribution list?

Please note that this email address will be publicly visible, so be sure to use one you don't mind being publicly visible in the README.md, similar to [how the TSC does it](https://github.com/nodejs/TSC#tsc-members).

If you would prefer to not have your email address listed publicly, please let me know and we'll see what else we can come up with.

**Comment by Fishrock123** [comment]
To clarify: listing it on the readme is a separate thing from aliasing, but the emails an alias forwards to **is** publicly visible on https://github.com/nodejs/email/blob/master/iojs.org/aliases.json.

**Comment by nebrius** [comment]
Related: https://github.com/nodejs/community-committee/issues/90

**Comment by gr2m** [comment]
add me as nodejs.commcomm@martynus.net

**Comment by bnb** [comment]
Could you please use `hello@bnb.im` for me 😄

**Comment by rachelnicole** [comment]
use my non-microsoft one, tracy has it.

**Comment by joesepi** [comment]
joesepi@gmail.com please and thank you.

**Comment by pup** [comment]
my email is `olivia@fastmail.com`!

**Comment by hackygolucky** [comment]
@Fishrock123 who admins the @iojs.org lists(if you aren't one)? It'd probably be helpful if I have direct contact. I don't want to mess this up 😅

**Comment by Fishrock123** [comment]
@hackygolucky No single person admins the @iojs.org lists, the alias just needs to be added with the emails to https://github.com/nodejs/email/blob/master/iojs.org/aliases.json (via a PR).

Setting up the @nodejs.org -> @iojs.org redirect is a separate thing. I am not sure how that is done, I think Mikeal was probably the last to touch that.

**Comment by RichardLitt** [comment]
`richard.littauer@gmail.com`, please.

**Comment by hackygolucky** [comment]
@nodejs/community-committee I want to be clear, from our last meeting, that emails provided here will be published in a public repo. Working on this today!

**Comment by hackygolucky** [comment]
https://github.com/nodejs/email/pull/46
