### ISSUE TITLE
list members' emails in README

### ISSUE THREAD

**Issue by pup** [nodejs/community-committee#90]
so, after #77 has landed, it might make sense to list the commcomm members' emails in the readme, just like the TSC, so that folks that have questions can individually contact us

**Comment by RichardLitt** [comment]
I'm curious. Has there been an issue with people being unable to individually contact commcomm members? Or, is there a need for this?

**Comment by pup** [comment]
@RichardLitt i was thinking it's more for prevention of those issues. like, the other top-level committees do a similar thing, so i'm assuming they've had a similar kind of issue before?

**Comment by bnb** [comment]
+1 for consistency with the TSC - maintaining this consistency is important from my point of view to keep uniformity and maintain quality across the committees.

**Comment by nebrius** [comment]
+1 for consistency too

**Comment by RichardLitt** [comment]
Alright! Works for me.

**Comment by renrutnnej** [comment]
+1

**Comment by pup** [comment]
@nodejs/community-committee if everyone is ok with #89 being a thing, does anyone mind if i create a PR for this using the same emails that are used for the email alias?

**Comment by nebrius** [comment]
Go for it @pup, and thank you!

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
FWIW, these emails can now be found in the [aliases](https://github.com/nodejs/email/blob/master/iojs.org/aliases.json) file in the emails repo - would be great to get this PR'ed!

**Comment by mikehostetler** [comment]
I took some time this morning to whip up this PR. I'm missing email addresses from @msmichellegar and @rachelnicole.

**Comment by mhdawson** [comment]
I think this can be close since it was PR'd in. Closing.  Please re-open if that was not the right thing to do.
