### ISSUE TITLE
Should we skip the July 20th meeting?

### ISSUE THREAD

**Issue by nebrius** [nodejs/community-committee#91]
Hi @nodejs/community-committee!

Currently we only have one item on the agenda for this week's meeting: Candidate "areas" for TSC and Community Committee  [#278](https://github.com/nodejs/TSC/issues/278).

Is there anything else that folks would like to discuss? If not, I propose we skip this week's meeting. Sound good?

**Comment by rachelnicole** [comment]
I have a conflict (like always ;_;), so I would appreciate it if we skipped.

**Comment by gr2m** [comment]
okay to skip from my side

**Comment by pup** [comment]
sure since we dont have consensus on the new member thing anyways

**Comment by pup** [comment]
oh wait i just saw that we do. nevermind

**Comment by RichardLitt** [comment]
Works for me.

**Comment by nebrius** [comment]
Ok, let's call it then. Our next meeting will be August 3rd, see you then!
