### ISSUE TITLE
Invite Interested Website WG members to Next CommComm meeting

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#95]
As requested by @fhemberger in https://github.com/nodejs/nodejs.org/issues/1297#issuecomment-315842723, I'd like to see if we can extend an invite to the @nodejs/website WG members who are interested in discussing website updates and a push on a new site/design.

**Comment by mikemaccana** [comment]
Interested!

**Comment by Fishrock123** [comment]
Which week is the next meeting? These always seem to conflict with TSC meetings.

Also is this for just website "Members" or website "Collaborators"?

**Comment by pup** [comment]
@Fishrock123 the next meeting is on the 3rd of august!

**Comment by sotayamashita** [comment]
@bnb  I am interested.

**Comment by fhemberger** [comment]
Thanks, that would be great.

At what time do you usually meet? With @bnb and @Fishrock123 (GMT-4), @pup and me (GMT+2) and @sotayamashita (GMT+9) we have a wide range to cover. 😀

**Comment by pup** [comment]
@fhemberger we meet at 10pm cest, which has worked even for me, but might be unfortunate for @sotayamashita (we haven't explored that yet since there's nobody from that timezone in commcomm)

**Comment by sotayamashita** [comment]
@pup I appreciate your concern.  What about 23:00 CEST? It's OK for me :+1:

**Comment by pup** [comment]
23:00 cest would work for me - what about you, @fhemberger?

**Comment by fhemberger** [comment]
@pup I can make it work as well.

**Comment by nebrius** [comment]
> Which week is the next meeting? These always seem to conflict with TSC meetings.

They intentionally alternate. Each CommComm meeting is on the off-week of TSC meetings.

> 23:00 cest would work for me - what about you, @fhemberger?

We can possibly make that work, we'll need to make sure that works for everyone else on CommComm.

**Comment by fhemberger** [comment]
So at what time is the meeting tomorrow? 23:00 CEST?
And how do we participate? Google Hangout? Something else?

**Comment by nebrius** [comment]
@fhemberger I'm about to post an issue with the schedule. It will be on Thursday, although unfortunately I didn't get a chance to coordinate with the rest of the committee, so it will still be at 20:30 UTC (22:30 CEST). I hope that's close enough!

**Comment by nebrius** [comment]
The action item from the last meeting was:

> Create issue in nodejs/nodejs.org to kick off a meeting with the involved parties (Leo, CommComm, Website WG, and Foundation)

Does anyone know if this has been done yet? If so, can we close this issue?

**Comment by fhemberger** [comment]
No, there isn't an issue in nodejs/nodejs.org.

**Comment by hackygolucky** [comment]
Tag I'm it, I think.

**Comment by hackygolucky** [comment]
Resulting issue opened and further action will be taken through the Website WG lens here https://github.com/nodejs/nodejs.org/issues/1338

**Comment by nebrius** [comment]
Thanks @hackygolucky!
