### ISSUE TITLE
Clarify / Clean-up CommComm Teams in Node.js org

### ISSUE THREAD

**Issue by bnb** [nodejs/community-committee#99]
Was looking for the CommComm team in the Node.js Org and saw that there were three different ones that are all for/about CommComm. It would be helpful if we could either clarify the purposes via updating names or cut out two of the three.

![image](https://user-images.githubusercontent.com/502396/28927290-2f19e3e4-7838-11e7-93d6-87de6d872013.png)

**Comment by pup** [comment]
iirc this is discussed in #77? we're just waiting for action on that one

**Comment by hackygolucky** [comment]
I think this has to be taken care of by @nebrius @MylesBorins @jasnell or @mhdawson as they have admin access to all of these? I can only edit some.

**Comment by nebrius** [comment]
> I think this has to be taken care of by @nebrius @MylesBorins @jasnell or @mhdawson as they have admin access to all of these? I can only edit some.

IIRC it needs to be done by the person who created the team, or an org owner. I am neither and don't have permission to make these changes either.

**Comment by MylesBorins** [comment]
I've removed the extra teams and made sure the membership of the community-committee team reflects the current membership in the readme. This involved adding some missing members and removing @jasnell (Sorry James 😭)

Closing as fixed, please chime in if we should re-open

Current @nodejs/community-committee has access to nodejs/community-committee and nodejs/education

**Comment by MylesBorins** [comment]
I also added the moderation repo

**Comment by pup** [comment]
@MylesBorins ❤️

**Comment by nebrius** [comment]
Thank you @MylesBorins!

**Comment by bnb** [comment]
Blown away by how much interaction this got and how fast it was solved. Only saw @pup's comment, refreshed to answer it and saw everything else. Y'all are amazing.

Thanks a bunch, @MylesBorins. 🙏
